<?xml version="1.0" encoding="UTF-8"?>
<VirtualComPortSetting>
  <!--This configuration file is automatic generated and maintained.
Please do not modify manually.-->
  <Version>1.00</Version>
  <DeviceType>1524</DeviceType>
  <EDGConfigNew_SinglePortBaseInfoV20>
    <m_PortState>1</m_PortState>
    <m_PortMode>1</m_PortMode>
    <m_PortType>485</m_PortType>
    <m_Databits>8</m_Databits>
    <m_Parity>0</m_Parity>
    <m_Stopbits>0</m_Stopbits>
    <m_FlowControl>0</m_FlowControl>
    <m_UsdgMode>1</m_UsdgMode>
    <m_UsdgProto>65535</m_UsdgProto>
    <m_EnAbleStatus>0</m_EnAbleStatus>
    <m_Baudrate>9600</m_Baudrate>
    <m_BufferingMode>1</m_BufferingMode>
    <m_BufferingSave>1</m_BufferingSave>
    <m_BufferingSize>0</m_BufferingSize>
  </EDGConfigNew_SinglePortBaseInfoV20>
  <EDGConfigNew_SinglePortBaseInfoV21>
    <m_PortState>1</m_PortState>
    <m_PortMode>1</m_PortMode>
    <m_PortType>485</m_PortType>
    <m_Databits>8</m_Databits>
    <m_Parity>0</m_Parity>
    <m_Stopbits>0</m_Stopbits>
    <m_FlowControl>0</m_FlowControl>
    <m_UsdgMode>1</m_UsdgMode>
    <m_UsdgProto>0</m_UsdgProto>
    <m_EnAbleStatus>0</m_EnAbleStatus>
    <m_Baudrate>9600</m_Baudrate>
    <m_BufferingMode>1</m_BufferingMode>
    <m_BufferingSave>1</m_BufferingSave>
    <m_BufferingSize>0</m_BufferingSize>
  </EDGConfigNew_SinglePortBaseInfoV21>
  <EDGConfigNew_SinglePortBaseInfoV22>
    <m_PortState>1</m_PortState>
    <m_PortMode>1</m_PortMode>
    <m_PortType>485</m_PortType>
    <m_Databits>8</m_Databits>
    <m_Parity>0</m_Parity>
    <m_Stopbits>0</m_Stopbits>
    <m_FlowControl>0</m_FlowControl>
    <m_UsdgMode>1</m_UsdgMode>
    <m_UsdgProto>0</m_UsdgProto>
    <m_EnAbleStatus>0</m_EnAbleStatus>
    <m_Baudrate>9600</m_Baudrate>
    <m_BufferingMode>1</m_BufferingMode>
    <m_BufferingSave>1</m_BufferingSave>
    <m_BufferingSize>0</m_BufferingSize>
  </EDGConfigNew_SinglePortBaseInfoV22>
  <EDGConfigNew_SinglePortBaseInfoV23>
    <m_PortState>1</m_PortState>
    <m_PortMode>1</m_PortMode>
    <m_PortType>485</m_PortType>
    <m_Databits>8</m_Databits>
    <m_Parity>0</m_Parity>
    <m_Stopbits>0</m_Stopbits>
    <m_FlowControl>0</m_FlowControl>
    <m_UsdgMode>1</m_UsdgMode>
    <m_UsdgProto>0</m_UsdgProto>
    <m_EnAbleStatus>0</m_EnAbleStatus>
    <m_Baudrate>9600</m_Baudrate>
    <m_BufferingMode>1</m_BufferingMode>
    <m_BufferingSave>1</m_BufferingSave>
    <m_BufferingSize>0</m_BufferingSize>
  </EDGConfigNew_SinglePortBaseInfoV23>
  <EDGConfigNew_SinglePortVComInfoV20>
    <m_HostIdleTimeout>60</m_HostIdleTimeout>
    <m_ResponseTimeout>0</m_ResponseTimeout>
    <m_FrameBreak>0</m_FrameBreak>
    <m_DisableFlag>0</m_DisableFlag>
    <m_DelayTime>0</m_DelayTime>
    <m_DataBufferThreshold>0</m_DataBufferThreshold>
    <m_DataBufferTime>0</m_DataBufferTime>
    <m_RTL>-1</m_RTL>
    <m_TTL>-1</m_TTL>
    <m_FCL>-1</m_FCL>
    <m_FCH>-1</m_FCH>
    <m_FIFOWriteSize>-1</m_FIFOWriteSize>
    <m_RTSStat>0</m_RTSStat>
    <m_DTRStat>0</m_DTRStat>
    <m_PackMode>0</m_PackMode>
    <m_PackSize>0</m_PackSize>
    <m_PackInterval>0</m_PackInterval>
    <m_PackEndChars>48</m_PackEndChars>
    <m_PackDisplay>2</m_PackDisplay>
  </EDGConfigNew_SinglePortVComInfoV20>
  <EDGConfigNew_SinglePortVComInfoV21>
    <m_HostIdleTimeout>60</m_HostIdleTimeout>
    <m_ResponseTimeout>0</m_ResponseTimeout>
    <m_FrameBreak>0</m_FrameBreak>
    <m_DisableFlag>0</m_DisableFlag>
    <m_DelayTime>0</m_DelayTime>
    <m_DataBufferThreshold>0</m_DataBufferThreshold>
    <m_DataBufferTime>0</m_DataBufferTime>
    <m_RTL>-1</m_RTL>
    <m_TTL>-1</m_TTL>
    <m_FCL>-1</m_FCL>
    <m_FCH>-1</m_FCH>
    <m_FIFOWriteSize>-1</m_FIFOWriteSize>
    <m_RTSStat>0</m_RTSStat>
    <m_DTRStat>0</m_DTRStat>
    <m_PackMode>0</m_PackMode>
    <m_PackSize>0</m_PackSize>
    <m_PackInterval>0</m_PackInterval>
    <m_PackEndChars>48</m_PackEndChars>
    <m_PackDisplay>2</m_PackDisplay>
  </EDGConfigNew_SinglePortVComInfoV21>
  <EDGConfigNew_SinglePortVComInfoV22>
    <m_HostIdleTimeout>60</m_HostIdleTimeout>
    <m_ResponseTimeout>0</m_ResponseTimeout>
    <m_FrameBreak>0</m_FrameBreak>
    <m_DisableFlag>0</m_DisableFlag>
    <m_DelayTime>0</m_DelayTime>
    <m_DataBufferThreshold>0</m_DataBufferThreshold>
    <m_DataBufferTime>0</m_DataBufferTime>
    <m_RTL>-1</m_RTL>
    <m_TTL>-1</m_TTL>
    <m_FCL>-1</m_FCL>
    <m_FCH>-1</m_FCH>
    <m_FIFOWriteSize>-1</m_FIFOWriteSize>
    <m_RTSStat>0</m_RTSStat>
    <m_DTRStat>0</m_DTRStat>
    <m_PackMode>0</m_PackMode>
    <m_PackSize>0</m_PackSize>
    <m_PackInterval>0</m_PackInterval>
    <m_PackEndChars>48</m_PackEndChars>
    <m_PackDisplay>2</m_PackDisplay>
  </EDGConfigNew_SinglePortVComInfoV22>
  <EDGConfigNew_SinglePortVComInfoV23>
    <m_HostIdleTimeout>60</m_HostIdleTimeout>
    <m_ResponseTimeout>0</m_ResponseTimeout>
    <m_FrameBreak>0</m_FrameBreak>
    <m_DisableFlag>0</m_DisableFlag>
    <m_DelayTime>0</m_DelayTime>
    <m_DataBufferThreshold>0</m_DataBufferThreshold>
    <m_DataBufferTime>0</m_DataBufferTime>
    <m_RTL>-1</m_RTL>
    <m_TTL>-1</m_TTL>
    <m_FCL>-1</m_FCL>
    <m_FCH>-1</m_FCH>
    <m_FIFOWriteSize>-1</m_FIFOWriteSize>
    <m_RTSStat>0</m_RTSStat>
    <m_DTRStat>0</m_DTRStat>
    <m_PackMode>0</m_PackMode>
    <m_PackSize>0</m_PackSize>
    <m_PackInterval>0</m_PackInterval>
    <m_PackEndChars>48</m_PackEndChars>
    <m_PackDisplay>2</m_PackDisplay>
  </EDGConfigNew_SinglePortVComInfoV23>
  <EDGConfigNew_SinglePortControlModeInfoV20>
    <m_DataIdleTimeout>660</m_DataIdleTimeout>
    <m_GuardTime>11000</m_GuardTime>
    <m_HangupChar>+</m_HangupChar>
  </EDGConfigNew_SinglePortControlModeInfoV20>
  <EDGConfigNew_SinglePortControlModeInfoV21>
    <m_DataIdleTimeout>660</m_DataIdleTimeout>
    <m_GuardTime>11000</m_GuardTime>
    <m_HangupChar>+</m_HangupChar>
  </EDGConfigNew_SinglePortControlModeInfoV21>
  <EDGConfigNew_SinglePortControlModeInfoV22>
    <m_DataIdleTimeout>660</m_DataIdleTimeout>
    <m_GuardTime>11000</m_GuardTime>
    <m_HangupChar>+</m_HangupChar>
  </EDGConfigNew_SinglePortControlModeInfoV22>
  <EDGConfigNew_SinglePortControlModeInfoV23>
    <m_DataIdleTimeout>660</m_DataIdleTimeout>
    <m_GuardTime>11000</m_GuardTime>
    <m_HangupChar>+</m_HangupChar>
  </EDGConfigNew_SinglePortControlModeInfoV23>
  <EDGConfigNew_SingleEthernetDnsInfoV20>
    <m_EthID>0</m_EthID>
    <m_EnableDns>0</m_EnableDns>
    <m_Dns0>255.255.255.255</m_Dns0>
    <m_Dns1>255.255.255.255</m_Dns1>
  </EDGConfigNew_SingleEthernetDnsInfoV20>
  <EDGConfigNew_SingleEthernetDnsInfoV21>
    <m_EthID>1</m_EthID>
    <m_EnableDns>0</m_EnableDns>
    <m_Dns0>255.255.255.255</m_Dns0>
    <m_Dns1>255.255.255.255</m_Dns1>
  </EDGConfigNew_SingleEthernetDnsInfoV21>
  <EDGConfigNew_SinglePortRfc2217InfoV20>
    <m_ListenPort>5500</m_ListenPort>
    <m_IdleTimeout>1</m_IdleTimeout>
    <m_ResponseTimeout>0</m_ResponseTimeout>
    <m_FrameBreak>0</m_FrameBreak>
  </EDGConfigNew_SinglePortRfc2217InfoV20>
  <EDGConfigNew_SinglePortRfc2217InfoV21>
    <m_ListenPort>5501</m_ListenPort>
    <m_IdleTimeout>1</m_IdleTimeout>
    <m_ResponseTimeout>0</m_ResponseTimeout>
    <m_FrameBreak>0</m_FrameBreak>
  </EDGConfigNew_SinglePortRfc2217InfoV21>
  <EDGConfigNew_SinglePortRfc2217InfoV22>
    <m_ListenPort>5502</m_ListenPort>
    <m_IdleTimeout>1</m_IdleTimeout>
    <m_ResponseTimeout>0</m_ResponseTimeout>
    <m_FrameBreak>0</m_FrameBreak>
  </EDGConfigNew_SinglePortRfc2217InfoV22>
  <EDGConfigNew_SinglePortRfc2217InfoV23>
    <m_ListenPort>5503</m_ListenPort>
    <m_IdleTimeout>1</m_IdleTimeout>
    <m_ResponseTimeout>0</m_ResponseTimeout>
    <m_FrameBreak>0</m_FrameBreak>
  </EDGConfigNew_SinglePortRfc2217InfoV23>
  <EDGConfigNew_SinglePortDataModeInfoV20>
    <m_DataIdleTimeout>60</m_DataIdleTimeout>
    <m_DataPort>5300</m_DataPort>
    <m_ATPort>5400</m_ATPort>
    <m_PeerNum>0</m_PeerNum>
    <m_MaxPeerNum>16</m_MaxPeerNum>
    <m_TCPResponseTimeout>0</m_TCPResponseTimeout>
    <m_TCPFrameBreak>0</m_TCPFrameBreak>
    <m_UDPResponseTimeout>1000</m_UDPResponseTimeout>
    <m_UDPFrameBreak>1000</m_UDPFrameBreak>
    <m_UDPServerModeSendEthPorts>1</m_UDPServerModeSendEthPorts>
    <m_PackageMode>0</m_PackageMode>
    <m_PackageSize>0</m_PackageSize>
    <m_PackInterval>0</m_PackInterval>
    <m_PackEndChars>48</m_PackEndChars>
    <m_PackDisplay>2</m_PackDisplay>
  </EDGConfigNew_SinglePortDataModeInfoV20>
  <EDGConfigNew_SinglePortDataModeInfoV21>
    <m_DataIdleTimeout>60</m_DataIdleTimeout>
    <m_DataPort>5301</m_DataPort>
    <m_ATPort>5400</m_ATPort>
    <m_PeerNum>0</m_PeerNum>
    <m_MaxPeerNum>16</m_MaxPeerNum>
    <m_TCPResponseTimeout>0</m_TCPResponseTimeout>
    <m_TCPFrameBreak>0</m_TCPFrameBreak>
    <m_UDPResponseTimeout>1000</m_UDPResponseTimeout>
    <m_UDPFrameBreak>1000</m_UDPFrameBreak>
    <m_UDPServerModeSendEthPorts>1</m_UDPServerModeSendEthPorts>
    <m_PackageMode>0</m_PackageMode>
    <m_PackageSize>0</m_PackageSize>
    <m_PackInterval>0</m_PackInterval>
    <m_PackEndChars>48</m_PackEndChars>
    <m_PackDisplay>2</m_PackDisplay>
  </EDGConfigNew_SinglePortDataModeInfoV21>
  <EDGConfigNew_SinglePortDataModeInfoV22>
    <m_DataIdleTimeout>60</m_DataIdleTimeout>
    <m_DataPort>5302</m_DataPort>
    <m_ATPort>5400</m_ATPort>
    <m_PeerNum>0</m_PeerNum>
    <m_MaxPeerNum>16</m_MaxPeerNum>
    <m_TCPResponseTimeout>0</m_TCPResponseTimeout>
    <m_TCPFrameBreak>0</m_TCPFrameBreak>
    <m_UDPResponseTimeout>1000</m_UDPResponseTimeout>
    <m_UDPFrameBreak>1000</m_UDPFrameBreak>
    <m_UDPServerModeSendEthPorts>1</m_UDPServerModeSendEthPorts>
    <m_PackageMode>0</m_PackageMode>
    <m_PackageSize>0</m_PackageSize>
    <m_PackInterval>0</m_PackInterval>
    <m_PackEndChars>48</m_PackEndChars>
    <m_PackDisplay>2</m_PackDisplay>
  </EDGConfigNew_SinglePortDataModeInfoV22>
  <EDGConfigNew_SinglePortDataModeInfoV23>
    <m_DataIdleTimeout>60</m_DataIdleTimeout>
    <m_DataPort>5303</m_DataPort>
    <m_ATPort>5400</m_ATPort>
    <m_PeerNum>0</m_PeerNum>
    <m_MaxPeerNum>16</m_MaxPeerNum>
    <m_TCPResponseTimeout>0</m_TCPResponseTimeout>
    <m_TCPFrameBreak>0</m_TCPFrameBreak>
    <m_UDPResponseTimeout>1000</m_UDPResponseTimeout>
    <m_UDPFrameBreak>1000</m_UDPFrameBreak>
    <m_UDPServerModeSendEthPorts>1</m_UDPServerModeSendEthPorts>
    <m_PackageMode>0</m_PackageMode>
    <m_PackageSize>0</m_PackageSize>
    <m_PackInterval>0</m_PackInterval>
    <m_PackEndChars>48</m_PackEndChars>
    <m_PackDisplay>2</m_PackDisplay>
  </EDGConfigNew_SinglePortDataModeInfoV23>
</VirtualComPortSetting>