// ===========================================================================
//  ARMS/ARMS_layout.gen.cpp
//  DO NOT EDIT -- GENERATED FILE. See the matching _layout.gen.h banner.
// ===========================================================================
#include "ARMS_layout.gen.h"

namespace ht9045_layout {

// (no custom-control properties in this form)

const DfmControlLayout kARMSLayout[] = {
    { "fARMS", "fARMS", "", "TfARMS", "", "", 0, 0, "ROOT", false, true, 270, true, 208, false, 0, false, 0, false, 0, -1, "", "", true, "MS Sans Serif", -11, "", true, -2147483640, "clWindowText", true, 12761254, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMS.pcARMSFoem", "pcARMSFoem", "IDC_ARMS_PCARMSFOEM", "TPageControl", "fARMS", "fARMS", 0, 1, "TABHOST", false, true, 0, true, 0, true, 784, true, 518, true, 0, -1, "alClient", "", true, "MS Sans Serif", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMS.pcARMSFoem.tsARMSMain", "tsARMSMain", "IDD_ARMS_PCARMSFOEM_TSARMSMAIN", "TTabSheet", "fARMS.pcARMSFoem", "fARMS", 0, 2, "SUBDLG", false, false, 0, false, 0, false, 0, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMS.pcARMSFoem.tsARMSMain.pnMain", "pnMain", "IDD_ARMS_PCARMSFOEM_TSARMSMAIN_PNMAIN", "TPanel", "fARMS.pcARMSFoem.tsARMSMain", "fARMS.pcARMSFoem.tsARMSMain", 0, 3, "SUBDLG", false, true, 0, true, 0, true, 776, true, 480, true, 0, -1, "alClient", "", false, "", 0, "", false, 0, "", true, 12761254, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMS.pcARMSFoem.tsARMSMain.pnMain.sbMoveToDownload", "sbMoveToDownload", "IDC_ARMS_SBMOVETODOWNLOAD", "TSpeedButton", "fARMS.pcARMSFoem.tsARMSMain.pnMain", "fARMS.pcARMSFoem.tsARMSMain.pnMain", 0, 4, "LEAF", true, true, 338, true, 134, true, 95, true, 30, false, 0, -1, "", "", true, "MS Sans Serif", -13, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMS.pcARMSFoem.tsARMSMain.pnMain.sbARMSRecipeDownload", "sbARMSRecipeDownload", "IDC_ARMS_SBARMSRECIPEDOWNLOAD", "TSpeedButton", "fARMS.pcARMSFoem.tsARMSMain.pnMain", "fARMS.pcARMSFoem.tsARMSMain.pnMain", 1, 4, "LEAF", true, true, 10, true, 328, true, 320, true, 41, false, 0, -1, "", "", true, "MS Sans Serif", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMS.pcARMSFoem.tsARMSMain.pnMain.sbARMSRecipeUpload", "sbARMSRecipeUpload", "IDC_ARMS_SBARMSRECIPEUPLOAD", "TSpeedButton", "fARMS.pcARMSFoem.tsARMSMain.pnMain", "fARMS.pcARMSFoem.tsARMSMain.pnMain", 2, 4, "LEAF", true, true, 442, true, 392, true, 320, true, 41, false, 0, -1, "", "", true, "MS Sans Serif", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMS.pcARMSFoem.tsARMSMain.pnMain.gbDownloadRecipe", "gbDownloadRecipe", "IDD_ARMS_PCARMSFOEM_TSARMSMAIN_PNMAIN_GBDOWNLOADRECIPE", "TGroupBox", "fARMS.pcARMSFoem.tsARMSMain.pnMain", "fARMS.pcARMSFoem.tsARMSMain.pnMain", 3, 4, "SUBDLG", false, true, 10, true, 10, true, 320, true, 310, true, 0, -1, "", "", true, "@新細明體", -19, "", true, 16711680, "clBlue", true, 12761254, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMS.pcARMSFoem.tsARMSMain.pnMain.gbDownloadRecipe.sbRefreshDownloadRecipe", "sbRefreshDownloadRecipe", "IDC_ARMS_SBREFRESHDOWNLOADRECIPE", "TSpeedButton", "fARMS.pcARMSFoem.tsARMSMain.pnMain.gbDownloadRecipe", "fARMS.pcARMSFoem.tsARMSMain.pnMain.gbDownloadRecipe", 0, 5, "LEAF", true, true, 210, true, 270, true, 100, true, 35, false, 0, -1, "", "", true, "@新細明體", -13, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMS.pcARMSFoem.tsARMSMain.pnMain.gbDownloadRecipe.sbDeletDownloadRecipe", "sbDeletDownloadRecipe", "IDC_ARMS_SBDELETDOWNLOADRECIPE", "TSpeedButton", "fARMS.pcARMSFoem.tsARMSMain.pnMain.gbDownloadRecipe", "fARMS.pcARMSFoem.tsARMSMain.pnMain.gbDownloadRecipe", 1, 5, "LEAF", true, true, 10, true, 270, true, 97, true, 35, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMS.pcARMSFoem.tsARMSMain.pnMain.gbDownloadRecipe.CheckListBoxDownloadRecipe", "CheckListBoxDownloadRecipe", "IDC_ARMS_CHECKLISTBOXDOWNLOADRECIPE", "TCheckListBox", "fARMS.pcARMSFoem.tsARMSMain.pnMain.gbDownloadRecipe", "fARMS.pcARMSFoem.tsARMSMain.pnMain.gbDownloadRecipe", 2, 5, "LEAF", false, true, 10, true, 25, true, 300, true, 240, true, 0, -1, "", "", false, "", 0, "", false, 0, "", true, 14670284, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMS.pcARMSFoem.tsARMSMain.pnMain.gbUploadRecipe", "gbUploadRecipe", "IDD_ARMS_PCARMSFOEM_TSARMSMAIN_PNMAIN_GBUPLOADRECIPE", "TGroupBox", "fARMS.pcARMSFoem.tsARMSMain.pnMain", "fARMS.pcARMSFoem.tsARMSMain.pnMain", 4, 4, "SUBDLG", false, true, 440, true, 10, true, 320, true, 310, true, 1, -1, "", "", true, "@新細明體", -19, "", true, 16711680, "clBlue", true, 12761254, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMS.pcARMSFoem.tsARMSMain.pnMain.gbUploadRecipe.sbRefreshUploadloadRecipe", "sbRefreshUploadloadRecipe", "IDC_ARMS_SBREFRESHUPLOADLOADRECIPE", "TSpeedButton", "fARMS.pcARMSFoem.tsARMSMain.pnMain.gbUploadRecipe", "fARMS.pcARMSFoem.tsARMSMain.pnMain.gbUploadRecipe", 0, 5, "LEAF", true, true, 210, true, 270, true, 100, true, 35, false, 0, -1, "", "", true, "@新細明體", -13, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMS.pcARMSFoem.tsARMSMain.pnMain.gbUploadRecipe.sbDeletUploadRecipe", "sbDeletUploadRecipe", "IDC_ARMS_SBDELETUPLOADRECIPE", "TSpeedButton", "fARMS.pcARMSFoem.tsARMSMain.pnMain.gbUploadRecipe", "fARMS.pcARMSFoem.tsARMSMain.pnMain.gbUploadRecipe", 1, 5, "LEAF", true, true, 10, true, 270, true, 97, true, 35, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMS.pcARMSFoem.tsARMSMain.pnMain.gbUploadRecipe.CheckListBoxUploadRecipe", "CheckListBoxUploadRecipe", "IDC_ARMS_CHECKLISTBOXUPLOADRECIPE", "TCheckListBox", "fARMS.pcARMSFoem.tsARMSMain.pnMain.gbUploadRecipe", "fARMS.pcARMSFoem.tsARMSMain.pnMain.gbUploadRecipe", 2, 5, "LEAF", false, true, 10, true, 25, true, 300, true, 240, true, 0, -1, "", "", false, "", 0, "", false, 0, "", true, 14670284, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMS.pcARMSFoem.tsARMSMain.pnMain.pnHandlerRecipeName", "pnHandlerRecipeName", "IDC_ARMS_PNHANDLERRECIPENAME", "TPanel", "fARMS.pcARMSFoem.tsARMSMain.pnMain", "fARMS.pcARMSFoem.tsARMSMain.pnMain", 5, 4, "LEAF", false, true, 440, true, 330, true, 321, true, 25, true, 2, -1, "", "", true, "MS Sans Serif", -16, "", true, 16777215, "clWhite", true, 9534289, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMS.pcARMSFoem.tsARMSMain.pnMain.cobHandlerRecipeName", "cobHandlerRecipeName", "IDC_ARMS_COBHANDLERRECIPENAME", "TComboBox", "fARMS.pcARMSFoem.tsARMSMain.pnMain", "fARMS.pcARMSFoem.tsARMSMain.pnMain", 6, 4, "LEAF", false, true, 440, true, 360, true, 321, true, 28, true, 3, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMS.pcARMSFoem.tsARMSMain.pnMain.DirectoryListBox1", "DirectoryListBox1", "IDC_ARMS_DIRECTORYLISTBOX1", "TDirectoryListBox", "fARMS.pcARMSFoem.tsARMSMain.pnMain", "fARMS.pcARMSFoem.tsARMSMain.pnMain", 7, 4, "LEAF", false, true, 608, true, 432, true, 41, true, 49, true, 4, 0, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMS.pcARMSFoem.tsARMSMain.pnMain.FileListBox1", "FileListBox1", "IDC_ARMS_FILELISTBOX1", "TFileListBox", "fARMS.pcARMSFoem.tsARMSMain.pnMain", "fARMS.pcARMSFoem.tsARMSMain.pnMain", 8, 4, "LEAF", false, true, 664, true, 440, true, 49, true, 41, true, 5, 0, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMS.pcARMSFoem.tsARMSSetup", "tsARMSSetup", "IDD_ARMS_PCARMSFOEM_TSARMSSETUP", "TTabSheet", "fARMS.pcARMSFoem", "fARMS", 1, 2, "SUBDLG", false, false, 0, false, 0, false, 0, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMS.pcARMSFoem.tsARMSSetup.gbServerPathSetup", "gbServerPathSetup", "IDD_ARMS_PCARMSFOEM_TSARMSSETUP_GBSERVERPATHSETUP", "TGroupBox", "fARMS.pcARMSFoem.tsARMSSetup", "fARMS.pcARMSFoem.tsARMSSetup", 0, 3, "SUBDLG", false, true, 0, true, 0, true, 776, true, 160, true, 0, -1, "alTop", "", true, "Arial", -16, "", true, 8388608, "clNavy", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMS.pcARMSFoem.tsARMSSetup.gbServerPathSetup.sbUploadRecipePath", "sbUploadRecipePath", "IDC_ARMS_SBUPLOADRECIPEPATH", "TSpeedButton", "fARMS.pcARMSFoem.tsARMSSetup.gbServerPathSetup", "fARMS.pcARMSFoem.tsARMSSetup.gbServerPathSetup", 0, 4, "LEAF", true, true, 700, true, 29, true, 49, true, 29, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMS.pcARMSFoem.tsARMSSetup.gbServerPathSetup.sbDownloadRecipePath", "sbDownloadRecipePath", "IDC_ARMS_SBDOWNLOADRECIPEPATH", "TSpeedButton", "fARMS.pcARMSFoem.tsARMSSetup.gbServerPathSetup", "fARMS.pcARMSFoem.tsARMSSetup.gbServerPathSetup", 1, 4, "LEAF", true, true, 700, true, 69, true, 49, true, 29, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMS.pcARMSFoem.tsARMSSetup.gbServerPathSetup.sbBackupUploadRecipe", "sbBackupUploadRecipe", "IDC_ARMS_SBBACKUPUPLOADRECIPE", "TSpeedButton", "fARMS.pcARMSFoem.tsARMSSetup.gbServerPathSetup", "fARMS.pcARMSFoem.tsARMSSetup.gbServerPathSetup", 2, 4, "LEAF", true, true, 700, true, 109, true, 49, true, 29, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMS.pcARMSFoem.tsARMSSetup.gbServerPathSetup.pnUploadRecipePath", "pnUploadRecipePath", "IDC_ARMS_PNUPLOADRECIPEPATH", "TPanel", "fARMS.pcARMSFoem.tsARMSSetup.gbServerPathSetup", "fARMS.pcARMSFoem.tsARMSSetup.gbServerPathSetup", 3, 4, "LEAF", false, true, 10, true, 29, true, 180, true, 30, true, 0, -1, "", "", true, "Arial", -16, "", true, 16777215, "clWhite", true, 9534289, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMS.pcARMSFoem.tsARMSSetup.gbServerPathSetup.edUploadRecipePath", "edUploadRecipePath", "IDC_ARMS_EDUPLOADRECIPEPATH", "TEdit", "fARMS.pcARMSFoem.tsARMSSetup.gbServerPathSetup", "fARMS.pcARMSFoem.tsARMSSetup.gbServerPathSetup", 4, 4, "LEAF", false, true, 196, true, 31, true, 500, true, 26, true, 1, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMS.pcARMSFoem.tsARMSSetup.gbServerPathSetup.edDownloadRecipePath", "edDownloadRecipePath", "IDC_ARMS_EDDOWNLOADRECIPEPATH", "TEdit", "fARMS.pcARMSFoem.tsARMSSetup.gbServerPathSetup", "fARMS.pcARMSFoem.tsARMSSetup.gbServerPathSetup", 5, 4, "LEAF", false, true, 196, true, 71, true, 500, true, 26, true, 2, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMS.pcARMSFoem.tsARMSSetup.gbServerPathSetup.pnDownloadRecipePath", "pnDownloadRecipePath", "IDC_ARMS_PNDOWNLOADRECIPEPATH", "TPanel", "fARMS.pcARMSFoem.tsARMSSetup.gbServerPathSetup", "fARMS.pcARMSFoem.tsARMSSetup.gbServerPathSetup", 6, 4, "LEAF", false, true, 10, true, 69, true, 180, true, 30, true, 3, -1, "", "", true, "Arial", -16, "", true, 16777215, "clWhite", true, 9534289, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMS.pcARMSFoem.tsARMSSetup.gbServerPathSetup.pnBackupUploadRecipe", "pnBackupUploadRecipe", "IDC_ARMS_PNBACKUPUPLOADRECIPE", "TPanel", "fARMS.pcARMSFoem.tsARMSSetup.gbServerPathSetup", "fARMS.pcARMSFoem.tsARMSSetup.gbServerPathSetup", 7, 4, "LEAF", false, true, 10, true, 109, true, 180, true, 30, true, 4, -1, "", "", true, "Arial", -16, "", true, 16777215, "clWhite", true, 9534289, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMS.pcARMSFoem.tsARMSSetup.gbServerPathSetup.edBackupUploadRecipe", "edBackupUploadRecipe", "IDC_ARMS_EDBACKUPUPLOADRECIPE", "TEdit", "fARMS.pcARMSFoem.tsARMSSetup.gbServerPathSetup", "fARMS.pcARMSFoem.tsARMSSetup.gbServerPathSetup", 8, 4, "LEAF", false, true, 196, true, 111, true, 500, true, 26, true, 5, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMS.pcARMSFoem.tsARMSSetup.gbARMSConfig", "gbARMSConfig", "IDD_ARMS_PCARMSFOEM_TSARMSSETUP_GBARMSCONFIG", "TGroupBox", "fARMS.pcARMSFoem.tsARMSSetup", "fARMS.pcARMSFoem.tsARMSSetup", 1, 3, "SUBDLG", false, true, 0, true, 160, true, 776, true, 120, true, 1, -1, "alTop", "", true, "Arial", -16, "", true, 8388608, "clNavy", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMS.pcARMSFoem.tsARMSSetup.gbARMSConfig.cbDownloadFormUploadPath", "cbDownloadFormUploadPath", "IDC_ARMS_CBDOWNLOADFORMUPLOADPATH", "TCheckBox", "fARMS.pcARMSFoem.tsARMSSetup.gbARMSConfig", "fARMS.pcARMSFoem.tsARMSSetup.gbARMSConfig", 0, 4, "LEAF", false, true, 20, true, 30, true, 413, true, 17, true, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMS.pcARMSFoem.tsARMSSetup.gbARMSConfig.cbRecipeDownloadIncludeOffsetFile", "cbRecipeDownloadIncludeOffsetFile", "IDC_ARMS_CBRECIPEDOWNLOADINCLUDEOFFSETFILE", "TCheckBox", "fARMS.pcARMSFoem.tsARMSSetup.gbARMSConfig", "fARMS.pcARMSFoem.tsARMSSetup.gbARMSConfig", 1, 4, "LEAF", false, true, 20, true, 60, true, 453, true, 17, true, 1, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMS.pcARMSFoem.tsBackup", "tsBackup", "IDD_ARMS_PCARMSFOEM_TSBACKUP", "TTabSheet", "fARMS.pcARMSFoem", "fARMS", 2, 2, "SUBDLG", false, false, 0, false, 0, false, 0, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMS.pcARMSFoem.tsBackup.pnBackup", "pnBackup", "IDD_ARMS_PCARMSFOEM_TSBACKUP_PNBACKUP", "TPanel", "fARMS.pcARMSFoem.tsBackup", "fARMS.pcARMSFoem.tsBackup", 0, 3, "SUBDLG", false, true, 0, true, 0, true, 775, true, 480, true, 0, -1, "", "", false, "", 0, "", false, 0, "", true, 12761254, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMS.pcARMSFoem.tsBackup.pnBackup.GroupBox1", "GroupBox1", "IDD_ARMS_PCARMSFOEM_TSBACKUP_PNBACKUP_GROUPBOX1", "TGroupBox", "fARMS.pcARMSFoem.tsBackup.pnBackup", "fARMS.pcARMSFoem.tsBackup.pnBackup", 0, 4, "SUBDLG", false, true, 2, true, 2, true, 320, true, 476, true, 0, -1, "alLeft", "", true, "Arial", -19, "", true, 16711680, "clBlue", true, 12761254, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMS.pcARMSFoem.tsBackup.pnBackup.GroupBox1.sbRefreshBackupUploadloadRecipe", "sbRefreshBackupUploadloadRecipe", "IDC_ARMS_SBREFRESHBACKUPUPLOADLOADRECIPE", "TSpeedButton", "fARMS.pcARMSFoem.tsBackup.pnBackup.GroupBox1", "fARMS.pcARMSFoem.tsBackup.pnBackup.GroupBox1", 0, 5, "LEAF", true, true, 206, true, 390, true, 100, true, 35, false, 0, -1, "", "", true, "Arial", -15, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMS.pcARMSFoem.tsBackup.pnBackup.GroupBox1.sbDeletBackupUploadRecipe", "sbDeletBackupUploadRecipe", "IDC_ARMS_SBDELETBACKUPUPLOADRECIPE", "TSpeedButton", "fARMS.pcARMSFoem.tsBackup.pnBackup.GroupBox1", "fARMS.pcARMSFoem.tsBackup.pnBackup.GroupBox1", 1, 5, "LEAF", true, true, 6, true, 390, true, 97, true, 35, false, 0, -1, "", "", true, "Arial", -15, "", true, 16711680, "clBlue", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMS.pcARMSFoem.tsBackup.pnBackup.GroupBox1.sbMoveToUploadRecipeFolder", "sbMoveToUploadRecipeFolder", "IDC_ARMS_SBMOVETOUPLOADRECIPEFOLDER", "TSpeedButton", "fARMS.pcARMSFoem.tsBackup.pnBackup.GroupBox1", "fARMS.pcARMSFoem.tsBackup.pnBackup.GroupBox1", 2, 5, "LEAF", true, true, 5, true, 430, true, 300, true, 40, false, 0, -1, "", "", true, "Arial", -15, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMS.pcARMSFoem.tsBackup.pnBackup.GroupBox1.CheckListBoxBackupUploadRecipe", "CheckListBoxBackupUploadRecipe", "IDC_ARMS_CHECKLISTBOXBACKUPUPLOADRECIPE", "TCheckListBox", "fARMS.pcARMSFoem.tsBackup.pnBackup.GroupBox1", "fARMS.pcARMSFoem.tsBackup.pnBackup.GroupBox1", 3, 5, "LEAF", false, true, 2, true, 24, true, 316, true, 357, true, 0, -1, "alTop", "", false, "", 0, "", false, 0, "", true, 14670284, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMS.pcARMSFoem.tsBackup.pnBackup.Panel1", "Panel1", "IDD_ARMS_PCARMSFOEM_TSBACKUP_PNBACKUP_PANEL1", "TPanel", "fARMS.pcARMSFoem.tsBackup.pnBackup", "fARMS.pcARMSFoem.tsBackup.pnBackup", 1, 4, "SUBDLG", false, true, 348, true, 2, true, 425, true, 476, true, 1, -1, "alRight", "", false, "", 0, "", false, 0, "", true, 12761254, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMS.pcARMSFoem.tsBackup.pnBackup.Panel1.FileListBoxARMS", "FileListBoxARMS", "IDC_ARMS_FILELISTBOXARMS", "TFileListBox", "fARMS.pcARMSFoem.tsBackup.pnBackup.Panel1", "fARMS.pcARMSFoem.tsBackup.pnBackup.Panel1", 0, 5, "LEAF", false, true, 0, true, 29, true, 425, true, 120, true, 1, -1, "alTop", "", false, "", 0, "", false, 0, "", true, 14670284, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMS.pcARMSFoem.tsBackup.pnBackup.Panel1.MemoRecipeLog", "MemoRecipeLog", "IDC_ARMS_MEMORECIPELOG", "TMemo", "fARMS.pcARMSFoem.tsBackup.pnBackup.Panel1", "fARMS.pcARMSFoem.tsBackup.pnBackup.Panel1", 1, 5, "LEAF", false, true, 0, true, 149, true, 425, true, 327, true, 2, -1, "alClient", "", false, "", 0, "", false, 0, "", true, 14670284, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMS.pcARMSFoem.tsBackup.pnBackup.Panel1.pnMainFix3FileTitle", "pnMainFix3FileTitle", "IDC_ARMS_PNMAINFIX3FILETITLE", "TPanel", "fARMS.pcARMSFoem.tsBackup.pnBackup.Panel1", "fARMS.pcARMSFoem.tsBackup.pnBackup.Panel1", 2, 5, "LEAF", false, true, 0, true, 0, true, 425, true, 29, true, 0, -1, "alTop", "", true, "Arial", -16, "", true, 16777215, "clWhite", true, 9534289, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMS.pnButtonTitle", "pnButtonTitle", "IDD_ARMS_PNBUTTONTITLE", "TPanel", "fARMS", "fARMS", 1, 1, "SUBDLG", false, true, 0, true, 518, true, 784, true, 44, true, 1, -1, "alBottom", "", false, "", 0, "", false, 0, "", true, 12761254, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMS.pnButtonTitle.sbExit", "sbExit", "IDC_ARMS_SBEXIT", "TSpeedButton", "fARMS.pnButtonTitle", "fARMS.pnButtonTitle", 0, 2, "LEAF", true, true, 655, true, 5, true, 110, true, 30, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMS.pnButtonTitle.sbEquipmentUpdate", "sbEquipmentUpdate", "IDC_ARMS_SBEQUIPMENTUPDATE", "TSpeedButton", "fARMS.pnButtonTitle", "fARMS.pnButtonTitle", 1, 2, "LEAF", true, true, 10, true, 5, true, 110, true, 30, false, 0, -1, "", "", true, "@新細明體", -16, "", true, 8388608, "clNavy", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
};

const int kARMSLayoutCount = 47;

} // namespace ht9045_layout
