// ===========================================================================
//  ARMS/ARMSLog_layout.gen.cpp
//  DO NOT EDIT -- GENERATED FILE. See the matching _layout.gen.h banner.
// ===========================================================================
#include "ARMSLog_layout.gen.h"

namespace ht9045_layout {

// (no custom-control properties in this form)

const DfmControlLayout kARMSLogLayout[] = {
    { "fARMSLog", "fARMSLog", "", "TfARMSLog", "", "", 0, 0, "ROOT", false, true, 439, true, 261, false, 0, false, 0, false, 0, -1, "", "", true, "MS Sans Serif", -11, "", true, -2147483640, "clWindowText", true, -2147483633, "clBtnFace", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMSLog.pnARMSLog", "pnARMSLog", "IDD_ARMSLOG_PNARMSLOG", "TPanel", "fARMSLog", "fARMSLog", 0, 1, "SUBDLG", false, true, 0, true, 0, true, 500, true, 401, true, 0, -1, "", "", false, "", 0, "", false, 0, "", true, 13487501, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMSLog.pnARMSLog.ShapeInfoBox1", "ShapeInfoBox1", "IDC_ARMSLOG_SHAPEINFOBOX1", "TShape", "fARMSLog.pnARMSLog", "fARMSLog.pnARMSLog", 0, 2, "LEAF", true, true, 0, true, 0, true, 20, true, 20, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMSLog.pnARMSLog.ShapeInfoBox2", "ShapeInfoBox2", "IDC_ARMSLOG_SHAPEINFOBOX2", "TShape", "fARMSLog.pnARMSLog", "fARMSLog.pnARMSLog", 1, 2, "LEAF", true, true, 20, true, 0, true, 20, true, 20, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMSLog.pnARMSLog.ShapeInfoBox3", "ShapeInfoBox3", "IDC_ARMSLOG_SHAPEINFOBOX3", "TShape", "fARMSLog.pnARMSLog", "fARMSLog.pnARMSLog", 2, 2, "LEAF", true, true, 40, true, 0, true, 20, true, 20, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMSLog.pnARMSLog.ShapeInfoBox4", "ShapeInfoBox4", "IDC_ARMSLOG_SHAPEINFOBOX4", "TShape", "fARMSLog.pnARMSLog", "fARMSLog.pnARMSLog", 3, 2, "LEAF", true, true, 60, true, 0, true, 25, true, 20, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMSLog.pnARMSLog.ShapeInfoBox5", "ShapeInfoBox5", "IDC_ARMSLOG_SHAPEINFOBOX5", "TShape", "fARMSLog.pnARMSLog", "fARMSLog.pnARMSLog", 4, 2, "LEAF", true, true, 80, true, 0, true, 20, true, 20, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMSLog.pnARMSLog.ShapeInfoBox6", "ShapeInfoBox6", "IDC_ARMSLOG_SHAPEINFOBOX6", "TShape", "fARMSLog.pnARMSLog", "fARMSLog.pnARMSLog", 5, 2, "LEAF", true, true, 100, true, 0, true, 20, true, 20, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMSLog.pnARMSLog.ShapeInfoBox7", "ShapeInfoBox7", "IDC_ARMSLOG_SHAPEINFOBOX7", "TShape", "fARMSLog.pnARMSLog", "fARMSLog.pnARMSLog", 6, 2, "LEAF", true, true, 120, true, 0, true, 20, true, 20, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMSLog.pnARMSLog.ShapeInfoBox8", "ShapeInfoBox8", "IDC_ARMSLOG_SHAPEINFOBOX8", "TShape", "fARMSLog.pnARMSLog", "fARMSLog.pnARMSLog", 7, 2, "LEAF", true, true, 140, true, 0, true, 20, true, 20, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMSLog.pnARMSLog.ShapeInfoBox9", "ShapeInfoBox9", "IDC_ARMSLOG_SHAPEINFOBOX9", "TShape", "fARMSLog.pnARMSLog", "fARMSLog.pnARMSLog", 8, 2, "LEAF", true, true, 160, true, 0, true, 20, true, 20, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMSLog.pnARMSLog.ShapeInfoBox10", "ShapeInfoBox10", "IDC_ARMSLOG_SHAPEINFOBOX10", "TShape", "fARMSLog.pnARMSLog", "fARMSLog.pnARMSLog", 9, 2, "LEAF", true, true, 180, true, 0, true, 20, true, 20, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMSLog.pnARMSLog.ShapeInfoBox11", "ShapeInfoBox11", "IDC_ARMSLOG_SHAPEINFOBOX11", "TShape", "fARMSLog.pnARMSLog", "fARMSLog.pnARMSLog", 10, 2, "LEAF", true, true, 200, true, 0, true, 20, true, 20, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMSLog.pnARMSLog.ShapeInfoBox12", "ShapeInfoBox12", "IDC_ARMSLOG_SHAPEINFOBOX12", "TShape", "fARMSLog.pnARMSLog", "fARMSLog.pnARMSLog", 11, 2, "LEAF", true, true, 220, true, 0, true, 20, true, 20, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMSLog.pnARMSLog.ShapeInfoBox13", "ShapeInfoBox13", "IDC_ARMSLOG_SHAPEINFOBOX13", "TShape", "fARMSLog.pnARMSLog", "fARMSLog.pnARMSLog", 12, 2, "LEAF", true, true, 240, true, 0, true, 20, true, 20, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMSLog.pnARMSLog.ShapeInfoBox14", "ShapeInfoBox14", "IDC_ARMSLOG_SHAPEINFOBOX14", "TShape", "fARMSLog.pnARMSLog", "fARMSLog.pnARMSLog", 13, 2, "LEAF", true, true, 260, true, 0, true, 20, true, 20, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMSLog.pnARMSLog.ShapeInfoBox15", "ShapeInfoBox15", "IDC_ARMSLOG_SHAPEINFOBOX15", "TShape", "fARMSLog.pnARMSLog", "fARMSLog.pnARMSLog", 14, 2, "LEAF", true, true, 280, true, 0, true, 20, true, 20, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMSLog.pnARMSLog.ShapeInfoBox16", "ShapeInfoBox16", "IDC_ARMSLOG_SHAPEINFOBOX16", "TShape", "fARMSLog.pnARMSLog", "fARMSLog.pnARMSLog", 15, 2, "LEAF", true, true, 300, true, 0, true, 20, true, 20, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMSLog.pnARMSLog.ShapeInfoBox17", "ShapeInfoBox17", "IDC_ARMSLOG_SHAPEINFOBOX17", "TShape", "fARMSLog.pnARMSLog", "fARMSLog.pnARMSLog", 16, 2, "LEAF", true, true, 320, true, 0, true, 20, true, 20, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMSLog.pnARMSLog.ShapeInfoBox18", "ShapeInfoBox18", "IDC_ARMSLOG_SHAPEINFOBOX18", "TShape", "fARMSLog.pnARMSLog", "fARMSLog.pnARMSLog", 17, 2, "LEAF", true, true, 340, true, 0, true, 20, true, 20, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMSLog.pnARMSLog.ShapeInfoBox19", "ShapeInfoBox19", "IDC_ARMSLOG_SHAPEINFOBOX19", "TShape", "fARMSLog.pnARMSLog", "fARMSLog.pnARMSLog", 18, 2, "LEAF", true, true, 360, true, 0, true, 20, true, 20, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMSLog.pnARMSLog.ShapeInfoBox20", "ShapeInfoBox20", "IDC_ARMSLOG_SHAPEINFOBOX20", "TShape", "fARMSLog.pnARMSLog", "fARMSLog.pnARMSLog", 19, 2, "LEAF", true, true, 380, true, 0, true, 20, true, 20, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMSLog.pnARMSLog.ShapeInfoBox21", "ShapeInfoBox21", "IDC_ARMSLOG_SHAPEINFOBOX21", "TShape", "fARMSLog.pnARMSLog", "fARMSLog.pnARMSLog", 20, 2, "LEAF", true, true, 400, true, 0, true, 20, true, 20, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMSLog.pnARMSLog.ShapeInfoBox22", "ShapeInfoBox22", "IDC_ARMSLOG_SHAPEINFOBOX22", "TShape", "fARMSLog.pnARMSLog", "fARMSLog.pnARMSLog", 21, 2, "LEAF", true, true, 420, true, 0, true, 20, true, 20, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMSLog.pnARMSLog.ShapeInfoBox23", "ShapeInfoBox23", "IDC_ARMSLOG_SHAPEINFOBOX23", "TShape", "fARMSLog.pnARMSLog", "fARMSLog.pnARMSLog", 22, 2, "LEAF", true, true, 440, true, 0, true, 20, true, 20, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMSLog.pnARMSLog.ShapeInfoBox24", "ShapeInfoBox24", "IDC_ARMSLOG_SHAPEINFOBOX24", "TShape", "fARMSLog.pnARMSLog", "fARMSLog.pnARMSLog", 23, 2, "LEAF", true, true, 460, true, 0, true, 20, true, 20, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMSLog.pnARMSLog.ShapeInfoBox25", "ShapeInfoBox25", "IDC_ARMSLOG_SHAPEINFOBOX25", "TShape", "fARMSLog.pnARMSLog", "fARMSLog.pnARMSLog", 24, 2, "LEAF", true, true, 480, true, 0, true, 20, true, 20, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMSLog.pnARMSLog.ShapeInfoBox26", "ShapeInfoBox26", "IDC_ARMSLOG_SHAPEINFOBOX26", "TShape", "fARMSLog.pnARMSLog", "fARMSLog.pnARMSLog", 25, 2, "LEAF", true, true, 481, true, 20, true, 20, true, 20, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMSLog.pnARMSLog.ShapeInfoBox27", "ShapeInfoBox27", "IDC_ARMSLOG_SHAPEINFOBOX27", "TShape", "fARMSLog.pnARMSLog", "fARMSLog.pnARMSLog", 26, 2, "LEAF", true, true, 481, true, 40, true, 20, true, 20, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMSLog.pnARMSLog.ShapeInfoBox28", "ShapeInfoBox28", "IDC_ARMSLOG_SHAPEINFOBOX28", "TShape", "fARMSLog.pnARMSLog", "fARMSLog.pnARMSLog", 27, 2, "LEAF", true, true, 481, true, 60, true, 20, true, 20, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMSLog.pnARMSLog.ShapeInfoBox52", "ShapeInfoBox52", "IDC_ARMSLOG_SHAPEINFOBOX52", "TShape", "fARMSLog.pnARMSLog", "fARMSLog.pnARMSLog", 28, 2, "LEAF", true, true, 0, true, 60, true, 20, true, 20, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMSLog.pnARMSLog.ShapeInfoBox51", "ShapeInfoBox51", "IDC_ARMSLOG_SHAPEINFOBOX51", "TShape", "fARMSLog.pnARMSLog", "fARMSLog.pnARMSLog", 29, 2, "LEAF", true, true, 20, true, 60, true, 20, true, 20, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMSLog.pnARMSLog.ShapeInfoBox50", "ShapeInfoBox50", "IDC_ARMSLOG_SHAPEINFOBOX50", "TShape", "fARMSLog.pnARMSLog", "fARMSLog.pnARMSLog", 30, 2, "LEAF", true, true, 40, true, 60, true, 20, true, 20, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMSLog.pnARMSLog.ShapeInfoBox49", "ShapeInfoBox49", "IDC_ARMSLOG_SHAPEINFOBOX49", "TShape", "fARMSLog.pnARMSLog", "fARMSLog.pnARMSLog", 31, 2, "LEAF", true, true, 60, true, 60, true, 20, true, 20, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMSLog.pnARMSLog.ShapeInfoBox48", "ShapeInfoBox48", "IDC_ARMSLOG_SHAPEINFOBOX48", "TShape", "fARMSLog.pnARMSLog", "fARMSLog.pnARMSLog", 32, 2, "LEAF", true, true, 80, true, 60, true, 20, true, 20, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMSLog.pnARMSLog.ShapeInfoBox47", "ShapeInfoBox47", "IDC_ARMSLOG_SHAPEINFOBOX47", "TShape", "fARMSLog.pnARMSLog", "fARMSLog.pnARMSLog", 33, 2, "LEAF", true, true, 100, true, 60, true, 20, true, 20, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMSLog.pnARMSLog.ShapeInfoBox46", "ShapeInfoBox46", "IDC_ARMSLOG_SHAPEINFOBOX46", "TShape", "fARMSLog.pnARMSLog", "fARMSLog.pnARMSLog", 34, 2, "LEAF", true, true, 120, true, 60, true, 20, true, 20, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMSLog.pnARMSLog.ShapeInfoBox45", "ShapeInfoBox45", "IDC_ARMSLOG_SHAPEINFOBOX45", "TShape", "fARMSLog.pnARMSLog", "fARMSLog.pnARMSLog", 35, 2, "LEAF", true, true, 140, true, 60, true, 20, true, 20, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMSLog.pnARMSLog.ShapeInfoBox44", "ShapeInfoBox44", "IDC_ARMSLOG_SHAPEINFOBOX44", "TShape", "fARMSLog.pnARMSLog", "fARMSLog.pnARMSLog", 36, 2, "LEAF", true, true, 160, true, 60, true, 20, true, 20, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMSLog.pnARMSLog.ShapeInfoBox43", "ShapeInfoBox43", "IDC_ARMSLOG_SHAPEINFOBOX43", "TShape", "fARMSLog.pnARMSLog", "fARMSLog.pnARMSLog", 37, 2, "LEAF", true, true, 180, true, 60, true, 20, true, 20, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMSLog.pnARMSLog.ShapeInfoBox42", "ShapeInfoBox42", "IDC_ARMSLOG_SHAPEINFOBOX42", "TShape", "fARMSLog.pnARMSLog", "fARMSLog.pnARMSLog", 38, 2, "LEAF", true, true, 200, true, 60, true, 20, true, 20, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMSLog.pnARMSLog.ShapeInfoBox41", "ShapeInfoBox41", "IDC_ARMSLOG_SHAPEINFOBOX41", "TShape", "fARMSLog.pnARMSLog", "fARMSLog.pnARMSLog", 39, 2, "LEAF", true, true, 220, true, 60, true, 20, true, 20, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMSLog.pnARMSLog.ShapeInfoBox40", "ShapeInfoBox40", "IDC_ARMSLOG_SHAPEINFOBOX40", "TShape", "fARMSLog.pnARMSLog", "fARMSLog.pnARMSLog", 40, 2, "LEAF", true, true, 240, true, 60, true, 20, true, 20, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMSLog.pnARMSLog.ShapeInfoBox39", "ShapeInfoBox39", "IDC_ARMSLOG_SHAPEINFOBOX39", "TShape", "fARMSLog.pnARMSLog", "fARMSLog.pnARMSLog", 41, 2, "LEAF", true, true, 260, true, 60, true, 20, true, 20, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMSLog.pnARMSLog.ShapeInfoBox38", "ShapeInfoBox38", "IDC_ARMSLOG_SHAPEINFOBOX38", "TShape", "fARMSLog.pnARMSLog", "fARMSLog.pnARMSLog", 42, 2, "LEAF", true, true, 280, true, 60, true, 20, true, 20, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMSLog.pnARMSLog.ShapeInfoBox37", "ShapeInfoBox37", "IDC_ARMSLOG_SHAPEINFOBOX37", "TShape", "fARMSLog.pnARMSLog", "fARMSLog.pnARMSLog", 43, 2, "LEAF", true, true, 300, true, 60, true, 20, true, 20, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMSLog.pnARMSLog.ShapeInfoBox36", "ShapeInfoBox36", "IDC_ARMSLOG_SHAPEINFOBOX36", "TShape", "fARMSLog.pnARMSLog", "fARMSLog.pnARMSLog", 44, 2, "LEAF", true, true, 320, true, 60, true, 20, true, 20, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMSLog.pnARMSLog.ShapeInfoBox35", "ShapeInfoBox35", "IDC_ARMSLOG_SHAPEINFOBOX35", "TShape", "fARMSLog.pnARMSLog", "fARMSLog.pnARMSLog", 45, 2, "LEAF", true, true, 340, true, 60, true, 20, true, 20, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMSLog.pnARMSLog.ShapeInfoBox34", "ShapeInfoBox34", "IDC_ARMSLOG_SHAPEINFOBOX34", "TShape", "fARMSLog.pnARMSLog", "fARMSLog.pnARMSLog", 46, 2, "LEAF", true, true, 360, true, 60, true, 20, true, 20, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMSLog.pnARMSLog.ShapeInfoBox33", "ShapeInfoBox33", "IDC_ARMSLOG_SHAPEINFOBOX33", "TShape", "fARMSLog.pnARMSLog", "fARMSLog.pnARMSLog", 47, 2, "LEAF", true, true, 380, true, 60, true, 20, true, 20, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMSLog.pnARMSLog.ShapeInfoBox32", "ShapeInfoBox32", "IDC_ARMSLOG_SHAPEINFOBOX32", "TShape", "fARMSLog.pnARMSLog", "fARMSLog.pnARMSLog", 48, 2, "LEAF", true, true, 400, true, 60, true, 20, true, 20, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMSLog.pnARMSLog.ShapeInfoBox31", "ShapeInfoBox31", "IDC_ARMSLOG_SHAPEINFOBOX31", "TShape", "fARMSLog.pnARMSLog", "fARMSLog.pnARMSLog", 49, 2, "LEAF", true, true, 420, true, 60, true, 20, true, 20, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMSLog.pnARMSLog.ShapeInfoBox30", "ShapeInfoBox30", "IDC_ARMSLOG_SHAPEINFOBOX30", "TShape", "fARMSLog.pnARMSLog", "fARMSLog.pnARMSLog", 50, 2, "LEAF", true, true, 440, true, 60, true, 20, true, 20, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMSLog.pnARMSLog.ShapeInfoBox29", "ShapeInfoBox29", "IDC_ARMSLOG_SHAPEINFOBOX29", "TShape", "fARMSLog.pnARMSLog", "fARMSLog.pnARMSLog", 51, 2, "LEAF", true, true, 460, true, 60, true, 20, true, 20, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMSLog.pnARMSLog.ShapeInfoBox53", "ShapeInfoBox53", "IDC_ARMSLOG_SHAPEINFOBOX53", "TShape", "fARMSLog.pnARMSLog", "fARMSLog.pnARMSLog", 52, 2, "LEAF", true, true, 1, true, 40, true, 20, true, 20, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMSLog.pnARMSLog.ShapeInfoBox54", "ShapeInfoBox54", "IDC_ARMSLOG_SHAPEINFOBOX54", "TShape", "fARMSLog.pnARMSLog", "fARMSLog.pnARMSLog", 53, 2, "LEAF", true, true, 1, true, 20, true, 20, true, 20, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMSLog.pnARMSLog.pnARMSTitle", "pnARMSTitle", "IDC_ARMSLOG_PNARMSTITLE", "TPanel", "fARMSLog.pnARMSLog", "fARMSLog.pnARMSLog", 54, 2, "LEAF", false, true, 20, true, 20, true, 460, true, 40, true, 0, -1, "", "", true, "MS Sans Serif", -19, "fsBold", true, 65535, "clYellow", true, 8421376, "clTeal", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMSLog.pnARMSLog.MemoARMSLog", "MemoARMSLog", "IDC_ARMSLOG_MEMOARMSLOG", "TMemo", "fARMSLog.pnARMSLog", "fARMSLog.pnARMSLog", 55, 2, "LEAF", false, true, 5, true, 80, true, 490, true, 275, true, 1, -1, "", "", true, "標楷體", -16, "", true, 8388608, "clNavy", true, 16777215, "clWhite", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMSLog.pnARMSLog.pnButtonTitle", "pnButtonTitle", "IDD_ARMSLOG_PNARMSLOG_PNBUTTONTITLE", "TPanel", "fARMSLog.pnARMSLog", "fARMSLog.pnARMSLog", 56, 2, "SUBDLG", false, true, 0, true, 360, true, 500, true, 40, true, 2, -1, "", "", false, "", 0, "", false, 0, "", true, 16776960, "clAqua", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMSLog.pnARMSLog.pnButtonTitle.sbExit", "sbExit", "IDC_ARMSLOG_SBEXIT", "TSpeedButton", "fARMSLog.pnARMSLog.pnButtonTitle", "fARMSLog.pnARMSLog.pnButtonTitle", 0, 3, "LEAF", true, true, 383, true, 5, true, 110, true, 30, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fARMSLog.pnARMSLog.pnButtonTitle.sbSave", "sbSave", "IDC_ARMSLOG_SBSAVE", "TSpeedButton", "fARMSLog.pnARMSLog.pnButtonTitle", "fARMSLog.pnARMSLog.pnButtonTitle", 1, 3, "LEAF", true, true, 10, true, 5, true, 110, true, 30, false, 0, -1, "", "", true, "@新細明體", -16, "", true, 8388608, "clNavy", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
};

const int kARMSLogLayoutCount = 61;

} // namespace ht9045_layout
