// ===========================================================================
//  ASE_K Socket/aseTest_layout.gen.cpp
//  DO NOT EDIT -- GENERATED FILE. See the matching _layout.gen.h banner.
// ===========================================================================
#include "aseTest_layout.gen.h"

namespace ht9045_layout {

// (no custom-control properties in this form)

const DfmControlLayout kaseTestLayout[] = {
    { "ASESendMessage", "ASESendMessage", "", "TASESendMessage", "", "", 0, 0, "ROOT", false, true, 472, true, 216, true, 923, true, 490, false, 0, -1, "", "", true, "MS Sans Serif", -11, "", true, -2147483640, "clWindowText", true, 12761254, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "ASESendMessage.PageControl1", "PageControl1", "IDC_ASETEST_PAGECONTROL1", "TPageControl", "ASESendMessage", "ASESendMessage", 0, 1, "TABHOST", false, true, 0, true, 0, true, 432, true, 451, true, 0, -1, "alLeft", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "ASESendMessage.PageControl1.Commucation", "Commucation", "IDD_ASETEST_PAGECONTROL1_COMMUCATION", "TTabSheet", "ASESendMessage.PageControl1", "ASESendMessage", 0, 2, "SUBDLG", false, false, 0, false, 0, false, 0, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "ASESendMessage.PageControl1.Commucation.btnTest", "btnTest", "IDC_ASETEST_BTNTEST", "TButton", "ASESendMessage.PageControl1.Commucation", "ASESendMessage.PageControl1.Commucation", 0, 3, "LEAF", false, true, 280, true, 0, true, 75, true, 25, true, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "ASESendMessage.PageControl1.Commucation.edtTestMsg", "edtTestMsg", "IDC_ASETEST_EDTTESTMSG", "TEdit", "ASESendMessage.PageControl1.Commucation", "ASESendMessage.PageControl1.Commucation", 1, 3, "LEAF", false, true, 4, true, 4, true, 265, true, 21, true, 1, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "ASESendMessage.PageControl1.Commucation.edtRecvMsg", "edtRecvMsg", "IDC_ASETEST_EDTRECVMSG", "TEdit", "ASESendMessage.PageControl1.Commucation", "ASESendMessage.PageControl1.Commucation", 2, 3, "LEAF", false, true, 4, true, 40, true, 265, true, 21, true, 2, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "ASESendMessage.PageControl1.Commucation.btnTestRecv", "btnTestRecv", "IDC_ASETEST_BTNTESTRECV", "TButton", "ASESendMessage.PageControl1.Commucation", "ASESendMessage.PageControl1.Commucation", 3, 3, "LEAF", false, true, 280, true, 36, true, 75, true, 25, true, 3, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "ASESendMessage.PageControl1.Setup", "Setup", "IDD_ASETEST_PAGECONTROL1_SETUP", "TTabSheet", "ASESendMessage.PageControl1", "ASESendMessage", 1, 2, "SUBDLG", false, false, 0, false, 0, false, 0, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "ASESendMessage.PageControl1.Setup.Label1", "Label1", "IDC_ASETEST_LABEL1", "TLabel", "ASESendMessage.PageControl1.Setup", "ASESendMessage.PageControl1.Setup", 0, 3, "LEAF", true, true, 35, true, 3, true, 54, true, 13, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "ASESendMessage.PageControl1.Setup.Label24", "Label24", "IDC_ASETEST_LABEL24", "TLabel", "ASESendMessage.PageControl1.Setup", "ASESendMessage.PageControl1.Setup", 1, 3, "LEAF", true, true, 3, true, 23, true, 27, true, 13, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "ASESendMessage.PageControl1.Setup.Label2", "Label2", "IDC_ASETEST_LABEL2", "TLabel", "ASESendMessage.PageControl1.Setup", "ASESendMessage.PageControl1.Setup", 2, 3, "LEAF", true, true, 187, true, 3, true, 58, true, 13, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "ASESendMessage.PageControl1.Setup.Label3", "Label3", "IDC_ASETEST_LABEL3", "TLabel", "ASESendMessage.PageControl1.Setup", "ASESendMessage.PageControl1.Setup", 3, 3, "LEAF", true, true, 191, true, 243, true, 58, true, 13, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "ASESendMessage.PageControl1.Setup.IPAddress1", "IPAddress1", "IDC_ASETEST_IPADDRESS1", "TEdit", "ASESendMessage.PageControl1.Setup", "ASESendMessage.PageControl1.Setup", 4, 3, "LEAF", false, true, 35, true, 19, true, 121, true, 21, true, 1, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "ASESendMessage.PageControl1.Setup.IPPort1", "IPPort1", "IDC_ASETEST_IPPORT1", "TEdit", "ASESendMessage.PageControl1.Setup", "ASESendMessage.PageControl1.Setup", 5, 3, "LEAF", false, true, 187, true, 19, true, 121, true, 21, true, 2, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "ASESendMessage.PageControl1.Setup.Connect", "Connect", "IDC_ASETEST_CONNECT", "TButton", "ASESendMessage.PageControl1.Setup", "ASESendMessage.PageControl1.Setup", 6, 3, "LEAF", false, true, 320, true, 16, true, 100, true, 25, true, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "ASESendMessage.PageControl1.Setup.SaveData", "SaveData", "IDC_ASETEST_SAVEDATA", "TButton", "ASESendMessage.PageControl1.Setup", "ASESendMessage.PageControl1.Setup", 7, 3, "LEAF", false, true, 320, true, 48, true, 100, true, 25, true, 3, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "ASESendMessage.PageControl1.Setup.Button2", "Button2", "IDC_ASETEST_BUTTON2", "TButton", "ASESendMessage.PageControl1.Setup", "ASESendMessage.PageControl1.Setup", 8, 3, "LEAF", false, true, 316, true, 256, true, 100, true, 25, true, 4, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "ASESendMessage.PageControl1.Setup.IPPort2", "IPPort2", "IDC_ASETEST_IPPORT2", "TEdit", "ASESendMessage.PageControl1.Setup", "ASESendMessage.PageControl1.Setup", 9, 3, "LEAF", false, true, 191, true, 259, true, 121, true, 21, true, 5, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "ASESendMessage.Memo1", "Memo1", "IDC_ASETEST_MEMO1", "TMemo", "ASESendMessage", "ASESendMessage", 1, 1, "LEAF", false, true, 432, true, 0, true, 475, true, 451, true, 1, -1, "alClient", "", false, "", 0, "", false, 0, "", true, 14670284, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "ASESendMessage.NMUDP1", "NMUDP1", "", "TNMUDP", "ASESendMessage", "ASESendMessage", 2, 1, "NONVISUAL", false, true, 376, false, 0, false, 0, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "ASESendMessage.NMUDP2", "NMUDP2", "", "TNMUDP", "ASESendMessage", "ASESendMessage", 3, 1, "NONVISUAL", false, true, 404, false, 0, false, 0, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
};

const int kaseTestLayoutCount = 21;

} // namespace ht9045_layout
