// ===========================================================================
//  ASE_K Socket/DataCompileForm_layout.gen.cpp
//  DO NOT EDIT -- GENERATED FILE. See the matching _layout.gen.h banner.
// ===========================================================================
#include "DataCompileForm_layout.gen.h"

namespace ht9045_layout {

// (no custom-control properties in this form)

const DfmControlLayout kDataCompileFormLayout[] = {
    { "DataCompile", "DataCompile", "", "TDataCompile", "", "", 0, 0, "ROOT", false, true, 326, true, 165, true, 1309, true, 561, false, 0, -1, "", "", true, "MS Sans Serif", -11, "", true, -2147483640, "clWindowText", true, 12761254, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "DataCompile.Panel1", "Panel1", "IDD_DATACOMPILEFORM_PANEL1", "TPanel", "DataCompile", "DataCompile", 0, 1, "SUBDLG", false, true, 0, true, 0, true, 1301, true, 530, true, 0, -1, "alClient", "", false, "", 0, "", false, 0, "", true, 12761254, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "DataCompile.Panel1.Label1", "Label1", "IDC_DATACOMPILEFORM_LABEL1", "TLabel", "DataCompile.Panel1", "DataCompile.Panel1", 0, 2, "LEAF", true, true, 8, true, 24, true, 106, true, 29, false, 0, -1, "", "", true, "MS Sans Serif", -24, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "DataCompile.Panel1.Label2", "Label2", "IDC_DATACOMPILEFORM_LABEL2", "TLabel", "DataCompile.Panel1", "DataCompile.Panel1", 1, 2, "LEAF", true, true, 8, true, 80, true, 113, true, 29, false, 0, -1, "", "", true, "MS Sans Serif", -24, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "DataCompile.Panel1.Label3", "Label3", "IDC_DATACOMPILEFORM_LABEL3", "TLabel", "DataCompile.Panel1", "DataCompile.Panel1", 2, 2, "LEAF", true, true, 10, true, 405, true, 79, true, 29, false, 0, -1, "", "", true, "MS Sans Serif", -24, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "DataCompile.Panel1.Label4", "Label4", "IDC_DATACOMPILEFORM_LABEL4", "TLabel", "DataCompile.Panel1", "DataCompile.Panel1", 3, 2, "LEAF", true, true, 10, true, 282, true, 97, true, 29, false, 0, -1, "", "", true, "MS Sans Serif", -24, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "DataCompile.Panel1.Label5", "Label5", "IDC_DATACOMPILEFORM_LABEL5", "TLabel", "DataCompile.Panel1", "DataCompile.Panel1", 4, 2, "LEAF", true, true, 7, true, 140, true, 99, true, 29, false, 0, -1, "", "", true, "MS Sans Serif", -24, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "DataCompile.Panel1.Label6", "Label6", "IDC_DATACOMPILEFORM_LABEL6", "TLabel", "DataCompile.Panel1", "DataCompile.Panel1", 5, 2, "LEAF", true, true, 8, true, 192, true, 97, true, 29, false, 0, -1, "", "", true, "MS Sans Serif", -24, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "DataCompile.Panel1.Label7", "Label7", "IDC_DATACOMPILEFORM_LABEL7", "TLabel", "DataCompile.Panel1", "DataCompile.Panel1", 6, 2, "LEAF", true, true, 161, true, 239, true, 157, true, 29, false, 0, -1, "", "", true, "MS Sans Serif", -24, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "DataCompile.Panel1.Label8", "Label8", "IDC_DATACOMPILEFORM_LABEL8", "TLabel", "DataCompile.Panel1", "DataCompile.Panel1", 7, 2, "LEAF", true, true, 161, true, 366, true, 821, true, 29, false, 0, -1, "", "", true, "MS Sans Serif", -24, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "DataCompile.Panel1.Label9", "Label9", "IDC_DATACOMPILEFORM_LABEL9", "TLabel", "DataCompile.Panel1", "DataCompile.Panel1", 8, 2, "LEAF", true, true, 264, true, 461, true, 6, true, 29, false, 0, -1, "", "", true, "MS Sans Serif", -24, "", true, 255, "clRed", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "DataCompile.Panel1.edtWorkTemp", "edtWorkTemp", "IDC_DATACOMPILEFORM_EDTWORKTEMP", "TEdit", "DataCompile.Panel1", "DataCompile.Panel1", 9, 2, "LEAF", false, true, 161, true, 24, true, 121, true, 37, true, 0, -1, "", "", true, "MS Sans Serif", -24, "", true, -2147483640, "clWindowText", true, 65535, "clYellow", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "DataCompile.Panel1.edtSoakTime", "edtSoakTime", "IDC_DATACOMPILEFORM_EDTSOAKTIME", "TEdit", "DataCompile.Panel1", "DataCompile.Panel1", 10, 2, "LEAF", false, true, 161, true, 78, true, 121, true, 37, true, 1, -1, "", "", true, "MS Sans Serif", -24, "", true, -2147483640, "clWindowText", true, 65535, "clYellow", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "DataCompile.Panel1.edtForcePerPin", "edtForcePerPin", "IDC_DATACOMPILEFORM_EDTFORCEPERPIN", "TEdit", "DataCompile.Panel1", "DataCompile.Panel1", 11, 2, "LEAF", false, true, 161, true, 135, true, 121, true, 37, true, 2, -1, "", "", true, "MS Sans Serif", -24, "", true, -2147483640, "clWindowText", true, 65535, "clYellow", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "DataCompile.Panel1.edtPinCount", "edtPinCount", "IDC_DATACOMPILEFORM_EDTPINCOUNT", "TEdit", "DataCompile.Panel1", "DataCompile.Panel1", 12, 2, "LEAF", false, true, 161, true, 189, true, 121, true, 37, true, 3, -1, "", "", true, "MS Sans Serif", -24, "", true, -2147483640, "clWindowText", true, 65535, "clYellow", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "DataCompile.Panel1.edtSiteMap", "edtSiteMap", "IDC_DATACOMPILEFORM_EDTSITEMAP", "TEdit", "DataCompile.Panel1", "DataCompile.Panel1", 13, 2, "LEAF", false, true, 161, true, 288, true, 1065, true, 37, true, 4, -1, "", "", true, "MS Sans Serif", -24, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "DataCompile.Panel1.edtBinMap", "edtBinMap", "IDC_DATACOMPILEFORM_EDTBINMAP", "TEdit", "DataCompile.Panel1", "DataCompile.Panel1", 14, 2, "LEAF", false, true, 161, true, 415, true, 1065, true, 37, true, 5, -1, "", "", true, "MS Sans Serif", -24, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "DataCompile.Panel1.btnCompare", "btnCompare", "IDC_DATACOMPILEFORM_BTNCOMPARE", "TButton", "DataCompile.Panel1", "DataCompile.Panel1", 15, 2, "LEAF", false, true, 1056, true, 464, true, 145, true, 37, true, 6, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
};

const int kDataCompileFormLayoutCount = 18;

} // namespace ht9045_layout
