// ===========================================================================
//  ASE_K Socket/Socket_ASE_KR_layout.gen.cpp
//  DO NOT EDIT -- GENERATED FILE. See the matching _layout.gen.h banner.
// ===========================================================================
#include "Socket_ASE_KR_layout.gen.h"

namespace ht9045_layout {

// (no custom-control properties in this form)

const DfmControlLayout kSocket_ASE_KRLayout[] = {
    { "fSocketCommunication", "fSocketCommunication", "", "TfSocketCommunication", "", "", 0, 0, "ROOT", false, true, 556, true, 121, true, 378, true, 608, false, 0, -1, "", "", true, "MS Sans Serif", -11, "", true, -2147483640, "clWindowText", true, 12761254, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSocketCommunication.Splitter1", "Splitter1", "IDC_SOCKET_ASE_KR_SPLITTER1", "TSplitter", "fSocketCommunication", "fSocketCommunication", 0, 1, "LEAF", false, true, 0, true, 217, true, 369, true, 8, false, 0, -1, "alNone", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSocketCommunication.GroupBox1", "GroupBox1", "IDD_SOCKET_ASE_KR_GROUPBOX1", "TGroupBox", "fSocketCommunication", "fSocketCommunication", 1, 1, "SUBDLG", false, true, 0, true, 0, true, 369, true, 217, true, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSocketCommunication.GroupBox1.OnLine", "OnLine", "IDC_SOCKET_ASE_KR_ONLINE", "TSpeedButton", "fSocketCommunication.GroupBox1", "fSocketCommunication.GroupBox1", 0, 2, "LEAF", true, true, 308, true, 12, true, 45, true, 45, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSocketCommunication.GroupBox1.cbEnableSocket", "cbEnableSocket", "IDC_SOCKET_ASE_KR_CBENABLESOCKET", "TCheckBox", "fSocketCommunication.GroupBox1", "fSocketCommunication.GroupBox1", 1, 2, "LEAF", false, true, 16, true, 16, true, 177, true, 17, true, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSocketCommunication.GroupBox1.gbSetting", "gbSetting", "IDD_SOCKET_ASE_KR_GROUPBOX1_GBSETTING", "TGroupBox", "fSocketCommunication.GroupBox1", "fSocketCommunication.GroupBox1", 2, 2, "SUBDLG", false, true, 8, true, 40, true, 289, true, 121, true, 1, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSocketCommunication.GroupBox1.gbSetting.Label1", "Label1", "IDC_SOCKET_ASE_KR_LABEL1", "TLabel", "fSocketCommunication.GroupBox1.gbSetting", "fSocketCommunication.GroupBox1.gbSetting", 0, 3, "LEAF", true, true, 16, true, 58, true, 72, true, 13, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSocketCommunication.GroupBox1.gbSetting.Label2", "Label2", "IDC_SOCKET_ASE_KR_LABEL2", "TLabel", "fSocketCommunication.GroupBox1.gbSetting", "fSocketCommunication.GroupBox1.gbSetting", 1, 3, "LEAF", true, true, 16, true, 92, true, 53, true, 13, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSocketCommunication.GroupBox1.gbSetting.Label3", "Label3", "IDC_SOCKET_ASE_KR_LABEL3", "TLabel", "fSocketCommunication.GroupBox1.gbSetting", "fSocketCommunication.GroupBox1.gbSetting", 2, 3, "LEAF", true, true, 16, true, 24, true, 106, true, 13, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSocketCommunication.GroupBox1.gbSetting.edtServerIP_1", "edtServerIP_1", "IDC_SOCKET_ASE_KR_EDTSERVERIP_1", "TEdit", "fSocketCommunication.GroupBox1.gbSetting", "fSocketCommunication.GroupBox1.gbSetting", 3, 3, "LEAF", false, true, 96, true, 50, true, 41, true, 21, true, 1, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSocketCommunication.GroupBox1.gbSetting.edtServerPort", "edtServerPort", "IDC_SOCKET_ASE_KR_EDTSERVERPORT", "TEdit", "fSocketCommunication.GroupBox1.gbSetting", "fSocketCommunication.GroupBox1.gbSetting", 4, 3, "LEAF", false, true, 96, true, 84, true, 57, true, 21, true, 5, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSocketCommunication.GroupBox1.gbSetting.edtSocketTimeout", "edtSocketTimeout", "IDC_SOCKET_ASE_KR_EDTSOCKETTIMEOUT", "TEdit", "fSocketCommunication.GroupBox1.gbSetting", "fSocketCommunication.GroupBox1.gbSetting", 5, 3, "LEAF", false, true, 133, true, 16, true, 105, true, 21, true, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSocketCommunication.GroupBox1.gbSetting.edtServerIP_2", "edtServerIP_2", "IDC_SOCKET_ASE_KR_EDTSERVERIP_2", "TEdit", "fSocketCommunication.GroupBox1.gbSetting", "fSocketCommunication.GroupBox1.gbSetting", 6, 3, "LEAF", false, true, 144, true, 50, true, 41, true, 21, true, 2, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSocketCommunication.GroupBox1.gbSetting.edtServerIP_3", "edtServerIP_3", "IDC_SOCKET_ASE_KR_EDTSERVERIP_3", "TEdit", "fSocketCommunication.GroupBox1.gbSetting", "fSocketCommunication.GroupBox1.gbSetting", 7, 3, "LEAF", false, true, 192, true, 50, true, 41, true, 21, true, 3, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSocketCommunication.GroupBox1.gbSetting.edtServerIP_4", "edtServerIP_4", "IDC_SOCKET_ASE_KR_EDTSERVERIP_4", "TEdit", "fSocketCommunication.GroupBox1.gbSetting", "fSocketCommunication.GroupBox1.gbSetting", 8, 3, "LEAF", false, true, 240, true, 50, true, 41, true, 21, true, 4, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSocketCommunication.GroupBox1.btnOK", "btnOK", "IDC_SOCKET_ASE_KR_BTNOK", "TButton", "fSocketCommunication.GroupBox1", "fSocketCommunication.GroupBox1", 3, 2, "LEAF", false, true, 40, true, 176, true, 75, true, 25, true, 2, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSocketCommunication.GroupBox1.btnCancel", "btnCancel", "IDC_SOCKET_ASE_KR_BTNCANCEL", "TButton", "fSocketCommunication.GroupBox1", "fSocketCommunication.GroupBox1", 4, 2, "LEAF", false, true, 192, true, 176, true, 75, true, 25, true, 3, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSocketCommunication.GroupBox3", "GroupBox3", "IDD_SOCKET_ASE_KR_GROUPBOX3", "TGroupBox", "fSocketCommunication", "fSocketCommunication", 2, 1, "SUBDLG", false, true, 1, true, 224, true, 369, true, 137, true, 1, 0, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSocketCommunication.GroupBox3.btnC1N1", "btnC1N1", "IDC_SOCKET_ASE_KR_BTNC1N1", "TButton", "fSocketCommunication.GroupBox3", "fSocketCommunication.GroupBox3", 0, 2, "LEAF", false, true, 24, true, 24, true, 75, true, 25, true, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSocketCommunication.GroupBox3.btnC1N3", "btnC1N3", "IDC_SOCKET_ASE_KR_BTNC1N3", "TButton", "fSocketCommunication.GroupBox3", "fSocketCommunication.GroupBox3", 1, 2, "LEAF", false, true, 148, true, 24, true, 75, true, 25, true, 1, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSocketCommunication.GroupBox3.btnC6N1", "btnC6N1", "IDC_SOCKET_ASE_KR_BTNC6N1", "TButton", "fSocketCommunication.GroupBox3", "fSocketCommunication.GroupBox3", 2, 2, "LEAF", false, true, 272, true, 24, true, 75, true, 25, true, 2, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSocketCommunication.GroupBox3.btnC9N1", "btnC9N1", "IDC_SOCKET_ASE_KR_BTNC9N1", "TButton", "fSocketCommunication.GroupBox3", "fSocketCommunication.GroupBox3", 3, 2, "LEAF", false, true, 24, true, 64, true, 75, true, 25, true, 3, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSocketCommunication.GroupBox3.btnC9N3", "btnC9N3", "IDC_SOCKET_ASE_KR_BTNC9N3", "TButton", "fSocketCommunication.GroupBox3", "fSocketCommunication.GroupBox3", 4, 2, "LEAF", false, true, 148, true, 64, true, 75, true, 25, true, 4, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSocketCommunication.GroupBox3.btnC9N5", "btnC9N5", "IDC_SOCKET_ASE_KR_BTNC9N5", "TButton", "fSocketCommunication.GroupBox3", "fSocketCommunication.GroupBox3", 5, 2, "LEAF", false, true, 272, true, 64, true, 75, true, 25, true, 5, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSocketCommunication.GroupBox3.Button1", "Button1", "IDC_SOCKET_ASE_KR_BUTTON1", "TButton", "fSocketCommunication.GroupBox3", "fSocketCommunication.GroupBox3", 6, 2, "LEAF", false, true, 64, true, 104, true, 75, true, 25, true, 6, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSocketCommunication.GroupBox3.Button2", "Button2", "IDC_SOCKET_ASE_KR_BUTTON2", "TButton", "fSocketCommunication.GroupBox3", "fSocketCommunication.GroupBox3", 7, 2, "LEAF", false, true, 224, true, 104, true, 75, true, 25, true, 7, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSocketCommunication.Memo", "Memo", "IDC_SOCKET_ASE_KR_MEMO", "TMemo", "fSocketCommunication", "fSocketCommunication", 3, 1, "LEAF", false, true, 0, true, 368, true, 369, true, 209, true, 2, 0, "", "", false, "", 0, "", false, 0, "", true, 14670284, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSocketCommunication.ClientSocket1", "ClientSocket1", "", "TClientSocket", "fSocketCommunication", "fSocketCommunication", 4, 1, "NONVISUAL", false, true, 272, true, 8, false, 0, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSocketCommunication.Timer1", "Timer1", "", "TTimer", "fSocketCommunication", "fSocketCommunication", 5, 1, "NONVISUAL", false, true, 304, true, 64, false, 0, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
};

const int kSocket_ASE_KRLayoutCount = 29;

} // namespace ht9045_layout
