// ===========================================================================
//  ui/layout/UiFormMap.h -- schema for the generated *_uimap.gen.{h,cpp}
//  join tables (D-GA4-1).
//
//  AI(W906-GA4) 20260804: NEW FILE, hand-authored SCHEMA (the per-form
//  *_uimap.gen.* files ARE generated by tools/dfm2rc/emit_uimap.py and carry
//  their own DO-NOT-EDIT banners). Same schema-vs-data split as
//  tools/dfm2rc/layout_out/DfmLayoutTypes.h, and for the same ODR reason.
//
//  WHY THIS TABLE EXISTS (the gap it closes -- docs/DESIGN_GA4_UI_ENGINES.md):
//  the layout table (DfmControlLayout) carries id_symbol STRINGS
//  ("IDC_MAIN_PGMAIN" / "IDD_MAIN_PGMAIN_TSMAIN"); the numeric values live
//  only in the generated _ids.h #defines and in the .rcmeta.json sidecar.
//  A runtime engine cannot resolve a string to a #define, so the join is
//  baked here at generation time, from rcmeta (the pipeline's sanctioned
//  join source -- see DfmLayoutTypes.h note 1's gate_id_symbol_join).
//  It also carries the four things the layout table truthfully lacks:
//    * synthesized controls (SYNTH_CONTAINER_FRAME / SYNTH_RADIOGROUP_ITEM)
//      -- they have numeric IDs but NO layout row (D-GA4-4's rescale set);
//    * TTabSheet captions (tab text; .dfm Caption, absent from both the
//      child DIALOGEX template and the layout table);
//    * per-TPageControl ActivePage / TabWidth;
//    * the ROOT client size (.dfm stores ClientWidth/ClientHeight, which are
//      NOT the Left/Top/Width/Height quartet the layout table carries).
//
//  JOIN KEYS. UiMapDialog::dfm_path and UiMapControl::source_path join
//  DfmControlLayout::dfm_path (the D11 name-join, string compare). Rows for
//  synthesized controls use the generator-invented source_path, which by
//  construction never collides with a real .dfm path and simply finds no
//  layout row -- that "miss" is meaningful (it selects the D-GA4-4 set).
// ===========================================================================
#ifndef HT9045_UI_LAYOUT_UIFORMMAP_H
#define HT9045_UI_LAYOUT_UIFORMMAP_H

namespace ht9045_uimap {

struct UiMapDialog {
    const char* dfm_path;      // "" never; e.g. "fMain", "fMain.pgMain.tsMain"
    int         idd_value;     // numeric dialog-template id (rcmeta idd_value)
    const char* owner_class;   // "TfMain" | "TTabSheet" | "TPanel" | ...
    const char* caption_utf8;  // IR Caption, "" when absent. UTF-8 (CJK real).
    bool        is_root;       // exactly one true row per form
};

struct UiMapControl {
    const char* source_path;   // joins DfmControlLayout::dfm_path (see banner)
    int         id_value;      // numeric control id (rcmeta controls[].value)
    const char* host_dfm_path; // owner dialog's dfm_path (rcmeta nesting).
                               // Carried HERE because a synthesized control
                               // has no layout row to learn its host from --
                               // GetDlgItem(hwnd(host_dfm_path), id_value) is
                               // how every control HWND gets indexed.
    bool        synthesized;   // true -> no layout row exists, D-GA4-4 set
    const char* rule;          // "" | "SYNTH_CONTAINER_FRAME" |
                               //      "SYNTH_RADIOGROUP_ITEM"
};

struct UiMapTabHost {
    const char* dfm_path;          // the TPageControl node's path
    const char* active_page_path;  // dfm_path of the initial TTabSheet;
                                   // "" -> first inserted tab
    int         tab_width;         // .dfm TabWidth; 0 = auto-sized tabs
};

struct UiMapForm {
    const char* form_stem;         // "main"
    int         root_client_w;     // IR ClientWidth (fallback Width; see
    int         root_client_h;     //   emit_uimap.py for the exact rule)
    const UiMapDialog*  dialogs;   int dialog_count;   // rcmeta order (pre-order,
                                                       // parents before children)
    const UiMapControl* controls;  int control_count;
    const UiMapTabHost* tabhosts;  int tabhost_count;
};

} // namespace ht9045_uimap

#endif // HT9045_UI_LAYOUT_UIFORMMAP_H
