#ifndef IncludeAllHeaderH
#define IncludeAllHeaderH

#include <vcl.h>
#include <vcl\vcl.h>
#include <stdlib.h>
#include <shellapi.h>
#include <time.h>
#include <dir.h>
#include <printers.hpp>
#include <vcl/inifiles.hpp>
#include <tlhelp32.h>
#include <windows.h>
#include <comctrls.hpp>

//---------------------------------------------------------------------------

#include <fcntl.h>


#include <winbase.h>
#include <io.h>

#include <algorithm.h>

#include <string.h>
#include <stdio.h>
#include <mmsystem.h>

#include <assert.h>
#include <vector.h>
#include <ComObj.hpp>
#include <utilcls.h>
#include <math.h>
#include <Registry.hpp>
#include <NMFtp.hpp>
#include <Filectrl.hpp>
#include <bitset>

#include <Classes.hpp>
#include <Controls.hpp>
#include <StdCtrls.hpp>
#include <Forms.hpp>


//#include "Dmccom.h"
//#include "HSL.h"
//#include "HSL_ErrorCode.h"
//#include "Mc88x1p_DLL.h"
//#include "handlerlog.h"
//#include "type_def.H"
//#include "CMNETError.H"
//#include "PCI_L112.H"
//#include "PCI_L122.H"
//#include "CMNET.h"
//#include "CMNETError.h"
//#include "Hontech_M4.H"
//#include "MN200.h"

//#include "mySYNTEKmotor.h" //pig 2014.09.05 TUBE IN\OUT MODE
//#include "MyLaneIo.h"    //pig 2014.09.05 TUBE IN\OUT MODE


using namespace std;

#endif
