// ===========================================================================
//  RotateKit/fRotate_layout.gen.cpp
//  DO NOT EDIT -- GENERATED FILE. See the matching _layout.gen.h banner.
// ===========================================================================
#include "fRotate_layout.gen.h"

namespace ht9045_layout {

const DfmCustomProp kfRotateCustomProps[] = {
    { "XItem", "4" },
};

const DfmControlLayout kfRotateLayout[] = {
    { "FrmRotate", "FrmRotate", "", "TFrmRotate", "", "", 0, 0, "ROOT", false, true, 443, true, 216, true, 800, true, 595, false, 0, -1, "", "", true, "MS Sans Serif", -11, "", true, -2147483640, "clWindowText", true, 13550775, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "FrmRotate.Panel1", "Panel1", "IDD_FROTATE_PANEL1", "TPanel", "FrmRotate", "FrmRotate", 0, 1, "SUBDLG", false, true, 0, true, 0, true, 792, true, 564, true, 0, -1, "alClient", "", true, "MS Sans Serif", -16, "", true, -2147483640, "clWindowText", true, 13550775, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "FrmRotate.Panel1.spbSave", "spbSave", "IDC_FROTATE_SPBSAVE", "TSpeedButton", "FrmRotate.Panel1", "FrmRotate.Panel1", 0, 2, "LEAF", true, true, 74, true, 512, true, 227, true, 40, false, 0, -1, "", "", true, "Arial", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "FrmRotate.Panel1.sbtExit", "sbtExit", "IDC_FROTATE_SBTEXIT", "TSpeedButton", "FrmRotate.Panel1", "FrmRotate.Panel1", 1, 2, "LEAF", true, true, 384, true, 512, true, 241, true, 41, false, 0, -1, "", "", true, "Arial", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "FrmRotate.Panel1.Label_Err", "Label_Err", "IDC_FROTATE_LABEL_ERR", "TLabel", "FrmRotate.Panel1", "FrmRotate.Panel1", 2, 2, "LEAF", true, true, 1, true, 1, true, 790, true, 20, false, 0, 0, "alTop", "", true, "MS Sans Serif", -19, "", true, 255, "clRed", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "FrmRotate.Panel1.LabelRotatePositon", "LabelRotatePositon", "IDC_FROTATE_LABELROTATEPOSITON", "TLabel", "FrmRotate.Panel1", "FrmRotate.Panel1", 3, 2, "LEAF", true, true, 792, true, 68, true, 217, true, 29, false, 0, -1, "", "", true, "MS Sans Serif", -24, "fsBold", true, 16711680, "clBlue", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "FrmRotate.Panel1.rgDutNum", "rgDutNum", "IDD_FROTATE_PANEL1_RGDUTNUM", "TRadioGroup", "FrmRotate.Panel1", "FrmRotate.Panel1", 4, 2, "SUBDLG", false, true, 8, true, 32, true, 209, true, 89, true, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "FrmRotate.Panel1.rgSelect", "rgSelect", "IDD_FROTATE_PANEL1_RGSELECT", "TRadioGroup", "FrmRotate.Panel1", "FrmRotate.Panel1", 5, 2, "SUBDLG", false, true, 8, true, 128, true, 153, true, 89, true, 3, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "FrmRotate.Panel1.GroupBox1", "GroupBox1", "IDD_FROTATE_PANEL1_GROUPBOX1", "TGroupBox", "FrmRotate.Panel1", "FrmRotate.Panel1", 6, 2, "SUBDLG", false, true, 8, true, 228, true, 153, true, 121, true, 5, -1, "", "", false, "", 0, "", false, 0, "", true, 8454143, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "FrmRotate.Panel1.GroupBox1.sgFTA", "sgFTA", "IDC_FROTATE_SGFTA", "TStringGrid", "FrmRotate.Panel1.GroupBox1", "FrmRotate.Panel1.GroupBox1", 0, 3, "LEAF", false, true, 2, true, 22, true, 149, true, 97, true, 0, -1, "alClient", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "FrmRotate.Panel1.cbActiveRotate", "cbActiveRotate", "IDC_FROTATE_CBACTIVEROTATE", "TCheckBox", "FrmRotate.Panel1", "FrmRotate.Panel1", 7, 2, "LEAF", false, true, 248, true, 32, true, 529, true, 37, true, 1, -1, "", "", true, "MS Sans Serif", -19, "fsBold", true, 8388608, "clNavy", true, 8454143, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "FrmRotate.Panel1.tmyRotatePosion", "tmyRotatePosion", "IDC_FROTATE_TMYROTATEPOSION", "TTMyTray", "FrmRotate.Panel1", "FrmRotate.Panel1", 8, 2, "LEAF", false, true, 792, true, 121, true, 366, true, 200, false, 0, -1, "", "", false, "", 0, "", false, 0, "", true, 16777215, "clWhite", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 1, &kfRotateCustomProps[0] },
    { "FrmRotate.Panel1.pgcRotate", "pgcRotate", "IDC_FROTATE_PGCROTATE", "TPageControl", "FrmRotate.Panel1", "FrmRotate.Panel1", 9, 2, "TABHOST", false, true, 246, true, 72, true, 529, true, 373, true, 2, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "FrmRotate.Panel1.pgcRotate.tsM1RotateIn", "tsM1RotateIn", "IDD_FROTATE_PANEL1_PGCROTATE_TSM1ROTATEIN", "TTabSheet", "FrmRotate.Panel1.pgcRotate", "FrmRotate.Panel1", 0, 3, "SUBDLG", false, false, 0, false, 0, false, 0, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "FrmRotate.Panel1.pgcRotate.tsM1RotateIn.sgRotateIn", "sgRotateIn", "IDC_FROTATE_SGROTATEIN", "TStringGrid", "FrmRotate.Panel1.pgcRotate.tsM1RotateIn", "FrmRotate.Panel1.pgcRotate.tsM1RotateIn", 0, 4, "LEAF", false, true, 0, true, 0, true, 521, true, 338, true, 0, -1, "alClient", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "FrmRotate.Panel1.pgcRotate.tsM1RotateOut", "tsM1RotateOut", "IDD_FROTATE_PANEL1_PGCROTATE_TSM1ROTATEOUT", "TTabSheet", "FrmRotate.Panel1.pgcRotate", "FrmRotate.Panel1", 1, 3, "SUBDLG", false, false, 0, false, 0, false, 0, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "FrmRotate.Panel1.pgcRotate.tsM1RotateOut.sgRotateOut", "sgRotateOut", "IDC_FROTATE_SGROTATEOUT", "TStringGrid", "FrmRotate.Panel1.pgcRotate.tsM1RotateOut", "FrmRotate.Panel1.pgcRotate.tsM1RotateOut", 0, 4, "LEAF", false, true, 0, true, 0, true, 521, true, 338, true, 0, -1, "alClient", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "FrmRotate.Panel1.pgcRotate.tsM8RotateIn", "tsM8RotateIn", "IDD_FROTATE_PANEL1_PGCROTATE_TSM8ROTATEIN", "TTabSheet", "FrmRotate.Panel1.pgcRotate", "FrmRotate.Panel1", 2, 3, "SUBDLG", false, false, 0, false, 0, false, 0, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "FrmRotate.Panel1.pgcRotate.tsM8RotateOut", "tsM8RotateOut", "IDD_FROTATE_PANEL1_PGCROTATE_TSM8ROTATEOUT", "TTabSheet", "FrmRotate.Panel1.pgcRotate", "FrmRotate.Panel1", 3, 3, "SUBDLG", false, false, 0, false, 0, false, 0, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "FrmRotate.Panel1.pgcRotate.tsM1RotateInRT", "tsM1RotateInRT", "IDD_FROTATE_PANEL1_PGCROTATE_TSM1ROTATEINRT", "TTabSheet", "FrmRotate.Panel1.pgcRotate", "FrmRotate.Panel1", 4, 3, "SUBDLG", false, false, 0, false, 0, false, 0, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "FrmRotate.Panel1.pgcRotate.tsM1RotateInRT.sgRotateInRT", "sgRotateInRT", "IDC_FROTATE_SGROTATEINRT", "TStringGrid", "FrmRotate.Panel1.pgcRotate.tsM1RotateInRT", "FrmRotate.Panel1.pgcRotate.tsM1RotateInRT", 0, 4, "LEAF", false, true, 0, true, 0, true, 521, true, 338, true, 0, -1, "alClient", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "FrmRotate.Panel1.pgcRotate.tsM1RotateOutRT", "tsM1RotateOutRT", "IDD_FROTATE_PANEL1_PGCROTATE_TSM1ROTATEOUTRT", "TTabSheet", "FrmRotate.Panel1.pgcRotate", "FrmRotate.Panel1", 5, 3, "SUBDLG", false, false, 0, false, 0, false, 0, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "FrmRotate.Panel1.pgcRotate.tsM1RotateOutRT.sgRotateOutRT", "sgRotateOutRT", "IDC_FROTATE_SGROTATEOUTRT", "TStringGrid", "FrmRotate.Panel1.pgcRotate.tsM1RotateOutRT", "FrmRotate.Panel1.pgcRotate.tsM1RotateOutRT", 0, 4, "LEAF", false, true, 0, true, 0, true, 521, true, 338, true, 0, -1, "alClient", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "FrmRotate.Panel1.cbOutRotateDifferentAngle", "cbOutRotateDifferentAngle", "IDC_FROTATE_CBOUTROTATEDIFFERENTANGLE", "TCheckBox", "FrmRotate.Panel1", "FrmRotate.Panel1", 10, 2, "LEAF", false, true, 8, true, 456, true, 265, true, 25, true, 9, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "FrmRotate.Panel1.Edit1", "Edit1", "IDC_FROTATE_EDIT1", "TEdit", "FrmRotate.Panel1", "FrmRotate.Panel1", 11, 2, "LEAF", false, true, 170, true, 414, true, 63, true, 28, true, 7, 0, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "FrmRotate.Panel1.chkPassBinNoRotate", "chkPassBinNoRotate", "IDC_FROTATE_CHKPASSBINNOROTATE", "TCheckBox", "FrmRotate.Panel1", "FrmRotate.Panel1", 12, 2, "LEAF", false, true, 8, true, 479, true, 169, true, 25, true, 10, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "FrmRotate.Panel1.chkRotateUseRTmode", "chkRotateUseRTmode", "IDC_FROTATE_CHKROTATEUSERTMODE", "TCheckBox", "FrmRotate.Panel1", "FrmRotate.Panel1", 13, 2, "LEAF", false, true, 192, true, 479, true, 169, true, 25, true, 11, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "FrmRotate.Panel1.chkART_RTNoRotate", "chkART_RTNoRotate", "IDC_FROTATE_CHKART_RTNOROTATE", "TCheckBox", "FrmRotate.Panel1", "FrmRotate.Panel1", 14, 2, "LEAF", false, true, 384, true, 479, true, 169, true, 25, true, 12, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "FrmRotate.Panel1.YPitch", "YPitch", "IDC_FROTATE_YPITCH", "TLabeledEdit", "FrmRotate.Panel1", "FrmRotate.Panel1", 15, 2, "LEAF", false, true, 172, true, 280, true, 65, true, 28, true, 6, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "FrmRotate.Panel1.XPitch", "XPitch", "IDC_FROTATE_XPITCH", "TLabeledEdit", "FrmRotate.Panel1", "FrmRotate.Panel1", 16, 2, "LEAF", false, true, 524, true, 448, true, 65, true, 28, true, 8, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "FrmRotate.Panel1.grpRotateOffset", "grpRotateOffset", "IDD_FROTATE_PANEL1_GRPROTATEOFFSET", "TGroupBox", "FrmRotate.Panel1", "FrmRotate.Panel1", 17, 2, "SUBDLG", false, true, 2, true, 356, true, 159, true, 77, true, 13, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "FrmRotate.Panel1.grpRotateOffset.Label1", "Label1", "IDC_FROTATE_LABEL1", "TLabel", "FrmRotate.Panel1.grpRotateOffset", "FrmRotate.Panel1.grpRotateOffset", 0, 3, "LEAF", true, true, 2, true, 40, true, 49, true, 20, false, 0, -1, "", "", true, "MS Sans Serif", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "FrmRotate.Panel1.grpRotateOffset.Label5", "Label5", "IDC_FROTATE_LABEL5", "TLabel", "FrmRotate.Panel1.grpRotateOffset", "FrmRotate.Panel1.grpRotateOffset", 1, 3, "LEAF", true, true, 54, true, 24, true, 37, true, 16, false, 0, -1, "", "", true, "MS Sans Serif", -13, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "FrmRotate.Panel1.grpRotateOffset.Label6", "Label6", "IDC_FROTATE_LABEL6", "TLabel", "FrmRotate.Panel1.grpRotateOffset", "FrmRotate.Panel1.grpRotateOffset", 2, 3, "LEAF", true, true, 106, true, 24, true, 47, true, 16, false, 0, -1, "", "", true, "MS Sans Serif", -13, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "FrmRotate.Panel1.grpRotateOffset.edInRotate_0", "edInRotate_0", "IDC_FROTATE_EDINROTATE_0", "TEdit", "FrmRotate.Panel1.grpRotateOffset", "FrmRotate.Panel1.grpRotateOffset", 3, 3, "LEAF", false, true, 54, true, 40, true, 40, true, 24, true, 0, -1, "", "", true, "MS Sans Serif", -13, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "FrmRotate.Panel1.grpRotateOffset.edOutRotate_0", "edOutRotate_0", "IDC_FROTATE_EDOUTROTATE_0", "TEdit", "FrmRotate.Panel1.grpRotateOffset", "FrmRotate.Panel1.grpRotateOffset", 4, 3, "LEAF", false, true, 106, true, 40, true, 40, true, 24, true, 1, -1, "", "", true, "MS Sans Serif", -13, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
};

const int kfRotateLayoutCount = 36;

} // namespace ht9045_layout
