// ============================================================================
// DO NOT EDIT -- machine-generated by emit_rc.py W7-B1b v1.0 on BarCode/BarcodeXML.dfm
// AI(W906-W7-B1b) 20260728: generated .rc/_ids.h from the .dfm IR (see
// docs/W7_UI_ARCHITECTURE_PLAN.md S6 W7-B1b). Hand edits will be
// overwritten and are rejected by the idempotence gate (G7).
// Source golden: BarCode/BarcodeXML.dfm
// ============================================================================

#ifndef HT9045_UI_GEN_BARCODEXML_IDS_H
#define HT9045_UI_GEN_BARCODEXML_IDS_H

// Dialog template IDs
#define IDD_BARCODEXML 8192

// Control IDs (D11 join key: mechanically derived from the
// .dfm leaf control name -- IDC_<FORMSTEM>_<CONTROLNAME>)

#endif // HT9045_UI_GEN_BARCODEXML_IDS_H
