// ===========================================================================
//  VacuumUnit/VacuumUnit_layout.gen.cpp
//  DO NOT EDIT -- GENERATED FILE. See the matching _layout.gen.h banner.
// ===========================================================================
#include "VacuumUnit_layout.gen.h"

namespace ht9045_layout {

const DfmCustomProp kVacuumUnitCustomProps[] = {
    { "LEDStyle", "LEDSqLarge" },
    { "Alias", "InArmSuckA_On" },
    { "TrueColor", "14464261" },
    { "FalseColor", "10307329" },
    { "TrueFontColor", "clWhite" },
    { "FalseFontColor", "clWhite" },
    { "Alias", "InArmSuckA_Off" },
    { "TrueColor", "14464261" },
    { "FalseColor", "10307329" },
    { "TrueFontColor", "clWhite" },
    { "FalseFontColor", "clWhite" },
};

const DfmControlLayout kVacuumUnitLayout[] = {
    { "fVacuumUnit", "fVacuumUnit", "", "TfVacuumUnit", "", "", 0, 0, "ROOT", false, true, 756, true, 127, true, 655, true, 711, false, 0, -1, "", "", true, "MS Sans Serif", -11, "", true, -2147483640, "clWindowText", true, -2147483633, "clBtnFace", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fVacuumUnit.pgcVacuumUnit", "pgcVacuumUnit", "IDC_VACUUMUNIT_PGCVACUUMUNIT", "TPageControl", "fVacuumUnit", "fVacuumUnit", 0, 1, "TABHOST", false, true, 0, true, 0, true, 647, true, 616, true, 0, -1, "alClient", "", true, "Arial", -17, "fsBold", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fVacuumUnit.pgcVacuumUnit.tsManual", "tsManual", "IDD_VACUUMUNIT_PGCVACUUMUNIT_TSMANUAL", "TTabSheet", "fVacuumUnit.pgcVacuumUnit", "fVacuumUnit", 0, 2, "SUBDLG", false, false, 0, false, 0, false, 0, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fVacuumUnit.pgcVacuumUnit.tsManual.GroupBox1", "GroupBox1", "IDD_VACUUMUNIT_PGCVACUUMUNIT_TSMANUAL_GROUPBOX1", "TGroupBox", "fVacuumUnit.pgcVacuumUnit.tsManual", "fVacuumUnit.pgcVacuumUnit.tsManual", 0, 3, "SUBDLG", false, true, 520, true, 0, true, 81, true, 177, true, 1, 0, "", "", false, "", 0, "", false, 0, "", true, -2147483633, "clBtnFace", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fVacuumUnit.pgcVacuumUnit.tsManual.GroupBox1.btnSV", "btnSV", "IDC_VACUUMUNIT_BTNSV", "TSpeedButton", "fVacuumUnit.pgcVacuumUnit.tsManual.GroupBox1", "fVacuumUnit.pgcVacuumUnit.tsManual.GroupBox1", 0, 4, "LEAF", true, true, 6, true, 92, true, 71, true, 23, false, 0, -1, "", "", true, "MS Sans Serif", -13, "fsBold", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fVacuumUnit.pgcVacuumUnit.tsManual.GroupBox1.myld1", "myld1", "IDC_VACUUMUNIT_MYLD1", "TMyLed", "fVacuumUnit.pgcVacuumUnit.tsManual.GroupBox1", "fVacuumUnit.pgcVacuumUnit.tsManual.GroupBox1", 1, 4, "LEAF", true, true, 30, true, 149, true, 20, true, 20, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 1, &kVacuumUnitCustomProps[0] },
    { "fVacuumUnit.pgcVacuumUnit.tsManual.GroupBox1.pnlCurectVal", "pnlCurectVal", "IDC_VACUUMUNIT_PNLCURECTVAL", "TPanel", "fVacuumUnit.pgcVacuumUnit.tsManual.GroupBox1", "fVacuumUnit.pgcVacuumUnit.tsManual.GroupBox1", 2, 4, "LEAF", false, true, 0, true, 12, true, 75, true, 15, true, 0, -1, "", "", true, "Arial", -15, "fsBold", true, 128, "clMaroon", true, 14540252, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fVacuumUnit.pgcVacuumUnit.tsManual.GroupBox1.pnlThreshold", "pnlThreshold", "IDC_VACUUMUNIT_PNLTHRESHOLD", "TPanel", "fVacuumUnit.pgcVacuumUnit.tsManual.GroupBox1", "fVacuumUnit.pgcVacuumUnit.tsManual.GroupBox1", 3, 4, "LEAF", false, true, 1, true, 52, true, 73, true, 14, true, 2, -1, "", "", true, "Arial", -15, "fsBold", true, 16711680, "clBlue", true, 14540252, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fVacuumUnit.pgcVacuumUnit.tsManual.GroupBox1.pnlEvent", "pnlEvent", "IDC_VACUUMUNIT_PNLEVENT", "TPanel", "fVacuumUnit.pgcVacuumUnit.tsManual.GroupBox1", "fVacuumUnit.pgcVacuumUnit.tsManual.GroupBox1", 4, 4, "LEAF", false, true, 3, true, 32, true, 73, true, 16, true, 1, -1, "", "", true, "Arial", -11, "fsBold", true, 0, "clBlack", true, 14540252, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fVacuumUnit.pgcVacuumUnit.tsManual.GroupBox1.edSV", "edSV", "IDC_VACUUMUNIT_EDSV", "TEdit", "fVacuumUnit.pgcVacuumUnit.tsManual.GroupBox1", "fVacuumUnit.pgcVacuumUnit.tsManual.GroupBox1", 5, 4, "LEAF", false, true, 5, true, 72, true, 71, true, 20, true, 3, -1, "", "", true, "Arial", -13, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fVacuumUnit.pgcVacuumUnit.tsManual.GroupBox1.bplOn", "bplOn", "IDC_VACUUMUNIT_BPLON", "TBtnPanelLane", "fVacuumUnit.pgcVacuumUnit.tsManual.GroupBox1", "fVacuumUnit.pgcVacuumUnit.tsManual.GroupBox1", 6, 4, "LEAF", false, true, 15, true, 120, true, 22, true, 24, true, 4, -1, "", "", true, "Arial", -13, "", true, 16777215, "clWhite", true, 10307329, "", true, 14464261, "", true, 10307329, "", true, 16777215, "clWhite", true, 16777215, "clWhite", 5, &kVacuumUnitCustomProps[1] },
    { "fVacuumUnit.pgcVacuumUnit.tsManual.GroupBox1.bplOff", "bplOff", "IDC_VACUUMUNIT_BPLOFF", "TBtnPanelLane", "fVacuumUnit.pgcVacuumUnit.tsManual.GroupBox1", "fVacuumUnit.pgcVacuumUnit.tsManual.GroupBox1", 7, 4, "LEAF", false, true, 41, true, 120, true, 22, true, 24, true, 5, -1, "", "", true, "Arial", -13, "", true, 16777215, "clWhite", true, 10307329, "", true, 14464261, "", true, 10307329, "", true, 16777215, "clWhite", true, 16777215, "clWhite", 5, &kVacuumUnitCustomProps[6] },
    { "fVacuumUnit.pgcVacuumUnit.tsManual.CheckBox1", "CheckBox1", "IDC_VACUUMUNIT_CHECKBOX1", "TCheckBox", "fVacuumUnit.pgcVacuumUnit.tsManual", "fVacuumUnit.pgcVacuumUnit.tsManual", 1, 3, "LEAF", false, true, 40, true, 408, true, 97, true, 17, true, 2, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fVacuumUnit.pgcVacuumUnit.tsManual.Edit1", "Edit1", "IDC_VACUUMUNIT_EDIT1", "TEdit", "fVacuumUnit.pgcVacuumUnit.tsManual", "fVacuumUnit.pgcVacuumUnit.tsManual", 2, 3, "LEAF", false, true, 40, true, 432, true, 121, true, 27, true, 3, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fVacuumUnit.pgcVacuumUnit.tsManual.grpSetAllValue", "grpSetAllValue", "IDD_VACUUMUNIT_PGCVACUUMUNIT_TSMANUAL_GRPSETALLVALUE", "TGroupBox", "fVacuumUnit.pgcVacuumUnit.tsManual", "fVacuumUnit.pgcVacuumUnit.tsManual", 3, 3, "SUBDLG", false, true, 0, true, 0, true, 297, true, 113, true, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fVacuumUnit.pgcVacuumUnit.tsManual.grpSetAllValue.lblInArm", "lblInArm", "IDC_VACUUMUNIT_LBLINARM", "TLabel", "fVacuumUnit.pgcVacuumUnit.tsManual.grpSetAllValue", "fVacuumUnit.pgcVacuumUnit.tsManual.grpSetAllValue", 0, 4, "LEAF", true, true, 30, true, 24, true, 46, true, 19, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fVacuumUnit.pgcVacuumUnit.tsManual.grpSetAllValue.lblIndexArm", "lblIndexArm", "IDC_VACUUMUNIT_LBLINDEXARM", "TLabel", "fVacuumUnit.pgcVacuumUnit.tsManual.grpSetAllValue", "fVacuumUnit.pgcVacuumUnit.tsManual.grpSetAllValue", 1, 4, "LEAF", true, true, 104, true, 24, true, 74, true, 19, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fVacuumUnit.pgcVacuumUnit.tsManual.grpSetAllValue.lblOutArm", "lblOutArm", "IDC_VACUUMUNIT_LBLOUTARM", "TLabel", "fVacuumUnit.pgcVacuumUnit.tsManual.grpSetAllValue", "fVacuumUnit.pgcVacuumUnit.tsManual.grpSetAllValue", 2, 4, "LEAF", true, true, 199, true, 24, true, 61, true, 19, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fVacuumUnit.pgcVacuumUnit.tsManual.grpSetAllValue.btnSetInArm", "btnSetInArm", "IDC_VACUUMUNIT_BTNSETINARM", "TButton", "fVacuumUnit.pgcVacuumUnit.tsManual.grpSetAllValue", "fVacuumUnit.pgcVacuumUnit.tsManual.grpSetAllValue", 3, 4, "LEAF", false, true, 24, true, 80, true, 57, true, 25, true, 3, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fVacuumUnit.pgcVacuumUnit.tsManual.grpSetAllValue.edSetInArm", "edSetInArm", "IDC_VACUUMUNIT_EDSETINARM", "TEdit", "fVacuumUnit.pgcVacuumUnit.tsManual.grpSetAllValue", "fVacuumUnit.pgcVacuumUnit.tsManual.grpSetAllValue", 4, 4, "LEAF", false, true, 16, true, 48, true, 73, true, 27, true, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fVacuumUnit.pgcVacuumUnit.tsManual.grpSetAllValue.edSetIndexArm", "edSetIndexArm", "IDC_VACUUMUNIT_EDSETINDEXARM", "TEdit", "fVacuumUnit.pgcVacuumUnit.tsManual.grpSetAllValue", "fVacuumUnit.pgcVacuumUnit.tsManual.grpSetAllValue", 5, 4, "LEAF", false, true, 104, true, 48, true, 73, true, 27, true, 1, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fVacuumUnit.pgcVacuumUnit.tsManual.grpSetAllValue.btnSetIndexArm", "btnSetIndexArm", "IDC_VACUUMUNIT_BTNSETINDEXARM", "TButton", "fVacuumUnit.pgcVacuumUnit.tsManual.grpSetAllValue", "fVacuumUnit.pgcVacuumUnit.tsManual.grpSetAllValue", 6, 4, "LEAF", false, true, 112, true, 80, true, 57, true, 25, true, 4, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fVacuumUnit.pgcVacuumUnit.tsManual.grpSetAllValue.btnSetOutArm", "btnSetOutArm", "IDC_VACUUMUNIT_BTNSETOUTARM", "TButton", "fVacuumUnit.pgcVacuumUnit.tsManual.grpSetAllValue", "fVacuumUnit.pgcVacuumUnit.tsManual.grpSetAllValue", 7, 4, "LEAF", false, true, 200, true, 80, true, 57, true, 25, true, 5, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fVacuumUnit.pgcVacuumUnit.tsManual.grpSetAllValue.edSetOutArm", "edSetOutArm", "IDC_VACUUMUNIT_EDSETOUTARM", "TEdit", "fVacuumUnit.pgcVacuumUnit.tsManual.grpSetAllValue", "fVacuumUnit.pgcVacuumUnit.tsManual.grpSetAllValue", 8, 4, "LEAF", false, true, 192, true, 48, true, 73, true, 27, true, 2, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fVacuumUnit.pgcVacuumUnit.tsInArm", "tsInArm", "IDD_VACUUMUNIT_PGCVACUUMUNIT_TSINARM", "TTabSheet", "fVacuumUnit.pgcVacuumUnit", "fVacuumUnit", 1, 2, "SUBDLG", false, false, 0, false, 0, false, 0, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fVacuumUnit.pgcVacuumUnit.tsInArm.grpInarm", "grpInarm", "IDD_VACUUMUNIT_PGCVACUUMUNIT_TSINARM_GRPINARM", "TGroupBox", "fVacuumUnit.pgcVacuumUnit.tsInArm", "fVacuumUnit.pgcVacuumUnit.tsInArm", 0, 3, "SUBDLG", false, true, 0, true, 0, true, 300, true, 300, true, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fVacuumUnit.pgcVacuumUnit.tsInArm.grpInarm.scrlbxInArm", "scrlbxInArm", "IDD_VACUUMUNIT_PGCVACUUMUNIT_TSINARM_GRPINARM_SCRLBXINARM", "TScrollBox", "fVacuumUnit.pgcVacuumUnit.tsInArm.grpInarm", "fVacuumUnit.pgcVacuumUnit.tsInArm.grpInarm", 0, 4, "SUBDLG", false, true, 2, true, 21, true, 296, true, 277, true, 0, -1, "alClient", "", false, "", 0, "", false, 0, "", true, -2147483633, "clBtnFace", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fVacuumUnit.pgcVacuumUnit.tsIndex", "tsIndex", "IDD_VACUUMUNIT_PGCVACUUMUNIT_TSINDEX", "TTabSheet", "fVacuumUnit.pgcVacuumUnit", "fVacuumUnit", 2, 2, "SUBDLG", false, false, 0, false, 0, false, 0, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fVacuumUnit.pgcVacuumUnit.tsIndex.grpIndexArm2", "grpIndexArm2", "IDD_VACUUMUNIT_PGCVACUUMUNIT_TSINDEX_GRPINDEXARM2", "TGroupBox", "fVacuumUnit.pgcVacuumUnit.tsIndex", "fVacuumUnit.pgcVacuumUnit.tsIndex", 0, 3, "SUBDLG", false, true, 8, true, 0, true, 300, true, 300, true, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fVacuumUnit.pgcVacuumUnit.tsIndex.grpIndexArm2.scrlbxIndexArm2", "scrlbxIndexArm2", "IDD_VACUUMUNIT_PGCVACUUMUNIT_TSINDEX_GRPINDEXARM2_SCRLBXINDEXARM2", "TScrollBox", "fVacuumUnit.pgcVacuumUnit.tsIndex.grpIndexArm2", "fVacuumUnit.pgcVacuumUnit.tsIndex.grpIndexArm2", 0, 4, "SUBDLG", false, true, 2, true, 21, true, 296, true, 277, true, 0, -1, "alClient", "", false, "", 0, "", false, 0, "", true, -2147483633, "clBtnFace", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fVacuumUnit.pgcVacuumUnit.tsIndex.grpIndexArm1", "grpIndexArm1", "IDD_VACUUMUNIT_PGCVACUUMUNIT_TSINDEX_GRPINDEXARM1", "TGroupBox", "fVacuumUnit.pgcVacuumUnit.tsIndex", "fVacuumUnit.pgcVacuumUnit.tsIndex", 1, 3, "SUBDLG", false, true, 8, true, 304, true, 297, true, 265, true, 1, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fVacuumUnit.pgcVacuumUnit.tsIndex.grpIndexArm1.scrlbxIndexArm1", "scrlbxIndexArm1", "IDD_VACUUMUNIT_PGCVACUUMUNIT_TSINDEX_GRPINDEXARM1_SCRLBXINDEXARM1", "TScrollBox", "fVacuumUnit.pgcVacuumUnit.tsIndex.grpIndexArm1", "fVacuumUnit.pgcVacuumUnit.tsIndex.grpIndexArm1", 0, 4, "SUBDLG", false, true, 2, true, 21, true, 293, true, 242, true, 0, -1, "alClient", "", false, "", 0, "", false, 0, "", true, -2147483633, "clBtnFace", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fVacuumUnit.pgcVacuumUnit.tsOutArm", "tsOutArm", "IDD_VACUUMUNIT_PGCVACUUMUNIT_TSOUTARM", "TTabSheet", "fVacuumUnit.pgcVacuumUnit", "fVacuumUnit", 3, 2, "SUBDLG", false, false, 0, false, 0, false, 0, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fVacuumUnit.pgcVacuumUnit.tsOutArm.grpOutarm", "grpOutarm", "IDD_VACUUMUNIT_PGCVACUUMUNIT_TSOUTARM_GRPOUTARM", "TGroupBox", "fVacuumUnit.pgcVacuumUnit.tsOutArm", "fVacuumUnit.pgcVacuumUnit.tsOutArm", 0, 3, "SUBDLG", false, true, 0, true, 0, true, 300, true, 300, true, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fVacuumUnit.pgcVacuumUnit.tsOutArm.grpOutarm.scrlbxOutArm", "scrlbxOutArm", "IDD_VACUUMUNIT_PGCVACUUMUNIT_TSOUTARM_GRPOUTARM_SCRLBXOUTARM", "TScrollBox", "fVacuumUnit.pgcVacuumUnit.tsOutArm.grpOutarm", "fVacuumUnit.pgcVacuumUnit.tsOutArm.grpOutarm", 0, 4, "SUBDLG", false, true, 2, true, 21, true, 296, true, 277, true, 0, -1, "alClient", "", false, "", 0, "", false, 0, "", true, -2147483633, "clBtnFace", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fVacuumUnit.Panel1", "Panel1", "IDD_VACUUMUNIT_PANEL1", "TPanel", "fVacuumUnit", "fVacuumUnit", 1, 1, "SUBDLG", false, true, 0, true, 616, true, 647, true, 64, true, 1, -1, "alBottom", "", false, "", 0, "", false, 0, "", true, 12761254, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fVacuumUnit.Panel1.spbSave", "spbSave", "IDC_VACUUMUNIT_SPBSAVE", "TSpeedButton", "fVacuumUnit.Panel1", "fVacuumUnit.Panel1", 0, 2, "LEAF", true, true, 22, true, 17, true, 211, true, 41, false, 0, -1, "", "", true, "Arial", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fVacuumUnit.Panel1.sbtExit", "sbtExit", "IDC_VACUUMUNIT_SBTEXIT", "TSpeedButton", "fVacuumUnit.Panel1", "fVacuumUnit.Panel1", 1, 2, "LEAF", true, true, 260, true, 17, true, 205, true, 41, false, 0, -1, "", "", true, "Arial", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fVacuumUnit.Panel1.sbReset", "sbReset", "IDC_VACUUMUNIT_SBRESET", "TSpeedButton", "fVacuumUnit.Panel1", "fVacuumUnit.Panel1", 2, 2, "LEAF", true, true, 527, true, 17, true, 106, true, 41, false, 0, -1, "", "", true, "OpenSymbol", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fVacuumUnit.tmr1", "tmr1", "", "TTimer", "fVacuumUnit", "fVacuumUnit", 2, 1, "NONVISUAL", false, true, 492, false, 0, false, 0, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
};

const int kVacuumUnitLayoutCount = 40;

} // namespace ht9045_layout
