// ============================================================================
// DO NOT EDIT -- machine-generated by emit_rc.py W7-B1b v1.0 on BinDisplay/BinDisp.dfm
// AI(W906-W7-B1b) 20260728: generated .rc/_ids.h from the .dfm IR (see
// docs/W7_UI_ARCHITECTURE_PLAN.md S6 W7-B1b). Hand edits will be
// overwritten and are rejected by the idempotence gate (G7).
// Source golden: BinDisplay/BinDisp.dfm
// ============================================================================

#ifndef HT9045_UI_GEN_BINDISP_IDS_H
#define HT9045_UI_GEN_BINDISP_IDS_H

// Dialog template IDs
#define IDD_BINDISP 8192
#define IDD_BINDISP_PANEL3 8193
#define IDD_BINDISP_PANEL3_GROUPBOX1 8194
#define IDD_BINDISP_PANEL3_GROUPBOX2 8195

// Control IDs (D11 join key: mechanically derived from the
// .dfm leaf control name -- IDC_<FORMSTEM>_<CONTROLNAME>)
#define IDC_BINDISP_STATUSBAR1 1024
#define IDC_BINDISP_LABEL7 1025
#define IDC_BINDISP_BUTTON1 1026
#define IDC_BINDISP_GROUPBOX1_FRAME 1027  // synthesized: SYNTH_CONTAINER_FRAME
#define IDC_BINDISP_CHECKBOX1 1028
#define IDC_BINDISP_CHECKBOX2 1029
#define IDC_BINDISP_CHECKBOX3 1030
#define IDC_BINDISP_CHECKBOX4 1031
#define IDC_BINDISP_CHECKBOX5 1032
#define IDC_BINDISP_CHECKBOX6 1033
#define IDC_BINDISP_CHECKBOX7 1034
#define IDC_BINDISP_CHECKBOX8 1035
#define IDC_BINDISP_CHECKBOX9 1036
#define IDC_BINDISP_CHECKBOX10 1037
#define IDC_BINDISP_CHECKBOX11 1038
#define IDC_BINDISP_CHECKBOX12 1039
#define IDC_BINDISP_GROUPBOX2_FRAME 1040  // synthesized: SYNTH_CONTAINER_FRAME
#define IDC_BINDISP_COMBOBOX1 1041
#define IDC_BINDISP_COMBOBOX2 1042

#endif // HT9045_UI_GEN_BINDISP_IDS_H
