<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>HT9045.App</RootNamespace>
    <AssemblyName>HT9045.App</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\HT9045.Core\HT9045.Core.csproj" />
    <ProjectReference Include="..\HT9045.HardwareAbstraction\HT9045.HardwareAbstraction.csproj" />
    <ProjectReference Include="..\HT9045.Presentation.Abstraction\HT9045.Presentation.Abstraction.csproj" />
    <ProjectReference Include="..\HT9045.Hardware.Sim\HT9045.Hardware.Sim.csproj" />
    <ProjectReference Include="..\HT9045.Hardware.Native\HT9045.Hardware.Native.csproj" />
    <ProjectReference Include="..\HT9045.Views.Stub\HT9045.Views.Stub.csproj" />
    <ProjectReference Include="..\HT9045.Infrastructure\HT9045.Infrastructure.csproj" />
  </ItemGroup>
</Project>
