// ===========================================================================
//  Automation/automation_layout.gen.cpp
//  DO NOT EDIT -- GENERATED FILE. See the matching _layout.gen.h banner.
// ===========================================================================
#include "automation_layout.gen.h"

namespace ht9045_layout {

// (no custom-control properties in this form)

const DfmControlLayout kautomationLayout[] = {
    { "fAutomation", "fAutomation", "", "TfAutomation", "", "", 0, 0, "ROOT", false, true, 391, true, 195, true, 884, true, 610, false, 0, -1, "", "", true, "MS Sans Serif", -11, "", true, -2147483640, "clWindowText", true, 12761254, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fAutomation.pgcOLP", "pgcOLP", "IDC_AUTOMATION_PGCOLP", "TPageControl", "fAutomation", "fAutomation", 0, 1, "TABHOST", false, true, 0, true, 113, true, 868, true, 458, true, 4, -1, "alClient", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fAutomation.pgcOLP.TabSheet20", "TabSheet20", "IDD_AUTOMATION_PGCOLP_TABSHEET20", "TTabSheet", "fAutomation.pgcOLP", "fAutomation", 0, 2, "SUBDLG", false, false, 0, false, 0, false, 0, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fAutomation.pgcOLP.TabSheet20.Memo", "Memo", "IDC_AUTOMATION_MEMO", "TMemo", "fAutomation.pgcOLP.TabSheet20", "fAutomation.pgcOLP.TabSheet20", 0, 3, "LEAF", false, true, 0, true, 0, true, 860, true, 430, true, 0, -1, "alClient", "", false, "", 0, "", false, 0, "", true, 14670284, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fAutomation.pgcOLP.TabSheet6", "TabSheet6", "IDD_AUTOMATION_PGCOLP_TABSHEET6", "TTabSheet", "fAutomation.pgcOLP", "fAutomation", 1, 2, "SUBDLG", false, false, 0, false, 0, false, 0, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fAutomation.pgcOLP.TabSheet6.MemoChar", "MemoChar", "IDC_AUTOMATION_MEMOCHAR", "TMemo", "fAutomation.pgcOLP.TabSheet6", "fAutomation.pgcOLP.TabSheet6", 0, 3, "LEAF", false, true, 0, true, 0, true, 860, true, 431, true, 0, -1, "alClient", "", true, "Arial", -16, "", true, -2147483640, "clWindowText", true, 14670284, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fAutomation.pgcOLP.TabSheet22", "TabSheet22", "IDD_AUTOMATION_PGCOLP_TABSHEET22", "TTabSheet", "fAutomation.pgcOLP", "fAutomation", 2, 2, "SUBDLG", false, false, 0, false, 0, false, 0, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fAutomation.pgcOLP.TabSheet22.MemoCode", "MemoCode", "IDC_AUTOMATION_MEMOCODE", "TMemo", "fAutomation.pgcOLP.TabSheet22", "fAutomation.pgcOLP.TabSheet22", 0, 3, "LEAF", false, true, 0, true, 0, true, 860, true, 431, true, 0, -1, "alClient", "", true, "Arial", -16, "", true, -2147483640, "clWindowText", true, 14670284, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fAutomation.gbAutomation", "gbAutomation", "IDD_AUTOMATION_GBAUTOMATION", "TGroupBox", "fAutomation", "fAutomation", 1, 1, "SUBDLG", false, true, 0, true, 0, true, 868, true, 113, true, 0, -1, "alTop", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fAutomation.gbAutomation.OnLine", "OnLine", "IDC_AUTOMATION_ONLINE", "TSpeedButton", "fAutomation.gbAutomation", "fAutomation.gbAutomation", 0, 2, "LEAF", true, true, 172, true, 12, true, 45, true, 45, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fAutomation.gbAutomation.OnLine2", "OnLine2", "IDC_AUTOMATION_ONLINE2", "TSpeedButton", "fAutomation.gbAutomation", "fAutomation.gbAutomation", 1, 2, "LEAF", true, true, 227, true, 12, true, 44, true, 45, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fAutomation.gbAutomation.cbbOLPCommand", "cbbOLPCommand", "IDC_AUTOMATION_CBBOLPCOMMAND", "TComboBox", "fAutomation.gbAutomation", "fAutomation.gbAutomation", 2, 2, "LEAF", false, true, 284, true, 13, true, 145, true, 21, true, 2, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fAutomation.gbAutomation.btEventReport", "btEventReport", "IDC_AUTOMATION_BTEVENTREPORT", "TButton", "fAutomation.gbAutomation", "fAutomation.gbAutomation", 3, 2, "LEAF", false, true, 285, true, 41, true, 146, true, 25, true, 3, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fAutomation.gbAutomation.btAlarmReport", "btAlarmReport", "IDC_AUTOMATION_BTALARMREPORT", "TButton", "fAutomation.gbAutomation", "fAutomation.gbAutomation", 4, 2, "LEAF", false, true, 436, true, 9, true, 144, true, 25, true, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fAutomation.gbAutomation.chkViewComm", "chkViewComm", "IDC_AUTOMATION_CHKVIEWCOMM", "TCheckBox", "fAutomation.gbAutomation", "fAutomation.gbAutomation", 5, 2, "LEAF", false, true, 605, true, 48, true, 121, true, 17, true, 6, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fAutomation.gbAutomation.btnConnect", "btnConnect", "IDC_AUTOMATION_BTNCONNECT", "TButton", "fAutomation.gbAutomation", "fAutomation.gbAutomation", 6, 2, "LEAF", false, true, 8, true, 13, true, 128, true, 25, true, 1, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fAutomation.gbAutomation.btnDisconnect", "btnDisconnect", "IDC_AUTOMATION_BTNDISCONNECT", "TButton", "fAutomation.gbAutomation", "fAutomation.gbAutomation", 7, 2, "LEAF", false, true, 8, true, 44, true, 128, true, 25, true, 5, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fAutomation.gbAutomation.btTestResult", "btTestResult", "IDC_AUTOMATION_BTTESTRESULT", "TButton", "fAutomation.gbAutomation", "fAutomation.gbAutomation", 8, 2, "LEAF", false, true, 436, true, 41, true, 144, true, 25, true, 4, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fAutomation.gbAutomation.Panel1", "Panel1", "IDD_AUTOMATION_GBAUTOMATION_PANEL1", "TPanel", "fAutomation.gbAutomation", "fAutomation.gbAutomation", 9, 2, "SUBDLG", false, true, 348, true, 72, true, 313, true, 30, true, 7, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fAutomation.gbAutomation.Panel1.lbIP", "lbIP", "IDC_AUTOMATION_LBIP", "TLabel", "fAutomation.gbAutomation.Panel1", "fAutomation.gbAutomation.Panel1", 0, 3, "LEAF", true, true, 4, true, 7, true, 74, true, 16, false, 0, -1, "", "", true, "MS Sans Serif", -13, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fAutomation.gbAutomation.Panel1.lbPORT", "lbPORT", "IDC_AUTOMATION_LBPORT", "TLabel", "fAutomation.gbAutomation.Panel1", "fAutomation.gbAutomation.Panel1", 1, 3, "LEAF", true, true, 200, true, 7, true, 41, true, 16, false, 0, -1, "", "", true, "MS Sans Serif", -13, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fAutomation.gbAutomation.Panel1.edinputIP", "edinputIP", "IDC_AUTOMATION_EDINPUTIP", "TEdit", "fAutomation.gbAutomation.Panel1", "fAutomation.gbAutomation.Panel1", 2, 3, "LEAF", false, true, 80, true, 2, true, 109, true, 24, true, 0, -1, "", "", true, "MS Sans Serif", -13, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fAutomation.gbAutomation.Panel1.edinputport", "edinputport", "IDC_AUTOMATION_EDINPUTPORT", "TEdit", "fAutomation.gbAutomation.Panel1", "fAutomation.gbAutomation.Panel1", 3, 3, "LEAF", false, true, 244, true, 2, true, 57, true, 21, true, 1, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fAutomation.btUDPSend", "btUDPSend", "IDC_AUTOMATION_BTUDPSEND", "TButton", "fAutomation", "fAutomation", 2, 1, "LEAF", false, true, 519, true, 8, true, 111, true, 36, true, 1, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fAutomation.btUDPMap", "btUDPMap", "IDC_AUTOMATION_BTUDPMAP", "TButton", "fAutomation", "fAutomation", 3, 1, "LEAF", false, true, 636, true, 8, true, 111, true, 36, true, 2, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fAutomation.btUDPTemp", "btUDPTemp", "IDC_AUTOMATION_BTUDPTEMP", "TButton", "fAutomation", "fAutomation", 4, 1, "LEAF", false, true, 753, true, 8, true, 111, true, 36, true, 3, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fAutomation.OLPServer", "OLPServer", "", "TServerSocket", "fAutomation", "fAutomation", 5, 1, "NONVISUAL", false, true, 788, true, 3, false, 0, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fAutomation.tmrOLP", "tmrOLP", "", "TTimer", "fAutomation", "fAutomation", 6, 1, "NONVISUAL", false, true, 756, true, 4, false, 0, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fAutomation.OLPClient", "OLPClient", "", "TClientSocket", "fAutomation", "fAutomation", 7, 1, "NONVISUAL", false, true, 724, true, 4, false, 0, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fAutomation.NMUDP1", "NMUDP1", "", "TNMUDP", "fAutomation", "fAutomation", 8, 1, "NONVISUAL", false, true, 820, true, 4, false, 0, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
};

const int kautomationLayoutCount = 30;

} // namespace ht9045_layout
