// ===========================================================================
//  Automation/fRENESAS_ServerFrm_layout.gen.cpp
//  DO NOT EDIT -- GENERATED FILE. See the matching _layout.gen.h banner.
// ===========================================================================
#include "fRENESAS_ServerFrm_layout.gen.h"

namespace ht9045_layout {

// (no custom-control properties in this form)

const DfmControlLayout kfRENESAS_ServerFrmLayout[] = {
    { "fServerFrm", "fServerFrm", "", "TfServerFrm", "", "", 0, 0, "ROOT", false, true, 311, true, 247, true, 508, true, 336, false, 0, -1, "", "", true, "MS Sans Serif", -11, "", true, -2147483640, "clWindowText", true, -2147483633, "clBtnFace", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fServerFrm.frameProdInfo1", "frameProdInfo1", "IDD_FRENESAS_SERVERFRM_FRAMEPRODINFO1", "TframeProdInfo", "fServerFrm", "fServerFrm", 0, 1, "SUBDLG", false, true, 4, true, 4, true, 173, true, 299, true, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fServerFrm.frameProdInfo1.lbledtLotNo", "lbledtLotNo", "IDC_FRENESAS_SERVERFRM_LBLEDTLOTNO", "TLabeledEdit", "fServerFrm.frameProdInfo1", "fServerFrm.frameProdInfo1", 0, 2, "LEAF", false, false, 0, false, 0, true, 150, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fServerFrm.frameProdInfo1.lbledtLotID", "lbledtLotID", "IDC_FRENESAS_SERVERFRM_LBLEDTLOTID", "TLabeledEdit", "fServerFrm.frameProdInfo1", "fServerFrm.frameProdInfo1", 1, 2, "LEAF", false, false, 0, false, 0, true, 150, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fServerFrm.frameProdInfo1.lbledtHdParameter", "lbledtHdParameter", "IDC_FRENESAS_SERVERFRM_LBLEDTHDPARAMETER", "TLabeledEdit", "fServerFrm.frameProdInfo1", "fServerFrm.frameProdInfo1", 2, 2, "LEAF", false, false, 0, false, 0, true, 150, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fServerFrm.frameProdInfo1.lbledtProduct", "lbledtProduct", "IDC_FRENESAS_SERVERFRM_LBLEDTPRODUCT", "TLabeledEdit", "fServerFrm.frameProdInfo1", "fServerFrm.frameProdInfo1", 3, 2, "LEAF", false, false, 0, false, 0, true, 150, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fServerFrm.frameProdInfo1.lbledtStepCode", "lbledtStepCode", "IDC_FRENESAS_SERVERFRM_LBLEDTSTEPCODE", "TLabeledEdit", "fServerFrm.frameProdInfo1", "fServerFrm.frameProdInfo1", 4, 2, "LEAF", false, false, 0, false, 0, true, 150, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fServerFrm.frameProdInfo1.lbledtQty", "lbledtQty", "IDC_FRENESAS_SERVERFRM_LBLEDTQTY", "TLabeledEdit", "fServerFrm.frameProdInfo1", "fServerFrm.frameProdInfo1", 5, 2, "LEAF", false, false, 0, false, 0, true, 150, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fServerFrm.frameProdInfo1.lbledtDate", "lbledtDate", "IDC_FRENESAS_SERVERFRM_LBLEDTDATE", "TLabeledEdit", "fServerFrm.frameProdInfo1", "fServerFrm.frameProdInfo1", 6, 2, "LEAF", false, false, 0, false, 0, true, 150, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fServerFrm.frameProdInfo1.ShowTimer", "ShowTimer", "", "TTimer", "fServerFrm.frameProdInfo1", "fServerFrm.frameProdInfo1", 7, 2, "NONVISUAL", false, false, 0, true, 268, false, 0, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fServerFrm.grpFTCTStatus", "grpFTCTStatus", "IDD_FRENESAS_SERVERFRM_GRPFTCTSTATUS", "TGroupBox", "fServerFrm", "fServerFrm", 1, 1, "SUBDLG", false, true, 188, true, 8, true, 177, true, 57, true, 1, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fServerFrm.grpFTCTStatus.pnlOnLine", "pnlOnLine", "IDC_FRENESAS_SERVERFRM_PNLONLINE", "TPanel", "fServerFrm.grpFTCTStatus", "fServerFrm.grpFTCTStatus", 0, 2, "LEAF", false, true, 9, true, 15, true, 160, true, 30, true, 0, -1, "", "", true, "MS Sans Serif", -19, "", true, 16777215, "clWhite", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fServerFrm.grpTestMode", "grpTestMode", "IDD_FRENESAS_SERVERFRM_GRPTESTMODE", "TGroupBox", "fServerFrm", "fServerFrm", 2, 1, "SUBDLG", false, true, 188, true, 72, true, 177, true, 57, true, 3, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fServerFrm.grpTestMode.pnlTestMode", "pnlTestMode", "IDC_FRENESAS_SERVERFRM_PNLTESTMODE", "TPanel", "fServerFrm.grpTestMode", "fServerFrm.grpTestMode", 0, 2, "LEAF", false, true, 9, true, 16, true, 160, true, 30, true, 0, -1, "", "", true, "MS Sans Serif", -19, "", true, 16777215, "clWhite", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fServerFrm.GroupBox1", "GroupBox1", "IDD_FRENESAS_SERVERFRM_GROUPBOX1", "TGroupBox", "fServerFrm", "fServerFrm", 3, 1, "SUBDLG", false, true, 188, true, 132, true, 309, true, 21, true, 5, 0, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fServerFrm.GroupBox1.lbledtHdPass", "lbledtHdPass", "IDC_FRENESAS_SERVERFRM_LBLEDTHDPASS", "TLabeledEdit", "fServerFrm.GroupBox1", "fServerFrm.GroupBox1", 0, 2, "LEAF", false, true, 8, true, 32, true, 73, true, 24, true, 0, -1, "", "", true, "MS Sans Serif", -13, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fServerFrm.GroupBox1.lbledtHdFail", "lbledtHdFail", "IDC_FRENESAS_SERVERFRM_LBLEDTHDFAIL", "TLabeledEdit", "fServerFrm.GroupBox1", "fServerFrm.GroupBox1", 1, 2, "LEAF", false, true, 8, true, 72, true, 73, true, 24, true, 3, -1, "", "", true, "MS Sans Serif", -13, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fServerFrm.GroupBox1.lbledtHdRejectATPass", "lbledtHdRejectATPass", "IDC_FRENESAS_SERVERFRM_LBLEDTHDREJECTATPASS", "TLabeledEdit", "fServerFrm.GroupBox1", "fServerFrm.GroupBox1", 2, 2, "LEAF", false, true, 8, true, 112, true, 73, true, 24, true, 6, -1, "", "", true, "MS Sans Serif", -13, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fServerFrm.GroupBox1.lbledtHdRejectATFail", "lbledtHdRejectATFail", "IDC_FRENESAS_SERVERFRM_LBLEDTHDREJECTATFAIL", "TLabeledEdit", "fServerFrm.GroupBox1", "fServerFrm.GroupBox1", 3, 2, "LEAF", false, true, 8, true, 152, true, 73, true, 24, true, 9, -1, "", "", true, "MS Sans Serif", -13, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fServerFrm.GroupBox1.lbledtHdRejectBT", "lbledtHdRejectBT", "IDC_FRENESAS_SERVERFRM_LBLEDTHDREJECTBT", "TLabeledEdit", "fServerFrm.GroupBox1", "fServerFrm.GroupBox1", 4, 2, "LEAF", false, true, 8, true, 192, true, 73, true, 24, true, 12, -1, "", "", true, "MS Sans Serif", -13, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fServerFrm.GroupBox1.lbledtTesterMatch", "lbledtTesterMatch", "IDC_FRENESAS_SERVERFRM_LBLEDTTESTERMATCH", "TLabeledEdit", "fServerFrm.GroupBox1", "fServerFrm.GroupBox1", 5, 2, "LEAF", false, true, 120, true, 32, true, 73, true, 24, true, 1, -1, "", "", true, "MS Sans Serif", -13, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fServerFrm.GroupBox1.lbledtTesterUnmatch", "lbledtTesterUnmatch", "IDC_FRENESAS_SERVERFRM_LBLEDTTESTERUNMATCH", "TLabeledEdit", "fServerFrm.GroupBox1", "fServerFrm.GroupBox1", 6, 2, "LEAF", false, true, 120, true, 72, true, 73, true, 24, true, 4, -1, "", "", true, "MS Sans Serif", -13, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fServerFrm.GroupBox1.lbledtTesterIgnore", "lbledtTesterIgnore", "IDC_FRENESAS_SERVERFRM_LBLEDTTESTERIGNORE", "TLabeledEdit", "fServerFrm.GroupBox1", "fServerFrm.GroupBox1", 7, 2, "LEAF", false, true, 120, true, 112, true, 73, true, 24, true, 7, -1, "", "", true, "MS Sans Serif", -13, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fServerFrm.GroupBox1.lbledtHdPickUp", "lbledtHdPickUp", "IDC_FRENESAS_SERVERFRM_LBLEDTHDPICKUP", "TLabeledEdit", "fServerFrm.GroupBox1", "fServerFrm.GroupBox1", 8, 2, "LEAF", false, true, 120, true, 152, true, 73, true, 24, true, 10, -1, "", "", true, "MS Sans Serif", -13, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fServerFrm.GroupBox1.lbledtHdPass1", "lbledtHdPass1", "IDC_FRENESAS_SERVERFRM_LBLEDTHDPASS1", "TLabeledEdit", "fServerFrm.GroupBox1", "fServerFrm.GroupBox1", 9, 2, "LEAF", false, true, 232, true, 32, true, 73, true, 24, true, 2, -1, "", "", true, "MS Sans Serif", -13, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fServerFrm.GroupBox1.lbledtHdPass2", "lbledtHdPass2", "IDC_FRENESAS_SERVERFRM_LBLEDTHDPASS2", "TLabeledEdit", "fServerFrm.GroupBox1", "fServerFrm.GroupBox1", 10, 2, "LEAF", false, true, 232, true, 76, true, 73, true, 24, true, 5, -1, "", "", true, "MS Sans Serif", -13, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fServerFrm.GroupBox1.lbledtHdRejectATPass1", "lbledtHdRejectATPass1", "IDC_FRENESAS_SERVERFRM_LBLEDTHDREJECTATPASS1", "TLabeledEdit", "fServerFrm.GroupBox1", "fServerFrm.GroupBox1", 11, 2, "LEAF", false, true, 232, true, 117, true, 73, true, 24, true, 8, -1, "", "", true, "MS Sans Serif", -13, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fServerFrm.GroupBox1.lbledtHdRejectATPass2", "lbledtHdRejectATPass2", "IDC_FRENESAS_SERVERFRM_LBLEDTHDREJECTATPASS2", "TLabeledEdit", "fServerFrm.GroupBox1", "fServerFrm.GroupBox1", 12, 2, "LEAF", false, true, 232, true, 157, true, 73, true, 24, true, 11, -1, "", "", true, "MS Sans Serif", -13, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fServerFrm.grpHandlerSeq", "grpHandlerSeq", "IDD_FRENESAS_SERVERFRM_GRPHANDLERSEQ", "TGroupBox", "fServerFrm", "fServerFrm", 4, 1, "SUBDLG", false, true, 372, true, 72, true, 125, true, 57, true, 4, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fServerFrm.grpHandlerSeq.pnlHandlerSeq", "pnlHandlerSeq", "IDC_FRENESAS_SERVERFRM_PNLHANDLERSEQ", "TPanel", "fServerFrm.grpHandlerSeq", "fServerFrm.grpHandlerSeq", 0, 2, "LEAF", false, true, 9, true, 16, true, 84, true, 30, true, 0, -1, "", "", true, "MS Sans Serif", -19, "", true, 0, "clBlack", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fServerFrm.GroupBox2", "GroupBox2", "IDD_FRENESAS_SERVERFRM_GROUPBOX2", "TGroupBox", "fServerFrm", "fServerFrm", 5, 1, "SUBDLG", false, true, 368, true, 8, true, 129, true, 57, true, 2, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fServerFrm.GroupBox2.pnlFTCTLastSeqStatus", "pnlFTCTLastSeqStatus", "IDC_FRENESAS_SERVERFRM_PNLFTCTLASTSEQSTATUS", "TPanel", "fServerFrm.GroupBox2", "fServerFrm.GroupBox2", 0, 2, "LEAF", false, true, 9, true, 16, true, 84, true, 30, true, 0, -1, "", "", true, "MS Sans Serif", -19, "", true, 0, "clBlack", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fServerFrm.grpAfter71RecvTimeOut", "grpAfter71RecvTimeOut", "IDD_FRENESAS_SERVERFRM_GRPAFTER71RECVTIMEOUT", "TGroupBox", "fServerFrm", "fServerFrm", 6, 1, "SUBDLG", false, true, 188, true, 160, true, 249, true, 73, true, 6, 0, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fServerFrm.grpAfter71RecvTimeOut.grpNowCounter", "grpNowCounter", "IDD_FRENESAS_SERVERFRM_GRPAFTER71RECVTIMEOUT_GRPNOWCOUNTER", "TGroupBox", "fServerFrm.grpAfter71RecvTimeOut", "fServerFrm.grpAfter71RecvTimeOut", 0, 2, "SUBDLG", false, true, 8, true, 16, true, 113, true, 52, true, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fServerFrm.grpAfter71RecvTimeOut.grpNowCounter.lblNowCounterUnit", "lblNowCounterUnit", "IDC_FRENESAS_SERVERFRM_LBLNOWCOUNTERUNIT", "TLabel", "fServerFrm.grpAfter71RecvTimeOut.grpNowCounter", "fServerFrm.grpAfter71RecvTimeOut.grpNowCounter", 0, 3, "LEAF", true, true, 76, true, 18, true, 33, true, 24, false, 0, -1, "", "", true, "MS Sans Serif", -19, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fServerFrm.grpAfter71RecvTimeOut.grpNowCounter.pnlNowCounter", "pnlNowCounter", "IDC_FRENESAS_SERVERFRM_PNLNOWCOUNTER", "TPanel", "fServerFrm.grpAfter71RecvTimeOut.grpNowCounter", "fServerFrm.grpAfter71RecvTimeOut.grpNowCounter", 1, 3, "LEAF", false, true, 9, true, 16, true, 64, true, 30, true, 0, -1, "", "", true, "MS Sans Serif", -19, "", true, 0, "clBlack", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fServerFrm.grpAfter71RecvTimeOut.grpSetCounter", "grpSetCounter", "IDD_FRENESAS_SERVERFRM_GRPAFTER71RECVTIMEOUT_GRPSETCOUNTER", "TGroupBox", "fServerFrm.grpAfter71RecvTimeOut", "fServerFrm.grpAfter71RecvTimeOut", 1, 2, "SUBDLG", false, true, 128, true, 16, true, 113, true, 52, true, 1, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fServerFrm.grpAfter71RecvTimeOut.grpSetCounter.lblSetCounterUnit", "lblSetCounterUnit", "IDC_FRENESAS_SERVERFRM_LBLSETCOUNTERUNIT", "TLabel", "fServerFrm.grpAfter71RecvTimeOut.grpSetCounter", "fServerFrm.grpAfter71RecvTimeOut.grpSetCounter", 0, 3, "LEAF", true, true, 76, true, 17, true, 33, true, 24, false, 0, -1, "", "", true, "MS Sans Serif", -19, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fServerFrm.grpAfter71RecvTimeOut.grpSetCounter.pnlSetCounter", "pnlSetCounter", "IDC_FRENESAS_SERVERFRM_PNLSETCOUNTER", "TPanel", "fServerFrm.grpAfter71RecvTimeOut.grpSetCounter", "fServerFrm.grpAfter71RecvTimeOut.grpSetCounter", 1, 3, "LEAF", false, true, 9, true, 16, true, 64, true, 30, true, 0, -1, "", "", true, "MS Sans Serif", -19, "", true, 0, "clBlack", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fServerFrm.ProcTimer", "ProcTimer", "", "TTimer", "fServerFrm", "fServerFrm", 7, 1, "NONVISUAL", false, true, 180, true, 272, false, 0, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
};

const int kfRENESAS_ServerFrmLayoutCount = 40;

} // namespace ht9045_layout
