// ============================================================================
// DO NOT EDIT -- machine-generated by emit_rc.py W7-B1b v1.0 on CCLink/CCINPUT.dfm
// AI(W906-W7-B1b) 20260728: generated .rc/_ids.h from the .dfm IR (see
// docs/W7_UI_ARCHITECTURE_PLAN.md S6 W7-B1b). Hand edits will be
// overwritten and are rejected by the idempotence gate (G7).
// Source golden: CCLink/CCINPUT.dfm
// ============================================================================

#ifndef HT9045_UI_GEN_CCINPUT_IDS_H
#define HT9045_UI_GEN_CCINPUT_IDS_H

// Dialog template IDs
#define IDD_CCINPUT 8192

// Control IDs (D11 join key: mechanically derived from the
// .dfm leaf control name -- IDC_<FORMSTEM>_<CONTROLNAME>)
#define IDC_CCINPUT_SPEEDBUTTON1 1024
#define IDC_CCINPUT_SPEEDBUTTON2 1025
#define IDC_CCINPUT_SPEEDBUTTON3 1026
#define IDC_CCINPUT_SPEEDBUTTON4 1027
#define IDC_CCINPUT_SPEEDBUTTON5 1028
#define IDC_CCINPUT_SPEEDBUTTON6 1029
#define IDC_CCINPUT_SPEEDBUTTON7 1030
#define IDC_CCINPUT_LABEL1 1031
#define IDC_CCINPUT_BUTTON1 1032
#define IDC_CCINPUT_BUTTON2 1033
#define IDC_CCINPUT_BUTTON3 1034
#define IDC_CCINPUT_BUTTON5 1035
#define IDC_CCINPUT_BUTTON6 1036
#define IDC_CCINPUT_BUTTON8 1037
#define IDC_CCINPUT_BUTTON9 1038
#define IDC_CCINPUT_BUTTON11 1039
#define IDC_CCINPUT_BUTTON12 1040
#define IDC_CCINPUT_BUTTON15 1041
#define IDC_CCINPUT_BUTTON17 1042
#define IDC_CCINPUT_BUTTON18 1043
#define IDC_CCINPUT_BUTTON13 1044
#define IDC_CCINPUT_BUTTON4 1045

#endif // HT9045_UI_GEN_CCINPUT_IDS_H
