//---------------------------------------------------------------------------

#ifndef cStartConditionH
#define cStartConditionH
//---------------------------------------------------------------------------
#include <Buttons.hpp>
#include <Classes.hpp>
#include <Controls.hpp>
#include <ExtCtrls.hpp>
#include <Grids.hpp>
#include <StdCtrls.hpp>
#include <ComCtrls.hpp>
#include <Forms.hpp>
#include <Menus.hpp>
#include "mycylin.h"
//---------------------------------------------------------------------------

class TfStartCondition : public TForm
{
__published:    // IDE-managed Components
    TPanel *spbExit;
    TPageControl *PageControl1;
    TTabSheet *tsStartMode;
    TTabSheet *tsLifeTime;
    TGroupBox *gbStartMode;
    TRadioButton *rbStartMode1;
    TRadioButton *rbStartMode2;
    TRadioButton *rbStartMode3;
    TGroupBox *gbCounterClear;
    TLabel *labLoadingCount;
    TLabel *labTestCategory;
    TLabel *labContactCount;
    TLabel *labSortingCount;
    TLabel *labScanner;
    TLabel *labAlarmData;
    TLabel *labTimeData;
    TGroupBox *gbInitialStart;
    TCheckBox *cbLoadingCount_FT;
    TCheckBox *cbTestCategory_FT;
    TCheckBox *cbContactCount_FT;
    TCheckBox *cbSortingCount_FT;
    TCheckBox *cbScanner_FT;
    TCheckBox *cbAlarmData_FT;
    TCheckBox *cbTimeData_FT;
    TGroupBox *gbContactCount;
    TSpeedButton *sbSameAsHead1;
    TSpeedButton *sbClearCount;
    TSpeedButton *sbSave;
    TStringGrid *sgContactCount;
    TEdit *edTemp;
    TPageControl *pgLifeTime;
    TTabSheet *tsCondition01;
    TTabSheet *tsCondition02;
    TTabSheet *tsCondition03;
    TStringGrid *sgHeadCondition3;
    TStringGrid *sgHeadCondition1;
    TStringGrid *sgHeadCondition2;
    TGroupBox *grRetestStart;
    TCheckBox *cbLoadingCount_RT;
    TCheckBox *cbTestCategory_RT;
    TCheckBox *cbContactCount_RT;
    TCheckBox *cbSortingCount_RT;
    TCheckBox *cbScanner_RT;
    TCheckBox *cbAlarmData_RT;
    TCheckBox *cbTimeData_RT;
    TTabSheet *TabsSocketID;
    TGroupBox *groupbSocketID;
    TLabel *labTestRowA;
    TLabel *labTestRowB;
    TLabel *labTestColA;
    TLabel *labTestColB;
    TLabel *labTestColC;
    TLabel *labTestColD;
    TLabel *labTestColE;
    TLabel *labTestColF;
    TLabel *labTestColG;
    TLabel *labTestColH;
    TLabel *labTestRowC;
    TLabel *labTestRowD;
    TEdit *editSocketAa;
    TEdit *editSocketAb;
    TEdit *editSocketAc;
    TEdit *editSocketAd;
    TEdit *editSocketAe;
    TEdit *editSocketAf;
    TEdit *editSocketAg;
    TEdit *editSocketAh;
    TEdit *editSocketBa;
    TEdit *editSocketBb;
    TEdit *editSocketBc;
    TEdit *editSocketBd;
    TEdit *editSocketBe;
    TEdit *editSocketBf;
    TEdit *editSocketBg;
    TEdit *editSocketBh;
    TEdit *editSocketCa;
    TEdit *editSocketCb;
    TEdit *editSocketCc;
    TEdit *editSocketCd;
    TEdit *editSocketCe;
    TEdit *editSocketCf;
    TEdit *editSocketCg;
    TEdit *editSocketCh;
    TEdit *editSocketDa;
    TEdit *editSocketDb;
    TEdit *editSocketDc;
    TEdit *editSocketDd;
    TEdit *editSocketDe;
    TEdit *editSocketDf;
    TEdit *editSocketDg;
    TEdit *editSocketDh;
    TPanel *PanelAa;
    TPanel *PanelAb;
    TPanel *PanelAc;
    TPanel *PanelAd;
    TPanel *PanelAe;
    TPanel *PanelAf;
    TPanel *PanelAg;
    TPanel *PanelAh;
    TPanel *PanelBa;
    TPanel *PanelBb;
    TPanel *PanelBc;
    TPanel *PanelBd;
    TPanel *PanelBe;
    TPanel *PanelBf;
    TPanel *PanelBg;
    TPanel *PanelBh;
    TPanel *PanelCa;
    TPanel *PanelCb;
    TPanel *PanelCc;
    TPanel *PanelCd;
    TPanel *PanelCe;
    TPanel *PanelCf;
    TPanel *PanelCg;
    TPanel *PanelCh;
    TPanel *PanelDa;
    TPanel *PanelDb;
    TPanel *PanelDc;
    TPanel *PanelDd;
    TPanel *PanelDe;
    TPanel *PanelDf;
    TPanel *PanelDg;
    TPanel *PanelDh;
    TLabel *LabelID_RowA;
    TLabel *LabelCnt_RowA;
    TLabel *LabelID_RowB;
    TLabel *LabelCnt_RowB;
    TLabel *LabelID_RowC;
    TLabel *LabelCnt_RowC;
    TLabel *LabelID_RowD;
    TLabel *LabelCnt_RowD;
    TTabSheet *tsVibration;
    TLabel *Label1;
    TPanel *palVibratorHP1;
    TLabel *Label2;
    TLabel *Label3;
    TPanel *palVibratorSht1;
    TLabel *Label6;
    TLabel *Label7;
    TPanel *palVibratorSht2;
    TLabel *Label8;
    TLabel *Label9;
    TPanel *palVibratorUnloader;
    TLabel *Label10;
    TLabel *Label11;
    TTabSheet *tsFunction;
    TCheckBox *cbStartModeOnlyFT;
    TTabSheet *tsSmartDiagnostic;
    TPanel *pn_Maintenance_SmartDiagnosticFunction;
    TSpeedButton *sb_Maintenance_SmartDiagnosticFunction;
    TPanel *pn_Maintenance_SmartDiagnosticFunctionTop;
    TTabSheet *tsSocketCount;
    TStringGrid *sgSocketCount;
    TTabSheet *tsPickerLifeTime;
    TScrollBox *ScrollBox1;
    TLabel *Label17;
    TGroupBox *GroupBox2;
    TLabel *Label19;
    TLabel *Label20;
    TLabel *Label21;
    TLabel *Label22;
    TLabel *Label23;
    TLabel *Label24;
    TLabel *Label25;
    TLabel *Label26;
    TEdit *edtOutArmC;
    TEdit *edtOutArmA;
    TEdit *edtOutArmG;
    TEdit *edtOutArmE;
    TEdit *edtOutArmB;
    TEdit *edtOutArmH;
    TEdit *edtOutArmF;
    TEdit *edtOutArmD;
    TButton *btnOutArmE;
    TButton *btnOutArmA;
    TButton *btnOutArmC;
    TButton *btnOutArmG;
    TButton *btnOutArmH;
    TButton *btnOutArmF;
    TButton *btnOutArmD;
    TButton *btnOutArmB;
    TGroupBox *GroupBox1;
    TLabel *Label4;
    TLabel *Label5;
    TLabel *Label12;
    TLabel *Label13;
    TLabel *Label14;
    TLabel *Label15;
    TLabel *Label16;
    TLabel *Label18;
    TEdit *edtInArmC;
    TEdit *edtInArmA;
    TEdit *edtInArmG;
    TEdit *edtInArmE;
    TEdit *edtInArmB;
    TEdit *edtInArmH;
    TEdit *edtInArmF;
    TEdit *edtInArmD;
    TButton *btnInArmA;
    TButton *btnInArmC;
    TButton *btnInArmE;
    TButton *btnInArmG;
    TButton *btnInArmB;
    TButton *btnInArmD;
    TButton *btnInArmF;
    TButton *btnInArmH;
    TGroupBox *GroupBox3;
    TLabel *Label27;
    TLabel *Label28;
    TLabel *Label29;
    TLabel *Label30;
    TLabel *Label31;
    TLabel *Label32;
    TLabel *Label33;
    TLabel *Label34;
    TLabel *Label35;
    TLabel *Label36;
    TLabel *Label37;
    TLabel *Label38;
    TLabel *Label39;
    TLabel *Label40;
    TLabel *Label41;
    TLabel *Label42;
    TEdit *edtArm2Ab;
    TEdit *edtArm2Aa;
    TEdit *edtArm2Ad;
    TEdit *edtArm2Ac;
    TEdit *edtArm2Ba;
    TEdit *edtArm2Bd;
    TEdit *edtArm2Bc;
    TEdit *edtArm2Bb;
    TButton *btnArm2Aa;
    TButton *btnArm2Ab;
    TButton *btnArm2Ac;
    TButton *btnArm2Ad;
    TButton *btnArm2Ba;
    TButton *btnArm2Bb;
    TButton *btnArm2Bc;
    TButton *btnArm2Bd;
    TEdit *edtArm2Af;
    TEdit *edtArm2Ae;
    TEdit *edtArm2Ah;
    TEdit *edtArm2Ag;
    TEdit *edtArm2Be;
    TEdit *edtArm2Bh;
    TEdit *edtArm2Bg;
    TEdit *edtArm2Bf;
    TButton *btnArm2Ae;
    TButton *btnArm2Af;
    TButton *btnArm2Ag;
    TButton *btnArm2Ah;
    TButton *btnArm2Be;
    TButton *btnArm2Bf;
    TButton *btnArm2Bg;
    TButton *btnArm2Bh;
    TEdit *edtInOutArmPickerAlmCnt;
    TGroupBox *GroupBox4;
    TLabel *Label43;
    TLabel *Label44;
    TLabel *Label45;
    TLabel *Label46;
    TLabel *Label47;
    TLabel *Label48;
    TLabel *Label49;
    TLabel *Label50;
    TLabel *Label51;
    TLabel *Label52;
    TLabel *Label53;
    TLabel *Label54;
    TLabel *Label55;
    TLabel *Label56;
    TLabel *Label57;
    TLabel *Label58;
    TEdit *edtArm1Ab;
    TEdit *edtArm1Aa;
    TEdit *edtArm1Ad;
    TEdit *edtArm1Ac;
    TEdit *edtArm1Ba;
    TEdit *edtArm1Bd;
    TEdit *edtArm1Bc;
    TEdit *edtArm1Bb;
    TButton *btnArm1Aa;
    TButton *btnArm1Ab;
    TButton *btnArm1Ac;
    TButton *btnArm1Ad;
    TButton *btnArm1Ba;
    TButton *btnArm1Bb;
    TButton *btnArm1Bc;
    TButton *btnArm1Bd;
    TEdit *edtArm1Af;
    TEdit *edtArm1Ae;
    TEdit *edtArm1Ah;
    TEdit *edtArm1Ag;
    TEdit *edtArm1Be;
    TEdit *edtArm1Bh;
    TEdit *edtArm1Bg;
    TEdit *edtArm1Bf;
    TButton *btnArm1Ae;
    TButton *btnArm1Af;
    TButton *btnArm1Ag;
    TButton *btnArm1Ah;
    TButton *btnArm1Be;
    TButton *btnArm1Bf;
    TButton *btnArm1Bg;
    TButton *btnArm1Bh;
    TPanel *Panel1;
    TSpeedButton *sbHeadCondition1Clear;
    TSpeedButton *sbHeadCondition1Save;
    TLabel *labContactCountAlarm;
    TEdit *editContactCountAlarm;
    TPanel *pnlKitNo1;
    TEdit *edtKitNo1;
    TLabel *lblKit1;
    TPanel *pnlKitNo2;
    TLabel *lblKit2;
    TEdit *edtKitNo2;
    TPanel *pnlKitNo3;
    TLabel *lblKit3;
    TEdit *edtKitNo3;
    TLabel *lblContactAlarmlint;
    TButton *btnClearAa;
    TButton *btnClearAb;
    TButton *btnClearAc;
    TButton *btnClearAd;
    TButton *btnClearAe;
    TButton *btnClearAf;
    TButton *btnClearAg;
    TButton *btnClearAh;
    TButton *btnClearBh;
    TButton *btnClearBg;
    TButton *btnClearBf;
    TButton *btnClearBe;
    TButton *btnClearBd;
    TButton *btnClearBc;
    TButton *btnClearBb;
    TButton *btnClearBa;
    TButton *btnClearCa;
    TButton *btnClearCb;
    TButton *btnClearCc;
    TButton *btnClearCd;
    TButton *btnClearCe;
    TButton *btnClearCf;
    TButton *btnClearCg;
    TButton *btnClearCh;
    TButton *btnClearDh;
    TButton *btnClearDg;
    TButton *btnClearDf;
    TButton *btnClearDe;
    TButton *btnClearDd;
    TButton *btnClearDc;
    TButton *btnClearDb;
    TButton *btnClearDa;
    TGroupBox *gbSetOffsetLimit;
    TLabel *labXYLimit;
    TLabel *labZLimit;
    TEdit *edtSetXYOffsetLimit;
    TEdit *edtSetZOffsetLimit;
    TButton *btnSetOffsetLimit;
        TTabSheet *tsCylinderView;
        TStringGrid *strngrdCylinderView;
        TPopupMenu *pmCylinder;
        TMenuItem *mniResetOnOffCount;
        TMenuItem *mniSetOnOffCountAlarm;
        TMenuItem *mniSetOnTimeAlarm;
        TMenuItem *mniSetOffTimeAlarm;
        TMenuItem *mniSettimeoutcountalarm;
        TMenuItem *mniSetOnTimeStandard;
        TMenuItem *mniSetOffTimeStandard;
        TEdit *edCylinderView;
    void __fastcall sbSameAsHead1Click(TObject *Sender);
    void __fastcall sbClearCountClick(TObject *Sender);
    void __fastcall sbSaveClick(TObject *Sender);
    void __fastcall FormShow(TObject *Sender);
    void __fastcall FormClose(TObject *Sender, TCloseAction &Action);
    void __fastcall sgContactCountSelectCell(TObject *Sender, int ACol, int ARow,
          bool &CanSelect);
    void __fastcall spbExitClick(TObject *Sender);
    void __fastcall sbHeadCondition1ClearClick(TObject *Sender);
    void __fastcall sbHeadCondition1SaveClick(TObject *Sender);
    void __fastcall sgHeadCondition1SelectCell(TObject *Sender, int ACol,
      int ARow, bool &CanSelect);
    void __fastcall pgLifeTimeChange(TObject *Sender);
    void __fastcall editContactCountAlarmMouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
    void __fastcall PanelAaDblClick(TObject *Sender);
    void __fastcall cbStartModeOnlyFTClick(TObject *Sender);

    void __fastcall sb_Maintenance_SmartDiagnosticFunctionClick(
          TObject *Sender);
    void __fastcall btnInArmAClick(TObject *Sender);
    void __fastcall btnOutArmAClick(TObject *Sender);
    void __fastcall btnArm2AaClick(TObject *Sender);
    void __fastcall btnArm1AaClick(TObject *Sender);
    void __fastcall edtInOutArmPickerAlmCntClick(TObject *Sender);
    void __fastcall edtInArmAClick(TObject *Sender);
    void __fastcall btnClearAaClick(TObject *Sender);
    void __fastcall btnSetOffsetLimitClick(TObject *Sender);
    void __fastcall edtSetXYOffsetLimitClick(TObject *Sender);
    void __fastcall edtSetZOffsetLimitClick(TObject *Sender);
    void __fastcall mniResetOnOffCountClick(TObject *Sender);
    void __fastcall strngrdCylinderViewDrawCell(TObject *Sender,
    int ACol, int ARow, TRect &Rect, TGridDrawState State);
    void __fastcall strngrdCylinderViewSelectCell(TObject *Sender,
    int ACol, int ARow, bool &CanSelect);
private:    // User declarations
public:     // User declarations
    __fastcall TfStartCondition(TComponent* Owner);
    void __fastcall TfStartCondition::SocketIDLog();
    void __fastcall DoIniDataToForm();                                          //JerryYang 20170214 (wei) DoIniDataToForm
    void __fastcall WritePickerCount();
    bool fShow;
    void ClearPickerCount(int iArea=-1, int iTag=-1);                           //Steven 20230110 : ²M°£Picker Count
    void ReadWriteStartCondition(bool bRead);                                   //Steven 20250822 : Socket ID¦sÀÉÅªÀÉ
    //Sam 20230516 : Pre Alrm Cylinder
    //==>
    int GetCylinderIndexByName(AnsiString sCylinderName);
    void __fastcall UpdateCylinderScreen(bool bRefrash=false);
    void LoadCylinderLife();
    void SaveCylinderLife();
    AnsiString sCylinderData[eCylPrAlarmItemTotal][MaxCylinderItem];
    HDC PtrDCCyl;
    TCanvas *pCanvasCyl;
    int iSelRow;
    int iSelCol;
    //<==
    //Sam 20230516 : Pre Alrm Cylinder
};
//---------------------------------------------------------------------------
extern PACKAGE TfStartCondition *fStartCondition;
//---------------------------------------------------------------------------
#endif
