//---------------------------------------------------------------------------

#ifndef HandlerSysH
#define HandlerSysH
//---------------------------------------------------------------------------
#include <Buttons.hpp>
#include <Classes.hpp>
#include <Controls.hpp>
#include <ExtCtrls.hpp>
#include <StdCtrls.hpp>
#include <ComCtrls.hpp>
#include <Forms.hpp>

extern void HeaterInsOpt_Read();                                                //AI(ht9045-heater-control) 20260618 (RogerYang) : 簿从承祇2type放北家舱砞﹚
//---------------------------------------------------------------------------
typedef struct TTempComponents
{
    TTempComponents(TRadioGroup *TCb)
    {
        Obj=TCb;
        Par=TCb->Parent;
        Caption=TCb->Caption.UpperCase();
    };
    TTempComponents(TGroupBox *TCb)
    {
        Obj=TCb;
        Par=TCb->Parent;
        Caption=TCb->Caption.UpperCase();
    };
    AnsiString Caption;
    TWinControl *Obj;
    TWinControl *Par;
}TTempComponents;
//---------------------------------------------------------------------------
class THandlerSystem : public TForm
{
__published:    // IDE-managed Components
    TPanel *Panel2;
    TPageControl *pcSetting;
    TTabSheet *TabSheet1;
    TTabSheet *TabSheet2;
    TTabSheet *tsInOutArm;
    TTabSheet *TabSheet4;
    TTabSheet *TabSheet3;
    TTabSheet *TabSheet5;
    TLabel *Label2;
    TLabel *Label3;
    TLabel *Label5;
    TLabel *Label6;
    TLabel *Label7;
    TLabel *Label8;
    TLabel *Label9;
    TLabel *lbl1;
    TLabel *lbl2;
    TLabel *lbl3;
    TLabel *lbl4;
    TLabel *labOCR;
    TComboBox *cbComIndex;
    TComboBox *cbComTemp;
    TComboBox *cbComTempOmron;
    TComboBox *cbComTester;
    TComboBox *cbComBinDisp;
    TComboBox *cbComRTC;
    TComboBox *cbComDyTemp;
    TComboBox *cbbATC2;
    TComboBox *cbbATC3;
    TComboBox *cbbATC4;
    TComboBox *cbbATC1;
    TButton *btnSetATCCom;
    TComboBox *cbOCR;
    TTabSheet *tsCustomerCode;
    TComboBox *cbOCRwithTester;
    TLabel *labOCRwithTester;
    TLabel *labAirConditioner;
    TComboBox *cbAirCon;
    TLabel *labEMAwarePort1;
    TComboBox *cbEMAwarePort1;
    TLabel *labEMAwarePort2;
    TLabel *labEMAwarePort3;
    TLabel *labEMAwarePort4;
    TComboBox *cbEMAwarePort2;
    TComboBox *cbEMAwarePort3;
    TComboBox *cbEMAwarePort4;
    TCheckBox *cbESDUse4COM;
    TLabel *labSimcoION_Novx3360;
    TComboBox *cbNovx3360;
    TLabel *labLaser1;
    TLabel *labLaser2;
    TLabel *labLaserInArm;
    TComboBox *cbComLaser1;
    TComboBox *cbComLaser2;
    TComboBox *cbComLaserInArm;
    TTabSheet *tsShuttle;
    TTabSheet *tsIONFan;
    TRadioGroup *rgColorSensor;
    TLabel *lab2DReader1;
    TLabel *lab2DReader2;
    TLabel *lab2DReader3;
    TLabel *lab2DReader4;
    TComboBox *cb2DReader1;
    TComboBox *cb2DReader2;
    TComboBox *cb2DReader3;
    TComboBox *cb2DReader4;
    TGroupBox *gbRotateKit;
    TRadioGroup *rgRotateKit;
    TRadioGroup *rgRotateKitIn;
    TRadioGroup *rgRotateKitOut;
    TRadioGroup *rgRotateKit_Type;
    TLabel *lblGroundMan;
    TComboBox *cbbGroundMan;
    TLabel *labKASUGA_Fan;
    TComboBox *cbKASUGA_Fan;
    TGroupBox *grpOther;
    TComboBox *cbSocketSenAmpCnt;
    TLabel *Label22;
    TLabel *Label23;
    TComboBox *cbRotateSenAmpCnt;
    TLabel *Label24;
    TComboBox *cbColorSenAmpCnt;
    TRadioGroup *rgSocketSen;
    TLabel *lblTrayStepMotor;
    TComboBox *cbbTrayStepMotor;
    TCheckBox *chkUseHPComCard;
    TGroupBox *grpCanBus;
    TRadioGroup *rgCanBusMethod;
    TLabel *Label30;
    TPanel *pnlLoader1;
    TRadioGroup *rgTrayVibration;
    TRadioGroup *rgNumberPanelType;
    TRadioGroup *rgInstallFix3;
    TRadioGroup *rgAutoAlignment;
    TRadioGroup *rgLoaderVibration;
    TPanel *pnlLoader2;
    TRadioGroup *Auto2SelectCy;
    TRadioGroup *rgLdUldUseStepMotor;
    TPanel *pnlLoader3;
    TRadioGroup *rgCKDFCM;
    TRadioGroup *rgCatchTrayModel;
    TPanel *pnlLoader4;
    TRadioGroup *rgAutoTrackCanGoRear;
    TPanel *pnlLoader5;
    TRadioGroup *rgTrayMappingGrabImage;
    TRadioGroup *rgLoaderKeyence;
    TRadioGroup *rgMultileEmptyTrayIDKeyence;
    TRadioGroup *rgEmptyKeyence;
    TRadioGroup *rgFix3FullPlace;
    TRadioGroup *rgRFIDSystem;
    TRadioGroup *rgCatchTrayBlock;
    TRadioGroup *rgTrayRobot;
    TRadioGroup *rgMultileEmpty;
    TPanel *pnlHandler3;
    TPanel *pnlHandler1;
    TGroupBox *GroupBox3;
    TLabel *Label4;
    TLabel *Label1;
    TLabel *Label10;
    TEdit *edtCustomerCode;
    TEdit *edtSeriaNo;
    TComboBox *cbHandlerModel;
    TRadioGroup *rgModel;
    TRadioGroup *rgMotionCard;
    TRadioGroup *rgIOCard;
    TRadioGroup *rgTTLCard;
    TRadioGroup *rgUseSucker_9046_DB;
    TRadioGroup *rgUseSensor_9046_DB;
    TPanel *pnlHandler2;
    TRadioGroup *rgSafeDoorLock;
    TRadioGroup *rgMNetSpeed;
    TRadioGroup *rgIndexMotionCard;
    TGroupBox *GroupBox1;
    TCheckBox *SafeDoor1;
    TCheckBox *SafeDoor2;
    TCheckBox *SafeDoor3;
    TCheckBox *SafeDoor4;
    TCheckBox *SafeDoor5;
    TCheckBox *SafeDoor6;
    TCheckBox *SafeDoor7;
    TCheckBox *SafeDoor8;
    TButton *BtnEnableAll;
    TCheckBox *SafeDoor9;
    TCheckBox *SafeDoor10;
    TGroupBox *GroupBox2;
    TCheckBox *HeaterDoor1;
    TCheckBox *HeaterDoor2;
    TPanel *pnlInArm1;
    TGroupBox *grpInOutArmYPitch;
    TLabel *lblMinYPitch;
    TLabel *lblMaxYPitch;
    TRadioGroup *rgInOutArmYPitch;
    TEdit *edtMinYPitch;
    TEdit *edtMaxYPitch;
    TPanel *pnlInArm2;
    TRadioGroup *rgLaserDistance;
    TRadioGroup *rgOCR;
    TRadioGroup *rgDeviceFlipper;
    TPanel *pnlInArm3;
    TRadioGroup *rgHotPlatePos;
    TRadioGroup *rgHotplateType;
    TRadioGroup *rgHotPlateLimit;
    TRadioGroup *rgMagneticScale;
    TRadioGroup *ArmZAtoZH;
    TRadioGroup *rgPickerCount;
    TRadioGroup *rgPreciser;
    TRadioGroup *rgPreciserPos;
    TRadioGroup *rgDieClean;
    TPanel *pnlOther1;
    TRadioGroup *rgSafeDoor;
    TRadioGroup *rgAOI;
    TGroupBox *GroupBox7;
    TEdit *ed24VMonitorPulseCount;
    TPanel *pnlSht3;
    TPanel *pnlSht2;
    TPanel *pnlSht1;
    TRadioGroup *rg2DBarcode;
    TRadioGroup *rgShuttleFloating;
    TRadioGroup *rgBottom2DID;
    TGroupBox *grpCognexCCD;
    TLabel *lblCognexCCD;
    TEdit *edCognexSystemCCD;
    TRadioGroup *rgShuttleSensor;
    TRadioGroup *rgShuttleZType;
    TRadioGroup *rgShuttleCrossSensor;
    TRadioGroup *rgAutoShuttleSensor;
    TRadioGroup *rgInShtLastSensor;
    TRadioGroup *rgShuttleVibration;
    TRadioGroup *rgUseOutSht;
    TPanel *pnlIndex4;
    TRadioGroup *rgUse4DUT;
    TRadioGroup *rgOTDInstall;
    TPanel *pnlIndex3;
    TRadioGroup *rgIOChangeToque;
    TRadioGroup *rgIndexMotorType;
    TRadioGroup *rgSocketClamp;
    TRadioGroup *rgRealTimeCCD;
    TRadioGroup *rgRealTimeCCDTempNum;
    TPanel *pnlIndex1;
    TRadioGroup *rgIndexPressType;
    TGroupBox *gbEPReadSetting;
    TLabel *Label12;
    TLabel *Label16;
    TEdit *edMaxMpaFB;
    TEdit *edtMinMpaFB;
    TRadioGroup *rgDoubleEPControl;
    TPanel *pnlIndex2;
    TRadioGroup *rgATC;
    TRadioGroup *rgHeaterType;
    TGroupBox *GroupBox4;
    TLabel *lbATCSystemIP;
    TLabel *Label15;
    TLabel *Label14;
    TEdit *edATCSystemIP;
    TEdit *edATCSystemPort;
    TEdit *edATCSystemUseHeat;
    TPanel *pnlIndex5;
    TRadioGroup *rgHighTempLimit;
    TGroupBox *grpContactHeight;
    TLabel *lblContactHeight;
    TCheckBox *chkUserDefMaxContactHeight;
    TEdit *edtUserDefMaxContactHeight;
    TGroupBox *GroupBox8;
    TLabel *Label17;
    TLabel *Label18;
    TLabel *Label19;
    TLabel *Label20;
    TEdit *edHotGunFlow_LineNo;
    TEdit *edHotGunFlow_DevNo;
    TEdit *edHotGunFlow_Gun1_ChannelNo;
    TEdit *edHotGunFlow_Gun2_ChannelNo;
    TRadioGroup *rgHotGunFlow;
    TRadioGroup *rgHeatGun;
    TRadioGroup *rgHeater;
    TRadioGroup *rgESDTemp;
    TRadioGroup *rgAirConditioner;
    TRadioGroup *ElectronPressure;
    TRadioGroup *rgWeightCali;
    TRadioGroup *rgIndexSuckerType;
    TGroupBox *gbEPSetting;
    TLabel *Label11;
    TLabel *Label13;
    TEdit *edMaxKpa;
    TEdit *edMinMpa;
    TRadioGroup *rgLBTemp;
    TRadioGroup *rgCleanAir;
    TRadioGroup *rgFinePitch;
    TLabel *Label26;
    TComboBox *cbIndEPCnt;
    TRadioGroup *rgDewpointHW;
    TRadioGroup *rgCCDTemp;
    TTabSheet *tsSearchFunction;
    TScrollBox *scrlbxSearchFunc;
    TLabeledEdit *edtSearchFunction;
    TPanel *pnlESD1;
    TRadioGroup *rgIonFanType;
    TRadioGroup *rgUsePulseType;
    TGroupBox *grpIONPulseCount;
    TEdit *edIONPulseCount;
    TPanel *pnlESD2;
    TGroupBox *grpGroundMan;
    TLabel *Label21;
    TRadioGroup *rgGroundMan;
    TRadioGroup *rgGroundMan_ScanPoint;
    TEdit *edGroundMan_AlarmOhm;
    TRadioGroup *rg_ControlPanelMode;
    TLabel *labTTL1RS232;
    TComboBox *cbComTTLRS232;
    TComboBox *cbComTTLRS232_2;
    TLabel *labTTL2RS232;
    TRadioGroup *rgTTLUseAddress;
    TRadioGroup *rgFixAICCD;
    TRadioGroup *rgATCHeatGun;
    TLabel *lblRFIDReader;
    TComboBox *cbbRFIDReader;
    TRadioGroup *rgCCDAutoAlignmentMode;
    TRadioGroup *rgInPlacement;
    TRadioGroup *rgIndexMotorAxis;
    TGroupBox *grpIndexZSafePos;
    TLabel *lblIndexHeight;
    TCheckBox *chkUser_Define_IndexZ_SafePos;
    TEdit *edtUserDefineIndexZSafePos;
    TRadioGroup *rgBottom2DID_CCD;
    TRadioGroup *rgTrayArmMode;
    TRadioGroup *rgBaseHeaterCount;
    TRadioGroup *rgShuttleFloodgate;
    TRadioGroup *rgNUECType;
    TRadioGroup *rgCOLORSENSOR_MUN;
    TRadioGroup *rgInOutArmXPitch;
    TLabel *lblXPitchMin;
    TEdit *edtMinXPitch;
    TEdit *edtMaxXPitch;
    TLabel *lblXPitchMax;
    TLabel *Label35;
    TEdit *edtHPLimit;
    TGroupBox *gbVibrationCommuncation;
    TRadioGroup *rgVibrationCommuncation;
    TLabel *labVibrateComm;
    TComboBox *cbVibrationCardQty;
    TRadioGroup *MachineTrack;
    TRadioGroup *rgLoaderHinge;
    TGroupBox *gbUseCassetteMode;
    TCheckBox *cbLoaderCassette;
    TCheckBox *cbEmptyCassette;
    TCheckBox *cbColorCassette;
    TCheckBox *cbAuto1Cassette;
    TCheckBox *cbAuto2Cassette;
    TCheckBox *cbAuto3Cassette;
    TCheckBox *cbAuto4Cassette;
    TCheckBox *cbAuto5Cassette;
    TCheckBox *cbAuto6Cassette;
    TGroupBox *grpTrayZUseMot;
    TCheckBox *chkLoader;
    TCheckBox *chkEmpty;
    TCheckBox *chkColor;
    TCheckBox *chkAuto1;
    TCheckBox *chkAuto2;
    TCheckBox *chkAuto3;
    TCheckBox *chkAuto6;
    TCheckBox *chkAuto5;
    TCheckBox *chkAuto4;
    TGroupBox *gbART;
    TRadioGroup *rgInstallAutoRestest;
    TRadioGroup *rgAuto1ART;
    TRadioGroup *rgAuto2ART;
    TRadioGroup *rgAuto3ART;
    TRadioGroup *rgInstallARTtwocylinder;
    TRadioGroup *rgAuto6ART;
    TRadioGroup *rgAuto5ART;
    TRadioGroup *rgAuto4ART;
    TLabel *lbl5;
    TComboBox *cbbComBinDisp2;
    TPanel *Panel1;
    TRadioGroup *rgMagBinDispType;
    TGroupBox *grpTriTemperature;
    TLabel *lbl7;
    TLabel *lbl8;
    TLabel *lbl9;
    TLabel *Label34;
    TRadioGroup *rgTriTempMachine;
    TRadioGroup *rgAirStreamSelect;
    TEdit *edtTriTemperature_MaxDegree;
    TEdit *edtTriTemperature_MinDegree;
    TEdit *edtTriTempTotalCh;
    TGroupBox *grp_SetHeaterTemp;
    TLabel *Label25;
    TLabel *Label32;
    TLabel *Label33;
    TEdit *edtOutShtMaxTemp;
    TEdit *edtIndexMaxTemp;
    TEdit *edtBaseMaxTemp;
    TEdit *edt_Total_Compressor;
    TRadioGroup *rgAutoFormSize;
    TRadioGroup *rgDoubleBeltMode;
    TRadioGroup *rg_IndexDoorHeater;
    TPanel *Panel3;
    TBitBtn *SaveBtn;
    TBitBtn *ExitBtn;
    TBitBtn *LoadBtn;
    TLabeledEdit *edtSearchCode;
    TPanel *pnlLoader6;
    TPanel *pnlInArm4;
    TGroupBox *grpOutSortArm;
    TLabel *lblOutSortXPitchMin;
    TLabel *lblOutSortXPitchMax;
    TEdit *edtOutSortXPitchMin;
    TEdit *edtOutSortXPitchMax;
    TRadioGroup *rgOutSortArm;
    TRadioGroup *rgVacuUnitType;
    TPanel *Panel4;
    TCheckBox *cbEnableOutShtSensor;
    TCheckBox *chkOutShtYSensorByLatch;
    TCheckBox *chk2x3modeUseAxisYSensor;
    TCheckBox *chkBiasModeUseYSensor;
    TRadioGroup *rgScanner_AOI;
    TRadioGroup *rgTopScanner_AOI;
    TRadioGroup *rgSafePlcIO;
    TLabel *Label27;
    TLabel *Label28;
    TLabel *Label29;
    TLabel *Label31;
    TComboBox *coNudn1Macid11;
    TComboBox *coNudn1Macid12;
    TComboBox *coNudn1Macid13;
    TComboBox *coCanBusNudn1;
    TRadioGroup *rgLBTemp2;
    TRadioGroup *rgCustomerList;
    TComboBox *coNudn1Macid14;
    TLabel *Label36;
    TLabel *Label37;
    TComboBox *cbSocketSenAmpCnt2nd;
    TRadioGroup *rgInShtAutoLatch;
    TRadioGroup *rgLDCarRotAtm;
    TRadioGroup *rgE84Sensor;
    TRadioGroup *rgLdUldCassetteMode;
    TRadioGroup *rgOutArmYPitch;
    TPanel *pnlCloseLoop;
    TRadioGroup *rg3M_EM_AWARE_Monitor;
    TRadioGroup *rgNovx3360;
    TRadioGroup *rgKasuga;
    TRadioGroup *rgKasuga_Fan;
    TRadioGroup *rgHTIonBar;
    TRadioGroup *rgChamberUsePulseType;
    TRadioGroup *rgAutoCleanIonFan;
    TRadioGroup *rgOCRYStepMot;
    TRadioGroup *rgCoverTrayID;
    TRadioGroup *rgRFIDReader;
    TRadioGroup *rg2ndLoader;
    TRadioGroup *rgAuto3Magazine;
    TRadioGroup *rgOHTSystem;
    TRadioGroup *rgMRSystem;
    TRadioGroup *rgTrayMapping;
    TGroupBox *grpTrayYUseMot;
    TCheckBox *chkLoaderY;
    TCheckBox *chkEmptyY;
    TCheckBox *chkColorY;
    TCheckBox *chkAuto1Y;
    TCheckBox *chkAuto2Y;
    TCheckBox *chkAuto3Y;                                                       //AI(ht9045-v899) 20260423: auto3 y stepper checkbox
    TRadioGroup *rgATCMixMode;
    TLabel *lab3rdSocketSensor;
    TComboBox *cbSocketSenAmpCnt3rd;
    TTabSheet *tsHeater;
    TGroupBox *grpHeater;
    void __fastcall FormShow(TObject *Sender);
    void __fastcall SaveBtnClick(TObject *Sender);
    void __fastcall LoadBtnClick(TObject *Sender);
    void __fastcall ExitBtnClick(TObject *Sender);
    void __fastcall BtnEnableAllClick(TObject *Sender);
    void __fastcall rgCustomerListClick(TObject *Sender);
    void __fastcall ExitBtnMouseDown(TObject *Sender, TMouseButton Button,
          TShiftState Shift, int X, int Y);
    void __fastcall FormClose(TObject *Sender, TCloseAction &Action);
    void __fastcall btnSetATCComClick(TObject *Sender);
    void __fastcall rgRotateKit_TypeClick(TObject *Sender);
    void __fastcall edtUserDefMaxContactHeightClick(TObject *Sender);
    void __fastcall pcSettingChange(TObject *Sender);
    void __fastcall FormDestroy(TObject *Sender);
    void __fastcall edtSearchCodeChange(TObject *Sender);
    void __fastcall edtSearchFunctionChange(TObject *Sender);
    void __fastcall rgTTLCardClick(TObject *Sender);
    void __fastcall edtUserDefineIndexZSafePosClick(TObject *Sender);
    void __fastcall edtCustomerCodeClick(TObject *Sender);
    void __fastcall edMaxMpaFBClick(TObject *Sender);
    void __fastcall edMaxKpaClick(TObject *Sender);
    void __fastcall edMinMpaClick(TObject *Sender);
    void __fastcall edATCSystemPortClick(TObject *Sender);
    void __fastcall edATCSystemUseHeatClick(TObject *Sender);
    void __fastcall edHotGunFlow_Gun1_ChannelNoClick(TObject *Sender);
    void __fastcall edHotGunFlow_DevNoClick(TObject *Sender);
    void __fastcall edtMinYPitchClick(TObject *Sender);
    void __fastcall edtMaxYPitchClick(TObject *Sender);
    void __fastcall edCognexSystemCCDClick(TObject *Sender);
    void __fastcall ed24VMonitorPulseCountClick(TObject *Sender);
    void __fastcall edGroundMan_AlarmOhmClick(TObject *Sender);
    void __fastcall edIONPulseCountClick(TObject *Sender);
    void __fastcall edtTriTempTotalChClick(TObject *Sender);
    void __fastcall edtOutShtMaxTempClick(TObject *Sender);
    void __fastcall edtTriTemperature_MaxDegreeClick(TObject *Sender);
    void __fastcall edtTriTemperature_MinDegreeClick(TObject *Sender);
    void __fastcall edtIndexMaxTempClick(TObject *Sender);
    void __fastcall edt_Total_CompressorChange(TObject *Sender);
    void __fastcall edtMinXPitchClick(TObject *Sender);
    void __fastcall edtMaxXPitchClick(TObject *Sender);
    void __fastcall cbHeaterInsOptChange_Base(TObject *Sender);
    void __fastcall rgHeaterTypeClick(TObject *Sender);                 //AI(ht9045-heater-control) 20260618 (RogerYang) : 簿从承祇2type放北家舱砞﹚
private:    // User declarations
public:     // User declarations
    __fastcall THandlerSystem(TComponent* Owner);
    void __fastcall LoaderSystemSet();
    void __fastcall SaveSystemSet();
    void __fastcall LoaderSafeDoorSet();
    void __fastcall SaveSafeDoorSet();
    AnsiString GetCustomerName();
    TStringList *slCustomerCode;
    void SortItemToMap();
    void InitItemToMap(TWinControl *PCtrl);
    vector <TTempComponents *>TempComp;
};
//---------------------------------------------------------------------------
extern PACKAGE THandlerSystem *HandlerSystem;
//---------------------------------------------------------------------------
#endif
