// ============================================================================
// DO NOT EDIT -- machine-generated by emit_rc.py W7-B1b v1.0 on Automation/automation.dfm
// AI(W906-W7-B1b) 20260728: generated .rc/_ids.h from the .dfm IR (see
// docs/W7_UI_ARCHITECTURE_PLAN.md S6 W7-B1b). Hand edits will be
// overwritten and are rejected by the idempotence gate (G7).
// Source golden: Automation/automation.dfm
// ============================================================================

#ifndef HT9045_UI_GEN_AUTOMATION_IDS_H
#define HT9045_UI_GEN_AUTOMATION_IDS_H

// Dialog template IDs
#define IDD_AUTOMATION 8192
#define IDD_AUTOMATION_PGCOLP_TABSHEET20 8193
#define IDD_AUTOMATION_PGCOLP_TABSHEET6 8194
#define IDD_AUTOMATION_PGCOLP_TABSHEET22 8195
#define IDD_AUTOMATION_GBAUTOMATION 8196
#define IDD_AUTOMATION_GBAUTOMATION_PANEL1 8197

// Control IDs (D11 join key: mechanically derived from the
// .dfm leaf control name -- IDC_<FORMSTEM>_<CONTROLNAME>)
#define IDC_AUTOMATION_PGCOLP 1024
#define IDC_AUTOMATION_BTUDPSEND 1025
#define IDC_AUTOMATION_BTUDPMAP 1026
#define IDC_AUTOMATION_BTUDPTEMP 1027
#define IDC_AUTOMATION_MEMO 1028
#define IDC_AUTOMATION_MEMOCHAR 1029
#define IDC_AUTOMATION_MEMOCODE 1030
#define IDC_AUTOMATION_GBAUTOMATION_FRAME 1031  // synthesized: SYNTH_CONTAINER_FRAME
#define IDC_AUTOMATION_ONLINE 1032
#define IDC_AUTOMATION_ONLINE2 1033
#define IDC_AUTOMATION_CBBOLPCOMMAND 1034
#define IDC_AUTOMATION_BTEVENTREPORT 1035
#define IDC_AUTOMATION_BTALARMREPORT 1036
#define IDC_AUTOMATION_CHKVIEWCOMM 1037
#define IDC_AUTOMATION_BTNCONNECT 1038
#define IDC_AUTOMATION_BTNDISCONNECT 1039
#define IDC_AUTOMATION_BTTESTRESULT 1040
#define IDC_AUTOMATION_LBIP 1041
#define IDC_AUTOMATION_LBPORT 1042
#define IDC_AUTOMATION_EDINPUTIP 1043
#define IDC_AUTOMATION_EDINPUTPORT 1044

#endif // HT9045_UI_GEN_AUTOMATION_IDS_H
