// ============================================================================
// DO NOT EDIT -- machine-generated by emit_rc.py W7-B1b v1.0 on Automation/ufrmProdInfo.dfm
// AI(W906-W7-B1b) 20260728: generated .rc/_ids.h from the .dfm IR (see
// docs/W7_UI_ARCHITECTURE_PLAN.md S6 W7-B1b). Hand edits will be
// overwritten and are rejected by the idempotence gate (G7).
// Source golden: Automation/ufrmProdInfo.dfm
// ============================================================================

#ifndef HT9045_UI_GEN_UFRMPRODINFO_IDS_H
#define HT9045_UI_GEN_UFRMPRODINFO_IDS_H

// Dialog template IDs
#define IDD_UFRMPRODINFO 8192

// Control IDs (D11 join key: mechanically derived from the
// .dfm leaf control name -- IDC_<FORMSTEM>_<CONTROLNAME>)
#define IDC_UFRMPRODINFO_LBLEDTLOTNO_LABEL 1025  // synthesized: SYNTH_LABELEDEDIT_LABEL
#define IDC_UFRMPRODINFO_LBLEDTLOTNO 1024
#define IDC_UFRMPRODINFO_LBLEDTLOTID_LABEL 1027  // synthesized: SYNTH_LABELEDEDIT_LABEL
#define IDC_UFRMPRODINFO_LBLEDTLOTID 1026
#define IDC_UFRMPRODINFO_LBLEDTHDPARAMETER_LABEL 1029  // synthesized: SYNTH_LABELEDEDIT_LABEL
#define IDC_UFRMPRODINFO_LBLEDTHDPARAMETER 1028
#define IDC_UFRMPRODINFO_LBLEDTPRODUCT_LABEL 1031  // synthesized: SYNTH_LABELEDEDIT_LABEL
#define IDC_UFRMPRODINFO_LBLEDTPRODUCT 1030
#define IDC_UFRMPRODINFO_LBLEDTSTEPCODE_LABEL 1033  // synthesized: SYNTH_LABELEDEDIT_LABEL
#define IDC_UFRMPRODINFO_LBLEDTSTEPCODE 1032
#define IDC_UFRMPRODINFO_LBLEDTQTY_LABEL 1035  // synthesized: SYNTH_LABELEDEDIT_LABEL
#define IDC_UFRMPRODINFO_LBLEDTQTY 1034
#define IDC_UFRMPRODINFO_LBLEDTDATE_LABEL 1037  // synthesized: SYNTH_LABELEDEDIT_LABEL
#define IDC_UFRMPRODINFO_LBLEDTDATE 1036

#endif // HT9045_UI_GEN_UFRMPRODINFO_IDS_H
