// ===========================================================================
//  Monitor/MonitorInterface_layout.gen.cpp
//  DO NOT EDIT -- GENERATED FILE. See the matching _layout.gen.h banner.
// ===========================================================================
#include "MonitorInterface_layout.gen.h"

namespace ht9045_layout {

const DfmCustomProp kMonitorInterfaceCustomProps[] = {
    { "LEDStyle", "LEDLarge" },
};

const DfmControlLayout kMonitorInterfaceLayout[] = {
    { "fMonitor", "fMonitor", "", "TfMonitor", "", "", 0, 0, "ROOT", false, true, 1222, true, 286, false, 0, false, 0, false, 0, -1, "", "", true, "MS Sans Serif", -11, "", true, -2147483640, "clWindowText", true, -2147483633, "clBtnFace", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fMonitor.pnMVConnectTitle", "pnMVConnectTitle", "IDD_MONITORINTERFACE_PNMVCONNECTTITLE", "TPanel", "fMonitor", "fMonitor", 0, 1, "SUBDLG", false, true, 0, true, 0, true, 600, true, 80, true, 0, -1, "", "", false, "", 0, "", false, 0, "", true, -2147483645, "clInactiveCaption", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fMonitor.pnMVConnectTitle.lbMVConnectState", "lbMVConnectState", "IDC_MONITORINTERFACE_LBMVCONNECTSTATE", "TLabel", "fMonitor.pnMVConnectTitle", "fMonitor.pnMVConnectTitle", 0, 2, "LEAF", true, true, 90, true, 23, true, 151, true, 39, false, 0, -1, "", "", true, "MS Sans Serif", -32, "", true, 8388608, "clNavy", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fMonitor.pnMVConnectTitle.sbMVConnect", "sbMVConnect", "IDC_MONITORINTERFACE_SBMVCONNECT", "TSpeedButton", "fMonitor.pnMVConnectTitle", "fMonitor.pnMVConnectTitle", 1, 2, "LEAF", true, true, 288, true, 24, true, 140, true, 40, false, 0, -1, "", "", true, "MS Sans Serif", -19, "", true, 8388608, "clNavy", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fMonitor.pnMVConnectTitle.sbMVDisconnect", "sbMVDisconnect", "IDC_MONITORINTERFACE_SBMVDISCONNECT", "TSpeedButton", "fMonitor.pnMVConnectTitle", "fMonitor.pnMVConnectTitle", 2, 2, "LEAF", true, true, 440, true, 24, true, 140, true, 40, false, 0, -1, "", "", true, "MS Sans Serif", -19, "", true, 8388608, "clNavy", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fMonitor.pnMVConnectTitle.pnMVState", "pnMVState", "IDC_MONITORINTERFACE_PNMVSTATE", "TPanel", "fMonitor.pnMVConnectTitle", "fMonitor.pnMVConnectTitle", 3, 2, "LEAF", false, true, 10, true, 10, true, 65, true, 60, true, 0, -1, "", "", false, "", 0, "", false, 0, "", true, 32768, "clGreen", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fMonitor.MVPageControl", "MVPageControl", "IDC_MONITORINTERFACE_MVPAGECONTROL", "TPageControl", "fMonitor", "fMonitor", 1, 1, "TABHOST", false, true, 0, true, 80, true, 510, true, 401, true, 1, -1, "", "", true, "MS Sans Serif", -13, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fMonitor.MVPageControl.tsMVMain", "tsMVMain", "IDD_MONITORINTERFACE_MVPAGECONTROL_TSMVMAIN", "TTabSheet", "fMonitor.MVPageControl", "fMonitor", 0, 2, "SUBDLG", false, false, 0, false, 0, false, 0, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fMonitor.MVPageControl.tsMVMain.sbMVLogClear", "sbMVLogClear", "IDC_MONITORINTERFACE_SBMVLOGCLEAR", "TSpeedButton", "fMonitor.MVPageControl.tsMVMain", "fMonitor.MVPageControl.tsMVMain", 0, 3, "LEAF", true, true, 0, true, 335, true, 500, true, 30, false, 0, -1, "", "", true, "MS Sans Serif", -16, "fsBold", true, 8388736, "clPurple", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fMonitor.MVPageControl.tsMVMain.MonitorMemo", "MonitorMemo", "IDC_MONITORINTERFACE_MONITORMEMO", "TMemo", "fMonitor.MVPageControl.tsMVMain", "fMonitor.MVPageControl.tsMVMain", 1, 3, "LEAF", false, true, 0, true, 184, true, 497, true, 150, true, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fMonitor.MVPageControl.tsMVMain.pnMVMain", "pnMVMain", "IDD_MONITORINTERFACE_MVPAGECONTROL_TSMVMAIN_PNMVMAIN", "TPanel", "fMonitor.MVPageControl.tsMVMain", "fMonitor.MVPageControl.tsMVMain", 2, 3, "SUBDLG", false, true, 0, true, 0, true, 500, true, 180, true, 1, -1, "", "", false, "", 0, "", false, 0, "", true, 16107399, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fMonitor.MVPageControl.tsMVMain.pnMVMain.sbSendCommand", "sbSendCommand", "IDC_MONITORINTERFACE_SBSENDCOMMAND", "TSpeedButton", "fMonitor.MVPageControl.tsMVMain.pnMVMain", "fMonitor.MVPageControl.tsMVMain.pnMVMain", 0, 4, "LEAF", true, true, 280, true, 16, true, 73, true, 22, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fMonitor.MVPageControl.tsMVMain.pnMVMain.sbMonitor1Open", "sbMonitor1Open", "IDC_MONITORINTERFACE_SBMONITOR1OPEN", "TSpeedButton", "fMonitor.MVPageControl.tsMVMain.pnMVMain", "fMonitor.MVPageControl.tsMVMain.pnMVMain", 1, 4, "LEAF", true, true, 48, true, 104, true, 100, true, 30, false, 0, -1, "", "", true, "MS Sans Serif", -13, "", true, 8388608, "clNavy", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fMonitor.MVPageControl.tsMVMain.pnMVMain.sbMonitor2Open", "sbMonitor2Open", "IDC_MONITORINTERFACE_SBMONITOR2OPEN", "TSpeedButton", "fMonitor.MVPageControl.tsMVMain.pnMVMain", "fMonitor.MVPageControl.tsMVMain.pnMVMain", 2, 4, "LEAF", true, true, 160, true, 104, true, 100, true, 30, false, 0, -1, "", "", true, "MS Sans Serif", -13, "", true, 8388608, "clNavy", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fMonitor.MVPageControl.tsMVMain.pnMVMain.sbMonitor3Open", "sbMonitor3Open", "IDC_MONITORINTERFACE_SBMONITOR3OPEN", "TSpeedButton", "fMonitor.MVPageControl.tsMVMain.pnMVMain", "fMonitor.MVPageControl.tsMVMain.pnMVMain", 3, 4, "LEAF", true, true, 272, true, 104, true, 100, true, 30, false, 0, -1, "", "", true, "MS Sans Serif", -13, "", true, 8388608, "clNavy", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fMonitor.MVPageControl.tsMVMain.pnMVMain.sbMonitor1Stop", "sbMonitor1Stop", "IDC_MONITORINTERFACE_SBMONITOR1STOP", "TSpeedButton", "fMonitor.MVPageControl.tsMVMain.pnMVMain", "fMonitor.MVPageControl.tsMVMain.pnMVMain", 4, 4, "LEAF", true, true, 48, true, 144, true, 100, true, 30, false, 0, -1, "", "", true, "MS Sans Serif", -13, "", true, 8388608, "clNavy", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fMonitor.MVPageControl.tsMVMain.pnMVMain.sbMonitor2Stop", "sbMonitor2Stop", "IDC_MONITORINTERFACE_SBMONITOR2STOP", "TSpeedButton", "fMonitor.MVPageControl.tsMVMain.pnMVMain", "fMonitor.MVPageControl.tsMVMain.pnMVMain", 5, 4, "LEAF", true, true, 160, true, 144, true, 100, true, 30, false, 0, -1, "", "", true, "MS Sans Serif", -13, "", true, 8388608, "clNavy", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fMonitor.MVPageControl.tsMVMain.pnMVMain.sbMonitor3Stop", "sbMonitor3Stop", "IDC_MONITORINTERFACE_SBMONITOR3STOP", "TSpeedButton", "fMonitor.MVPageControl.tsMVMain.pnMVMain", "fMonitor.MVPageControl.tsMVMain.pnMVMain", 6, 4, "LEAF", true, true, 272, true, 144, true, 100, true, 30, false, 0, -1, "", "", true, "MS Sans Serif", -13, "", true, 8388608, "clNavy", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fMonitor.MVPageControl.tsMVMain.pnMVMain.MyLed1", "MyLed1", "IDC_MONITORINTERFACE_MYLED1", "TMyLed", "fMonitor.MVPageControl.tsMVMain.pnMVMain", "fMonitor.MVPageControl.tsMVMain.pnMVMain", 7, 4, "LEAF", true, true, 7, true, 104, true, 32, true, 32, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 1, &kMonitorInterfaceCustomProps[0] },
    { "fMonitor.MVPageControl.tsMVMain.pnMVMain.sbMonitorGetHDSpace", "sbMonitorGetHDSpace", "IDC_MONITORINTERFACE_SBMONITORGETHDSPACE", "TSpeedButton", "fMonitor.MVPageControl.tsMVMain.pnMVMain", "fMonitor.MVPageControl.tsMVMain.pnMVMain", 8, 4, "LEAF", true, true, 384, true, 104, true, 100, true, 30, false, 0, -1, "", "", true, "MS Sans Serif", -13, "", true, 8388608, "clNavy", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fMonitor.MVPageControl.tsMVMain.pnMVMain.edCommandData", "edCommandData", "IDC_MONITORINTERFACE_EDCOMMANDDATA", "TEdit", "fMonitor.MVPageControl.tsMVMain.pnMVMain", "fMonitor.MVPageControl.tsMVMain.pnMVMain", 9, 4, "LEAF", false, true, 8, true, 16, true, 265, true, 24, true, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fMonitor.MVPageControl.tsMVSettingPage", "tsMVSettingPage", "IDD_MONITORINTERFACE_MVPAGECONTROL_TSMVSETTINGPAGE", "TTabSheet", "fMonitor.MVPageControl", "fMonitor", 1, 2, "SUBDLG", false, false, 0, false, 0, false, 0, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fMonitor.MVPageControl.tsMVSettingPage.pnMVSetupPage", "pnMVSetupPage", "IDD_MONITORINTERFACE_MVPAGECONTROL_TSMVSETTINGPAGE_PNMVSETUPPAGE", "TPanel", "fMonitor.MVPageControl.tsMVSettingPage", "fMonitor.MVPageControl.tsMVSettingPage", 0, 3, "SUBDLG", false, true, 0, true, 0, true, 500, true, 365, true, 0, -1, "", "", false, "", 0, "", false, 0, "", true, 16107399, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fMonitor.MVPageControl.tsMVSettingPage.pnMVSetupPage.lbMVAddress", "lbMVAddress", "IDC_MONITORINTERFACE_LBMVADDRESS", "TLabel", "fMonitor.MVPageControl.tsMVSettingPage.pnMVSetupPage", "fMonitor.MVPageControl.tsMVSettingPage.pnMVSetupPage", 0, 4, "LEAF", true, true, 29, true, 20, true, 59, true, 20, false, 0, -1, "", "", true, "MS Sans Serif", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fMonitor.MVPageControl.tsMVSettingPage.pnMVSetupPage.lbMVPort", "lbMVPort", "IDC_MONITORINTERFACE_LBMVPORT", "TLabel", "fMonitor.MVPageControl.tsMVSettingPage.pnMVSetupPage", "fMonitor.MVPageControl.tsMVSettingPage.pnMVSetupPage", 1, 4, "LEAF", true, true, 29, true, 50, true, 29, true, 20, false, 0, -1, "", "", true, "MS Sans Serif", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fMonitor.MVPageControl.tsMVSettingPage.pnMVSetupPage.edMVPort", "edMVPort", "IDC_MONITORINTERFACE_EDMVPORT", "TEdit", "fMonitor.MVPageControl.tsMVSettingPage.pnMVSetupPage", "fMonitor.MVPageControl.tsMVSettingPage.pnMVSetupPage", 2, 4, "LEAF", false, true, 94, true, 48, true, 60, true, 28, true, 0, -1, "", "", true, "MS Sans Serif", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fMonitor.MVPageControl.tsMVSettingPage.pnMVSetupPage.edMVAddress", "edMVAddress", "IDC_MONITORINTERFACE_EDMVADDRESS", "TEdit", "fMonitor.MVPageControl.tsMVSettingPage.pnMVSetupPage", "fMonitor.MVPageControl.tsMVSettingPage.pnMVSetupPage", 3, 4, "LEAF", false, true, 94, true, 16, true, 140, true, 28, true, 1, -1, "", "", true, "MS Sans Serif", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fMonitor.MVPageControl.tsMVSettingPage.pnMVSetupPage.Memo1", "Memo1", "IDC_MONITORINTERFACE_MEMO1", "TMemo", "fMonitor.MVPageControl.tsMVSettingPage.pnMVSetupPage", "fMonitor.MVPageControl.tsMVSettingPage.pnMVSetupPage", 4, 4, "LEAF", false, true, 10, true, 120, true, 480, true, 240, true, 2, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fMonitor.MVPageControl.tsMonitorSpecific", "tsMonitorSpecific", "IDD_MONITORINTERFACE_MVPAGECONTROL_TSMONITORSPECIFIC", "TTabSheet", "fMonitor.MVPageControl", "fMonitor", 2, 2, "SUBDLG", false, false, 0, false, 0, false, 0, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fMonitor.MVPageControl.tsMonitorSpecific.lbWhenHDFullPrompt", "lbWhenHDFullPrompt", "IDC_MONITORINTERFACE_LBWHENHDFULLPROMPT", "TLabel", "fMonitor.MVPageControl.tsMonitorSpecific", "fMonitor.MVPageControl.tsMonitorSpecific", 0, 3, "LEAF", true, true, 29, true, 40, true, 250, true, 16, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fMonitor.MVPageControl.tsMonitorSpecific.cbWhenHDFullAlarm", "cbWhenHDFullAlarm", "IDC_MONITORINTERFACE_CBWHENHDFULLALARM", "TCheckBox", "fMonitor.MVPageControl.tsMonitorSpecific", "fMonitor.MVPageControl.tsMonitorSpecific", 1, 3, "LEAF", false, true, 10, true, 10, true, 311, true, 17, true, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fMonitor.MVPageControl.tsMonitorSpecific.edLowHDSpace", "edLowHDSpace", "IDC_MONITORINTERFACE_EDLOWHDSPACE", "TEdit", "fMonitor.MVPageControl.tsMonitorSpecific", "fMonitor.MVPageControl.tsMonitorSpecific", 2, 3, "LEAF", false, true, 168, true, 8, true, 49, true, 24, true, 1, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fMonitor.MVPageControl.tsMonitorSpecific.edWhenHDFullPrompt", "edWhenHDFullPrompt", "IDC_MONITORINTERFACE_EDWHENHDFULLPROMPT", "TEdit", "fMonitor.MVPageControl.tsMonitorSpecific", "fMonitor.MVPageControl.tsMonitorSpecific", 3, 3, "LEAF", false, true, 168, true, 40, true, 49, true, 24, true, 2, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fMonitor.MVPageControl.tsMonitorSpecific.cbAfterHandlerTrayFeedMonitor1ClosedVideo", "cbAfterHandlerTrayFeedMonitor1ClosedVideo", "IDC_MONITORINTERFACE_CBAFTERHANDLERTRAYFEEDMONITOR1CLOSEDVIDEO", "TCheckBox", "fMonitor.MVPageControl.tsMonitorSpecific", "fMonitor.MVPageControl.tsMonitorSpecific", 4, 3, "LEAF", false, true, 10, true, 82, true, 415, true, 17, true, 3, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fMonitor.MVPageControl.tsMonitorSpecific.edAfterHandlerTrayFeedMonitor1ClosedVideoWaitTime", "edAfterHandlerTrayFeedMonitor1ClosedVideoWaitTime", "IDC_MONITORINTERFACE_EDAFTERHANDLERTRAYFEEDMONITOR1CLOSEDVIDEOWAITTIME", "TEdit", "fMonitor.MVPageControl.tsMonitorSpecific", "fMonitor.MVPageControl.tsMonitorSpecific", 5, 3, "LEAF", false, true, 349, true, 78, true, 49, true, 24, true, 4, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fMonitor.pnMVButtonTitle", "pnMVButtonTitle", "IDD_MONITORINTERFACE_PNMVBUTTONTITLE", "TPanel", "fMonitor", "fMonitor", 2, 1, "SUBDLG", false, true, 504, true, 78, true, 95, true, 395, true, 2, -1, "", "", false, "", 0, "", false, 0, "", true, 13487501, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fMonitor.pnMVButtonTitle.sbMVUpdate", "sbMVUpdate", "IDC_MONITORINTERFACE_SBMVUPDATE", "TSpeedButton", "fMonitor.pnMVButtonTitle", "fMonitor.pnMVButtonTitle", 0, 2, "LEAF", true, true, 5, true, 325, true, 85, true, 30, false, 0, -1, "", "", true, "MS Sans Serif", -13, "", true, 8388608, "clNavy", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fMonitor.pnMVButtonTitle.sbMVExit", "sbMVExit", "IDC_MONITORINTERFACE_SBMVEXIT", "TSpeedButton", "fMonitor.pnMVButtonTitle", "fMonitor.pnMVButtonTitle", 1, 2, "LEAF", true, true, 5, true, 357, true, 85, true, 30, false, 0, -1, "", "", true, "Times New Roman", -16, "", true, 8388608, "clNavy", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fMonitor.MonitorTimer", "MonitorTimer", "", "TTimer", "fMonitor", "fMonitor", 3, 1, "NONVISUAL", false, true, 532, true, 86, false, 0, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fMonitor.MonitorClientSocket", "MonitorClientSocket", "", "TClientSocket", "fMonitor", "fMonitor", 4, 1, "NONVISUAL", false, true, 564, true, 86, false, 0, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
};

const int kMonitorInterfaceLayoutCount = 40;

} // namespace ht9045_layout
