// ===========================================================================
//  ArmOffsetData_layout.gen.cpp
//  DO NOT EDIT -- GENERATED FILE. See the matching _layout.gen.h banner.
// ===========================================================================
#include "ArmOffsetData_layout.gen.h"

namespace ht9045_layout {

// (no custom-control properties in this form)

const DfmControlLayout kArmOffsetDataLayout[] = {
    { "fArmOffsetData", "fArmOffsetData", "", "TfArmOffsetData", "", "", 0, 0, "ROOT", false, true, 1071, true, 236, false, 0, false, 0, false, 0, -1, "", "", true, "MS Sans Serif", -11, "", true, -2147483640, "clWindowText", true, 12761254, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fArmOffsetData.pgcArmOffset", "pgcArmOffset", "IDC_ARMOFFSETDATA_PGCARMOFFSET", "TPageControl", "fArmOffsetData", "fArmOffsetData", 0, 1, "TABHOST", false, true, 0, true, 0, true, 736, true, 464, true, 0, -1, "alClient", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fArmOffsetData.pgcArmOffset.tsInArm", "tsInArm", "IDD_ARMOFFSETDATA_PGCARMOFFSET_TSINARM", "TTabSheet", "fArmOffsetData.pgcArmOffset", "fArmOffsetData", 0, 2, "SUBDLG", false, false, 0, false, 0, false, 0, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fArmOffsetData.pgcArmOffset.tsInArm.pnlInArm", "pnlInArm", "IDD_ARMOFFSETDATA_PGCARMOFFSET_TSINARM_PNLINARM", "TPanel", "fArmOffsetData.pgcArmOffset.tsInArm", "fArmOffsetData.pgcArmOffset.tsInArm", 0, 3, "SUBDLG", false, true, 0, true, 40, true, 728, true, 257, true, 1, -1, "alTop", "", false, "", 0, "", false, 0, "", true, 12761254, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fArmOffsetData.pgcArmOffset.tsInArm.pnlInArm.Label1", "Label1", "IDC_ARMOFFSETDATA_LABEL1", "TLabel", "fArmOffsetData.pgcArmOffset.tsInArm.pnlInArm", "fArmOffsetData.pgcArmOffset.tsInArm.pnlInArm", 0, 4, "LEAF", true, true, 84, true, 10, true, 33, true, 13, false, 0, -1, "", "", true, "MS Sans Serif", -11, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fArmOffsetData.pgcArmOffset.tsInArm.pnlInArm.Label2", "Label2", "IDC_ARMOFFSETDATA_LABEL2", "TLabel", "fArmOffsetData.pgcArmOffset.tsInArm.pnlInArm", "fArmOffsetData.pgcArmOffset.tsInArm.pnlInArm", 1, 4, "LEAF", true, true, 16, true, 30, true, 36, true, 13, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fArmOffsetData.pgcArmOffset.tsInArm.pnlInArm.Label3", "Label3", "IDC_ARMOFFSETDATA_LABEL3", "TLabel", "fArmOffsetData.pgcArmOffset.tsInArm.pnlInArm", "fArmOffsetData.pgcArmOffset.tsInArm.pnlInArm", 2, 4, "LEAF", true, true, 16, true, 55, true, 36, true, 13, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fArmOffsetData.pgcArmOffset.tsInArm.pnlInArm.Label4", "Label4", "IDC_ARMOFFSETDATA_LABEL4", "TLabel", "fArmOffsetData.pgcArmOffset.tsInArm.pnlInArm", "fArmOffsetData.pgcArmOffset.tsInArm.pnlInArm", 3, 4, "LEAF", true, true, 16, true, 105, true, 36, true, 13, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fArmOffsetData.pgcArmOffset.tsInArm.pnlInArm.Label5", "Label5", "IDC_ARMOFFSETDATA_LABEL5", "TLabel", "fArmOffsetData.pgcArmOffset.tsInArm.pnlInArm", "fArmOffsetData.pgcArmOffset.tsInArm.pnlInArm", 4, 4, "LEAF", true, true, 16, true, 80, true, 39, true, 13, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fArmOffsetData.pgcArmOffset.tsInArm.pnlInArm.Label6", "Label6", "IDC_ARMOFFSETDATA_LABEL6", "TLabel", "fArmOffsetData.pgcArmOffset.tsInArm.pnlInArm", "fArmOffsetData.pgcArmOffset.tsInArm.pnlInArm", 5, 4, "LEAF", true, true, 16, true, 130, true, 43, true, 13, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fArmOffsetData.pgcArmOffset.tsInArm.pnlInArm.Label9", "Label9", "IDC_ARMOFFSETDATA_LABEL9", "TLabel", "fArmOffsetData.pgcArmOffset.tsInArm.pnlInArm", "fArmOffsetData.pgcArmOffset.tsInArm.pnlInArm", 6, 4, "LEAF", true, true, 201, true, 10, true, 50, true, 13, false, 0, -1, "", "", true, "MS Sans Serif", -11, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fArmOffsetData.pgcArmOffset.tsInArm.pnlInArm.Label10", "Label10", "IDC_ARMOFFSETDATA_LABEL10", "TLabel", "fArmOffsetData.pgcArmOffset.tsInArm.pnlInArm", "fArmOffsetData.pgcArmOffset.tsInArm.pnlInArm", 7, 4, "LEAF", true, true, 323, true, 10, true, 50, true, 13, false, 0, -1, "", "", true, "MS Sans Serif", -11, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fArmOffsetData.pgcArmOffset.tsInArm.pnlInArm.Label11", "Label11", "IDC_ARMOFFSETDATA_LABEL11", "TLabel", "fArmOffsetData.pgcArmOffset.tsInArm.pnlInArm", "fArmOffsetData.pgcArmOffset.tsInArm.pnlInArm", 8, 4, "LEAF", true, true, 450, true, 10, true, 42, true, 13, false, 0, -1, "", "", true, "MS Sans Serif", -11, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fArmOffsetData.pgcArmOffset.tsInArm.pnlInArm.Label12", "Label12", "IDC_ARMOFFSETDATA_LABEL12", "TLabel", "fArmOffsetData.pgcArmOffset.tsInArm.pnlInArm", "fArmOffsetData.pgcArmOffset.tsInArm.pnlInArm", 9, 4, "LEAF", true, true, 572, true, 10, true, 42, true, 13, false, 0, -1, "", "", true, "MS Sans Serif", -11, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fArmOffsetData.pgcArmOffset.tsInArm.pnlInArm.Label28", "Label28", "IDC_ARMOFFSETDATA_LABEL28", "TLabel", "fArmOffsetData.pgcArmOffset.tsInArm.pnlInArm", "fArmOffsetData.pgcArmOffset.tsInArm.pnlInArm", 10, 4, "LEAF", true, true, 16, true, 155, true, 43, true, 13, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fArmOffsetData.pgcArmOffset.tsInArm.pnlInArm.Label29", "Label29", "IDC_ARMOFFSETDATA_LABEL29", "TLabel", "fArmOffsetData.pgcArmOffset.tsInArm.pnlInArm", "fArmOffsetData.pgcArmOffset.tsInArm.pnlInArm", 11, 4, "LEAF", true, true, 16, true, 180, true, 43, true, 13, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fArmOffsetData.pgcArmOffset.tsInArm.pnlInArm.Label30", "Label30", "IDC_ARMOFFSETDATA_LABEL30", "TLabel", "fArmOffsetData.pgcArmOffset.tsInArm.pnlInArm", "fArmOffsetData.pgcArmOffset.tsInArm.pnlInArm", 12, 4, "LEAF", true, true, 16, true, 205, true, 43, true, 13, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fArmOffsetData.pgcArmOffset.tsInArm.pnlInArm.Label31", "Label31", "IDC_ARMOFFSETDATA_LABEL31", "TLabel", "fArmOffsetData.pgcArmOffset.tsInArm.pnlInArm", "fArmOffsetData.pgcArmOffset.tsInArm.pnlInArm", 13, 4, "LEAF", true, true, 16, true, 230, true, 34, true, 13, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fArmOffsetData.pgcArmOffset.tsInArm.palOffsetParts", "palOffsetParts", "IDD_ARMOFFSETDATA_PGCARMOFFSET_TSINARM_PALOFFSETPARTS", "TPanel", "fArmOffsetData.pgcArmOffset.tsInArm", "fArmOffsetData.pgcArmOffset.tsInArm", 1, 3, "SUBDLG", false, true, 0, true, 0, true, 728, true, 40, true, 0, -1, "alTop", "", true, "Arial Black", -24, "fsBold", true, 16777215, "clWhite", true, 9534289, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fArmOffsetData.pgcArmOffset.tsInArm.palOffsetParts.Label27", "Label27", "IDC_ARMOFFSETDATA_LABEL27", "TLabel", "fArmOffsetData.pgcArmOffset.tsInArm.palOffsetParts", "fArmOffsetData.pgcArmOffset.tsInArm.palOffsetParts", 0, 4, "LEAF", true, true, 674, true, 0, true, 54, true, 40, false, 0, -1, "alRight", "", true, "MS Sans Serif", -13, "", true, 16711935, "clFuchsia", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fArmOffsetData.pgcArmOffset.tsOutArm", "tsOutArm", "IDD_ARMOFFSETDATA_PGCARMOFFSET_TSOUTARM", "TTabSheet", "fArmOffsetData.pgcArmOffset", "fArmOffsetData", 1, 2, "SUBDLG", false, false, 0, false, 0, false, 0, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fArmOffsetData.pgcArmOffset.tsOutArm.pnlOutArm", "pnlOutArm", "IDD_ARMOFFSETDATA_PGCARMOFFSET_TSOUTARM_PNLOUTARM", "TPanel", "fArmOffsetData.pgcArmOffset.tsOutArm", "fArmOffsetData.pgcArmOffset.tsOutArm", 0, 3, "SUBDLG", false, true, 0, true, 40, true, 728, true, 396, true, 1, -1, "alClient", "", false, "", 0, "", false, 0, "", true, 12761254, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fArmOffsetData.pgcArmOffset.tsOutArm.pnlOutArm.Label13", "Label13", "IDC_ARMOFFSETDATA_LABEL13", "TLabel", "fArmOffsetData.pgcArmOffset.tsOutArm.pnlOutArm", "fArmOffsetData.pgcArmOffset.tsOutArm.pnlOutArm", 0, 4, "LEAF", true, true, 80, true, 10, true, 42, true, 13, false, 0, -1, "", "", true, "MS Sans Serif", -11, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fArmOffsetData.pgcArmOffset.tsOutArm.pnlOutArm.Label19", "Label19", "IDC_ARMOFFSETDATA_LABEL19", "TLabel", "fArmOffsetData.pgcArmOffset.tsOutArm.pnlOutArm", "fArmOffsetData.pgcArmOffset.tsOutArm.pnlOutArm", 1, 4, "LEAF", true, true, 159, true, 10, true, 42, true, 13, false, 0, -1, "", "", true, "MS Sans Serif", -11, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fArmOffsetData.pgcArmOffset.tsOutArm.pnlOutArm.Label20", "Label20", "IDC_ARMOFFSETDATA_LABEL20", "TLabel", "fArmOffsetData.pgcArmOffset.tsOutArm.pnlOutArm", "fArmOffsetData.pgcArmOffset.tsOutArm.pnlOutArm", 2, 4, "LEAF", true, true, 238, true, 10, true, 31, true, 13, false, 0, -1, "", "", true, "MS Sans Serif", -11, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fArmOffsetData.pgcArmOffset.tsOutArm.pnlOutArm.Label21", "Label21", "IDC_ARMOFFSETDATA_LABEL21", "TLabel", "fArmOffsetData.pgcArmOffset.tsOutArm.pnlOutArm", "fArmOffsetData.pgcArmOffset.tsOutArm.pnlOutArm", 3, 4, "LEAF", true, true, 317, true, 10, true, 31, true, 13, false, 0, -1, "", "", true, "MS Sans Serif", -11, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fArmOffsetData.pgcArmOffset.tsOutArm.pnlOutArm.Label22", "Label22", "IDC_ARMOFFSETDATA_LABEL22", "TLabel", "fArmOffsetData.pgcArmOffset.tsOutArm.pnlOutArm", "fArmOffsetData.pgcArmOffset.tsOutArm.pnlOutArm", 4, 4, "LEAF", true, true, 395, true, 10, true, 31, true, 13, false, 0, -1, "", "", true, "MS Sans Serif", -11, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fArmOffsetData.pgcArmOffset.tsOutArm.pnlOutArm.Label23", "Label23", "IDC_ARMOFFSETDATA_LABEL23", "TLabel", "fArmOffsetData.pgcArmOffset.tsOutArm.pnlOutArm", "fArmOffsetData.pgcArmOffset.tsOutArm.pnlOutArm", 5, 4, "LEAF", true, true, 474, true, 10, true, 22, true, 13, false, 0, -1, "", "", true, "MS Sans Serif", -11, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fArmOffsetData.pgcArmOffset.tsOutArm.pnlOutArm.Label24", "Label24", "IDC_ARMOFFSETDATA_LABEL24", "TLabel", "fArmOffsetData.pgcArmOffset.tsOutArm.pnlOutArm", "fArmOffsetData.pgcArmOffset.tsOutArm.pnlOutArm", 6, 4, "LEAF", true, true, 553, true, 10, true, 22, true, 13, false, 0, -1, "", "", true, "MS Sans Serif", -11, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fArmOffsetData.pgcArmOffset.tsOutArm.pnlOutArm.Label25", "Label25", "IDC_ARMOFFSETDATA_LABEL25", "TLabel", "fArmOffsetData.pgcArmOffset.tsOutArm.pnlOutArm", "fArmOffsetData.pgcArmOffset.tsOutArm.pnlOutArm", 7, 4, "LEAF", true, true, 632, true, 10, true, 22, true, 13, false, 0, -1, "", "", true, "MS Sans Serif", -11, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fArmOffsetData.pgcArmOffset.tsOutArm.pnlOutArm.Label14", "Label14", "IDC_ARMOFFSETDATA_LABEL14", "TLabel", "fArmOffsetData.pgcArmOffset.tsOutArm.pnlOutArm", "fArmOffsetData.pgcArmOffset.tsOutArm.pnlOutArm", 8, 4, "LEAF", true, true, 16, true, 30, true, 36, true, 13, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fArmOffsetData.pgcArmOffset.tsOutArm.pnlOutArm.Label15", "Label15", "IDC_ARMOFFSETDATA_LABEL15", "TLabel", "fArmOffsetData.pgcArmOffset.tsOutArm.pnlOutArm", "fArmOffsetData.pgcArmOffset.tsOutArm.pnlOutArm", 9, 4, "LEAF", true, true, 16, true, 55, true, 36, true, 13, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fArmOffsetData.pgcArmOffset.tsOutArm.pnlOutArm.Label16", "Label16", "IDC_ARMOFFSETDATA_LABEL16", "TLabel", "fArmOffsetData.pgcArmOffset.tsOutArm.pnlOutArm", "fArmOffsetData.pgcArmOffset.tsOutArm.pnlOutArm", 10, 4, "LEAF", true, true, 16, true, 105, true, 36, true, 13, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fArmOffsetData.pgcArmOffset.tsOutArm.pnlOutArm.Label17", "Label17", "IDC_ARMOFFSETDATA_LABEL17", "TLabel", "fArmOffsetData.pgcArmOffset.tsOutArm.pnlOutArm", "fArmOffsetData.pgcArmOffset.tsOutArm.pnlOutArm", 11, 4, "LEAF", true, true, 16, true, 80, true, 39, true, 13, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fArmOffsetData.pgcArmOffset.tsOutArm.pnlOutArm.Label18", "Label18", "IDC_ARMOFFSETDATA_LABEL18", "TLabel", "fArmOffsetData.pgcArmOffset.tsOutArm.pnlOutArm", "fArmOffsetData.pgcArmOffset.tsOutArm.pnlOutArm", 12, 4, "LEAF", true, true, 16, true, 130, true, 43, true, 13, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fArmOffsetData.pgcArmOffset.tsOutArm.pnlOutArm.Label32", "Label32", "IDC_ARMOFFSETDATA_LABEL32", "TLabel", "fArmOffsetData.pgcArmOffset.tsOutArm.pnlOutArm", "fArmOffsetData.pgcArmOffset.tsOutArm.pnlOutArm", 13, 4, "LEAF", true, true, 16, true, 155, true, 43, true, 13, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fArmOffsetData.pgcArmOffset.tsOutArm.pnlOutArm.Label33", "Label33", "IDC_ARMOFFSETDATA_LABEL33", "TLabel", "fArmOffsetData.pgcArmOffset.tsOutArm.pnlOutArm", "fArmOffsetData.pgcArmOffset.tsOutArm.pnlOutArm", 14, 4, "LEAF", true, true, 16, true, 180, true, 43, true, 13, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fArmOffsetData.pgcArmOffset.tsOutArm.pnlOutArm.Label34", "Label34", "IDC_ARMOFFSETDATA_LABEL34", "TLabel", "fArmOffsetData.pgcArmOffset.tsOutArm.pnlOutArm", "fArmOffsetData.pgcArmOffset.tsOutArm.pnlOutArm", 15, 4, "LEAF", true, true, 16, true, 205, true, 43, true, 13, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fArmOffsetData.pgcArmOffset.tsOutArm.pnlOutArm.Label35", "Label35", "IDC_ARMOFFSETDATA_LABEL35", "TLabel", "fArmOffsetData.pgcArmOffset.tsOutArm.pnlOutArm", "fArmOffsetData.pgcArmOffset.tsOutArm.pnlOutArm", 16, 4, "LEAF", true, true, 16, true, 230, true, 34, true, 13, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fArmOffsetData.pgcArmOffset.tsOutArm.Panel1", "Panel1", "IDD_ARMOFFSETDATA_PGCARMOFFSET_TSOUTARM_PANEL1", "TPanel", "fArmOffsetData.pgcArmOffset.tsOutArm", "fArmOffsetData.pgcArmOffset.tsOutArm", 1, 3, "SUBDLG", false, true, 0, true, 0, true, 728, true, 40, true, 0, -1, "alTop", "", true, "Arial Black", -24, "fsBold", true, 16777215, "clWhite", true, 9534289, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fArmOffsetData.pgcArmOffset.tsOutArm.Panel1.Label8", "Label8", "IDC_ARMOFFSETDATA_LABEL8", "TLabel", "fArmOffsetData.pgcArmOffset.tsOutArm.Panel1", "fArmOffsetData.pgcArmOffset.tsOutArm.Panel1", 0, 4, "LEAF", true, true, 674, true, 0, true, 54, true, 40, false, 0, -1, "alRight", "", true, "MS Sans Serif", -13, "", true, 16711935, "clFuchsia", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fArmOffsetData.Panel2", "Panel2", "IDD_ARMOFFSETDATA_PANEL2", "TPanel", "fArmOffsetData", "fArmOffsetData", 1, 1, "SUBDLG", false, true, 0, true, 464, true, 736, true, 40, true, 1, -1, "alBottom", "", false, "", 0, "", false, 0, "", true, 12761254, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fArmOffsetData.Panel2.btnSave", "btnSave", "IDC_ARMOFFSETDATA_BTNSAVE", "TButton", "fArmOffsetData.Panel2", "fArmOffsetData.Panel2", 0, 2, "LEAF", false, true, 116, true, 5, true, 150, true, 30, true, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fArmOffsetData.Panel2.btnExit", "btnExit", "IDC_ARMOFFSETDATA_BTNEXIT", "TButton", "fArmOffsetData.Panel2", "fArmOffsetData.Panel2", 1, 2, "LEAF", false, true, 509, true, 5, true, 150, true, 30, true, 1, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
};

const int kArmOffsetDataLayoutCount = 44;

} // namespace ht9045_layout
