// ===========================================================================
//  cCounterSel_layout.gen.cpp
//  DO NOT EDIT -- GENERATED FILE. See the matching _layout.gen.h banner.
// ===========================================================================
#include "cCounterSel_layout.gen.h"

namespace ht9045_layout {

// (no custom-control properties in this form)

const DfmControlLayout kcCounterSelLayout[] = {
    { "fCounterSel", "fCounterSel", "", "TfCounterSel", "", "", 0, 0, "ROOT", false, true, 279, true, 116, false, 0, false, 0, false, 0, -1, "", "", true, "MS Sans Serif", -11, "", true, -2147483640, "clWindowText", true, 12761254, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fCounterSel.spbExit", "spbExit", "IDC_CCOUNTERSEL_SPBEXIT", "TSpeedButton", "fCounterSel", "fCounterSel", 0, 1, "LEAF", true, true, 43, true, 504, true, 314, true, 48, false, 0, -1, "", "", true, "Arial", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fCounterSel.GroupBox17", "GroupBox17", "IDD_CCOUNTERSEL_GROUPBOX17", "TGroupBox", "fCounterSel", "fCounterSel", 1, 1, "SUBDLG", false, true, 20, true, 15, true, 353, true, 462, true, 0, -1, "", "", true, "MS Sans Serif", -12, "", true, 8388608, "clNavy", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fCounterSel.GroupBox17.gbLoadingCount", "gbLoadingCount", "IDD_CCOUNTERSEL_GROUPBOX17_GBLOADINGCOUNT", "TGroupBox", "fCounterSel.GroupBox17", "fCounterSel.GroupBox17", 0, 2, "SUBDLG", false, true, 11, true, 12, true, 332, true, 59, true, 0, -1, "", "", true, "MS Sans Serif", -12, "", true, 8388608, "clNavy", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fCounterSel.GroupBox17.gbLoadingCount.labLoadingCount", "labLoadingCount", "IDC_CCOUNTERSEL_LABLOADINGCOUNT", "TLabel", "fCounterSel.GroupBox17.gbLoadingCount", "fCounterSel.GroupBox17.gbLoadingCount", 0, 3, "LEAF", true, true, 15, true, 25, true, 78, true, 13, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fCounterSel.GroupBox17.gbLoadingCount.rbLoadingCount_On", "rbLoadingCount_On", "IDC_CCOUNTERSEL_RBLOADINGCOUNT_ON", "TRadioButton", "fCounterSel.GroupBox17.gbLoadingCount", "fCounterSel.GroupBox17.gbLoadingCount", 1, 3, "LEAF", false, true, 119, true, 25, true, 60, true, 13, true, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fCounterSel.GroupBox17.gbLoadingCount.rbLoadingCount_Off", "rbLoadingCount_Off", "IDC_CCOUNTERSEL_RBLOADINGCOUNT_OFF", "TRadioButton", "fCounterSel.GroupBox17.gbLoadingCount", "fCounterSel.GroupBox17.gbLoadingCount", 2, 3, "LEAF", false, true, 186, true, 25, true, 60, true, 13, true, 1, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fCounterSel.GroupBox17.gbContactCount", "gbContactCount", "IDD_CCOUNTERSEL_GROUPBOX17_GBCONTACTCOUNT", "TGroupBox", "fCounterSel.GroupBox17", "fCounterSel.GroupBox17", 1, 2, "SUBDLG", false, true, 11, true, 72, true, 332, true, 59, true, 1, -1, "", "", true, "MS Sans Serif", -12, "", true, 8388608, "clNavy", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fCounterSel.GroupBox17.gbContactCount.labContactCount", "labContactCount", "IDC_CCOUNTERSEL_LABCONTACTCOUNT", "TLabel", "fCounterSel.GroupBox17.gbContactCount", "fCounterSel.GroupBox17.gbContactCount", 0, 3, "LEAF", true, true, 16, true, 25, true, 68, true, 13, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fCounterSel.GroupBox17.gbContactCount.rbContactCount_On", "rbContactCount_On", "IDC_CCOUNTERSEL_RBCONTACTCOUNT_ON", "TRadioButton", "fCounterSel.GroupBox17.gbContactCount", "fCounterSel.GroupBox17.gbContactCount", 1, 3, "LEAF", false, true, 119, true, 25, true, 60, true, 18, true, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fCounterSel.GroupBox17.gbContactCount.rbContactCount_Off", "rbContactCount_Off", "IDC_CCOUNTERSEL_RBCONTACTCOUNT_OFF", "TRadioButton", "fCounterSel.GroupBox17.gbContactCount", "fCounterSel.GroupBox17.gbContactCount", 2, 3, "LEAF", false, true, 186, true, 25, true, 60, true, 18, true, 1, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fCounterSel.GroupBox17.gbTestCategory", "gbTestCategory", "IDD_CCOUNTERSEL_GROUPBOX17_GBTESTCATEGORY", "TGroupBox", "fCounterSel.GroupBox17", "fCounterSel.GroupBox17", 2, 2, "SUBDLG", false, true, 11, true, 134, true, 332, true, 58, true, 2, -1, "", "", true, "MS Sans Serif", -12, "", true, 8388608, "clNavy", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fCounterSel.GroupBox17.gbTestCategory.labTestCategory", "labTestCategory", "IDC_CCOUNTERSEL_LABTESTCATEGORY", "TLabel", "fCounterSel.GroupBox17.gbTestCategory", "fCounterSel.GroupBox17.gbTestCategory", 0, 3, "LEAF", true, true, 16, true, 25, true, 75, true, 13, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fCounterSel.GroupBox17.gbTestCategory.rbTestCategory_On", "rbTestCategory_On", "IDC_CCOUNTERSEL_RBTESTCATEGORY_ON", "TRadioButton", "fCounterSel.GroupBox17.gbTestCategory", "fCounterSel.GroupBox17.gbTestCategory", 1, 3, "LEAF", false, true, 119, true, 25, true, 60, true, 18, true, 1, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fCounterSel.GroupBox17.gbTestCategory.rbTestCategory_Off", "rbTestCategory_Off", "IDC_CCOUNTERSEL_RBTESTCATEGORY_OFF", "TRadioButton", "fCounterSel.GroupBox17.gbTestCategory", "fCounterSel.GroupBox17.gbTestCategory", 2, 3, "LEAF", false, true, 186, true, 25, true, 60, true, 18, true, 2, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fCounterSel.GroupBox17.gbTestCategory.rgTestCategory", "rgTestCategory", "IDD_CCOUNTERSEL_GROUPBOX17_GBTESTCATEGORY_RGTESTCATEGORY", "TRadioGroup", "fCounterSel.GroupBox17.gbTestCategory", "fCounterSel.GroupBox17.gbTestCategory", 3, 3, "SUBDLG", false, true, 242, true, 8, true, 82, true, 45, true, 0, -1, "", "", true, "MS Sans Serif", -9, "", true, 8388608, "clNavy", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fCounterSel.GroupBox17.gbScanner", "gbScanner", "IDD_CCOUNTERSEL_GROUPBOX17_GBSCANNER", "TGroupBox", "fCounterSel.GroupBox17", "fCounterSel.GroupBox17", 3, 2, "SUBDLG", false, true, 11, true, 194, true, 332, true, 59, true, 3, -1, "", "", true, "MS Sans Serif", -12, "", true, 8388608, "clNavy", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fCounterSel.GroupBox17.gbScanner.labScanner", "labScanner", "IDC_CCOUNTERSEL_LABSCANNER", "TLabel", "fCounterSel.GroupBox17.gbScanner", "fCounterSel.GroupBox17.gbScanner", 0, 3, "LEAF", true, true, 14, true, 25, true, 85, true, 13, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fCounterSel.GroupBox17.gbScanner.rbScanner_On", "rbScanner_On", "IDC_CCOUNTERSEL_RBSCANNER_ON", "TRadioButton", "fCounterSel.GroupBox17.gbScanner", "fCounterSel.GroupBox17.gbScanner", 1, 3, "LEAF", false, true, 119, true, 25, true, 60, true, 18, true, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fCounterSel.GroupBox17.gbScanner.rbScanner_Off", "rbScanner_Off", "IDC_CCOUNTERSEL_RBSCANNER_OFF", "TRadioButton", "fCounterSel.GroupBox17.gbScanner", "fCounterSel.GroupBox17.gbScanner", 2, 3, "LEAF", false, true, 186, true, 25, true, 60, true, 18, true, 1, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fCounterSel.GroupBox17.gbTemperature", "gbTemperature", "IDD_CCOUNTERSEL_GROUPBOX17_GBTEMPERATURE", "TGroupBox", "fCounterSel.GroupBox17", "fCounterSel.GroupBox17", 4, 2, "SUBDLG", false, true, 11, true, 255, true, 332, true, 59, true, 4, -1, "", "", true, "MS Sans Serif", -12, "", true, 8388608, "clNavy", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fCounterSel.GroupBox17.gbTemperature.labTemperature", "labTemperature", "IDC_CCOUNTERSEL_LABTEMPERATURE", "TLabel", "fCounterSel.GroupBox17.gbTemperature", "fCounterSel.GroupBox17.gbTemperature", 0, 3, "LEAF", true, true, 16, true, 25, true, 60, true, 13, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fCounterSel.GroupBox17.gbTemperature.rbTemperature_On", "rbTemperature_On", "IDC_CCOUNTERSEL_RBTEMPERATURE_ON", "TRadioButton", "fCounterSel.GroupBox17.gbTemperature", "fCounterSel.GroupBox17.gbTemperature", 1, 3, "LEAF", false, true, 119, true, 25, true, 60, true, 18, true, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fCounterSel.GroupBox17.gbTemperature.rbTemperature_Off", "rbTemperature_Off", "IDC_CCOUNTERSEL_RBTEMPERATURE_OFF", "TRadioButton", "fCounterSel.GroupBox17.gbTemperature", "fCounterSel.GroupBox17.gbTemperature", 2, 3, "LEAF", false, true, 186, true, 25, true, 60, true, 18, true, 1, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fCounterSel.GroupBox17.gbBinAssign", "gbBinAssign", "IDD_CCOUNTERSEL_GROUPBOX17_GBBINASSIGN", "TGroupBox", "fCounterSel.GroupBox17", "fCounterSel.GroupBox17", 5, 2, "SUBDLG", false, true, 11, true, 316, true, 332, true, 58, true, 5, -1, "", "", true, "MS Sans Serif", -12, "", true, 8388608, "clNavy", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fCounterSel.GroupBox17.gbBinAssign.labBinAssign", "labBinAssign", "IDC_CCOUNTERSEL_LABBINASSIGN", "TLabel", "fCounterSel.GroupBox17.gbBinAssign", "fCounterSel.GroupBox17.gbBinAssign", 0, 3, "LEAF", true, true, 16, true, 25, true, 49, true, 13, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fCounterSel.GroupBox17.gbBinAssign.rbBinAssign_On", "rbBinAssign_On", "IDC_CCOUNTERSEL_RBBINASSIGN_ON", "TRadioButton", "fCounterSel.GroupBox17.gbBinAssign", "fCounterSel.GroupBox17.gbBinAssign", 1, 3, "LEAF", false, true, 119, true, 25, true, 60, true, 18, true, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fCounterSel.GroupBox17.gbBinAssign.rbBinAssign_Off", "rbBinAssign_Off", "IDC_CCOUNTERSEL_RBBINASSIGN_OFF", "TRadioButton", "fCounterSel.GroupBox17.gbBinAssign", "fCounterSel.GroupBox17.gbBinAssign", 2, 3, "LEAF", false, true, 186, true, 25, true, 60, true, 18, true, 1, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fCounterSel.GroupBox17.gbStatus", "gbStatus", "IDD_CCOUNTERSEL_GROUPBOX17_GBSTATUS", "TGroupBox", "fCounterSel.GroupBox17", "fCounterSel.GroupBox17", 6, 2, "SUBDLG", false, true, 11, true, 376, true, 332, true, 74, true, 6, -1, "", "", true, "MS Sans Serif", -12, "", true, 8388608, "clNavy", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fCounterSel.GroupBox17.gbStatus.labStatus", "labStatus", "IDC_CCOUNTERSEL_LABSTATUS", "TLabel", "fCounterSel.GroupBox17.gbStatus", "fCounterSel.GroupBox17.gbStatus", 0, 3, "LEAF", true, true, 16, true, 32, true, 30, true, 13, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fCounterSel.GroupBox17.gbStatus.cbIndexTime", "cbIndexTime", "IDC_CCOUNTERSEL_CBINDEXTIME", "TCheckBox", "fCounterSel.GroupBox17.gbStatus", "fCounterSel.GroupBox17.gbStatus", 1, 3, "LEAF", false, true, 126, true, 15, true, 90, true, 16, true, 0, -1, "", "", true, "MS Sans Serif", -12, "", true, 8388608, "clNavy", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fCounterSel.GroupBox17.gbStatus.cbUPH", "cbUPH", "IDC_CCOUNTERSEL_CBUPH", "TCheckBox", "fCounterSel.GroupBox17.gbStatus", "fCounterSel.GroupBox17.gbStatus", 2, 3, "LEAF", false, true, 126, true, 46, true, 98, true, 15, true, 1, -1, "", "", true, "MS Sans Serif", -12, "", true, 8388608, "clNavy", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fCounterSel.GroupBox17.gbStatus.cbCycleTime", "cbCycleTime", "IDC_CCOUNTERSEL_CBCYCLETIME", "TCheckBox", "fCounterSel.GroupBox17.gbStatus", "fCounterSel.GroupBox17.gbStatus", 3, 3, "LEAF", false, true, 230, true, 15, true, 90, true, 16, true, 2, -1, "", "", true, "MS Sans Serif", -12, "", true, 8388608, "clNavy", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fCounterSel.GroupBox17.gbStatus.cbContactHeight", "cbContactHeight", "IDC_CCOUNTERSEL_CBCONTACTHEIGHT", "TCheckBox", "fCounterSel.GroupBox17.gbStatus", "fCounterSel.GroupBox17.gbStatus", 4, 3, "LEAF", false, true, 230, true, 46, true, 98, true, 15, true, 3, -1, "", "", true, "MS Sans Serif", -12, "", true, 8388608, "clNavy", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fCounterSel.cbDefaultValue", "cbDefaultValue", "IDC_CCOUNTERSEL_CBDEFAULTVALUE", "TCheckBox", "fCounterSel", "fCounterSel", 2, 1, "LEAF", false, true, 226, true, 483, true, 151, true, 16, true, 1, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
};

const int kcCounterSelLayoutCount = 35;

} // namespace ht9045_layout
