// ===========================================================================
//  cheksocket_layout.gen.cpp
//  DO NOT EDIT -- GENERATED FILE. See the matching _layout.gen.h banner.
// ===========================================================================
#include "cheksocket_layout.gen.h"

namespace ht9045_layout {

// (no custom-control properties in this form)

const DfmControlLayout kcheksocketLayout[] = {
    { "fCCDPin1", "fCCDPin1", "", "TfCCDPin1", "", "", 0, 0, "ROOT", false, true, 16, true, 1, true, 899, true, 698, false, 0, -1, "", "", true, "MS Sans Serif", -11, "", true, -2147483640, "clWindowText", true, -2147483633, "clBtnFace", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fCCDPin1.SpeedButton1", "SpeedButton1", "IDC_CHEKSOCKET_SPEEDBUTTON1", "TSpeedButton", "fCCDPin1", "fCCDPin1", 0, 1, "LEAF", true, true, 6, true, 530, true, 137, true, 33, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fCCDPin1.SpeedButton2", "SpeedButton2", "IDC_CHEKSOCKET_SPEEDBUTTON2", "TSpeedButton", "fCCDPin1", "fCCDPin1", 1, 1, "LEAF", true, true, 6, true, 570, true, 137, true, 33, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fCCDPin1.SpeedButton3", "SpeedButton3", "IDC_CHEKSOCKET_SPEEDBUTTON3", "TSpeedButton", "fCCDPin1", "fCCDPin1", 2, 1, "LEAF", true, true, 6, true, 610, true, 137, true, 33, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fCCDPin1.SpeedButton8", "SpeedButton8", "IDC_CHEKSOCKET_SPEEDBUTTON8", "TSpeedButton", "fCCDPin1", "fCCDPin1", 3, 1, "LEAF", true, true, 144, true, 530, true, 137, true, 33, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fCCDPin1.Label3", "Label3", "IDC_CHEKSOCKET_LABEL3", "TLabel", "fCCDPin1", "fCCDPin1", 4, 1, "LEAF", true, true, 536, true, 536, true, 32, true, 13, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fCCDPin1.Label1", "Label1", "IDC_CHEKSOCKET_LABEL1", "TLabel", "fCCDPin1", "fCCDPin1", 5, 1, "LEAF", true, true, 696, true, 16, true, 44, true, 13, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fCCDPin1.PageControl1", "PageControl1", "IDC_CHEKSOCKET_PAGECONTROL1", "TPageControl", "fCCDPin1", "fCCDPin1", 6, 1, "TABHOST", false, true, 3, true, 1, true, 655, true, 521, true, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fCCDPin1.PageControl1.TabSheet1", "TabSheet1", "IDD_CHEKSOCKET_PAGECONTROL1_TABSHEET1", "TTabSheet", "fCCDPin1.PageControl1", "fCCDPin1", 0, 2, "SUBDLG", false, false, 0, false, 0, false, 0, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fCCDPin1.PageControl1.TabSheet1.LiveImage", "LiveImage", "IDC_CHEKSOCKET_LIVEIMAGE", "TEBW8Image", "fCCDPin1.PageControl1.TabSheet1", "fCCDPin1.PageControl1.TabSheet1", 0, 3, "LEAF", false, true, 3, true, 7, true, 640, true, 480, true, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fCCDPin1.PageControl1.TabSheet2", "TabSheet2", "IDD_CHEKSOCKET_PAGECONTROL1_TABSHEET2", "TTabSheet", "fCCDPin1.PageControl1", "fCCDPin1", 1, 2, "SUBDLG", false, false, 0, false, 0, false, 0, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fCCDPin1.PageControl1.TabSheet2.SourceImage", "SourceImage", "IDC_CHEKSOCKET_SOURCEIMAGE", "TEBW8Image", "fCCDPin1.PageControl1.TabSheet2", "fCCDPin1.PageControl1.TabSheet2", 0, 3, "LEAF", false, true, 3, true, 7, true, 640, true, 480, true, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fCCDPin1.PageControl1.TabSheet3", "TabSheet3", "IDD_CHEKSOCKET_PAGECONTROL1_TABSHEET3", "TTabSheet", "fCCDPin1.PageControl1", "fCCDPin1", 2, 2, "SUBDLG", false, false, 0, false, 0, false, 0, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fCCDPin1.PageControl1.TabSheet3.EBW8Image1", "EBW8Image1", "IDC_CHEKSOCKET_EBW8IMAGE1", "TEBW8Image", "fCCDPin1.PageControl1.TabSheet3", "fCCDPin1.PageControl1.TabSheet3", 0, 3, "LEAF", false, true, 3, true, 7, true, 640, true, 480, true, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fCCDPin1.PageControl1.TabSheet4", "TabSheet4", "IDD_CHEKSOCKET_PAGECONTROL1_TABSHEET4", "TTabSheet", "fCCDPin1.PageControl1", "fCCDPin1", 3, 2, "SUBDLG", false, false, 0, false, 0, false, 0, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fCCDPin1.PageControl1.TabSheet4.EBW8Image2", "EBW8Image2", "IDC_CHEKSOCKET_EBW8IMAGE2", "TEBW8Image", "fCCDPin1.PageControl1.TabSheet4", "fCCDPin1.PageControl1.TabSheet4", 0, 3, "LEAF", false, true, 3, true, 7, true, 640, true, 480, true, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fCCDPin1.ROI1", "ROI1", "IDC_CHEKSOCKET_ROI1", "TEBW8ROI", "fCCDPin1", "fCCDPin1", 7, 1, "LEAF", false, true, 288, true, 528, true, 32, true, 32, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fCCDPin1.EasyMain", "EasyMain", "IDC_CHEKSOCKET_EASYMAIN", "TEasyMain", "fCCDPin1", "fCCDPin1", 8, 1, "LEAF", false, true, 374, true, 529, true, 32, true, 32, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fCCDPin1.Button1", "Button1", "IDC_CHEKSOCKET_BUTTON1", "TButton", "fCCDPin1", "fCCDPin1", 9, 1, "LEAF", false, true, 144, true, 569, true, 137, true, 33, true, 3, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fCCDPin1.Button2", "Button2", "IDC_CHEKSOCKET_BUTTON2", "TButton", "fCCDPin1", "fCCDPin1", 10, 1, "LEAF", false, true, 288, true, 570, true, 97, true, 29, true, 4, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fCCDPin1.ROI2", "ROI2", "IDC_CHEKSOCKET_ROI2", "TEBW8ROI", "fCCDPin1", "fCCDPin1", 11, 1, "LEAF", false, true, 328, true, 528, true, 32, true, 32, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fCCDPin1.Memo1", "Memo1", "IDC_CHEKSOCKET_MEMO1", "TMemo", "fCCDPin1", "fCCDPin1", 12, 1, "LEAF", false, true, 688, true, 64, true, 202, true, 577, true, 6, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fCCDPin1.CCD", "CCD", "IDC_CHEKSOCKET_CCD", "TECameraPicolo", "fCCDPin1", "fCCDPin1", 13, 1, "LEAF", false, true, 400, true, 568, true, 32, true, 32, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fCCDPin1.ScrollBar1", "ScrollBar1", "IDC_CHEKSOCKET_SCROLLBAR1", "TScrollBar", "fCCDPin1", "fCCDPin1", 14, 1, "LEAF", false, true, 664, true, 24, true, 16, true, 497, true, 8, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fCCDPin1.Edit3", "Edit3", "IDC_CHEKSOCKET_EDIT3", "TEdit", "fCCDPin1", "fCCDPin1", 15, 1, "LEAF", false, true, 696, true, 32, true, 121, true, 21, true, 9, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
};

const int kcheksocketLayoutCount = 25;

} // namespace ht9045_layout
