// ===========================================================================
//  cHotPlate_layout.gen.cpp
//  DO NOT EDIT -- GENERATED FILE. See the matching _layout.gen.h banner.
// ===========================================================================
#include "cHotPlate_layout.gen.h"

namespace ht9045_layout {

// (no custom-control properties in this form)

const DfmControlLayout kcHotPlateLayout[] = {
    { "fHotPlate", "fHotPlate", "", "TfHotPlate", "", "", 0, 0, "ROOT", false, true, 350, true, 191, true, 614, true, 562, false, 0, -1, "", "", true, "MS Sans Serif", -11, "", true, -2147483640, "clWindowText", true, 12761254, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fHotPlate.Panel1", "Panel1", "IDD_CHOTPLATE_PANEL1", "TPanel", "fHotPlate", "fHotPlate", 0, 1, "SUBDLG", false, true, 0, true, 0, true, 606, true, 72, true, 0, -1, "alTop", "", true, "MS Sans Serif", -16, "", true, 8388608, "clNavy", true, 12761254, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fHotPlate.Panel1.Label1", "Label1", "IDC_CHOTPLATE_LABEL1", "TLabel", "fHotPlate.Panel1", "fHotPlate.Panel1", 0, 2, "LEAF", true, true, 10, true, 26, true, 136, true, 24, false, 0, -1, "", "", true, "MS Sans Serif", -19, "", true, 8388608, "clNavy", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fHotPlate.Panel1.HotPlateName", "HotPlateName", "IDC_CHOTPLATE_HOTPLATENAME", "TEdit", "fHotPlate.Panel1", "fHotPlate.Panel1", 1, 2, "LEAF", false, true, 152, true, 22, true, 400, true, 32, true, 0, -1, "", "", true, "MS Sans Serif", -19, "", true, 8388608, "clNavy", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fHotPlate.GroupBox1", "GroupBox1", "IDD_CHOTPLATE_GROUPBOX1", "TGroupBox", "fHotPlate", "fHotPlate", 1, 1, "SUBDLG", false, true, 0, true, 72, true, 121, true, 403, true, 1, -1, "alLeft", "", true, "MS Sans Serif", -13, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fHotPlate.GroupBox1.Image1", "Image1", "IDC_CHOTPLATE_IMAGE1", "TImage", "fHotPlate.GroupBox1", "fHotPlate.GroupBox1", 0, 2, "LEAF", true, true, 16, true, 48, true, 81, true, 129, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fHotPlate.GroupBox1.Image2", "Image2", "IDC_CHOTPLATE_IMAGE2", "TImage", "fHotPlate.GroupBox1", "fHotPlate.GroupBox1", 1, 2, "LEAF", true, true, 16, true, 232, true, 81, true, 129, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fHotPlate.GroupBox1.cbEnableHP2", "cbEnableHP2", "IDC_CHOTPLATE_CBENABLEHP2", "TCheckBox", "fHotPlate.GroupBox1", "fHotPlate.GroupBox1", 2, 2, "LEAF", false, true, 8, true, 24, true, 97, true, 17, true, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fHotPlate.GroupBox1.cbEnableHP1", "cbEnableHP1", "IDC_CHOTPLATE_CBENABLEHP1", "TCheckBox", "fHotPlate.GroupBox1", "fHotPlate.GroupBox1", 3, 2, "LEAF", false, true, 8, true, 208, true, 97, true, 17, true, 1, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fHotPlate.GroupBox2", "GroupBox2", "IDD_CHOTPLATE_GROUPBOX2", "TGroupBox", "fHotPlate", "fHotPlate", 2, 1, "SUBDLG", false, true, 121, true, 72, true, 485, true, 403, true, 2, -1, "alClient", "", true, "MS Sans Serif", -13, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fHotPlate.GroupBox2.Image3", "Image3", "IDC_CHOTPLATE_IMAGE3", "TImage", "fHotPlate.GroupBox2", "fHotPlate.GroupBox2", 0, 2, "LEAF", true, true, 40, true, 45, true, 401, true, 305, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fHotPlate.GroupBox2.Label2", "Label2", "IDC_CHOTPLATE_LABEL2", "TLabel", "fHotPlate.GroupBox2", "fHotPlate.GroupBox2", 1, 2, "LEAF", true, true, 138, true, 35, true, 39, true, 16, false, 0, -1, "", "", true, "MS Sans Serif", -13, "", true, 0, "clBlack", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fHotPlate.GroupBox2.Label3", "Label3", "IDC_CHOTPLATE_LABEL3", "TLabel", "fHotPlate.GroupBox2", "fHotPlate.GroupBox2", 2, 2, "LEAF", true, true, 204, true, 35, true, 41, true, 16, false, 0, -1, "", "", true, "MS Sans Serif", -13, "", true, 0, "clBlack", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fHotPlate.GroupBox2.Label4", "Label4", "IDC_CHOTPLATE_LABEL4", "TLabel", "fHotPlate.GroupBox2", "fHotPlate.GroupBox2", 3, 2, "LEAF", true, true, 290, true, 35, true, 60, true, 16, false, 0, -1, "", "", true, "MS Sans Serif", -13, "", true, 0, "clBlack", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fHotPlate.GroupBox2.Label5", "Label5", "IDC_CHOTPLATE_LABEL5", "TLabel", "fHotPlate.GroupBox2", "fHotPlate.GroupBox2", 4, 2, "LEAF", true, true, 54, true, 116, true, 40, true, 16, false, 0, -1, "", "", true, "MS Sans Serif", -13, "", true, 0, "clBlack", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fHotPlate.GroupBox2.Label6", "Label6", "IDC_CHOTPLATE_LABEL6", "TLabel", "fHotPlate.GroupBox2", "fHotPlate.GroupBox2", 5, 2, "LEAF", true, true, 54, true, 185, true, 42, true, 16, false, 0, -1, "", "", true, "MS Sans Serif", -13, "", true, 0, "clBlack", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fHotPlate.GroupBox2.Label7", "Label7", "IDC_CHOTPLATE_LABEL7", "TLabel", "fHotPlate.GroupBox2", "fHotPlate.GroupBox2", 6, 2, "LEAF", true, true, 46, true, 286, true, 61, true, 16, false, 0, -1, "", "", true, "MS Sans Serif", -13, "", true, 0, "clBlack", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fHotPlate.GroupBox2.Label8", "Label8", "IDC_CHOTPLATE_LABEL8", "TLabel", "fHotPlate.GroupBox2", "fHotPlate.GroupBox2", 7, 2, "LEAF", true, true, 167, true, 13, true, 278, true, 16, false, 0, -1, "", "", true, "MS Sans Serif", -13, "fsBold", true, 255, "clRed", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fHotPlate.GroupBox2.XST1", "XST1", "IDC_CHOTPLATE_XST1", "TEdit", "fHotPlate.GroupBox2", "fHotPlate.GroupBox2", 8, 2, "LEAF", false, true, 129, true, 58, true, 61, true, 24, true, 0, -1, "", "", true, "MS Sans Serif", -13, "", true, 0, "clBlack", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fHotPlate.GroupBox2.XPitch1", "XPitch1", "IDC_CHOTPLATE_XPITCH1", "TEdit", "fHotPlate.GroupBox2", "fHotPlate.GroupBox2", 9, 2, "LEAF", false, true, 195, true, 58, true, 61, true, 24, true, 1, -1, "", "", true, "MS Sans Serif", -13, "", true, 0, "clBlack", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fHotPlate.GroupBox2.XCT1", "XCT1", "IDC_CHOTPLATE_XCT1", "TEdit", "fHotPlate.GroupBox2", "fHotPlate.GroupBox2", 10, 2, "LEAF", false, true, 281, true, 58, true, 61, true, 24, true, 2, -1, "", "", true, "MS Sans Serif", -13, "", true, 0, "clBlack", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fHotPlate.GroupBox2.YST1", "YST1", "IDC_CHOTPLATE_YST1", "TEdit", "fHotPlate.GroupBox2", "fHotPlate.GroupBox2", 11, 2, "LEAF", false, true, 45, true, 136, true, 61, true, 24, true, 3, -1, "", "", true, "MS Sans Serif", -13, "", true, 0, "clBlack", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fHotPlate.GroupBox2.YPitch1", "YPitch1", "IDC_CHOTPLATE_YPITCH1", "TEdit", "fHotPlate.GroupBox2", "fHotPlate.GroupBox2", 12, 2, "LEAF", false, true, 45, true, 202, true, 61, true, 24, true, 4, -1, "", "", true, "MS Sans Serif", -13, "", true, 0, "clBlack", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fHotPlate.GroupBox2.YCT1", "YCT1", "IDC_CHOTPLATE_YCT1", "TEdit", "fHotPlate.GroupBox2", "fHotPlate.GroupBox2", 13, 2, "LEAF", false, true, 45, true, 306, true, 61, true, 24, true, 5, -1, "", "", true, "MS Sans Serif", -13, "", true, 0, "clBlack", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fHotPlate.GroupBox2.cbSelectHPFromDB", "cbSelectHPFromDB", "IDC_CHOTPLATE_CBSELECTHPFROMDB", "TComboBox", "fHotPlate.GroupBox2", "fHotPlate.GroupBox2", 14, 2, "LEAF", false, true, 204, true, 356, true, 241, true, 24, true, 7, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fHotPlate.GroupBox2.chkUseWideHotplate", "chkUseWideHotplate", "IDC_CHOTPLATE_CHKUSEWIDEHOTPLATE", "TCheckBox", "fHotPlate.GroupBox2", "fHotPlate.GroupBox2", 15, 2, "LEAF", false, true, 12, true, 360, true, 149, true, 17, true, 8, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fHotPlate.GroupBox2.chkTrayHotplateCheck", "chkTrayHotplateCheck", "IDC_CHOTPLATE_CHKTRAYHOTPLATECHECK", "TCheckBox", "fHotPlate.GroupBox2", "fHotPlate.GroupBox2", 16, 2, "LEAF", false, true, 164, true, 332, true, 159, true, 17, true, 6, 0, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fHotPlate.Panel2", "Panel2", "IDD_CHOTPLATE_PANEL2", "TPanel", "fHotPlate", "fHotPlate", 3, 1, "SUBDLG", false, true, 0, true, 475, true, 606, true, 56, true, 3, -1, "alBottom", "", false, "", 0, "", false, 0, "", true, 12761254, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fHotPlate.Panel2.spbSave", "spbSave", "IDC_CHOTPLATE_SPBSAVE", "TSpeedButton", "fHotPlate.Panel2", "fHotPlate.Panel2", 0, 2, "LEAF", true, true, 54, true, 8, true, 227, true, 40, false, 0, -1, "", "", true, "Arial", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fHotPlate.Panel2.sbtExit", "sbtExit", "IDC_CHOTPLATE_SBTEXIT", "TSpeedButton", "fHotPlate.Panel2", "fHotPlate.Panel2", 1, 2, "LEAF", true, true, 332, true, 7, true, 241, true, 41, false, 0, -1, "", "", true, "Arial", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
};

const int kcHotPlateLayoutCount = 30;

} // namespace ht9045_layout
