// ===========================================================================
//  cLd_ULd_layout.gen.cpp
//  DO NOT EDIT -- GENERATED FILE. See the matching _layout.gen.h banner.
// ===========================================================================
#include "cLd_ULd_layout.gen.h"

namespace ht9045_layout {

// (no custom-control properties in this form)

const DfmControlLayout kcLd_ULdLayout[] = {
    { "fLd_ULd", "fLd_ULd", "", "TfLd_ULd", "", "", 0, 0, "ROOT", false, true, 319, true, 63, true, 743, true, 748, false, 0, -1, "", "", true, "MS Sans Serif", -11, "", true, -2147483640, "clWindowText", true, 12761254, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fLd_ULd.Panel1", "Panel1", "IDD_CLD_ULD_PANEL1", "TPanel", "fLd_ULd", "fLd_ULd", 0, 1, "SUBDLG", false, true, 0, true, 653, true, 735, true, 64, true, 1, -1, "alBottom", "", false, "", 0, "", false, 0, "", true, 12761254, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fLd_ULd.Panel1.spbSave", "spbSave", "IDC_CLD_ULD_SPBSAVE", "TSpeedButton", "fLd_ULd.Panel1", "fLd_ULd.Panel1", 0, 2, "LEAF", true, true, 22, true, 17, true, 241, true, 41, false, 0, -1, "", "", true, "Arial", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fLd_ULd.Panel1.sbtExit", "sbtExit", "IDC_CLD_ULD_SBTEXIT", "TSpeedButton", "fLd_ULd.Panel1", "fLd_ULd.Panel1", 1, 2, "LEAF", true, true, 316, true, 17, true, 241, true, 41, false, 0, -1, "", "", true, "Arial", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fLd_ULd.Panel1.btnDefaultValue", "btnDefaultValue", "IDC_CLD_ULD_BTNDEFAULTVALUE", "TSpeedButton", "fLd_ULd.Panel1", "fLd_ULd.Panel1", 2, 2, "LEAF", true, true, 604, true, 22, true, 113, true, 32, false, 0, -1, "", "", true, "MS Sans Serif", -13, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fLd_ULd.Panel1.rbTemp", "rbTemp", "IDC_CLD_ULD_RBTEMP", "TRadioButton", "fLd_ULd.Panel1", "fLd_ULd.Panel1", 3, 2, "LEAF", false, true, -77, true, -4, true, 113, true, 17, true, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fLd_ULd.PageControl1", "PageControl1", "IDC_CLD_ULD_PAGECONTROL1", "TPageControl", "fLd_ULd", "fLd_ULd", 1, 1, "TABHOST", false, true, 0, true, 0, true, 735, true, 653, true, 0, -1, "alClient", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fLd_ULd.PageControl1.TabSheet1", "TabSheet1", "IDD_CLD_ULD_PAGECONTROL1_TABSHEET1", "TTabSheet", "fLd_ULd.PageControl1", "fLd_ULd", 0, 2, "SUBDLG", false, false, 0, false, 0, false, 0, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fLd_ULd.PageControl1.TabSheet1.Panel2", "Panel2", "IDD_CLD_ULD_PAGECONTROL1_TABSHEET1_PANEL2", "TPanel", "fLd_ULd.PageControl1.TabSheet1", "fLd_ULd.PageControl1.TabSheet1", 0, 3, "SUBDLG", false, true, 0, true, 0, true, 727, true, 604, true, 0, -1, "alClient", "", false, "", 0, "", false, 0, "", true, 12761254, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fLd_ULd.PageControl1.TabSheet1.Panel2.grpLoader", "grpLoader", "IDD_CLD_ULD_PAGECONTROL1_TABSHEET1_PANEL2_GRPLOADER", "TGroupBox", "fLd_ULd.PageControl1.TabSheet1.Panel2", "fLd_ULd.PageControl1.TabSheet1.Panel2", 0, 4, "SUBDLG", false, true, 0, true, 0, true, 358, true, 604, true, 0, -1, "alLeft", "", true, "MS Sans Serif", -13, "", true, 8388608, "clNavy", true, 12761254, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fLd_ULd.PageControl1.TabSheet1.Panel2.grpLoader.Image1", "Image1", "IDC_CLD_ULD_IMAGE1", "TImage", "fLd_ULd.PageControl1.TabSheet1.Panel2.grpLoader", "fLd_ULd.PageControl1.TabSheet1.Panel2.grpLoader", 0, 5, "LEAF", true, true, 8, true, 16, true, 340, true, 540, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fLd_ULd.PageControl1.TabSheet1.Panel2.grpLoader.Label1", "Label1", "IDC_CLD_ULD_LABEL1", "TLabel", "fLd_ULd.PageControl1.TabSheet1.Panel2.grpLoader", "fLd_ULd.PageControl1.TabSheet1.Panel2.grpLoader", 1, 5, "LEAF", true, true, 230, true, 161, true, 75, true, 13, false, 0, -1, "", "", true, "MS Sans Serif", -5, "", true, 8388608, "clNavy", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fLd_ULd.PageControl1.TabSheet1.Panel2.grpLoader.Label3", "Label3", "IDC_CLD_ULD_LABEL3", "TLabel", "fLd_ULd.PageControl1.TabSheet1.Panel2.grpLoader", "fLd_ULd.PageControl1.TabSheet1.Panel2.grpLoader", 2, 5, "LEAF", true, true, 80, true, 240, true, 142, true, 13, false, 0, -1, "", "", true, "MS Sans Serif", -11, "", true, 8388608, "clNavy", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fLd_ULd.PageControl1.TabSheet1.Panel2.grpLoader.Label5", "Label5", "IDC_CLD_ULD_LABEL5", "TLabel", "fLd_ULd.PageControl1.TabSheet1.Panel2.grpLoader", "fLd_ULd.PageControl1.TabSheet1.Panel2.grpLoader", 3, 5, "LEAF", true, true, 9, true, 384, true, 202, true, 13, false, 0, -1, "", "", true, "MS Sans Serif", -11, "", true, 8388608, "clNavy", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fLd_ULd.PageControl1.TabSheet1.Panel2.grpLoader.Label7", "Label7", "IDC_CLD_ULD_LABEL7", "TLabel", "fLd_ULd.PageControl1.TabSheet1.Panel2.grpLoader", "fLd_ULd.PageControl1.TabSheet1.Panel2.grpLoader", 4, 5, "LEAF", true, true, 17, true, 561, true, 181, true, 13, false, 0, -1, "", "", true, "MS Sans Serif", -11, "", true, 8388608, "clNavy", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fLd_ULd.PageControl1.TabSheet1.Panel2.grpLoader.Label2", "Label2", "IDC_CLD_ULD_LABEL2", "TLabel", "fLd_ULd.PageControl1.TabSheet1.Panel2.grpLoader", "fLd_ULd.PageControl1.TabSheet1.Panel2.grpLoader", 5, 5, "LEAF", true, true, 17, true, 533, true, 88, true, 13, false, 0, -1, "", "", true, "MS Sans Serif", -11, "", true, 8388608, "clNavy", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fLd_ULd.PageControl1.TabSheet1.Panel2.grpLoader.edtLD_TrayArrivalDely", "edtLD_TrayArrivalDely", "IDC_CLD_ULD_EDTLD_TRAYARRIVALDELY", "TEdit", "fLd_ULd.PageControl1.TabSheet1.Panel2.grpLoader", "fLd_ULd.PageControl1.TabSheet1.Panel2.grpLoader", 6, 5, "LEAF", false, true, 227, true, 175, true, 97, true, 24, true, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fLd_ULd.PageControl1.TabSheet1.Panel2.grpLoader.edtLD_FixTrayDely", "edtLD_FixTrayDely", "IDC_CLD_ULD_EDTLD_FIXTRAYDELY", "TEdit", "fLd_ULd.PageControl1.TabSheet1.Panel2.grpLoader", "fLd_ULd.PageControl1.TabSheet1.Panel2.grpLoader", 7, 5, "LEAF", false, true, 227, true, 236, true, 97, true, 24, true, 1, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fLd_ULd.PageControl1.TabSheet1.Panel2.grpLoader.edtLD_MiddLockDelay", "edtLD_MiddLockDelay", "IDC_CLD_ULD_EDTLD_MIDDLOCKDELAY", "TEdit", "fLd_ULd.PageControl1.TabSheet1.Panel2.grpLoader", "fLd_ULd.PageControl1.TabSheet1.Panel2.grpLoader", 8, 5, "LEAF", false, true, 227, true, 380, true, 97, true, 24, true, 2, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fLd_ULd.PageControl1.TabSheet1.Panel2.grpLoader.edtLD_LiftDownDelay", "edtLD_LiftDownDelay", "IDC_CLD_ULD_EDTLD_LIFTDOWNDELAY", "TEdit", "fLd_ULd.PageControl1.TabSheet1.Panel2.grpLoader", "fLd_ULd.PageControl1.TabSheet1.Panel2.grpLoader", 9, 5, "LEAF", false, true, 227, true, 556, true, 97, true, 24, true, 4, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fLd_ULd.PageControl1.TabSheet1.Panel2.grpLoader.edtLD_BeforeDownDelay", "edtLD_BeforeDownDelay", "IDC_CLD_ULD_EDTLD_BEFOREDOWNDELAY", "TEdit", "fLd_ULd.PageControl1.TabSheet1.Panel2.grpLoader", "fLd_ULd.PageControl1.TabSheet1.Panel2.grpLoader", 10, 5, "LEAF", false, true, 227, true, 528, true, 97, true, 24, true, 3, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fLd_ULd.PageControl1.TabSheet1.Panel2.grpUnloader", "grpUnloader", "IDD_CLD_ULD_PAGECONTROL1_TABSHEET1_PANEL2_GRPUNLOADER", "TGroupBox", "fLd_ULd.PageControl1.TabSheet1.Panel2", "fLd_ULd.PageControl1.TabSheet1.Panel2", 1, 4, "SUBDLG", false, true, 358, true, 0, true, 358, true, 604, true, 1, -1, "alLeft", "", true, "MS Sans Serif", -13, "", true, 8388608, "clNavy", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fLd_ULd.PageControl1.TabSheet1.Panel2.grpUnloader.Image2", "Image2", "IDC_CLD_ULD_IMAGE2", "TImage", "fLd_ULd.PageControl1.TabSheet1.Panel2.grpUnloader", "fLd_ULd.PageControl1.TabSheet1.Panel2.grpUnloader", 0, 5, "LEAF", true, true, 8, true, 16, true, 340, true, 540, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fLd_ULd.PageControl1.TabSheet1.Panel2.grpUnloader.Label9", "Label9", "IDC_CLD_ULD_LABEL9", "TLabel", "fLd_ULd.PageControl1.TabSheet1.Panel2.grpUnloader", "fLd_ULd.PageControl1.TabSheet1.Panel2.grpUnloader", 1, 5, "LEAF", true, true, 189, true, 159, true, 84, true, 13, false, 0, -1, "", "", true, "MS Sans Serif", -11, "", true, 8388608, "clNavy", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fLd_ULd.PageControl1.TabSheet1.Panel2.grpUnloader.Label12", "Label12", "IDC_CLD_ULD_LABEL12", "TLabel", "fLd_ULd.PageControl1.TabSheet1.Panel2.grpUnloader", "fLd_ULd.PageControl1.TabSheet1.Panel2.grpUnloader", 2, 5, "LEAF", true, true, 32, true, 240, true, 142, true, 13, false, 0, -1, "", "", true, "MS Sans Serif", -11, "", true, 8388608, "clNavy", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fLd_ULd.PageControl1.TabSheet1.Panel2.grpUnloader.Label13", "Label13", "IDC_CLD_ULD_LABEL13", "TLabel", "fLd_ULd.PageControl1.TabSheet1.Panel2.grpUnloader", "fLd_ULd.PageControl1.TabSheet1.Panel2.grpUnloader", 3, 5, "LEAF", true, true, 113, true, 384, true, 89, true, 13, false, 0, -1, "", "", true, "MS Sans Serif", -11, "", true, 8388608, "clNavy", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fLd_ULd.PageControl1.TabSheet1.Panel2.grpUnloader.Label15", "Label15", "IDC_CLD_ULD_LABEL15", "TLabel", "fLd_ULd.PageControl1.TabSheet1.Panel2.grpUnloader", "fLd_ULd.PageControl1.TabSheet1.Panel2.grpUnloader", 4, 5, "LEAF", true, true, 17, true, 561, true, 181, true, 13, false, 0, -1, "", "", true, "MS Sans Serif", -11, "", true, 8388608, "clNavy", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fLd_ULd.PageControl1.TabSheet1.Panel2.grpUnloader.Label17", "Label17", "IDC_CLD_ULD_LABEL17", "TLabel", "fLd_ULd.PageControl1.TabSheet1.Panel2.grpUnloader", "fLd_ULd.PageControl1.TabSheet1.Panel2.grpUnloader", 5, 5, "LEAF", true, true, 225, true, 463, true, 89, true, 13, false, 0, -1, "", "", true, "MS Sans Serif", -11, "", true, 8388608, "clNavy", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fLd_ULd.PageControl1.TabSheet1.Panel2.grpUnloader.edtULD_TrayArrivalDelay", "edtULD_TrayArrivalDelay", "IDC_CLD_ULD_EDTULD_TRAYARRIVALDELAY", "TEdit", "fLd_ULd.PageControl1.TabSheet1.Panel2.grpUnloader", "fLd_ULd.PageControl1.TabSheet1.Panel2.grpUnloader", 6, 5, "LEAF", false, true, 181, true, 175, true, 97, true, 24, true, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fLd_ULd.PageControl1.TabSheet1.Panel2.grpUnloader.edtULD_FixTrayDely", "edtULD_FixTrayDely", "IDC_CLD_ULD_EDTULD_FIXTRAYDELY", "TEdit", "fLd_ULd.PageControl1.TabSheet1.Panel2.grpUnloader", "fLd_ULd.PageControl1.TabSheet1.Panel2.grpUnloader", 7, 5, "LEAF", false, true, 181, true, 236, true, 97, true, 24, true, 1, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fLd_ULd.PageControl1.TabSheet1.Panel2.grpUnloader.edtULD_TrayBackDelay", "edtULD_TrayBackDelay", "IDC_CLD_ULD_EDTULD_TRAYBACKDELAY", "TEdit", "fLd_ULd.PageControl1.TabSheet1.Panel2.grpUnloader", "fLd_ULd.PageControl1.TabSheet1.Panel2.grpUnloader", 8, 5, "LEAF", false, true, 214, true, 380, true, 97, true, 24, true, 2, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fLd_ULd.PageControl1.TabSheet1.Panel2.grpUnloader.edtULD_LiftDownDelay", "edtULD_LiftDownDelay", "IDC_CLD_ULD_EDTULD_LIFTDOWNDELAY", "TEdit", "fLd_ULd.PageControl1.TabSheet1.Panel2.grpUnloader", "fLd_ULd.PageControl1.TabSheet1.Panel2.grpUnloader", 9, 5, "LEAF", false, true, 222, true, 556, true, 97, true, 24, true, 4, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fLd_ULd.PageControl1.TabSheet1.Panel2.grpUnloader.edtULD_TrayArrivalWait", "edtULD_TrayArrivalWait", "IDC_CLD_ULD_EDTULD_TRAYARRIVALWAIT", "TEdit", "fLd_ULd.PageControl1.TabSheet1.Panel2.grpUnloader", "fLd_ULd.PageControl1.TabSheet1.Panel2.grpUnloader", 10, 5, "LEAF", false, true, 222, true, 483, true, 97, true, 24, true, 3, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fLd_ULd.PageControl1.TabSheet1.Panel3", "Panel3", "IDD_CLD_ULD_PAGECONTROL1_TABSHEET1_PANEL3", "TPanel", "fLd_ULd.PageControl1.TabSheet1", "fLd_ULd.PageControl1.TabSheet1", 1, 3, "SUBDLG", false, true, 0, true, 604, true, 727, true, 21, true, 1, -1, "alBottom", "", false, "", 0, "", false, 0, "", true, 12761254, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fLd_ULd.PageControl1.TabSheet1.Panel3.lblUnit", "lblUnit", "IDC_CLD_ULD_LBLUNIT", "TLabel", "fLd_ULd.PageControl1.TabSheet1.Panel3", "fLd_ULd.PageControl1.TabSheet1.Panel3", 0, 4, "LEAF", true, true, 656, true, 8, true, 50, true, 13, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fLd_ULd.PageControl1.tsKnocker", "tsKnocker", "IDD_CLD_ULD_PAGECONTROL1_TSKNOCKER", "TTabSheet", "fLd_ULd.PageControl1", "fLd_ULd", 1, 2, "SUBDLG", false, false, 0, false, 0, false, 0, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fLd_ULd.PageControl1.tsKnocker.palKnocker", "palKnocker", "IDD_CLD_ULD_PAGECONTROL1_TSKNOCKER_PALKNOCKER", "TPanel", "fLd_ULd.PageControl1.tsKnocker", "fLd_ULd.PageControl1.tsKnocker", 0, 3, "SUBDLG", false, true, 0, true, 0, true, 719, true, 617, true, 0, -1, "alClient", "", false, "", 0, "", false, 0, "", true, 12761254, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fLd_ULd.PageControl1.tsKnocker.palKnocker.labP13", "labP13", "IDC_CLD_ULD_LABP13", "TLabel", "fLd_ULd.PageControl1.tsKnocker.palKnocker", "fLd_ULd.PageControl1.tsKnocker.palKnocker", 0, 4, "LEAF", true, true, 37, true, 35, true, 282, true, 16, false, 0, -1, "", "", true, "MS Sans Serif", -13, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fLd_ULd.PageControl1.tsKnocker.palKnocker.labP14_2", "labP14_2", "IDC_CLD_ULD_LABP14_2", "TLabel", "fLd_ULd.PageControl1.tsKnocker.palKnocker", "fLd_ULd.PageControl1.tsKnocker.palKnocker", 1, 4, "LEAF", true, true, 37, true, 149, true, 329, true, 16, false, 0, -1, "", "", true, "MS Sans Serif", -13, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fLd_ULd.PageControl1.tsKnocker.palKnocker.labP14_1", "labP14_1", "IDC_CLD_ULD_LABP14_1", "TLabel", "fLd_ULd.PageControl1.tsKnocker.palKnocker", "fLd_ULd.PageControl1.tsKnocker.palKnocker", 2, 4, "LEAF", true, true, 37, true, 117, true, 236, true, 16, false, 0, -1, "", "", true, "MS Sans Serif", -13, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fLd_ULd.PageControl1.tsKnocker.palKnocker.labP16", "labP16", "IDC_CLD_ULD_LABP16", "TLabel", "fLd_ULd.PageControl1.tsKnocker.palKnocker", "fLd_ULd.PageControl1.tsKnocker.palKnocker", 3, 4, "LEAF", true, true, 37, true, 218, true, 282, true, 16, false, 0, -1, "", "", true, "MS Sans Serif", -13, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fLd_ULd.PageControl1.tsKnocker.palKnocker.labP16_2", "labP16_2", "IDC_CLD_ULD_LABP16_2", "TLabel", "fLd_ULd.PageControl1.tsKnocker.palKnocker", "fLd_ULd.PageControl1.tsKnocker.palKnocker", 4, 4, "LEAF", true, true, 37, true, 244, true, 268, true, 16, false, 0, -1, "", "", true, "MS Sans Serif", -13, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fLd_ULd.PageControl1.tsKnocker.palKnocker.labP13_2", "labP13_2", "IDC_CLD_ULD_LABP13_2", "TLabel", "fLd_ULd.PageControl1.tsKnocker.palKnocker", "fLd_ULd.PageControl1.tsKnocker.palKnocker", 5, 4, "LEAF", true, true, 37, true, 60, true, 268, true, 16, false, 0, -1, "", "", true, "MS Sans Serif", -13, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fLd_ULd.PageControl1.tsKnocker.palKnocker.labF40_2", "labF40_2", "IDC_CLD_ULD_LABF40_2", "TLabel", "fLd_ULd.PageControl1.tsKnocker.palKnocker", "fLd_ULd.PageControl1.tsKnocker.palKnocker", 6, 4, "LEAF", true, true, 37, true, 349, true, 267, true, 16, false, 0, -1, "", "", true, "MS Sans Serif", -13, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fLd_ULd.PageControl1.tsKnocker.palKnocker.labF40_3", "labF40_3", "IDC_CLD_ULD_LABF40_3", "TLabel", "fLd_ULd.PageControl1.tsKnocker.palKnocker", "fLd_ULd.PageControl1.tsKnocker.palKnocker", 7, 4, "LEAF", true, true, 37, true, 374, true, 268, true, 16, false, 0, -1, "", "", true, "MS Sans Serif", -13, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fLd_ULd.PageControl1.tsKnocker.palKnocker.labF40_1", "labF40_1", "IDC_CLD_ULD_LABF40_1", "TLabel", "fLd_ULd.PageControl1.tsKnocker.palKnocker", "fLd_ULd.PageControl1.tsKnocker.palKnocker", 8, 4, "LEAF", true, true, 37, true, 325, true, 153, true, 16, false, 0, -1, "", "", true, "MS Sans Serif", -13, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fLd_ULd.PageControl1.tsKnocker.palKnocker.cbP13", "cbP13", "IDC_CLD_ULD_CBP13", "TCheckBox", "fLd_ULd.PageControl1.tsKnocker.palKnocker", "fLd_ULd.PageControl1.tsKnocker.palKnocker", 9, 4, "LEAF", false, true, 5, true, 8, true, 392, true, 17, true, 0, -1, "", "", true, "MS Sans Serif", -13, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fLd_ULd.PageControl1.tsKnocker.palKnocker.edP13_1", "edP13_1", "IDC_CLD_ULD_EDP13_1", "TEdit", "fLd_ULd.PageControl1.tsKnocker.palKnocker", "fLd_ULd.PageControl1.tsKnocker.palKnocker", 10, 4, "LEAF", false, true, 179, true, 31, true, 49, true, 24, true, 1, -1, "", "", true, "MS Sans Serif", -13, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fLd_ULd.PageControl1.tsKnocker.palKnocker.cbP14", "cbP14", "IDC_CLD_ULD_CBP14", "TCheckBox", "fLd_ULd.PageControl1.tsKnocker.palKnocker", "fLd_ULd.PageControl1.tsKnocker.palKnocker", 11, 4, "LEAF", false, true, 5, true, 91, true, 331, true, 17, true, 2, -1, "", "", true, "MS Sans Serif", -13, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fLd_ULd.PageControl1.tsKnocker.palKnocker.edP14_1", "edP14_1", "IDC_CLD_ULD_EDP14_1", "TEdit", "fLd_ULd.PageControl1.tsKnocker.palKnocker", "fLd_ULd.PageControl1.tsKnocker.palKnocker", 12, 4, "LEAF", false, true, 280, true, 112, true, 49, true, 24, true, 3, -1, "", "", true, "MS Sans Serif", -13, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fLd_ULd.PageControl1.tsKnocker.palKnocker.edP14_2", "edP14_2", "IDC_CLD_ULD_EDP14_2", "TEdit", "fLd_ULd.PageControl1.tsKnocker.palKnocker", "fLd_ULd.PageControl1.tsKnocker.palKnocker", 13, 4, "LEAF", false, true, 230, true, 144, true, 49, true, 24, true, 4, -1, "", "", true, "MS Sans Serif", -13, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fLd_ULd.PageControl1.tsKnocker.palKnocker.cbP16", "cbP16", "IDC_CLD_ULD_CBP16", "TCheckBox", "fLd_ULd.PageControl1.tsKnocker.palKnocker", "fLd_ULd.PageControl1.tsKnocker.palKnocker", 14, 4, "LEAF", false, true, 5, true, 192, true, 392, true, 17, true, 5, -1, "", "", true, "MS Sans Serif", -13, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fLd_ULd.PageControl1.tsKnocker.palKnocker.edP16_1", "edP16_1", "IDC_CLD_ULD_EDP16_1", "TEdit", "fLd_ULd.PageControl1.tsKnocker.palKnocker", "fLd_ULd.PageControl1.tsKnocker.palKnocker", 15, 4, "LEAF", false, true, 180, true, 214, true, 49, true, 24, true, 6, -1, "", "", true, "MS Sans Serif", -13, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fLd_ULd.PageControl1.tsKnocker.palKnocker.edP16_2", "edP16_2", "IDC_CLD_ULD_EDP16_2", "TEdit", "fLd_ULd.PageControl1.tsKnocker.palKnocker", "fLd_ULd.PageControl1.tsKnocker.palKnocker", 16, 4, "LEAF", false, true, 168, true, 242, true, 49, true, 24, true, 7, -1, "", "", true, "MS Sans Serif", -13, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fLd_ULd.PageControl1.tsKnocker.palKnocker.edP13_2", "edP13_2", "IDC_CLD_ULD_EDP13_2", "TEdit", "fLd_ULd.PageControl1.tsKnocker.palKnocker", "fLd_ULd.PageControl1.tsKnocker.palKnocker", 17, 4, "LEAF", false, true, 168, true, 59, true, 49, true, 24, true, 8, -1, "", "", true, "MS Sans Serif", -13, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fLd_ULd.PageControl1.tsKnocker.palKnocker.cbF23", "cbF23", "IDC_CLD_ULD_CBF23", "TCheckBox", "fLd_ULd.PageControl1.tsKnocker.palKnocker", "fLd_ULd.PageControl1.tsKnocker.palKnocker", 18, 4, "LEAF", false, true, 5, true, 276, true, 368, true, 17, true, 9, -1, "", "", true, "MS Sans Serif", -13, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fLd_ULd.PageControl1.tsKnocker.palKnocker.edF23", "edF23", "IDC_CLD_ULD_EDF23", "TEdit", "fLd_ULd.PageControl1.tsKnocker.palKnocker", "fLd_ULd.PageControl1.tsKnocker.palKnocker", 19, 4, "LEAF", false, true, 204, true, 274, true, 45, true, 21, true, 10, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fLd_ULd.PageControl1.tsKnocker.palKnocker.cbF40", "cbF40", "IDC_CLD_ULD_CBF40", "TCheckBox", "fLd_ULd.PageControl1.tsKnocker.palKnocker", "fLd_ULd.PageControl1.tsKnocker.palKnocker", 20, 4, "LEAF", false, true, 5, true, 304, true, 368, true, 17, true, 11, -1, "", "", true, "MS Sans Serif", -13, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fLd_ULd.PageControl1.tsKnocker.palKnocker.edP40_2", "edP40_2", "IDC_CLD_ULD_EDP40_2", "TEdit", "fLd_ULd.PageControl1.tsKnocker.palKnocker", "fLd_ULd.PageControl1.tsKnocker.palKnocker", 21, 4, "LEAF", false, true, 167, true, 345, true, 49, true, 24, true, 12, -1, "", "", true, "MS Sans Serif", -13, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fLd_ULd.PageControl1.tsKnocker.palKnocker.edP40_3", "edP40_3", "IDC_CLD_ULD_EDP40_3", "TEdit", "fLd_ULd.PageControl1.tsKnocker.palKnocker", "fLd_ULd.PageControl1.tsKnocker.palKnocker", 22, 4, "LEAF", false, true, 168, true, 373, true, 49, true, 24, true, 13, -1, "", "", true, "MS Sans Serif", -13, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fLd_ULd.PageControl1.tsKnocker.palKnocker.edP40_1", "edP40_1", "IDC_CLD_ULD_EDP40_1", "TEdit", "fLd_ULd.PageControl1.tsKnocker.palKnocker", "fLd_ULd.PageControl1.tsKnocker.palKnocker", 23, 4, "LEAF", false, true, 196, true, 321, true, 49, true, 24, true, 14, -1, "", "", true, "MS Sans Serif", -13, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
};

const int kcLd_ULdLayoutCount = 61;

} // namespace ht9045_layout
