// ===========================================================================
//  cSecurity_layout.gen.cpp
//  DO NOT EDIT -- GENERATED FILE. See the matching _layout.gen.h banner.
// ===========================================================================
#include "cSecurity_layout.gen.h"

namespace ht9045_layout {

// (no custom-control properties in this form)

const DfmControlLayout kcSecurityLayout[] = {
    { "fSecurity", "fSecurity", "", "TfSecurity", "", "", 0, 0, "ROOT", false, true, 66, true, 40, false, 0, false, 0, false, 0, -1, "", "", true, "MS Sans Serif", -11, "", true, -2147483640, "clWindowText", true, 12761254, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSecurity.Panel13", "Panel13", "IDC_CSECURITY_PANEL13", "TPanel", "fSecurity", "fSecurity", 0, 1, "LEAF", false, true, 0, true, 0, true, 874, true, 31, true, 0, -1, "alTop", "", true, "Arial", -19, "", true, 16777215, "clWhite", true, 9534289, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSecurity.Panel1", "Panel1", "IDD_CSECURITY_PANEL1", "TPanel", "fSecurity", "fSecurity", 1, 1, "SUBDLG", false, true, 0, true, 31, true, 874, true, 53, true, 1, -1, "alTop", "", false, "", 0, "", false, 0, "", true, 12761254, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSecurity.Panel1.sbSupervisor", "sbSupervisor", "IDC_CSECURITY_SBSUPERVISOR", "TSpeedButton", "fSecurity.Panel1", "fSecurity.Panel1", 0, 2, "LEAF", true, true, 67, true, 11, true, 186, true, 33, false, 0, -1, "", "", true, "Arial", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSecurity.Panel1.sbEngineer", "sbEngineer", "IDC_CSECURITY_SBENGINEER", "TSpeedButton", "fSecurity.Panel1", "fSecurity.Panel1", 1, 2, "LEAF", true, true, 497, true, 11, true, 186, true, 33, false, 0, -1, "", "", true, "Arial", -15, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSecurity.Panel1.btnHonPrec", "btnHonPrec", "IDC_CSECURITY_BTNHONPREC", "TSpeedButton", "fSecurity.Panel1", "fSecurity.Panel1", 2, 2, "LEAF", true, true, 282, true, 11, true, 186, true, 33, false, 0, -1, "", "", true, "Arial", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSecurity.Panel1.btnOperator", "btnOperator", "IDC_CSECURITY_BTNOPERATOR", "TSpeedButton", "fSecurity.Panel1", "fSecurity.Panel1", 3, 2, "LEAF", true, true, 645, true, 11, true, 186, true, 33, false, 0, -1, "", "", true, "Arial", -15, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSecurity.Panel17", "Panel17", "IDC_CSECURITY_PANEL17", "TPanel", "fSecurity", "fSecurity", 2, 1, "LEAF", false, true, 0, true, 84, true, 874, true, 31, true, 2, -1, "alTop", "", true, "Arial", -19, "", true, 16777215, "clWhite", true, 9534289, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSecurity.SecurityExit", "SecurityExit", "IDC_CSECURITY_SECURITYEXIT", "TPanel", "fSecurity", "fSecurity", 3, 1, "LEAF", false, true, 0, true, 830, true, 874, true, 41, true, 4, -1, "alBottom", "", true, "Arial", -27, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSecurity.PageControl1", "PageControl1", "IDC_CSECURITY_PAGECONTROL1", "TPageControl", "fSecurity", "fSecurity", 4, 1, "TABHOST", false, true, 0, true, 115, true, 874, true, 715, true, 3, -1, "alClient", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSecurity.PageControl1.tsMain", "tsMain", "IDD_CSECURITY_PAGECONTROL1_TSMAIN", "TTabSheet", "fSecurity.PageControl1", "fSecurity", 0, 2, "SUBDLG", false, false, 0, false, 0, false, 0, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSecurity.PageControl1.tsMain.sbMain", "sbMain", "IDD_CSECURITY_PAGECONTROL1_TSMAIN_SBMAIN", "TScrollBox", "fSecurity.PageControl1.tsMain", "fSecurity.PageControl1.tsMain", 0, 3, "SUBDLG", false, true, 0, true, 0, true, 841, true, 601, true, 0, -1, "alClient", "", true, "Arial", -13, "", true, -2147483640, "clWindowText", true, 12761254, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSecurity.PageControl1.tsTools", "tsTools", "IDD_CSECURITY_PAGECONTROL1_TSTOOLS", "TTabSheet", "fSecurity.PageControl1", "fSecurity", 1, 2, "SUBDLG", false, false, 0, false, 0, false, 0, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSecurity.PageControl1.tsTools.sbTools", "sbTools", "IDD_CSECURITY_PAGECONTROL1_TSTOOLS_SBTOOLS", "TScrollBox", "fSecurity.PageControl1.tsTools", "fSecurity.PageControl1.tsTools", 0, 3, "SUBDLG", false, true, 0, true, 0, true, 841, true, 601, true, 0, -1, "alClient", "", true, "Arial", -13, "", true, -2147483640, "clWindowText", true, 12761254, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSecurity.PageControl1.tsConfig", "tsConfig", "IDD_CSECURITY_PAGECONTROL1_TSCONFIG", "TTabSheet", "fSecurity.PageControl1", "fSecurity", 2, 2, "SUBDLG", false, false, 0, false, 0, false, 0, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSecurity.PageControl1.tsConfig.sbConfig", "sbConfig", "IDD_CSECURITY_PAGECONTROL1_TSCONFIG_SBCONFIG", "TScrollBox", "fSecurity.PageControl1.tsConfig", "fSecurity.PageControl1.tsConfig", 0, 3, "SUBDLG", false, true, 0, true, 0, true, 841, true, 601, true, 0, -1, "alClient", "", true, "Arial", -13, "", true, -2147483640, "clWindowText", true, 12761254, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSecurity.PageControl1.tsContact", "tsContact", "IDD_CSECURITY_PAGECONTROL1_TSCONTACT", "TTabSheet", "fSecurity.PageControl1", "fSecurity", 3, 2, "SUBDLG", false, false, 0, false, 0, false, 0, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSecurity.PageControl1.tsContact.sbContact", "sbContact", "IDD_CSECURITY_PAGECONTROL1_TSCONTACT_SBCONTACT", "TScrollBox", "fSecurity.PageControl1.tsContact", "fSecurity.PageControl1.tsContact", 0, 3, "SUBDLG", false, true, 0, true, 0, true, 841, true, 601, true, 0, -1, "alClient", "", true, "Arial", -13, "", true, -2147483640, "clWindowText", true, 12761254, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSecurity.PageControl1.tsSetup", "tsSetup", "IDD_CSECURITY_PAGECONTROL1_TSSETUP", "TTabSheet", "fSecurity.PageControl1", "fSecurity", 4, 2, "SUBDLG", false, false, 0, false, 0, false, 0, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSecurity.PageControl1.tsSetup.sbSetup", "sbSetup", "IDD_CSECURITY_PAGECONTROL1_TSSETUP_SBSETUP", "TScrollBox", "fSecurity.PageControl1.tsSetup", "fSecurity.PageControl1.tsSetup", 0, 3, "SUBDLG", false, true, 0, true, 0, true, 841, true, 490, true, 0, -1, "alClient", "", true, "Arial", -13, "", true, -2147483640, "clWindowText", true, 12761254, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSecurity.PageControl1.tsTemp", "tsTemp", "IDD_CSECURITY_PAGECONTROL1_TSTEMP", "TTabSheet", "fSecurity.PageControl1", "fSecurity", 5, 2, "SUBDLG", false, false, 0, false, 0, false, 0, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSecurity.PageControl1.tsTemp.sbTemp", "sbTemp", "IDD_CSECURITY_PAGECONTROL1_TSTEMP_SBTEMP", "TScrollBox", "fSecurity.PageControl1.tsTemp", "fSecurity.PageControl1.tsTemp", 0, 3, "SUBDLG", false, true, 0, true, 0, true, 841, true, 490, true, 0, -1, "alClient", "", true, "Arial", -13, "", true, -2147483640, "clWindowText", true, 12761254, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSecurity.PageControl1.tsIo", "tsIo", "IDD_CSECURITY_PAGECONTROL1_TSIO", "TTabSheet", "fSecurity.PageControl1", "fSecurity", 6, 2, "SUBDLG", false, false, 0, false, 0, false, 0, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSecurity.PageControl1.tsIo.sbIO", "sbIO", "IDD_CSECURITY_PAGECONTROL1_TSIO_SBIO", "TScrollBox", "fSecurity.PageControl1.tsIo", "fSecurity.PageControl1.tsIo", 0, 3, "SUBDLG", false, true, 0, true, 0, true, 841, true, 490, true, 0, -1, "alClient", "", true, "Arial", -13, "", true, -2147483640, "clWindowText", true, 12761254, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSecurity.PageControl1.tsConfiguration", "tsConfiguration", "IDD_CSECURITY_PAGECONTROL1_TSCONFIGURATION", "TTabSheet", "fSecurity.PageControl1", "fSecurity", 7, 2, "SUBDLG", false, false, 0, false, 0, false, 0, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSecurity.PageControl1.tsConfiguration.sbConfiguration", "sbConfiguration", "IDD_CSECURITY_PAGECONTROL1_TSCONFIGURATION_SBCONFIGURATION", "TScrollBox", "fSecurity.PageControl1.tsConfiguration", "fSecurity.PageControl1.tsConfiguration", 0, 3, "SUBDLG", false, true, 0, true, 0, true, 841, true, 490, true, 0, -1, "alClient", "", true, "Arial", -13, "", true, -2147483640, "clWindowText", true, 12761254, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSecurity.PageControl1.tsYield", "tsYield", "IDD_CSECURITY_PAGECONTROL1_TSYIELD", "TTabSheet", "fSecurity.PageControl1", "fSecurity", 8, 2, "SUBDLG", false, false, 0, false, 0, false, 0, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSecurity.PageControl1.tsYield.sbYield", "sbYield", "IDD_CSECURITY_PAGECONTROL1_TSYIELD_SBYIELD", "TScrollBox", "fSecurity.PageControl1.tsYield", "fSecurity.PageControl1.tsYield", 0, 3, "SUBDLG", false, true, 0, true, 0, true, 841, true, 490, true, 0, -1, "alClient", "", true, "Arial", -13, "", true, -2147483640, "clWindowText", true, 12761254, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSecurity.PageControl1.tsOther", "tsOther", "IDD_CSECURITY_PAGECONTROL1_TSOTHER", "TTabSheet", "fSecurity.PageControl1", "fSecurity", 9, 2, "SUBDLG", false, false, 0, false, 0, false, 0, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSecurity.PageControl1.tsOther.sbOther", "sbOther", "IDD_CSECURITY_PAGECONTROL1_TSOTHER_SBOTHER", "TScrollBox", "fSecurity.PageControl1.tsOther", "fSecurity.PageControl1.tsOther", 0, 3, "SUBDLG", false, true, 0, true, 0, true, 841, true, 554, true, 0, -1, "alClient", "", true, "Arial", -13, "", true, -2147483640, "clWindowText", true, 12761254, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSecurity.PageControl1.tsJamCode", "tsJamCode", "IDD_CSECURITY_PAGECONTROL1_TSJAMCODE", "TTabSheet", "fSecurity.PageControl1", "fSecurity", 10, 2, "SUBDLG", false, false, 0, false, 0, false, 0, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSecurity.PageControl1.tsJamCode.labJamArea", "labJamArea", "IDC_CSECURITY_LABJAMAREA", "TLabel", "fSecurity.PageControl1.tsJamCode", "fSecurity.PageControl1.tsJamCode", 0, 3, "LEAF", true, true, 4, true, 0, true, 47, true, 20, false, 0, -1, "", "", true, "微軟正黑體", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSecurity.PageControl1.tsJamCode.labJamCode", "labJamCode", "IDC_CSECURITY_LABJAMCODE", "TLabel", "fSecurity.PageControl1.tsJamCode", "fSecurity.PageControl1.tsJamCode", 1, 3, "LEAF", true, true, 4, true, 36, true, 52, true, 20, false, 0, -1, "", "", true, "微軟正黑體", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSecurity.PageControl1.tsJamCode.Label1", "Label1", "IDC_CSECURITY_LABEL1", "TLabel", "fSecurity.PageControl1.tsJamCode", "fSecurity.PageControl1.tsJamCode", 2, 3, "LEAF", true, true, 4, true, 72, true, 50, true, 20, false, 0, -1, "", "", true, "微軟正黑體", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSecurity.PageControl1.tsJamCode.labLang", "labLang", "IDC_CSECURITY_LABLANG", "TLabel", "fSecurity.PageControl1.tsJamCode", "fSecurity.PageControl1.tsJamCode", 3, 3, "LEAF", true, true, 0, true, 189, true, 87, true, 20, false, 0, -1, "", "", true, "微軟正黑體", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSecurity.PageControl1.tsJamCode.spbExport", "spbExport", "IDC_CSECURITY_SPBEXPORT", "TSpeedButton", "fSecurity.PageControl1.tsJamCode", "fSecurity.PageControl1.tsJamCode", 4, 3, "LEAF", true, true, 687, true, 317, true, 143, true, 55, false, 0, -1, "", "", true, "Arial", -13, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSecurity.PageControl1.tsJamCode.spbImport", "spbImport", "IDC_CSECURITY_SPBIMPORT", "TSpeedButton", "fSecurity.PageControl1.tsJamCode", "fSecurity.PageControl1.tsJamCode", 5, 3, "LEAF", true, true, 535, true, 317, true, 141, true, 55, false, 0, -1, "", "", true, "Arial", -13, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSecurity.PageControl1.tsJamCode.labMustCheck_35", "labMustCheck_35", "IDC_CSECURITY_LABMUSTCHECK_35", "TLabel", "fSecurity.PageControl1.tsJamCode", "fSecurity.PageControl1.tsJamCode", 6, 3, "LEAF", true, true, 92, true, 112, true, 354, true, 16, false, 0, 0, "", "", true, "MS Sans Serif", -13, "fsBold", true, 255, "clRed", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSecurity.PageControl1.tsJamCode.rgJamLevel", "rgJamLevel", "IDD_CSECURITY_PAGECONTROL1_TSJAMCODE_RGJAMLEVEL", "TRadioGroup", "fSecurity.PageControl1.tsJamCode", "fSecurity.PageControl1.tsJamCode", 7, 3, "SUBDLG", false, true, 92, true, 64, true, 433, true, 45, true, 3, -1, "", "", true, "微軟正黑體", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSecurity.PageControl1.tsJamCode.cbJamArea", "cbJamArea", "IDC_CSECURITY_CBJAMAREA", "TComboBox", "fSecurity.PageControl1.tsJamCode", "fSecurity.PageControl1.tsJamCode", 8, 3, "LEAF", false, true, 92, true, 0, true, 145, true, 28, true, 0, -1, "", "", true, "微軟正黑體", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSecurity.PageControl1.tsJamCode.cbJamCode", "cbJamCode", "IDC_CSECURITY_CBJAMCODE", "TComboBox", "fSecurity.PageControl1.tsJamCode", "fSecurity.PageControl1.tsJamCode", 9, 3, "LEAF", false, true, 92, true, 32, true, 725, true, 28, true, 2, -1, "", "", true, "微軟正黑體", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSecurity.PageControl1.tsJamCode.cbJamLang", "cbJamLang", "IDC_CSECURITY_CBJAMLANG", "TComboBox", "fSecurity.PageControl1.tsJamCode", "fSecurity.PageControl1.tsJamCode", 10, 3, "LEAF", false, true, 88, true, 185, true, 145, true, 28, true, 10, -1, "", "", true, "微軟正黑體", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSecurity.PageControl1.tsJamCode.RichEditJamCode", "RichEditJamCode", "IDC_CSECURITY_RICHEDITJAMCODE", "TRichEdit", "fSecurity.PageControl1.tsJamCode", "fSecurity.PageControl1.tsJamCode", 11, 3, "LEAF", false, true, 0, true, 389, true, 866, true, 298, true, 18, -1, "alBottom", "", true, "MS Sans Serif", -11, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSecurity.PageControl1.tsJamCode.cbJamNeedRed", "cbJamNeedRed", "IDC_CSECURITY_CBJAMNEEDRED", "TCheckBox", "fSecurity.PageControl1.tsJamCode", "fSecurity.PageControl1.tsJamCode", 12, 3, "LEAF", false, true, 560, true, 64, true, 217, true, 17, true, 4, -1, "", "", true, "微軟正黑體", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSecurity.PageControl1.tsJamCode.cbSilentMode", "cbSilentMode", "IDC_CSECURITY_CBSILENTMODE", "TCheckBox", "fSecurity.PageControl1.tsJamCode", "fSecurity.PageControl1.tsJamCode", 13, 3, "LEAF", false, true, 560, true, 88, true, 217, true, 17, true, 5, -1, "", "", true, "微軟正黑體", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSecurity.PageControl1.tsJamCode.cbUnlockPassWord", "cbUnlockPassWord", "IDC_CSECURITY_CBUNLOCKPASSWORD", "TCheckBox", "fSecurity.PageControl1.tsJamCode", "fSecurity.PageControl1.tsJamCode", 14, 3, "LEAF", false, true, 560, true, 112, true, 217, true, 17, true, 6, -1, "", "", true, "微軟正黑體", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSecurity.PageControl1.tsJamCode.rgMachineStatusBit8", "rgMachineStatusBit8", "IDD_CSECURITY_PAGECONTROL1_TSJAMCODE_RGMACHINESTATUSBIT8", "TRadioGroup", "fSecurity.PageControl1.tsJamCode", "fSecurity.PageControl1.tsJamCode", 15, 3, "SUBDLG", false, true, 264, true, 185, true, 207, true, 45, true, 11, -1, "", "", true, "微軟正黑體", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSecurity.PageControl1.tsJamCode.cbIncludeMTBA", "cbIncludeMTBA", "IDC_CSECURITY_CBINCLUDEMTBA", "TCheckBox", "fSecurity.PageControl1.tsJamCode", "fSecurity.PageControl1.tsJamCode", 16, 3, "LEAF", false, true, 560, true, 136, true, 217, true, 17, true, 7, -1, "", "", true, "微軟正黑體", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSecurity.PageControl1.tsJamCode.chkCheckContAlarm", "chkCheckContAlarm", "IDC_CSECURITY_CHKCHECKCONTALARM", "TCheckBox", "fSecurity.PageControl1.tsJamCode", "fSecurity.PageControl1.tsJamCode", 17, 3, "LEAF", false, true, 560, true, 160, true, 277, true, 17, true, 8, -1, "", "", true, "微軟正黑體", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSecurity.PageControl1.tsJamCode.chkO17", "chkO17", "IDC_CSECURITY_CHKO17", "TCheckBox", "fSecurity.PageControl1.tsJamCode", "fSecurity.PageControl1.tsJamCode", 18, 3, "LEAF", false, true, 560, true, 184, true, 277, true, 17, true, 9, -1, "", "", true, "微軟正黑體", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSecurity.PageControl1.tsJamCode.cbAddAlarmLog", "cbAddAlarmLog", "IDC_CSECURITY_CBADDALARMLOG", "TCheckBox", "fSecurity.PageControl1.tsJamCode", "fSecurity.PageControl1.tsJamCode", 19, 3, "LEAF", false, true, 560, true, 208, true, 277, true, 17, true, 12, -1, "", "", true, "微軟正黑體", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSecurity.PageControl1.tsJamCode.cbN27AddBoard", "cbN27AddBoard", "IDC_CSECURITY_CBN27ADDBOARD", "TCheckBox", "fSecurity.PageControl1.tsJamCode", "fSecurity.PageControl1.tsJamCode", 20, 3, "LEAF", false, true, 720, true, 232, true, 145, true, 17, true, 14, -1, "", "", true, "微軟正黑體", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSecurity.PageControl1.tsJamCode.cbN27AlarmSel", "cbN27AlarmSel", "IDC_CSECURITY_CBN27ALARMSEL", "TCheckBox", "fSecurity.PageControl1.tsJamCode", "fSecurity.PageControl1.tsJamCode", 21, 3, "LEAF", false, true, 560, true, 232, true, 153, true, 17, true, 13, -1, "", "", true, "微軟正黑體", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSecurity.PageControl1.tsJamCode.cbN27AlarmSelByArea", "cbN27AlarmSelByArea", "IDC_CSECURITY_CBN27ALARMSELBYAREA", "TCheckBox", "fSecurity.PageControl1.tsJamCode", "fSecurity.PageControl1.tsJamCode", 22, 3, "LEAF", false, true, 248, true, 6, true, 217, true, 17, true, 1, -1, "", "", true, "微軟正黑體", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSecurity.PageControl1.tsJamCode.chkTCPAlarm", "chkTCPAlarm", "IDC_CSECURITY_CHKTCPALARM", "TCheckBox", "fSecurity.PageControl1.tsJamCode", "fSecurity.PageControl1.tsJamCode", 23, 3, "LEAF", false, true, 560, true, 256, true, 113, true, 17, true, 15, -1, "", "", true, "微軟正黑體", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSecurity.PageControl1.tsJamCode.cbContAlarmNotUpload", "cbContAlarmNotUpload", "IDC_CSECURITY_CBCONTALARMNOTUPLOAD", "TCheckBox", "fSecurity.PageControl1.tsJamCode", "fSecurity.PageControl1.tsJamCode", 24, 3, "LEAF", false, true, 244, true, 304, true, 277, true, 17, true, 17, -1, "", "", true, "微軟正黑體", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSecurity.PageControl1.tsJamCode.chkAlarmAfterFullTray", "chkAlarmAfterFullTray", "IDC_CSECURITY_CHKALARMAFTERFULLTRAY", "TCheckBox", "fSecurity.PageControl1.tsJamCode", "fSecurity.PageControl1.tsJamCode", 25, 3, "LEAF", false, true, 560, true, 280, true, 281, true, 17, true, 16, -1, "", "", true, "微軟正黑體", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSecurity.PageControl1.tsStatisticsJam", "tsStatisticsJam", "IDD_CSECURITY_PAGECONTROL1_TSSTATISTICSJAM", "TTabSheet", "fSecurity.PageControl1", "fSecurity", 11, 2, "SUBDLG", false, false, 0, false, 0, false, 0, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSecurity.PageControl1.tsStatisticsJam.sgStatisticsJam", "sgStatisticsJam", "IDC_CSECURITY_SGSTATISTICSJAM", "TStringGrid", "fSecurity.PageControl1.tsStatisticsJam", "fSecurity.PageControl1.tsStatisticsJam", 0, 3, "LEAF", false, true, 0, true, 0, true, 841, true, 554, true, 0, -1, "alClient", "", false, "", 0, "", false, 0, "", true, 14670284, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSecurity.OpenDialog1", "OpenDialog1", "", "TOpenDialog", "fSecurity", "fSecurity", 5, 1, "NONVISUAL", false, true, 776, true, 139, false, 0, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSecurity.SaveDialog1", "SaveDialog1", "", "TSaveDialog", "fSecurity", "fSecurity", 6, 1, "NONVISUAL", false, true, 804, true, 139, false, 0, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
};

const int kcSecurityLayoutCount = 61;

} // namespace ht9045_layout
