// ===========================================================================
//  cTowerLight_layout.gen.cpp
//  DO NOT EDIT -- GENERATED FILE. See the matching _layout.gen.h banner.
// ===========================================================================
#include "cTowerLight_layout.gen.h"

namespace ht9045_layout {

const DfmCustomProp kcTowerLightCustomProps[] = {
    { "LEDStyle", "LEDSqLarge" },
    { "Interval", "300" },
    { "FalseColor", "22272" },
    { "LEDStyle", "LEDSqLarge" },
    { "Interval", "300" },
    { "FalseColor", "22272" },
    { "LEDStyle", "LEDSqLarge" },
    { "Interval", "300" },
    { "FalseColor", "22272" },
    { "LEDStyle", "LEDSqLarge" },
    { "Interval", "300" },
    { "FalseColor", "22272" },
    { "LEDStyle", "LEDSqLarge" },
    { "Interval", "300" },
    { "FalseColor", "22272" },
    { "LEDStyle", "LEDSqLarge" },
    { "Interval", "300" },
    { "FalseColor", "22272" },
    { "LEDStyle", "LEDSqLarge" },
    { "Interval", "300" },
    { "TrueColor", "clYellow" },
    { "FalseColor", "881034" },
    { "LEDStyle", "LEDSqLarge" },
    { "Interval", "300" },
    { "TrueColor", "clYellow" },
    { "FalseColor", "881034" },
    { "LEDStyle", "LEDSqLarge" },
    { "Interval", "300" },
    { "TrueColor", "clYellow" },
    { "FalseColor", "881034" },
    { "LEDStyle", "LEDSqLarge" },
    { "Interval", "300" },
    { "TrueColor", "clYellow" },
    { "FalseColor", "881034" },
    { "LEDStyle", "LEDSqLarge" },
    { "Interval", "300" },
    { "TrueColor", "clYellow" },
    { "FalseColor", "881034" },
    { "LEDStyle", "LEDSqLarge" },
    { "Interval", "300" },
    { "TrueColor", "clYellow" },
    { "FalseColor", "881034" },
    { "LEDStyle", "LEDSqLarge" },
    { "Interval", "300" },
    { "TrueColor", "clRed" },
    { "FalseColor", "clMaroon" },
    { "LEDStyle", "LEDSqLarge" },
    { "Interval", "300" },
    { "TrueColor", "clRed" },
    { "FalseColor", "clMaroon" },
    { "LEDStyle", "LEDSqLarge" },
    { "Interval", "300" },
    { "TrueColor", "clRed" },
    { "FalseColor", "clMaroon" },
    { "LEDStyle", "LEDSqLarge" },
    { "Interval", "300" },
    { "TrueColor", "clRed" },
    { "FalseColor", "clMaroon" },
    { "LEDStyle", "LEDSqLarge" },
    { "Interval", "300" },
    { "TrueColor", "clRed" },
    { "FalseColor", "clMaroon" },
    { "LEDStyle", "LEDSqLarge" },
    { "Interval", "300" },
    { "TrueColor", "clRed" },
    { "FalseColor", "clMaroon" },
    { "LEDStyle", "LEDSqLarge" },
    { "Interval", "300" },
    { "FalseColor", "22272" },
    { "LEDStyle", "LEDSqLarge" },
    { "Interval", "300" },
    { "TrueColor", "clYellow" },
    { "FalseColor", "881034" },
    { "LEDStyle", "LEDSqLarge" },
    { "Interval", "300" },
    { "TrueColor", "clRed" },
    { "FalseColor", "clMaroon" },
    { "LEDStyle", "LEDSqLarge" },
    { "Interval", "300" },
    { "TrueColor", "clRed" },
    { "FalseColor", "clMaroon" },
    { "LEDStyle", "LEDSqLarge" },
    { "Interval", "300" },
    { "TrueColor", "clYellow" },
    { "FalseColor", "881034" },
    { "LEDStyle", "LEDSqLarge" },
    { "Interval", "300" },
    { "FalseColor", "22272" },
};

const DfmControlLayout kcTowerLightLayout[] = {
    { "fTowerLight", "fTowerLight", "", "TfTowerLight", "", "", 0, 0, "ROOT", false, true, 762, true, 160, false, 0, false, 0, false, 0, -1, "", "", true, "MS Sans Serif", -11, "", true, -2147483640, "clWindowText", true, 12761254, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fTowerLight.Panel3", "Panel3", "IDD_CTOWERLIGHT_PANEL3", "TPanel", "fTowerLight", "fTowerLight", 0, 1, "SUBDLG", false, true, 0, true, 33, true, 760, true, 456, true, 1, -1, "alClient", "", false, "", 0, "", false, 0, "", true, 12761254, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fTowerLight.Panel3.RGB50", "RGB50", "IDC_CTOWERLIGHT_RGB50", "TALed", "fTowerLight.Panel3", "fTowerLight.Panel3", 0, 2, "LEAF", true, true, 168, true, 260, true, 22, true, 22, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", true, 22272, "", false, 0, "", false, 0, "", 3, &kcTowerLightCustomProps[0] },
    { "fTowerLight.Panel3.RGB40", "RGB40", "IDC_CTOWERLIGHT_RGB40", "TALed", "fTowerLight.Panel3", "fTowerLight.Panel3", 1, 2, "LEAF", true, true, 168, true, 219, true, 22, true, 22, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", true, 22272, "", false, 0, "", false, 0, "", 3, &kcTowerLightCustomProps[3] },
    { "fTowerLight.Panel3.RGB30", "RGB30", "IDC_CTOWERLIGHT_RGB30", "TALed", "fTowerLight.Panel3", "fTowerLight.Panel3", 2, 2, "LEAF", true, true, 168, true, 177, true, 22, true, 22, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", true, 22272, "", false, 0, "", false, 0, "", 3, &kcTowerLightCustomProps[6] },
    { "fTowerLight.Panel3.RGB20", "RGB20", "IDC_CTOWERLIGHT_RGB20", "TALed", "fTowerLight.Panel3", "fTowerLight.Panel3", 3, 2, "LEAF", true, true, 168, true, 136, true, 22, true, 22, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", true, 22272, "", false, 0, "", false, 0, "", 3, &kcTowerLightCustomProps[9] },
    { "fTowerLight.Panel3.RGB10", "RGB10", "IDC_CTOWERLIGHT_RGB10", "TALed", "fTowerLight.Panel3", "fTowerLight.Panel3", 4, 2, "LEAF", true, true, 168, true, 95, true, 22, true, 22, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", true, 22272, "", false, 0, "", false, 0, "", 3, &kcTowerLightCustomProps[12] },
    { "fTowerLight.Panel3.RGB00", "RGB00", "IDC_CTOWERLIGHT_RGB00", "TALed", "fTowerLight.Panel3", "fTowerLight.Panel3", 5, 2, "LEAF", true, true, 168, true, 54, true, 22, true, 22, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", true, 22272, "", false, 0, "", false, 0, "", 3, &kcTowerLightCustomProps[15] },
    { "fTowerLight.Panel3.RGB01", "RGB01", "IDC_CTOWERLIGHT_RGB01", "TALed", "fTowerLight.Panel3", "fTowerLight.Panel3", 6, 2, "LEAF", true, true, 224, true, 55, true, 22, true, 22, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", true, 65535, "clYellow", true, 881034, "", false, 0, "", false, 0, "", 4, &kcTowerLightCustomProps[18] },
    { "fTowerLight.Panel3.RGB11", "RGB11", "IDC_CTOWERLIGHT_RGB11", "TALed", "fTowerLight.Panel3", "fTowerLight.Panel3", 7, 2, "LEAF", true, true, 224, true, 95, true, 22, true, 22, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", true, 65535, "clYellow", true, 881034, "", false, 0, "", false, 0, "", 4, &kcTowerLightCustomProps[22] },
    { "fTowerLight.Panel3.RGB21", "RGB21", "IDC_CTOWERLIGHT_RGB21", "TALed", "fTowerLight.Panel3", "fTowerLight.Panel3", 8, 2, "LEAF", true, true, 224, true, 136, true, 22, true, 22, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", true, 65535, "clYellow", true, 881034, "", false, 0, "", false, 0, "", 4, &kcTowerLightCustomProps[26] },
    { "fTowerLight.Panel3.RGB31", "RGB31", "IDC_CTOWERLIGHT_RGB31", "TALed", "fTowerLight.Panel3", "fTowerLight.Panel3", 9, 2, "LEAF", true, true, 224, true, 177, true, 22, true, 22, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", true, 65535, "clYellow", true, 881034, "", false, 0, "", false, 0, "", 4, &kcTowerLightCustomProps[30] },
    { "fTowerLight.Panel3.RGB41", "RGB41", "IDC_CTOWERLIGHT_RGB41", "TALed", "fTowerLight.Panel3", "fTowerLight.Panel3", 10, 2, "LEAF", true, true, 224, true, 219, true, 22, true, 22, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", true, 65535, "clYellow", true, 881034, "", false, 0, "", false, 0, "", 4, &kcTowerLightCustomProps[34] },
    { "fTowerLight.Panel3.RGB51", "RGB51", "IDC_CTOWERLIGHT_RGB51", "TALed", "fTowerLight.Panel3", "fTowerLight.Panel3", 11, 2, "LEAF", true, true, 224, true, 260, true, 22, true, 22, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", true, 65535, "clYellow", true, 881034, "", false, 0, "", false, 0, "", 4, &kcTowerLightCustomProps[38] },
    { "fTowerLight.Panel3.RGB52", "RGB52", "IDC_CTOWERLIGHT_RGB52", "TALed", "fTowerLight.Panel3", "fTowerLight.Panel3", 12, 2, "LEAF", true, true, 280, true, 260, true, 22, true, 22, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", true, 255, "clRed", true, 128, "clMaroon", false, 0, "", false, 0, "", 4, &kcTowerLightCustomProps[42] },
    { "fTowerLight.Panel3.RGB42", "RGB42", "IDC_CTOWERLIGHT_RGB42", "TALed", "fTowerLight.Panel3", "fTowerLight.Panel3", 13, 2, "LEAF", true, true, 279, true, 218, true, 22, true, 22, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", true, 255, "clRed", true, 128, "clMaroon", false, 0, "", false, 0, "", 4, &kcTowerLightCustomProps[46] },
    { "fTowerLight.Panel3.RGB32", "RGB32", "IDC_CTOWERLIGHT_RGB32", "TALed", "fTowerLight.Panel3", "fTowerLight.Panel3", 14, 2, "LEAF", true, true, 280, true, 177, true, 22, true, 22, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", true, 255, "clRed", true, 128, "clMaroon", false, 0, "", false, 0, "", 4, &kcTowerLightCustomProps[50] },
    { "fTowerLight.Panel3.RGB22", "RGB22", "IDC_CTOWERLIGHT_RGB22", "TALed", "fTowerLight.Panel3", "fTowerLight.Panel3", 15, 2, "LEAF", true, true, 280, true, 136, true, 22, true, 22, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", true, 255, "clRed", true, 128, "clMaroon", false, 0, "", false, 0, "", 4, &kcTowerLightCustomProps[54] },
    { "fTowerLight.Panel3.RGB12", "RGB12", "IDC_CTOWERLIGHT_RGB12", "TALed", "fTowerLight.Panel3", "fTowerLight.Panel3", 16, 2, "LEAF", true, true, 280, true, 95, true, 22, true, 22, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", true, 255, "clRed", true, 128, "clMaroon", false, 0, "", false, 0, "", 4, &kcTowerLightCustomProps[58] },
    { "fTowerLight.Panel3.RGB02", "RGB02", "IDC_CTOWERLIGHT_RGB02", "TALed", "fTowerLight.Panel3", "fTowerLight.Panel3", 17, 2, "LEAF", true, true, 280, true, 54, true, 22, true, 22, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", true, 255, "clRed", true, 128, "clMaroon", false, 0, "", false, 0, "", 4, &kcTowerLightCustomProps[62] },
    { "fTowerLight.Panel3.Label2", "Label2", "IDC_CTOWERLIGHT_LABEL2", "TLabel", "fTowerLight.Panel3", "fTowerLight.Panel3", 18, 2, "LEAF", true, true, 164, true, 24, true, 29, true, 13, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fTowerLight.Panel3.Label3", "Label3", "IDC_CTOWERLIGHT_LABEL3", "TLabel", "fTowerLight.Panel3", "fTowerLight.Panel3", 19, 2, "LEAF", true, true, 219, true, 24, true, 31, true, 13, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fTowerLight.Panel3.Label4", "Label4", "IDC_CTOWERLIGHT_LABEL4", "TLabel", "fTowerLight.Panel3", "fTowerLight.Panel3", 20, 2, "LEAF", true, true, 281, true, 24, true, 20, true, 13, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fTowerLight.Panel3.Label6", "Label6", "IDC_CTOWERLIGHT_LABEL6", "TLabel", "fTowerLight.Panel3", "fTowerLight.Panel3", 21, 2, "LEAF", true, true, 344, true, 24, true, 61, true, 13, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fTowerLight.Panel3.Bevel1", "Bevel1", "IDC_CTOWERLIGHT_BEVEL1", "TBevel", "fTowerLight.Panel3", "fTowerLight.Panel3", 22, 2, "LEAF", true, true, 177, true, 362, true, 7, true, 50, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fTowerLight.Panel3.Bevel2", "Bevel2", "IDC_CTOWERLIGHT_BEVEL2", "TBevel", "fTowerLight.Panel3", "fTowerLight.Panel3", 23, 2, "LEAF", true, true, 233, true, 362, true, 7, true, 50, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fTowerLight.Panel3.Bevel3", "Bevel3", "IDC_CTOWERLIGHT_BEVEL3", "TBevel", "fTowerLight.Panel3", "fTowerLight.Panel3", 24, 2, "LEAF", true, true, 289, true, 362, true, 7, true, 50, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fTowerLight.Panel3.Bevel4", "Bevel4", "IDC_CTOWERLIGHT_BEVEL4", "TBevel", "fTowerLight.Panel3", "fTowerLight.Panel3", 25, 2, "LEAF", true, true, 177, true, 362, true, 134, true, 51, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fTowerLight.Panel3.Label43", "Label43", "IDC_CTOWERLIGHT_LABEL43", "TLabel", "fTowerLight.Panel3", "fTowerLight.Panel3", 26, 2, "LEAF", true, true, 316, true, 406, true, 74, true, 13, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fTowerLight.Panel3.RGB60", "RGB60", "IDC_CTOWERLIGHT_RGB60", "TALed", "fTowerLight.Panel3", "fTowerLight.Panel3", 27, 2, "LEAF", true, true, 168, true, 300, true, 22, true, 22, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", true, 22272, "", false, 0, "", false, 0, "", 3, &kcTowerLightCustomProps[66] },
    { "fTowerLight.Panel3.RGB61", "RGB61", "IDC_CTOWERLIGHT_RGB61", "TALed", "fTowerLight.Panel3", "fTowerLight.Panel3", 28, 2, "LEAF", true, true, 224, true, 300, true, 22, true, 22, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", true, 65535, "clYellow", true, 881034, "", false, 0, "", false, 0, "", 4, &kcTowerLightCustomProps[69] },
    { "fTowerLight.Panel3.RGB62", "RGB62", "IDC_CTOWERLIGHT_RGB62", "TALed", "fTowerLight.Panel3", "fTowerLight.Panel3", 29, 2, "LEAF", true, true, 280, true, 300, true, 22, true, 22, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", true, 255, "clRed", true, 128, "clMaroon", false, 0, "", false, 0, "", 4, &kcTowerLightCustomProps[73] },
    { "fTowerLight.Panel3.Panel4", "Panel4", "IDC_CTOWERLIGHT_PANEL4", "TPanel", "fTowerLight.Panel3", "fTowerLight.Panel3", 30, 2, "LEAF", false, true, 40, true, 48, true, 121, true, 33, true, 0, -1, "", "", true, "MS Sans Serif", -15, "", true, 16777215, "clWhite", true, 9534289, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fTowerLight.Panel3.Panel5", "Panel5", "IDC_CTOWERLIGHT_PANEL5", "TPanel", "fTowerLight.Panel3", "fTowerLight.Panel3", 31, 2, "LEAF", false, true, 40, true, 89, true, 121, true, 33, true, 3, -1, "", "", true, "MS Sans Serif", -15, "", true, 16777215, "clWhite", true, 9534289, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fTowerLight.Panel3.Panel6", "Panel6", "IDC_CTOWERLIGHT_PANEL6", "TPanel", "fTowerLight.Panel3", "fTowerLight.Panel3", 32, 2, "LEAF", false, true, 40, true, 130, true, 121, true, 33, true, 5, -1, "", "", true, "MS Sans Serif", -15, "", true, 16777215, "clWhite", true, 9534289, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fTowerLight.Panel3.Panel7", "Panel7", "IDC_CTOWERLIGHT_PANEL7", "TPanel", "fTowerLight.Panel3", "fTowerLight.Panel3", 33, 2, "LEAF", false, true, 40, true, 171, true, 121, true, 33, true, 7, -1, "", "", true, "MS Sans Serif", -15, "", true, 16777215, "clWhite", true, 9534289, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fTowerLight.Panel3.Panel8", "Panel8", "IDC_CTOWERLIGHT_PANEL8", "TPanel", "fTowerLight.Panel3", "fTowerLight.Panel3", 34, 2, "LEAF", false, true, 40, true, 213, true, 121, true, 33, true, 9, -1, "", "", true, "MS Sans Serif", -15, "", true, 16777215, "clWhite", true, 9534289, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fTowerLight.Panel3.Panel9", "Panel9", "IDC_CTOWERLIGHT_PANEL9", "TPanel", "fTowerLight.Panel3", "fTowerLight.Panel3", 35, 2, "LEAF", false, true, 40, true, 254, true, 121, true, 33, true, 11, -1, "", "", true, "MS Sans Serif", -15, "", true, 16777215, "clWhite", true, 9534289, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fTowerLight.Panel3.cbRunning", "cbRunning", "IDC_CTOWERLIGHT_CBRUNNING", "TComboBox", "fTowerLight.Panel3", "fTowerLight.Panel3", 36, 2, "LEAF", false, true, 344, true, 50, true, 89, true, 21, true, 1, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fTowerLight.Panel3.cbJam", "cbJam", "IDC_CTOWERLIGHT_CBJAM", "TComboBox", "fTowerLight.Panel3", "fTowerLight.Panel3", 37, 2, "LEAF", false, true, 344, true, 92, true, 89, true, 21, true, 4, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fTowerLight.Panel3.cbPause", "cbPause", "IDC_CTOWERLIGHT_CBPAUSE", "TComboBox", "fTowerLight.Panel3", "fTowerLight.Panel3", 38, 2, "LEAF", false, true, 344, true, 133, true, 89, true, 21, true, 6, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fTowerLight.Panel3.cbMessage", "cbMessage", "IDC_CTOWERLIGHT_CBMESSAGE", "TComboBox", "fTowerLight.Panel3", "fTowerLight.Panel3", 39, 2, "LEAF", false, true, 344, true, 174, true, 89, true, 21, true, 8, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fTowerLight.Panel3.cbHeating", "cbHeating", "IDC_CTOWERLIGHT_CBHEATING", "TComboBox", "fTowerLight.Panel3", "fTowerLight.Panel3", 40, 2, "LEAF", false, true, 344, true, 216, true, 89, true, 21, true, 10, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fTowerLight.Panel3.cbHome", "cbHome", "IDC_CTOWERLIGHT_CBHOME", "TComboBox", "fTowerLight.Panel3", "fTowerLight.Panel3", 41, 2, "LEAF", false, true, 344, true, 257, true, 89, true, 21, true, 12, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fTowerLight.Panel3.rgMusicTest", "rgMusicTest", "IDD_CTOWERLIGHT_PANEL3_RGMUSICTEST", "TRadioGroup", "fTowerLight.Panel3", "fTowerLight.Panel3", 42, 2, "SUBDLG", false, true, 520, true, 56, true, 185, true, 225, true, 2, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fTowerLight.Panel3.Panel1", "Panel1", "IDC_CTOWERLIGHT_PANEL1", "TPanel", "fTowerLight.Panel3", "fTowerLight.Panel3", 43, 2, "LEAF", false, true, 40, true, 294, true, 121, true, 33, true, 13, -1, "", "", true, "MS Sans Serif", -15, "", true, 16777215, "clWhite", true, 9534289, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fTowerLight.Panel3.cbOffLine", "cbOffLine", "IDC_CTOWERLIGHT_CBOFFLINE", "TComboBox", "fTowerLight.Panel3", "fTowerLight.Panel3", 44, 2, "LEAF", false, true, 344, true, 297, true, 89, true, 21, true, 14, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fTowerLight.Panel3.Panel11", "Panel11", "IDD_CTOWERLIGHT_PANEL3_PANEL11", "TPanel", "fTowerLight.Panel3", "fTowerLight.Panel3", 45, 2, "SUBDLG", false, true, 40, true, 332, true, 405, true, 33, true, 15, -1, "", "", false, "", 0, "", false, 0, "", true, 12761254, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fTowerLight.Panel3.Panel11.RGB72", "RGB72", "IDC_CTOWERLIGHT_RGB72", "TALed", "fTowerLight.Panel3.Panel11", "fTowerLight.Panel3.Panel11", 0, 3, "LEAF", true, true, 240, true, 8, true, 22, true, 22, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", true, 255, "clRed", true, 128, "clMaroon", false, 0, "", false, 0, "", 4, &kcTowerLightCustomProps[77] },
    { "fTowerLight.Panel3.Panel11.RGB71", "RGB71", "IDC_CTOWERLIGHT_RGB71", "TALed", "fTowerLight.Panel3.Panel11", "fTowerLight.Panel3.Panel11", 1, 3, "LEAF", true, true, 184, true, 8, true, 22, true, 22, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", true, 65535, "clYellow", true, 881034, "", false, 0, "", false, 0, "", 4, &kcTowerLightCustomProps[81] },
    { "fTowerLight.Panel3.Panel11.RGB70", "RGB70", "IDC_CTOWERLIGHT_RGB70", "TALed", "fTowerLight.Panel3.Panel11", "fTowerLight.Panel3.Panel11", 2, 3, "LEAF", true, true, 128, true, 8, true, 22, true, 22, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", true, 22272, "", false, 0, "", false, 0, "", 3, &kcTowerLightCustomProps[85] },
    { "fTowerLight.Panel3.Panel11.cbART", "cbART", "IDC_CTOWERLIGHT_CBART", "TComboBox", "fTowerLight.Panel3.Panel11", "fTowerLight.Panel3.Panel11", 3, 3, "LEAF", false, true, 304, true, 5, true, 89, true, 21, true, 1, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fTowerLight.Panel3.Panel11.palART", "palART", "IDC_CTOWERLIGHT_PALART", "TPanel", "fTowerLight.Panel3.Panel11", "fTowerLight.Panel3.Panel11", 4, 3, "LEAF", false, true, 0, true, 2, true, 121, true, 33, true, 0, -1, "", "", true, "MS Sans Serif", -15, "", true, 16777215, "clWhite", true, 9534289, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fTowerLight.Panel2", "Panel2", "IDC_CTOWERLIGHT_PANEL2", "TPanel", "fTowerLight", "fTowerLight", 1, 1, "LEAF", false, true, 0, true, 0, true, 760, true, 33, true, 0, -1, "alTop", "", true, "Arial", -16, "", true, 16777215, "clWhite", true, 9534289, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fTowerLight.spbExit", "spbExit", "IDC_CTOWERLIGHT_SPBEXIT", "TPanel", "fTowerLight", "fTowerLight", 2, 1, "LEAF", false, true, 0, true, 489, true, 760, true, 41, true, 2, -1, "alBottom", "", true, "Arial", -19, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fTowerLight.Timer1", "Timer1", "", "TTimer", "fTowerLight", "fTowerLight", 3, 1, "NONVISUAL", false, true, 516, true, 32, false, 0, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
};

const int kcTowerLightLayoutCount = 56;

} // namespace ht9045_layout
