// ===========================================================================
//  DIOInterFaceCFG_layout.gen.cpp
//  DO NOT EDIT -- GENERATED FILE. See the matching _layout.gen.h banner.
// ===========================================================================
#include "DIOInterFaceCFG_layout.gen.h"

namespace ht9045_layout {

// (no custom-control properties in this form)

const DfmControlLayout kDIOInterFaceCFGLayout[] = {
    { "fDIOFrom", "fDIOFrom", "", "TfDIOFrom", "", "", 0, 0, "ROOT", false, true, 208, true, 328, false, 0, false, 0, false, 0, -1, "", "", true, "MS Sans Serif", -11, "", true, -2147483640, "clWindowText", true, 12761254, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fDIOFrom.GroupBox3", "GroupBox3", "IDD_DIOINTERFACECFG_GROUPBOX3", "TGroupBox", "fDIOFrom", "fDIOFrom", 0, 1, "SUBDLG", false, true, 289, true, 0, true, 309, true, 357, true, 1, -1, "alRight", "", true, "Arial", -15, "", true, 8388608, "clNavy", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fDIOFrom.GroupBox3.rgBinLogic", "rgBinLogic", "IDD_DIOINTERFACECFG_GROUPBOX3_RGBINLOGIC", "TRadioGroup", "fDIOFrom.GroupBox3", "fDIOFrom.GroupBox3", 0, 2, "SUBDLG", false, true, 23, true, 18, true, 257, true, 50, true, 0, -1, "", "", true, "Arial", -15, "", true, 0, "clBlack", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fDIOFrom.GroupBox3.rgBinBitLength", "rgBinBitLength", "IDD_DIOINTERFACECFG_GROUPBOX3_RGBINBITLENGTH", "TRadioGroup", "fDIOFrom.GroupBox3", "fDIOFrom.GroupBox3", 1, 2, "SUBDLG", false, true, 23, true, 89, true, 257, true, 151, true, 1, -1, "", "", true, "Arial", -15, "", true, 0, "clBlack", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fDIOFrom.GroupBox3.rgBinDataType", "rgBinDataType", "IDD_DIOINTERFACECFG_GROUPBOX3_RGBINDATATYPE", "TRadioGroup", "fDIOFrom.GroupBox3", "fDIOFrom.GroupBox3", 2, 2, "SUBDLG", false, true, 23, true, 264, true, 257, true, 63, true, 2, -1, "", "", true, "Arial", -15, "", true, 0, "clBlack", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fDIOFrom.GroupBox4", "GroupBox4", "IDD_DIOINTERFACECFG_GROUPBOX4", "TGroupBox", "fDIOFrom", "fDIOFrom", 1, 1, "SUBDLG", false, true, 0, true, 357, true, 598, true, 71, true, 2, -1, "alBottom", "", true, "Arial", -15, "", true, 8388608, "clNavy", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fDIOFrom.GroupBox4.Label6", "Label6", "IDC_DIOINTERFACECFG_LABEL6", "TLabel", "fDIOFrom.GroupBox4", "fDIOFrom.GroupBox4", 0, 2, "LEAF", true, true, 14, true, 31, true, 76, true, 18, false, 0, -1, "", "", true, "Arial", -15, "", true, 0, "clBlack", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fDIOFrom.GroupBox4.spbSave", "spbSave", "IDC_DIOINTERFACECFG_SPBSAVE", "TSpeedButton", "fDIOFrom.GroupBox4", "fDIOFrom.GroupBox4", 1, 2, "LEAF", true, true, 283, true, 19, true, 100, true, 40, false, 0, -1, "", "", true, "Arial", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fDIOFrom.GroupBox4.spbLoad", "spbLoad", "IDC_DIOINTERFACECFG_SPBLOAD", "TSpeedButton", "fDIOFrom.GroupBox4", "fDIOFrom.GroupBox4", 2, 2, "LEAF", true, true, 388, true, 20, true, 100, true, 40, false, 0, -1, "", "", true, "Arial", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fDIOFrom.GroupBox4.spbDelete", "spbDelete", "IDC_DIOINTERFACECFG_SPBDELETE", "TSpeedButton", "fDIOFrom.GroupBox4", "fDIOFrom.GroupBox4", 3, 2, "LEAF", true, true, 496, true, 20, true, 100, true, 40, false, 0, -1, "", "", true, "Arial", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fDIOFrom.GroupBox4.edTTLModeName", "edTTLModeName", "IDC_DIOINTERFACECFG_EDTTLMODENAME", "TEdit", "fDIOFrom.GroupBox4", "fDIOFrom.GroupBox4", 4, 2, "LEAF", false, true, 89, true, 25, true, 157, true, 25, true, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fDIOFrom.spbExit", "spbExit", "IDC_DIOINTERFACECFG_SPBEXIT", "TPanel", "fDIOFrom", "fDIOFrom", 2, 1, "LEAF", false, true, 0, true, 428, true, 598, true, 41, true, 3, -1, "alBottom", "", true, "Arial", -19, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fDIOFrom.Panel1", "Panel1", "IDD_DIOINTERFACECFG_PANEL1", "TPanel", "fDIOFrom", "fDIOFrom", 3, 1, "SUBDLG", false, true, 0, true, 0, true, 289, true, 357, true, 0, -1, "alClient", "", false, "", 0, "", false, 0, "", true, 12761254, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fDIOFrom.Panel1.GroupBox2", "GroupBox2", "IDD_DIOINTERFACECFG_PANEL1_GROUPBOX2", "TGroupBox", "fDIOFrom.Panel1", "fDIOFrom.Panel1", 0, 2, "SUBDLG", false, true, 0, true, 205, true, 289, true, 152, true, 1, -1, "alClient", "", true, "Arial", -15, "", true, 8388608, "clNavy", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fDIOFrom.Panel1.GroupBox2.Label1", "Label1", "IDC_DIOINTERFACECFG_LABEL1", "TLabel", "fDIOFrom.Panel1.GroupBox2", "fDIOFrom.Panel1.GroupBox2", 0, 3, "LEAF", true, true, 14, true, 111, true, 102, true, 18, false, 0, -1, "", "", true, "Arial", -15, "", true, 0, "clBlack", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fDIOFrom.Panel1.GroupBox2.Label2", "Label2", "IDC_DIOINTERFACECFG_LABEL2", "TLabel", "fDIOFrom.Panel1.GroupBox2", "fDIOFrom.Panel1.GroupBox2", 1, 3, "LEAF", true, true, 207, true, 104, true, 37, true, 17, false, 0, -1, "", "", true, "Arial", -15, "", true, 0, "clBlack", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fDIOFrom.Panel1.GroupBox2.Label3", "Label3", "IDC_DIOINTERFACECFG_LABEL3", "TLabel", "fDIOFrom.Panel1.GroupBox2", "fDIOFrom.Panel1.GroupBox2", 2, 3, "LEAF", true, true, 14, true, 70, true, 117, true, 18, false, 0, -1, "", "", true, "Arial", -15, "", true, 0, "clBlack", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fDIOFrom.Panel1.GroupBox2.Label4", "Label4", "IDC_DIOINTERFACECFG_LABEL4", "TLabel", "fDIOFrom.Panel1.GroupBox2", "fDIOFrom.Panel1.GroupBox2", 3, 3, "LEAF", true, true, 206, true, 66, true, 37, true, 17, false, 0, -1, "", "", true, "Arial", -15, "", true, 0, "clBlack", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fDIOFrom.Panel1.GroupBox2.Label5", "Label5", "IDC_DIOINTERFACECFG_LABEL5", "TLabel", "fDIOFrom.Panel1.GroupBox2", "fDIOFrom.Panel1.GroupBox2", 4, 3, "LEAF", true, true, 14, true, 29, true, 59, true, 18, false, 0, -1, "", "", true, "Arial", -15, "", true, 0, "clBlack", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fDIOFrom.Panel1.GroupBox2.edSignalAfterOff", "edSignalAfterOff", "IDC_DIOINTERFACECFG_EDSIGNALAFTEROFF", "TEdit", "fDIOFrom.Panel1.GroupBox2", "fDIOFrom.Panel1.GroupBox2", 5, 3, "LEAF", false, true, 99, true, 101, true, 92, true, 25, true, 2, -1, "", "", true, "Arial", -15, "", true, 0, "clBlack", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fDIOFrom.Panel1.GroupBox2.cbSignalType", "cbSignalType", "IDC_DIOINTERFACECFG_CBSIGNALTYPE", "TComboBox", "fDIOFrom.Panel1.GroupBox2", "fDIOFrom.Panel1.GroupBox2", 6, 3, "LEAF", false, true, 68, true, 27, true, 178, true, 25, true, 0, -1, "", "", true, "Arial", -15, "", true, 0, "clBlack", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fDIOFrom.Panel1.GroupBox2.edSignalBeforeOn", "edSignalBeforeOn", "IDC_DIOINTERFACECFG_EDSIGNALBEFOREON", "TEdit", "fDIOFrom.Panel1.GroupBox2", "fDIOFrom.Panel1.GroupBox2", 7, 3, "LEAF", false, true, 99, true, 64, true, 92, true, 25, true, 1, -1, "", "", true, "Arial", -15, "", true, 0, "clBlack", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fDIOFrom.Panel1.GroupBox1", "GroupBox1", "IDD_DIOINTERFACECFG_PANEL1_GROUPBOX1", "TGroupBox", "fDIOFrom.Panel1", "fDIOFrom.Panel1", 1, 2, "SUBDLG", false, true, 0, true, 0, true, 289, true, 205, true, 0, -1, "alTop", "", true, "Arial", -15, "", true, 8388608, "clNavy", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fDIOFrom.Panel1.GroupBox1.Label52", "Label52", "IDC_DIOINTERFACECFG_LABEL52", "TLabel", "fDIOFrom.Panel1.GroupBox1", "fDIOFrom.Panel1.GroupBox1", 0, 3, "LEAF", true, true, 23, true, 165, true, 84, true, 19, false, 0, -1, "", "", true, "Arial", -15, "", true, 0, "clBlack", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fDIOFrom.Panel1.GroupBox1.Label55", "Label55", "IDC_DIOINTERFACECFG_LABEL55", "TLabel", "fDIOFrom.Panel1.GroupBox1", "fDIOFrom.Panel1.GroupBox1", 1, 3, "LEAF", true, true, 237, true, 164, true, 37, true, 17, false, 0, -1, "", "", true, "Arial", -15, "", true, 0, "clBlack", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fDIOFrom.Panel1.GroupBox1.rgStartLogic", "rgStartLogic", "IDD_DIOINTERFACECFG_PANEL1_GROUPBOX1_RGSTARTLOGIC", "TRadioGroup", "fDIOFrom.Panel1.GroupBox1", "fDIOFrom.Panel1.GroupBox1", 2, 3, "SUBDLG", false, true, 23, true, 20, true, 239, true, 65, true, 0, -1, "", "", true, "Arial", -15, "", true, 0, "clBlack", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fDIOFrom.Panel1.GroupBox1.rgStartChannel", "rgStartChannel", "IDD_DIOINTERFACECFG_PANEL1_GROUPBOX1_RGSTARTCHANNEL", "TRadioGroup", "fDIOFrom.Panel1.GroupBox1", "fDIOFrom.Panel1.GroupBox1", 3, 3, "SUBDLG", false, true, 23, true, 90, true, 239, true, 61, true, 1, -1, "", "", true, "Arial", -15, "", true, 0, "clBlack", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fDIOFrom.Panel1.GroupBox1.edPulseWidth", "edPulseWidth", "IDC_DIOINTERFACECFG_EDPULSEWIDTH", "TEdit", "fDIOFrom.Panel1.GroupBox1", "fDIOFrom.Panel1.GroupBox1", 4, 3, "LEAF", false, true, 111, true, 163, true, 113, true, 25, true, 3, -1, "", "", true, "Arial", -15, "", true, 0, "clBlack", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fDIOFrom.Panel1.GroupBox1.cbOneSTChannel", "cbOneSTChannel", "IDC_DIOINTERFACECFG_CBONESTCHANNEL", "TComboBox", "fDIOFrom.Panel1.GroupBox1", "fDIOFrom.Panel1.GroupBox1", 5, 3, "LEAF", false, true, 206, true, 115, true, 50, true, 25, true, 2, -1, "", "", true, "Arial", -15, "", true, 8388608, "clNavy", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fDIOFrom.OpenDialog1", "OpenDialog1", "", "TOpenDialog", "fDIOFrom", "fDIOFrom", 4, 1, "NONVISUAL", false, true, 515, true, 4, false, 0, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fDIOFrom.SaveDialog1", "SaveDialog1", "", "TSaveDialog", "fDIOFrom", "fDIOFrom", 5, 1, "NONVISUAL", false, true, 542, true, 4, false, 0, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
};

const int kDIOInterFaceCFGLayoutCount = 31;

} // namespace ht9045_layout
