// ===========================================================================
//  FixAICCD_layout.gen.cpp
//  DO NOT EDIT -- GENERATED FILE. See the matching _layout.gen.h banner.
// ===========================================================================
#include "FixAICCD_layout.gen.h"

namespace ht9045_layout {

// (no custom-control properties in this form)

const DfmControlLayout kFixAICCDLayout[] = {
    { "fFixAICCD", "fFixAICCD", "", "TfFixAICCD", "", "", 0, 0, "ROOT", false, true, 326, true, 174, true, 1011, true, 675, false, 0, -1, "", "", true, "MS Sans Serif", -11, "", true, -2147483640, "clWindowText", true, 12761254, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fFixAICCD.PageControl1", "PageControl1", "IDC_FIXAICCD_PAGECONTROL1", "TPageControl", "fFixAICCD", "fFixAICCD", 0, 1, "TABHOST", false, true, 0, true, 0, true, 995, true, 592, true, 0, -1, "alClient", "", true, "MS Sans Serif", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fFixAICCD.PageControl1.tsTraySetting", "tsTraySetting", "IDD_FIXAICCD_PAGECONTROL1_TSTRAYSETTING", "TTabSheet", "fFixAICCD.PageControl1", "fFixAICCD", 0, 2, "SUBDLG", false, false, 0, false, 0, false, 0, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fFixAICCD.PageControl1.tsTraySetting.lbllFix2AICCDGetResultTimeOut", "lbllFix2AICCDGetResultTimeOut", "IDC_FIXAICCD_LBLLFIX2AICCDGETRESULTTIMEOUT", "TLabel", "fFixAICCD.PageControl1.tsTraySetting", "fFixAICCD.PageControl1.tsTraySetting", 0, 3, "LEAF", true, true, 14, true, 376, true, 174, true, 20, false, 0, -1, "", "", true, "MS Sans Serif", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fFixAICCD.PageControl1.tsTraySetting.lblFix2AICCDStartDelay", "lblFix2AICCDStartDelay", "IDC_FIXAICCD_LBLFIX2AICCDSTARTDELAY", "TLabel", "fFixAICCD.PageControl1.tsTraySetting", "fFixAICCD.PageControl1.tsTraySetting", 1, 3, "LEAF", true, true, 14, true, 251, true, 153, true, 20, false, 0, -1, "", "", true, "MS Sans Serif", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fFixAICCD.PageControl1.tsTraySetting.lablFix2AICCDAutoRetry", "lablFix2AICCDAutoRetry", "IDC_FIXAICCD_LABLFIX2AICCDAUTORETRY", "TLabel", "fFixAICCD.PageControl1.tsTraySetting", "fFixAICCD.PageControl1.tsTraySetting", 2, 3, "LEAF", true, true, 14, true, 314, true, 121, true, 20, false, 0, -1, "", "", true, "MS Sans Serif", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fFixAICCD.PageControl1.tsTraySetting.lbllFix2AICCDExposureTimeOut", "lbllFix2AICCDExposureTimeOut", "IDC_FIXAICCD_LBLLFIX2AICCDEXPOSURETIMEOUT", "TLabel", "fFixAICCD.PageControl1.tsTraySetting", "fFixAICCD.PageControl1.tsTraySetting", 3, 3, "LEAF", true, true, 14, true, 283, true, 171, true, 20, false, 0, -1, "", "", true, "MS Sans Serif", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fFixAICCD.PageControl1.tsTraySetting.lablFix2AICCDInspectCycle", "lablFix2AICCDInspectCycle", "IDC_FIXAICCD_LABLFIX2AICCDINSPECTCYCLE", "TLabel", "fFixAICCD.PageControl1.tsTraySetting", "fFixAICCD.PageControl1.tsTraySetting", 4, 3, "LEAF", true, true, 14, true, 407, true, 190, true, 20, false, 0, -1, "", "", true, "MS Sans Serif", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fFixAICCD.PageControl1.tsTraySetting.lablFix2AICCDInspectCycleCounter", "lablFix2AICCDInspectCycleCounter", "IDC_FIXAICCD_LABLFIX2AICCDINSPECTCYCLECOUNTER", "TLabel", "fFixAICCD.PageControl1.tsTraySetting", "fFixAICCD.PageControl1.tsTraySetting", 5, 3, "LEAF", true, true, 334, true, 407, true, 9, true, 20, false, 0, -1, "", "", true, "MS Sans Serif", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fFixAICCD.PageControl1.tsTraySetting.lblInspectResultThres", "lblInspectResultThres", "IDC_FIXAICCD_LBLINSPECTRESULTTHRES", "TLabel", "fFixAICCD.PageControl1.tsTraySetting", "fFixAICCD.PageControl1.tsTraySetting", 6, 3, "LEAF", true, true, 14, true, 345, true, 185, true, 20, false, 0, -1, "", "", true, "MS Sans Serif", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fFixAICCD.PageControl1.tsTraySetting.Label3", "Label3", "IDC_FIXAICCD_LABEL3", "TLabel", "fFixAICCD.PageControl1.tsTraySetting", "fFixAICCD.PageControl1.tsTraySetting", 7, 3, "LEAF", true, true, 38, true, 87, true, 350, true, 19, false, 0, -1, "", "", true, "微軟正黑體", -15, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fFixAICCD.PageControl1.tsTraySetting.edtlFix2AICCDGetResultTimeOut", "edtlFix2AICCDGetResultTimeOut", "IDC_FIXAICCD_EDTLFIX2AICCDGETRESULTTIMEOUT", "TEdit", "fFixAICCD.PageControl1.tsTraySetting", "fFixAICCD.PageControl1.tsTraySetting", 8, 3, "LEAF", false, true, 242, true, 372, true, 81, true, 28, true, 7, -1, "", "", true, "MS Sans Serif", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fFixAICCD.PageControl1.tsTraySetting.edtlFix2AICCDStartDelay", "edtlFix2AICCDStartDelay", "IDC_FIXAICCD_EDTLFIX2AICCDSTARTDELAY", "TEdit", "fFixAICCD.PageControl1.tsTraySetting", "fFixAICCD.PageControl1.tsTraySetting", 9, 3, "LEAF", false, true, 242, true, 247, true, 81, true, 28, true, 3, -1, "", "", true, "MS Sans Serif", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fFixAICCD.PageControl1.tsTraySetting.edtlFix2AICCDAutoRetry", "edtlFix2AICCDAutoRetry", "IDC_FIXAICCD_EDTLFIX2AICCDAUTORETRY", "TEdit", "fFixAICCD.PageControl1.tsTraySetting", "fFixAICCD.PageControl1.tsTraySetting", 10, 3, "LEAF", false, true, 242, true, 310, true, 81, true, 28, true, 5, -1, "", "", true, "MS Sans Serif", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fFixAICCD.PageControl1.tsTraySetting.edtlFix2AICCDExposureTimeOut", "edtlFix2AICCDExposureTimeOut", "IDC_FIXAICCD_EDTLFIX2AICCDEXPOSURETIMEOUT", "TEdit", "fFixAICCD.PageControl1.tsTraySetting", "fFixAICCD.PageControl1.tsTraySetting", 11, 3, "LEAF", false, true, 242, true, 279, true, 81, true, 28, true, 4, -1, "", "", true, "MS Sans Serif", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fFixAICCD.PageControl1.tsTraySetting.Panel4", "Panel4", "IDD_FIXAICCD_PAGECONTROL1_TSTRAYSETTING_PANEL4", "TPanel", "fFixAICCD.PageControl1.tsTraySetting", "fFixAICCD.PageControl1.tsTraySetting", 12, 3, "SUBDLG", false, true, 4, true, 12, true, 217, true, 37, true, 0, -1, "", "", false, "", 0, "", false, 0, "", true, 12761254, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fFixAICCD.PageControl1.tsTraySetting.Panel4.chkEnableFix2AICCD", "chkEnableFix2AICCD", "IDC_FIXAICCD_CHKENABLEFIX2AICCD", "TCheckBox", "fFixAICCD.PageControl1.tsTraySetting.Panel4", "fFixAICCD.PageControl1.tsTraySetting.Panel4", 0, 4, "LEAF", false, true, 4, true, 6, true, 273, true, 19, true, 0, -1, "", "", true, "Arial", -19, "fsBold", true, 255, "clRed", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fFixAICCD.PageControl1.tsTraySetting.chkEnableLearningMode", "chkEnableLearningMode", "IDC_FIXAICCD_CHKENABLELEARNINGMODE", "TCheckBox", "fFixAICCD.PageControl1.tsTraySetting", "fFixAICCD.PageControl1.tsTraySetting", 13, 3, "LEAF", false, true, 8, true, 63, true, 237, true, 19, true, 1, -1, "", "", true, "Arial", -19, "fsBold", true, 255, "clRed", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fFixAICCD.PageControl1.tsTraySetting.rgFixAICCD", "rgFixAICCD", "IDD_FIXAICCD_PAGECONTROL1_TSTRAYSETTING_RGFIXAICCD", "TRadioGroup", "fFixAICCD.PageControl1.tsTraySetting", "fFixAICCD.PageControl1.tsTraySetting", 14, 3, "SUBDLG", false, true, 636, true, 72, true, 145, true, 74, true, 2, 0, "", "", true, "MS Sans Serif", -16, "fsBold", true, 8388608, "clNavy", true, 65535, "clYellow", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fFixAICCD.PageControl1.tsTraySetting.edtOutArmCycleInsp", "edtOutArmCycleInsp", "IDC_FIXAICCD_EDTOUTARMCYCLEINSP", "TEdit", "fFixAICCD.PageControl1.tsTraySetting", "fFixAICCD.PageControl1.tsTraySetting", 15, 3, "LEAF", false, true, 242, true, 403, true, 81, true, 28, true, 8, -1, "", "", true, "MS Sans Serif", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fFixAICCD.PageControl1.tsTraySetting.edtInspectResultThres", "edtInspectResultThres", "IDC_FIXAICCD_EDTINSPECTRESULTTHRES", "TEdit", "fFixAICCD.PageControl1.tsTraySetting", "fFixAICCD.PageControl1.tsTraySetting", 16, 3, "LEAF", false, true, 242, true, 341, true, 81, true, 28, true, 6, -1, "", "", true, "MS Sans Serif", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fFixAICCD.PageControl1.tsTrayCCD", "tsTrayCCD", "IDD_FIXAICCD_PAGECONTROL1_TSTRAYCCD", "TTabSheet", "fFixAICCD.PageControl1", "fFixAICCD", 1, 2, "SUBDLG", false, false, 0, false, 0, false, 0, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fFixAICCD.PageControl1.tsTrayCCD.Panel2", "Panel2", "IDD_FIXAICCD_PAGECONTROL1_TSTRAYCCD_PANEL2", "TPanel", "fFixAICCD.PageControl1.tsTrayCCD", "fFixAICCD.PageControl1.tsTrayCCD", 0, 3, "SUBDLG", false, true, 0, true, 0, true, 373, true, 558, true, 0, -1, "alLeft", "", false, "", 0, "", false, 0, "", true, 12761254, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fFixAICCD.PageControl1.tsTrayCCD.Panel2.GroupBox2", "GroupBox2", "IDD_FIXAICCD_PAGECONTROL1_TSTRAYCCD_PANEL2_GROUPBOX2", "TGroupBox", "fFixAICCD.PageControl1.tsTrayCCD.Panel2", "fFixAICCD.PageControl1.tsTrayCCD.Panel2", 0, 4, "SUBDLG", false, true, 0, true, 0, true, 373, true, 369, true, 0, -1, "alTop", "", true, "Arial", -19, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fFixAICCD.PageControl1.tsTrayCCD.Panel2.GroupBox2.Label5", "Label5", "IDC_FIXAICCD_LABEL5", "TLabel", "fFixAICCD.PageControl1.tsTrayCCD.Panel2.GroupBox2", "fFixAICCD.PageControl1.tsTrayCCD.Panel2.GroupBox2", 0, 5, "LEAF", true, true, 9, true, 22, true, 68, true, 18, false, 0, -1, "", "", true, "Arial", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fFixAICCD.PageControl1.tsTrayCCD.Panel2.GroupBox2.Label6", "Label6", "IDC_FIXAICCD_LABEL6", "TLabel", "fFixAICCD.PageControl1.tsTrayCCD.Panel2.GroupBox2", "fFixAICCD.PageControl1.tsTrayCCD.Panel2.GroupBox2", 1, 5, "LEAF", true, true, 143, true, 22, true, 29, true, 18, false, 0, -1, "", "", true, "Arial", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fFixAICCD.PageControl1.tsTrayCCD.Panel2.GroupBox2.lblBGALightValue", "lblBGALightValue", "IDC_FIXAICCD_LBLBGALIGHTVALUE", "TLabel", "fFixAICCD.PageControl1.tsTrayCCD.Panel2.GroupBox2", "fFixAICCD.PageControl1.tsTrayCCD.Panel2.GroupBox2", 2, 5, "LEAF", true, true, 146, true, 317, true, 11, true, 22, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fFixAICCD.PageControl1.tsTrayCCD.Panel2.GroupBox2.Label1", "Label1", "IDC_FIXAICCD_LABEL1", "TLabel", "fFixAICCD.PageControl1.tsTrayCCD.Panel2.GroupBox2", "fFixAICCD.PageControl1.tsTrayCCD.Panel2.GroupBox2", 3, 5, "LEAF", true, true, 12, true, 122, true, 68, true, 18, false, 0, -1, "", "", true, "Arial", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fFixAICCD.PageControl1.tsTrayCCD.Panel2.GroupBox2.Label2", "Label2", "IDC_FIXAICCD_LABEL2", "TLabel", "fFixAICCD.PageControl1.tsTrayCCD.Panel2.GroupBox2", "fFixAICCD.PageControl1.tsTrayCCD.Panel2.GroupBox2", 4, 5, "LEAF", true, true, 146, true, 122, true, 29, true, 18, false, 0, -1, "", "", true, "Arial", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fFixAICCD.PageControl1.tsTrayCCD.Panel2.GroupBox2.edFix2AICCD_Address", "edFix2AICCD_Address", "IDC_FIXAICCD_EDFIX2AICCD_ADDRESS", "TEdit", "fFixAICCD.PageControl1.tsTrayCCD.Panel2.GroupBox2", "fFixAICCD.PageControl1.tsTrayCCD.Panel2.GroupBox2", 5, 5, "LEAF", false, true, 7, true, 46, true, 130, true, 26, true, 1, -1, "", "", true, "Arial", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fFixAICCD.PageControl1.tsTrayCCD.Panel2.GroupBox2.edtFix2AICCD_Port", "edtFix2AICCD_Port", "IDC_FIXAICCD_EDTFIX2AICCD_PORT", "TEdit", "fFixAICCD.PageControl1.tsTrayCCD.Panel2.GroupBox2", "fFixAICCD.PageControl1.tsTrayCCD.Panel2.GroupBox2", 6, 5, "LEAF", false, true, 142, true, 46, true, 60, true, 26, true, 2, -1, "", "", true, "Arial", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fFixAICCD.PageControl1.tsTrayCCD.Panel2.GroupBox2.btnFix2AICCD_Connect", "btnFix2AICCD_Connect", "IDC_FIXAICCD_BTNFIX2AICCD_CONNECT", "TBitBtn", "fFixAICCD.PageControl1.tsTrayCCD.Panel2.GroupBox2", "fFixAICCD.PageControl1.tsTrayCCD.Panel2.GroupBox2", 7, 5, "LEAF", false, true, 6, true, 76, true, 120, true, 30, true, 4, -1, "", "", true, "Arial", -16, "fsBold", true, 32768, "clGreen", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fFixAICCD.PageControl1.tsTrayCCD.Panel2.GroupBox2.btnFix2AICCD_Disconnect", "btnFix2AICCD_Disconnect", "IDC_FIXAICCD_BTNFIX2AICCD_DISCONNECT", "TBitBtn", "fFixAICCD.PageControl1.tsTrayCCD.Panel2.GroupBox2", "fFixAICCD.PageControl1.tsTrayCCD.Panel2.GroupBox2", 8, 5, "LEAF", false, true, 130, true, 76, true, 120, true, 30, true, 5, -1, "", "", true, "Arial", -16, "fsBold", true, 4210816, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fFixAICCD.PageControl1.tsTrayCCD.Panel2.GroupBox2.btFix2AICCD_Trigger", "btFix2AICCD_Trigger", "IDC_FIXAICCD_BTFIX2AICCD_TRIGGER", "TButton", "fFixAICCD.PageControl1.tsTrayCCD.Panel2.GroupBox2", "fFixAICCD.PageControl1.tsTrayCCD.Panel2.GroupBox2", 9, 5, "LEAF", false, true, 212, true, 16, true, 90, true, 29, true, 0, -1, "", "", true, "Arial", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fFixAICCD.PageControl1.tsTrayCCD.Panel2.GroupBox2.edtFix2AICCD_CMD", "edtFix2AICCD_CMD", "IDC_FIXAICCD_EDTFIX2AICCD_CMD", "TEdit", "fFixAICCD.PageControl1.tsTrayCCD.Panel2.GroupBox2", "fFixAICCD.PageControl1.tsTrayCCD.Panel2.GroupBox2", 10, 5, "LEAF", false, true, 211, true, 46, true, 90, true, 26, true, 3, -1, "", "", true, "Arial", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fFixAICCD.PageControl1.tsTrayCCD.Panel2.GroupBox2.pnlBGALightValue", "pnlBGALightValue", "IDC_FIXAICCD_PNLBGALIGHTVALUE", "TPanel", "fFixAICCD.PageControl1.tsTrayCCD.Panel2.GroupBox2", "fFixAICCD.PageControl1.tsTrayCCD.Panel2.GroupBox2", 11, 5, "LEAF", false, true, 8, true, 316, true, 105, true, 24, true, 6, -1, "", "", true, "MS Sans Serif", -15, "fsBold", true, 16777215, "clWhite", true, 8421376, "clTeal", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fFixAICCD.PageControl1.tsTrayCCD.Panel2.GroupBox2.scrBGALightValue", "scrBGALightValue", "IDC_FIXAICCD_SCRBGALIGHTVALUE", "TScrollBar", "fFixAICCD.PageControl1.tsTrayCCD.Panel2.GroupBox2", "fFixAICCD.PageControl1.tsTrayCCD.Panel2.GroupBox2", 12, 5, "LEAF", false, true, 7, true, 346, true, 158, true, 17, true, 7, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fFixAICCD.PageControl1.tsTrayCCD.Panel2.GroupBox2.edFix2AICCD_Address2", "edFix2AICCD_Address2", "IDC_FIXAICCD_EDFIX2AICCD_ADDRESS2", "TEdit", "fFixAICCD.PageControl1.tsTrayCCD.Panel2.GroupBox2", "fFixAICCD.PageControl1.tsTrayCCD.Panel2.GroupBox2", 13, 5, "LEAF", false, true, 10, true, 146, true, 130, true, 26, true, 8, -1, "", "", true, "Arial", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fFixAICCD.PageControl1.tsTrayCCD.Panel2.GroupBox2.edtFix2AICCD_Port2", "edtFix2AICCD_Port2", "IDC_FIXAICCD_EDTFIX2AICCD_PORT2", "TEdit", "fFixAICCD.PageControl1.tsTrayCCD.Panel2.GroupBox2", "fFixAICCD.PageControl1.tsTrayCCD.Panel2.GroupBox2", 14, 5, "LEAF", false, true, 145, true, 146, true, 60, true, 26, true, 9, -1, "", "", true, "Arial", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fFixAICCD.PageControl1.tsTrayCCD.Panel2.GroupBox2.btnFix2AICCD_Connect2", "btnFix2AICCD_Connect2", "IDC_FIXAICCD_BTNFIX2AICCD_CONNECT2", "TBitBtn", "fFixAICCD.PageControl1.tsTrayCCD.Panel2.GroupBox2", "fFixAICCD.PageControl1.tsTrayCCD.Panel2.GroupBox2", 15, 5, "LEAF", false, true, 9, true, 176, true, 120, true, 30, true, 10, -1, "", "", true, "Arial", -16, "fsBold", true, 32768, "clGreen", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fFixAICCD.PageControl1.tsTrayCCD.Panel2.GroupBox2.btnFix2AICCD_Disconnect2", "btnFix2AICCD_Disconnect2", "IDC_FIXAICCD_BTNFIX2AICCD_DISCONNECT2", "TBitBtn", "fFixAICCD.PageControl1.tsTrayCCD.Panel2.GroupBox2", "fFixAICCD.PageControl1.tsTrayCCD.Panel2.GroupBox2", 16, 5, "LEAF", false, true, 133, true, 176, true, 120, true, 30, true, 11, -1, "", "", true, "Arial", -16, "fsBold", true, 4210816, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fFixAICCD.PageControl1.tsTrayCCD.Panel2.GroupBox2.btFix2AICCD_Trigger2", "btFix2AICCD_Trigger2", "IDC_FIXAICCD_BTFIX2AICCD_TRIGGER2", "TButton", "fFixAICCD.PageControl1.tsTrayCCD.Panel2.GroupBox2", "fFixAICCD.PageControl1.tsTrayCCD.Panel2.GroupBox2", 17, 5, "LEAF", false, true, 215, true, 116, true, 90, true, 29, true, 12, -1, "", "", true, "Arial", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fFixAICCD.PageControl1.tsTrayCCD.Panel2.GroupBox2.edtFix2AICCD_CMD2", "edtFix2AICCD_CMD2", "IDC_FIXAICCD_EDTFIX2AICCD_CMD2", "TEdit", "fFixAICCD.PageControl1.tsTrayCCD.Panel2.GroupBox2", "fFixAICCD.PageControl1.tsTrayCCD.Panel2.GroupBox2", 18, 5, "LEAF", false, true, 214, true, 146, true, 90, true, 26, true, 13, -1, "", "", true, "Arial", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fFixAICCD.PageControl1.tsTrayCCD.memoFix2AICCDCommLog", "memoFix2AICCDCommLog", "IDC_FIXAICCD_MEMOFIX2AICCDCOMMLOG", "TMemo", "fFixAICCD.PageControl1.tsTrayCCD", "fFixAICCD.PageControl1.tsTrayCCD", 1, 3, "LEAF", false, true, 373, true, 0, true, 614, true, 558, true, 1, -1, "alClient", "", false, "", 0, "", false, 0, "", true, 14670284, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fFixAICCD.Panel1", "Panel1", "IDD_FIXAICCD_PANEL1", "TPanel", "fFixAICCD", "fFixAICCD", 1, 1, "SUBDLG", false, true, 0, true, 592, true, 995, true, 44, true, 2, -1, "alBottom", "", false, "", 0, "", false, 0, "", true, 12761254, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fFixAICCD.Panel1.spbSave", "spbSave", "IDC_FIXAICCD_SPBSAVE", "TSpeedButton", "fFixAICCD.Panel1", "fFixAICCD.Panel1", 0, 2, "LEAF", true, true, 206, true, 4, true, 227, true, 40, false, 0, -1, "", "", true, "Arial", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fFixAICCD.Panel1.sbtExit", "sbtExit", "IDC_FIXAICCD_SBTEXIT", "TSpeedButton", "fFixAICCD.Panel1", "fFixAICCD.Panel1", 1, 2, "LEAF", true, true, 556, true, 3, true, 241, true, 41, false, 0, -1, "", "", true, "Arial", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fFixAICCD.rgResultShowType", "rgResultShowType", "IDD_FIXAICCD_RGRESULTSHOWTYPE", "TRadioGroup", "fFixAICCD", "fFixAICCD", 2, 1, "SUBDLG", false, true, 16, true, 160, true, 345, true, 105, true, 1, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fFixAICCD.tmrProcessFixAICCDData", "tmrProcessFixAICCDData", "", "TTimer", "fFixAICCD", "fFixAICCD", 3, 1, "NONVISUAL", false, true, 820, true, 36, false, 0, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fFixAICCD.ClientSocket_FixAICCD", "ClientSocket_FixAICCD", "", "TClientSocket", "fFixAICCD", "fFixAICCD", 4, 1, "NONVISUAL", false, true, 880, true, 36, false, 0, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fFixAICCD.TimerDownFixAICCDConnect", "TimerDownFixAICCDConnect", "", "TTimer", "fFixAICCD", "fFixAICCD", 5, 1, "NONVISUAL", false, true, 936, true, 36, false, 0, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fFixAICCD.tmrLightControl", "tmrLightControl", "", "TTimer", "fFixAICCD", "fFixAICCD", 6, 1, "NONVISUAL", false, true, 820, true, 76, false, 0, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fFixAICCD.ClientSocket_FixAICCD2", "ClientSocket_FixAICCD2", "", "TClientSocket", "fFixAICCD", "fFixAICCD", 7, 1, "NONVISUAL", false, true, 880, true, 76, false, 0, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
};

const int kFixAICCDLayoutCount = 53;

} // namespace ht9045_layout
