// ===========================================================================
//  Password_layout.gen.cpp
//  DO NOT EDIT -- GENERATED FILE. See the matching _layout.gen.h banner.
// ===========================================================================
#include "Password_layout.gen.h"

namespace ht9045_layout {

// (no custom-control properties in this form)

const DfmControlLayout kPasswordLayout[] = {
    { "fPassword", "fPassword", "", "TfPassword", "", "", 0, 0, "ROOT", false, true, 508, true, 379, true, 617, true, 336, false, 0, -1, "", "", true, "Arial", -11, "", true, -2147483640, "clWindowText", true, 12761254, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fPassword.PageControl1", "PageControl1", "IDC_PASSWORD_PAGECONTROL1", "TPageControl", "fPassword", "fPassword", 0, 1, "TABHOST", false, true, 0, true, 0, true, 609, true, 305, true, 0, -1, "alClient", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fPassword.PageControl1.tsPassword", "tsPassword", "IDD_PASSWORD_PAGECONTROL1_TSPASSWORD", "TTabSheet", "fPassword.PageControl1", "fPassword", 0, 2, "SUBDLG", false, false, 0, false, 0, false, 0, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fPassword.PageControl1.tsPassword.Label3", "Label3", "IDC_PASSWORD_LABEL3", "TLabel", "fPassword.PageControl1.tsPassword", "fPassword.PageControl1.tsPassword", 0, 3, "LEAF", true, true, 4, true, 4, true, 559, true, 29, false, 0, 0, "", "", true, "MS Sans Serif", -24, "fsBold", true, 255, "clRed", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fPassword.PageControl1.tsPassword.Label4", "Label4", "IDC_PASSWORD_LABEL4", "TLabel", "fPassword.PageControl1.tsPassword", "fPassword.PageControl1.tsPassword", 1, 3, "LEAF", true, true, 112, true, 40, true, 343, true, 24, false, 0, 0, "", "", true, "新細明體", -24, "fsBold", true, 255, "clRed", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fPassword.PageControl1.tsPassword.Label5", "Label5", "IDC_PASSWORD_LABEL5", "TLabel", "fPassword.PageControl1.tsPassword", "fPassword.PageControl1.tsPassword", 2, 3, "LEAF", true, true, 62, true, 8, true, 443, true, 29, false, 0, 0, "", "", true, "MS Sans Serif", -24, "fsBold", true, 255, "clRed", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fPassword.PageControl1.tsPassword.Label6", "Label6", "IDC_PASSWORD_LABEL6", "TLabel", "fPassword.PageControl1.tsPassword", "fPassword.PageControl1.tsPassword", 3, 3, "LEAF", true, true, 116, true, 44, true, 335, true, 24, false, 0, 0, "", "", true, "新細明體", -24, "fsBold", true, 255, "clRed", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fPassword.PageControl1.tsPassword.btnOK", "btnOK", "IDC_PASSWORD_BTNOK", "TSpeedButton", "fPassword.PageControl1.tsPassword", "fPassword.PageControl1.tsPassword", 4, 3, "LEAF", true, true, 27, true, 196, true, 170, true, 50, false, 0, -1, "", "", true, "Arial", -24, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fPassword.PageControl1.tsPassword.spbCancel", "spbCancel", "IDC_PASSWORD_SPBCANCEL", "TSpeedButton", "fPassword.PageControl1.tsPassword", "fPassword.PageControl1.tsPassword", 5, 3, "LEAF", true, true, 226, true, 196, true, 170, true, 50, false, 0, -1, "", "", true, "Arial", -24, "", true, 0, "clBlack", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fPassword.PageControl1.tsPassword.lblUserName", "lblUserName", "IDC_PASSWORD_LBLUSERNAME", "TLabel", "fPassword.PageControl1.tsPassword", "fPassword.PageControl1.tsPassword", 6, 3, "LEAF", true, true, 14, true, 84, true, 191, true, 40, false, 0, -1, "", "", true, "Arial", -32, "fsBold", true, 16777215, "clWhite", true, 8421440, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fPassword.PageControl1.tsPassword.Label2", "Label2", "IDC_PASSWORD_LABEL2", "TLabel", "fPassword.PageControl1.tsPassword", "fPassword.PageControl1.tsPassword", 7, 3, "LEAF", true, true, 14, true, 136, true, 191, true, 40, false, 0, -1, "", "", true, "Arial", -32, "fsBold", true, 16777215, "clWhite", true, 8421440, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fPassword.PageControl1.tsPassword.btnDownload", "btnDownload", "IDC_PASSWORD_BTNDOWNLOAD", "TSpeedButton", "fPassword.PageControl1.tsPassword", "fPassword.PageControl1.tsPassword", 8, 3, "LEAF", true, true, 424, true, 196, true, 170, true, 50, false, 0, -1, "", "", true, "Arial", -24, "", true, 0, "clBlack", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fPassword.PageControl1.tsPassword.lblPWDownload", "lblPWDownload", "IDC_PASSWORD_LBLPWDOWNLOAD", "TLabel", "fPassword.PageControl1.tsPassword", "fPassword.PageControl1.tsPassword", 9, 3, "LEAF", true, true, 256, true, 252, true, 261, true, 24, false, 0, 0, "", "", true, "新細明體", -24, "fsBold", true, 255, "clRed", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fPassword.PageControl1.tsPassword.edPassword", "edPassword", "IDC_PASSWORD_EDPASSWORD", "TEdit", "fPassword.PageControl1.tsPassword", "fPassword.PageControl1.tsPassword", 10, 3, "LEAF", false, true, 216, true, 132, true, 300, true, 44, true, 2, -1, "", "", true, "Arial", -32, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fPassword.PageControl1.tsPassword.edUserName", "edUserName", "IDC_PASSWORD_EDUSERNAME", "TEdit", "fPassword.PageControl1.tsPassword", "fPassword.PageControl1.tsPassword", 11, 3, "LEAF", false, true, 216, true, 80, true, 300, true, 44, true, 0, -1, "", "", true, "Arial", -32, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fPassword.PageControl1.tsPassword.cbUserName", "cbUserName", "IDC_PASSWORD_CBUSERNAME", "TComboBox", "fPassword.PageControl1.tsPassword", "fPassword.PageControl1.tsPassword", 12, 3, "LEAF", false, true, 238, true, 80, true, 300, true, 44, true, 1, -1, "", "", true, "Arial", -32, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fPassword.PageControl1.tsEventlogLogin", "tsEventlogLogin", "IDD_PASSWORD_PAGECONTROL1_TSEVENTLOGLOGIN", "TTabSheet", "fPassword.PageControl1", "fPassword", 1, 2, "SUBDLG", false, false, 0, false, 0, false, 0, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fPassword.PageControl1.tsEventlogLogin.lbPasswordUserName", "lbPasswordUserName", "IDC_PASSWORD_LBPASSWORDUSERNAME", "TLabel", "fPassword.PageControl1.tsEventlogLogin", "fPassword.PageControl1.tsEventlogLogin", 0, 3, "LEAF", true, true, 38, true, 60, true, 191, true, 40, false, 0, -1, "", "", true, "Arial", -32, "fsBold", true, 16777215, "clWhite", true, 8421440, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fPassword.PageControl1.tsEventlogLogin.lbPasswordPassWord", "lbPasswordPassWord", "IDC_PASSWORD_LBPASSWORDPASSWORD", "TLabel", "fPassword.PageControl1.tsEventlogLogin", "fPassword.PageControl1.tsEventlogLogin", 1, 3, "LEAF", true, true, 38, true, 112, true, 191, true, 40, false, 0, -1, "", "", true, "Arial", -32, "fsBold", true, 16777215, "clWhite", true, 8421440, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fPassword.PageControl1.tsEventlogLogin.sbPasswordModify", "sbPasswordModify", "IDC_PASSWORD_SBPASSWORDMODIFY", "TSpeedButton", "fPassword.PageControl1.tsEventlogLogin", "fPassword.PageControl1.tsEventlogLogin", 2, 3, "LEAF", true, true, 408, true, 216, true, 170, true, 50, false, 0, -1, "", "", true, "Arial", -24, "", true, 0, "clBlack", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fPassword.PageControl1.tsEventlogLogin.sbPasswordCancel", "sbPasswordCancel", "IDC_PASSWORD_SBPASSWORDCANCEL", "TSpeedButton", "fPassword.PageControl1.tsEventlogLogin", "fPassword.PageControl1.tsEventlogLogin", 3, 3, "LEAF", true, true, 210, true, 216, true, 170, true, 50, false, 0, -1, "", "", true, "Arial", -24, "", true, 0, "clBlack", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fPassword.PageControl1.tsEventlogLogin.sbPasswordOK", "sbPasswordOK", "IDC_PASSWORD_SBPASSWORDOK", "TSpeedButton", "fPassword.PageControl1.tsEventlogLogin", "fPassword.PageControl1.tsEventlogLogin", 4, 3, "LEAF", true, true, 11, true, 216, true, 170, true, 50, false, 0, -1, "", "", true, "Arial", -24, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fPassword.PageControl1.tsEventlogLogin.cob_UseIDList", "cob_UseIDList", "IDC_PASSWORD_COB_USEIDLIST", "TComboBox", "fPassword.PageControl1.tsEventlogLogin", "fPassword.PageControl1.tsEventlogLogin", 5, 3, "LEAF", false, true, 254, true, 56, true, 270, true, 44, true, 0, -1, "", "", true, "Arial", -32, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fPassword.PageControl1.tsEventlogLogin.edPasswordPassWord", "edPasswordPassWord", "IDC_PASSWORD_EDPASSWORDPASSWORD", "TEdit", "fPassword.PageControl1.tsEventlogLogin", "fPassword.PageControl1.tsEventlogLogin", 6, 3, "LEAF", false, true, 254, true, 105, true, 270, true, 44, true, 1, -1, "", "", true, "Arial", -32, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fPassword.PageControl1.tsEventLogLoginModify", "tsEventLogLoginModify", "IDD_PASSWORD_PAGECONTROL1_TSEVENTLOGLOGINMODIFY", "TTabSheet", "fPassword.PageControl1", "fPassword", 2, 2, "SUBDLG", false, false, 0, false, 0, false, 0, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fPassword.PageControl1.tsEventLogLoginModify.Label7", "Label7", "IDC_PASSWORD_LABEL7", "TLabel", "fPassword.PageControl1.tsEventLogLoginModify", "fPassword.PageControl1.tsEventLogLoginModify", 0, 3, "LEAF", true, true, 10, true, 20, true, 220, true, 40, false, 0, -1, "", "", true, "Arial", -32, "fsBold", true, 16777215, "clWhite", true, 8421440, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fPassword.PageControl1.tsEventLogLoginModify.Label8", "Label8", "IDC_PASSWORD_LABEL8", "TLabel", "fPassword.PageControl1.tsEventLogLoginModify", "fPassword.PageControl1.tsEventLogLoginModify", 1, 3, "LEAF", true, true, 10, true, 72, true, 220, true, 40, false, 0, -1, "", "", true, "Arial", -32, "fsBold", true, 16777215, "clWhite", true, 8421440, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fPassword.PageControl1.tsEventLogLoginModify.Label9", "Label9", "IDC_PASSWORD_LABEL9", "TLabel", "fPassword.PageControl1.tsEventLogLoginModify", "fPassword.PageControl1.tsEventLogLoginModify", 2, 3, "LEAF", true, true, 10, true, 120, true, 220, true, 40, false, 0, -1, "", "", true, "Arial", -32, "fsBold", true, 16777215, "clWhite", true, 8421440, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fPassword.PageControl1.tsEventLogLoginModify.sbPasswordModifyOK", "sbPasswordModifyOK", "IDC_PASSWORD_SBPASSWORDMODIFYOK", "TSpeedButton", "fPassword.PageControl1.tsEventLogLoginModify", "fPassword.PageControl1.tsEventLogLoginModify", 3, 3, "LEAF", true, true, 83, true, 196, true, 170, true, 50, false, 0, -1, "", "", true, "Arial", -29, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fPassword.PageControl1.tsEventLogLoginModify.sbPasswordModifyCancel", "sbPasswordModifyCancel", "IDC_PASSWORD_SBPASSWORDMODIFYCANCEL", "TSpeedButton", "fPassword.PageControl1.tsEventLogLoginModify", "fPassword.PageControl1.tsEventLogLoginModify", 4, 3, "LEAF", true, true, 326, true, 195, true, 170, true, 50, false, 0, -1, "", "", true, "Arial", -29, "", true, 0, "clBlack", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fPassword.PageControl1.tsEventLogLoginModify.cob_ModifyUseIDList", "cob_ModifyUseIDList", "IDC_PASSWORD_COB_MODIFYUSEIDLIST", "TComboBox", "fPassword.PageControl1.tsEventLogLoginModify", "fPassword.PageControl1.tsEventLogLoginModify", 5, 3, "LEAF", false, true, 242, true, 18, true, 270, true, 44, true, 0, -1, "", "", true, "Arial", -32, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fPassword.PageControl1.tsEventLogLoginModify.edModifyPassword", "edModifyPassword", "IDC_PASSWORD_EDMODIFYPASSWORD", "TEdit", "fPassword.PageControl1.tsEventLogLoginModify", "fPassword.PageControl1.tsEventLogLoginModify", 6, 3, "LEAF", false, true, 242, true, 70, true, 270, true, 44, true, 1, -1, "", "", true, "Arial", -32, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fPassword.PageControl1.tsEventLogLoginModify.edReModifyPassword", "edReModifyPassword", "IDC_PASSWORD_EDREMODIFYPASSWORD", "TEdit", "fPassword.PageControl1.tsEventLogLoginModify", "fPassword.PageControl1.tsEventLogLoginModify", 7, 3, "LEAF", false, true, 242, true, 118, true, 270, true, 44, true, 2, -1, "", "", true, "Arial", -32, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
};

const int kPasswordLayoutCount = 33;

} // namespace ht9045_layout
