// ===========================================================================
//  Precaution_layout.gen.cpp
//  DO NOT EDIT -- GENERATED FILE. See the matching _layout.gen.h banner.
// ===========================================================================
#include "Precaution_layout.gen.h"

namespace ht9045_layout {

// (no custom-control properties in this form)

const DfmControlLayout kPrecautionLayout[] = {
    { "fPrecaution", "fPrecaution", "", "TfPrecaution", "", "", 0, 0, "ROOT", false, true, 756, true, 155, false, 0, false, 0, false, 0, -1, "", "", true, "MS Sans Serif", -11, "", true, -2147483640, "clWindowText", true, -2147483633, "clBtnFace", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fPrecaution.pnPrecautionsRecord", "pnPrecautionsRecord", "IDD_PRECAUTION_PNPRECAUTIONSRECORD", "TPanel", "fPrecaution", "fPrecaution", 0, 1, "SUBDLG", false, true, 0, true, 0, true, 574, true, 473, true, 0, -1, "alClient", "", true, "Courier New", -16, "fsBold", true, 0, "clBlack", true, 9534289, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fPrecaution.pnPrecautionsRecord.pnMaintenanceRecord", "pnMaintenanceRecord", "IDD_PRECAUTION_PNPRECAUTIONSRECORD_PNMAINTENANCERECORD", "TPanel", "fPrecaution.pnPrecautionsRecord", "fPrecaution.pnPrecautionsRecord", 0, 2, "SUBDLG", false, true, 12, true, 8, true, 549, true, 457, true, 0, -1, "", "", false, "", 0, "", false, 0, "", true, 12761254, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fPrecaution.pnPrecautionsRecord.pnMaintenanceRecord.pnMaintenanceRecordTitle", "pnMaintenanceRecordTitle", "IDC_PRECAUTION_PNMAINTENANCERECORDTITLE", "TPanel", "fPrecaution.pnPrecautionsRecord.pnMaintenanceRecord", "fPrecaution.pnPrecautionsRecord.pnMaintenanceRecord", 0, 3, "LEAF", false, true, 2, true, 2, true, 545, true, 30, true, 0, -1, "alTop", "", true, "Courier New", -19, "fsBold", true, 16777215, "clWhite", true, 9534289, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fPrecaution.pnPrecautionsRecord.pnMaintenanceRecord.MemoHandlerPrecautionRecord", "MemoHandlerPrecautionRecord", "IDC_PRECAUTION_MEMOHANDLERPRECAUTIONRECORD", "TMemo", "fPrecaution.pnPrecautionsRecord.pnMaintenanceRecord", "fPrecaution.pnPrecautionsRecord.pnMaintenanceRecord", 1, 3, "LEAF", false, true, 5, true, 104, true, 536, true, 225, true, 6, -1, "", "", true, "Courier New", -16, "fsBold", true, 8388608, "clNavy", true, 14670284, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fPrecaution.pnPrecautionsRecord.pnMaintenanceRecord.pnPrecautionRecordDocumentNoTitle", "pnPrecautionRecordDocumentNoTitle", "IDC_PRECAUTION_PNPRECAUTIONRECORDDOCUMENTNOTITLE", "TPanel", "fPrecaution.pnPrecautionsRecord.pnMaintenanceRecord", "fPrecaution.pnPrecautionsRecord.pnMaintenanceRecord", 2, 3, "LEAF", false, true, 5, true, 40, true, 150, true, 26, true, 2, -1, "", "", true, "標楷體", -16, "", true, 16777215, "clWhite", true, 6055843, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fPrecaution.pnPrecautionsRecord.pnMaintenanceRecord.Panel91", "Panel91", "IDC_PRECAUTION_PANEL91", "TPanel", "fPrecaution.pnPrecautionsRecord.pnMaintenanceRecord", "fPrecaution.pnPrecautionsRecord.pnMaintenanceRecord", 3, 3, "LEAF", false, true, 310, true, 40, true, 231, true, 26, true, 3, -1, "", "", true, "標楷體", -16, "", true, 16777215, "clWhite", true, 6055843, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fPrecaution.pnPrecautionsRecord.pnMaintenanceRecord.Panel92", "Panel92", "IDC_PRECAUTION_PANEL92", "TPanel", "fPrecaution.pnPrecautionsRecord.pnMaintenanceRecord", "fPrecaution.pnPrecautionsRecord.pnMaintenanceRecord", 4, 3, "LEAF", false, true, 5, true, 72, true, 150, true, 26, true, 5, -1, "", "", true, "標楷體", -16, "", true, 16777215, "clWhite", true, 6055843, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fPrecaution.pnPrecautionsRecord.pnMaintenanceRecord.Panel93", "Panel93", "IDC_PRECAUTION_PANEL93", "TPanel", "fPrecaution.pnPrecautionsRecord.pnMaintenanceRecord", "fPrecaution.pnPrecautionsRecord.pnMaintenanceRecord", 5, 3, "LEAF", false, true, 5, true, 338, true, 115, true, 26, true, 8, -1, "", "", true, "標楷體", -16, "", true, 16777215, "clWhite", true, 6055843, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fPrecaution.pnPrecautionsRecord.pnMaintenanceRecord.Panel94", "Panel94", "IDC_PRECAUTION_PANEL94", "TPanel", "fPrecaution.pnPrecautionsRecord.pnMaintenanceRecord", "fPrecaution.pnPrecautionsRecord.pnMaintenanceRecord", 6, 3, "LEAF", false, true, 290, true, 337, true, 115, true, 26, true, 7, -1, "", "", true, "標楷體", -16, "", true, 16777215, "clWhite", true, 6055843, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fPrecaution.pnPrecautionsRecord.pnMaintenanceRecord.Panel95", "Panel95", "IDC_PRECAUTION_PANEL95", "TPanel", "fPrecaution.pnPrecautionsRecord.pnMaintenanceRecord", "fPrecaution.pnPrecautionsRecord.pnMaintenanceRecord", 7, 3, "LEAF", false, true, 5, true, 370, true, 115, true, 26, true, 11, -1, "", "", true, "標楷體", -16, "", true, 16777215, "clWhite", true, 6055843, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fPrecaution.pnPrecautionsRecord.pnMaintenanceRecord.pnPrecautionStartTime", "pnPrecautionStartTime", "IDC_PRECAUTION_PNPRECAUTIONSTARTTIME", "TPanel", "fPrecaution.pnPrecautionsRecord.pnMaintenanceRecord", "fPrecaution.pnPrecautionsRecord.pnMaintenanceRecord", 8, 3, "LEAF", false, true, 140, true, 370, true, 120, true, 26, true, 12, -1, "", "", true, "MS Sans Serif", -11, "", true, 8388736, "clPurple", true, 8421376, "clTeal", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fPrecaution.pnPrecautionsRecord.pnMaintenanceRecord.Panel96", "Panel96", "IDC_PRECAUTION_PANEL96", "TPanel", "fPrecaution.pnPrecautionsRecord.pnMaintenanceRecord", "fPrecaution.pnPrecautionsRecord.pnMaintenanceRecord", 9, 3, "LEAF", false, true, 290, true, 370, true, 115, true, 26, true, 13, -1, "", "", true, "標楷體", -16, "", true, 16777215, "clWhite", true, 6055843, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fPrecaution.pnPrecautionsRecord.pnMaintenanceRecord.pnPrecautionEndTime", "pnPrecautionEndTime", "IDC_PRECAUTION_PNPRECAUTIONENDTIME", "TPanel", "fPrecaution.pnPrecautionsRecord.pnMaintenanceRecord", "fPrecaution.pnPrecautionsRecord.pnMaintenanceRecord", 10, 3, "LEAF", false, true, 416, true, 370, true, 120, true, 26, true, 14, -1, "", "", true, "MS Sans Serif", -13, "", true, 8388736, "clPurple", true, 8421376, "clTeal", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fPrecaution.pnPrecautionsRecord.pnMaintenanceRecord.pnPrecautionRecordDocumentNo", "pnPrecautionRecordDocumentNo", "IDC_PRECAUTION_PNPRECAUTIONRECORDDOCUMENTNO", "TPanel", "fPrecaution.pnPrecautionsRecord.pnMaintenanceRecord", "fPrecaution.pnPrecautionsRecord.pnMaintenanceRecord", 11, 3, "LEAF", false, true, 159, true, 39, true, 146, true, 26, true, 1, -1, "", "", true, "MS Sans Serif", -19, "", true, 8388736, "clPurple", true, 8421376, "clTeal", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fPrecaution.pnPrecautionsRecord.pnMaintenanceRecord.pnNoteContents", "pnNoteContents", "IDC_PRECAUTION_PNNOTECONTENTS", "TPanel", "fPrecaution.pnPrecautionsRecord.pnMaintenanceRecord", "fPrecaution.pnPrecautionsRecord.pnMaintenanceRecord", 12, 3, "LEAF", false, true, 159, true, 71, true, 382, true, 26, true, 4, -1, "", "", true, "MS Sans Serif", -19, "", true, 8388736, "clPurple", true, 8421376, "clTeal", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fPrecaution.pnPrecautionsRecord.pnMaintenanceRecord.pnApprovedManager", "pnApprovedManager", "IDC_PRECAUTION_PNAPPROVEDMANAGER", "TPanel", "fPrecaution.pnPrecautionsRecord.pnMaintenanceRecord", "fPrecaution.pnPrecautionsRecord.pnMaintenanceRecord", 13, 3, "LEAF", false, true, 140, true, 338, true, 120, true, 26, true, 9, -1, "", "", true, "MS Sans Serif", -16, "", true, 8388736, "clPurple", true, 8421376, "clTeal", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fPrecaution.pnPrecautionsRecord.pnMaintenanceRecord.pnWatchmakers", "pnWatchmakers", "IDC_PRECAUTION_PNWATCHMAKERS", "TPanel", "fPrecaution.pnPrecautionsRecord.pnMaintenanceRecord", "fPrecaution.pnPrecautionsRecord.pnMaintenanceRecord", 14, 3, "LEAF", false, true, 416, true, 338, true, 120, true, 26, true, 10, -1, "", "", true, "MS Sans Serif", -16, "", true, 8388736, "clPurple", true, 8421376, "clTeal", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fPrecaution.pnPrecautionsRecord.pnMaintenanceRecord.Panel1", "Panel1", "IDC_PRECAUTION_PANEL1", "TPanel", "fPrecaution.pnPrecautionsRecord.pnMaintenanceRecord", "fPrecaution.pnPrecautionsRecord.pnMaintenanceRecord", 15, 3, "LEAF", false, true, 5, true, 402, true, 115, true, 26, true, 15, -1, "", "", true, "標楷體", -16, "", true, 16777215, "clWhite", true, 6055843, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fPrecaution.pnPrecautionsRecord.pnMaintenanceRecord.pnCloseType", "pnCloseType", "IDC_PRECAUTION_PNCLOSETYPE", "TPanel", "fPrecaution.pnPrecautionsRecord.pnMaintenanceRecord", "fPrecaution.pnPrecautionsRecord.pnMaintenanceRecord", 16, 3, "LEAF", false, true, 140, true, 402, true, 120, true, 26, true, 16, -1, "", "", true, "MS Sans Serif", -16, "", true, 8388736, "clPurple", true, 8421376, "clTeal", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fPrecaution.pnPrecautionsRecord.pnMaintenanceRecord.Panel3", "Panel3", "IDC_PRECAUTION_PANEL3", "TPanel", "fPrecaution.pnPrecautionsRecord.pnMaintenanceRecord", "fPrecaution.pnPrecautionsRecord.pnMaintenanceRecord", 17, 3, "LEAF", false, true, 290, true, 402, true, 115, true, 26, true, 17, -1, "", "", true, "標楷體", -16, "", true, 16777215, "clWhite", true, 6055843, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fPrecaution.pnPrecautionsRecord.pnMaintenanceRecord.pnCloseName", "pnCloseName", "IDC_PRECAUTION_PNCLOSENAME", "TPanel", "fPrecaution.pnPrecautionsRecord.pnMaintenanceRecord", "fPrecaution.pnPrecautionsRecord.pnMaintenanceRecord", 18, 3, "LEAF", false, true, 416, true, 402, true, 120, true, 26, true, 18, -1, "", "", true, "MS Sans Serif", -16, "", true, 8388736, "clPurple", true, 8421376, "clTeal", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fPrecaution.pnPrecautionsRecord.pnMaintenanceRecord.pnPRSpecification", "pnPRSpecification", "IDC_PRECAUTION_PNPRSPECIFICATION", "TPanel", "fPrecaution.pnPrecautionsRecord.pnMaintenanceRecord", "fPrecaution.pnPrecautionsRecord.pnMaintenanceRecord", 19, 3, "LEAF", false, true, 416, true, 432, true, 120, true, 20, true, 19, -1, "", "", true, "MS Sans Serif", -13, "", true, 8388736, "clPurple", true, 12632256, "clSilver", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fPrecaution.tm_CheckEditEmpty", "tm_CheckEditEmpty", "", "TTimer", "fPrecaution", "fPrecaution", 1, 1, "NONVISUAL", false, true, 500, true, 144, false, 0, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
};

const int kPrecautionLayoutCount = 24;

} // namespace ht9045_layout
