// ===========================================================================
//  QAMode_layout.gen.cpp
//  DO NOT EDIT -- GENERATED FILE. See the matching _layout.gen.h banner.
// ===========================================================================
#include "QAMode_layout.gen.h"

namespace ht9045_layout {

// (no custom-control properties in this form)

const DfmControlLayout kQAModeLayout[] = {
    { "fQAMode", "fQAMode", "", "TfQAMode", "", "", 0, 0, "ROOT", false, true, 761, true, 257, true, 502, true, 500, false, 0, -1, "", "", true, "MS Sans Serif", -11, "", true, -2147483640, "clWindowText", true, 12761254, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fQAMode.btnApply", "btnApply", "IDC_QAMODE_BTNAPPLY", "TButton", "fQAMode", "fQAMode", 0, 1, "LEAF", false, true, 12, true, 415, true, 200, true, 40, true, 1, -1, "", "", true, "MS Sans Serif", -19, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fQAMode.btnOk", "btnOk", "IDC_QAMODE_BTNOK", "TButton", "fQAMode", "fQAMode", 1, 1, "LEAF", false, true, 257, true, 415, true, 200, true, 40, true, 2, -1, "", "", true, "MS Sans Serif", -19, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fQAMode.pgcQAMode", "pgcQAMode", "IDC_QAMODE_PGCQAMODE", "TPageControl", "fQAMode", "fQAMode", 2, 1, "TABHOST", false, true, 0, true, 0, true, 486, true, 405, true, 0, -1, "alTop", "", true, "MS Sans Serif", -15, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fQAMode.pgcQAMode.tsQAMode", "tsQAMode", "IDD_QAMODE_PGCQAMODE_TSQAMODE", "TTabSheet", "fQAMode.pgcQAMode", "fQAMode", 0, 2, "SUBDLG", false, false, 0, false, 0, false, 0, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fQAMode.pgcQAMode.tsQAMode.gbQAMode", "gbQAMode", "IDD_QAMODE_PGCQAMODE_TSQAMODE_GBQAMODE", "TGroupBox", "fQAMode.pgcQAMode.tsQAMode", "fQAMode.pgcQAMode.tsQAMode", 0, 3, "SUBDLG", false, true, 0, true, 0, true, 478, true, 374, true, 0, -1, "alClient", "", true, "Arial Black", -16, "", true, 16711680, "clBlue", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fQAMode.pgcQAMode.tsQAMode.gbQAMode.Label34", "Label34", "IDC_QAMODE_LABEL34", "TLabel", "fQAMode.pgcQAMode.tsQAMode.gbQAMode", "fQAMode.pgcQAMode.tsQAMode.gbQAMode", 0, 4, "LEAF", true, true, 12, true, 32, true, 111, true, 20, false, 0, -1, "", "", true, "MS Sans Serif", -16, "", true, 0, "clBlack", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fQAMode.pgcQAMode.tsQAMode.gbQAMode.Label35", "Label35", "IDC_QAMODE_LABEL35", "TLabel", "fQAMode.pgcQAMode.tsQAMode.gbQAMode", "fQAMode.pgcQAMode.tsQAMode.gbQAMode", 1, 4, "LEAF", true, true, 76, true, 57, true, 182, true, 20, false, 0, -1, "", "", true, "MS Sans Serif", -16, "", true, 255, "clRed", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fQAMode.pgcQAMode.tsQAMode.gbQAMode.labQAModeBin", "labQAModeBin", "IDC_QAMODE_LABQAMODEBIN", "TLabel", "fQAMode.pgcQAMode.tsQAMode.gbQAMode", "fQAMode.pgcQAMode.tsQAMode.gbQAMode", 2, 4, "LEAF", true, true, 12, true, 216, true, 214, true, 20, false, 0, -1, "", "", true, "MS Sans Serif", -16, "", true, 0, "clBlack", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fQAMode.pgcQAMode.tsQAMode.gbQAMode.edQAMode", "edQAMode", "IDC_QAMODE_EDQAMODE", "TEdit", "fQAMode.pgcQAMode.tsQAMode.gbQAMode", "fQAMode.pgcQAMode.tsQAMode.gbQAMode", 3, 4, "LEAF", false, true, 136, true, 28, true, 121, true, 28, true, 1, -1, "", "", true, "MS Sans Serif", -16, "", true, 0, "clBlack", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fQAMode.pgcQAMode.tsQAMode.gbQAMode.rgQARunMode", "rgQARunMode", "IDD_QAMODE_PGCQAMODE_TSQAMODE_GBQAMODE_RGQARUNMODE", "TRadioGroup", "fQAMode.pgcQAMode.tsQAMode.gbQAMode", "fQAMode.pgcQAMode.tsQAMode.gbQAMode", 4, 4, "SUBDLG", false, true, 8, true, 104, true, 461, true, 105, true, 2, -1, "", "", true, "MS Sans Serif", -16, "", true, 0, "clBlack", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fQAMode.pgcQAMode.tsQAMode.gbQAMode.cbQAModeBin", "cbQAModeBin", "IDC_QAMODE_CBQAMODEBIN", "TComboBox", "fQAMode.pgcQAMode.tsQAMode.gbQAMode", "fQAMode.pgcQAMode.tsQAMode.gbQAMode", 5, 4, "LEAF", false, true, 232, true, 212, true, 145, true, 28, true, 3, -1, "", "", true, "MS Sans Serif", -16, "", true, 0, "clBlack", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fQAMode.pgcQAMode.tsQAMode.gbQAMode.gbLoaderDirection", "gbLoaderDirection", "IDD_QAMODE_PGCQAMODE_TSQAMODE_GBQAMODE_GBLOADERDIRECTION", "TGroupBox", "fQAMode.pgcQAMode.tsQAMode.gbQAMode", "fQAMode.pgcQAMode.tsQAMode.gbQAMode", 6, 4, "SUBDLG", false, true, 372, true, 15, true, 94, true, 87, true, 0, -1, "", "", true, "MS Sans Serif", -13, "", true, 0, "clBlack", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fQAMode.pgcQAMode.tsQAMode.gbQAMode.gbLoaderDirection.Image1", "Image1", "IDC_QAMODE_IMAGE1", "TImage", "fQAMode.pgcQAMode.tsQAMode.gbQAMode.gbLoaderDirection", "fQAMode.pgcQAMode.tsQAMode.gbQAMode.gbLoaderDirection", 0, 5, "LEAF", true, true, 18, true, 20, true, 61, true, 61, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fQAMode.pgcQAMode.tsQAMode.gbQAMode.cbTrayEndDoQAModeAgain", "cbTrayEndDoQAModeAgain", "IDC_QAMODE_CBTRAYENDDOQAMODEAGAIN", "TCheckBox", "fQAMode.pgcQAMode.tsQAMode.gbQAMode", "fQAMode.pgcQAMode.tsQAMode.gbQAMode", 7, 4, "LEAF", false, true, 12, true, 256, true, 349, true, 17, true, 4, -1, "", "", true, "MS Sans Serif", -16, "", true, 0, "clBlack", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fQAMode.pgcQAMode.tsQAMode.gbQAMode.cbTrayEndCloseYield100Site", "cbTrayEndCloseYield100Site", "IDC_QAMODE_CBTRAYENDCLOSEYIELD100SITE", "TCheckBox", "fQAMode.pgcQAMode.tsQAMode.gbQAMode", "fQAMode.pgcQAMode.tsQAMode.gbQAMode", 8, 4, "LEAF", false, true, 12, true, 304, true, 325, true, 17, true, 7, -1, "", "", true, "MS Sans Serif", -16, "", true, 0, "clBlack", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fQAMode.pgcQAMode.tsQAMode.gbQAMode.cbQAD22Double", "cbQAD22Double", "IDC_QAMODE_CBQAD22DOUBLE", "TCheckBox", "fQAMode.pgcQAMode.tsQAMode.gbQAMode", "fQAMode.pgcQAMode.tsQAMode.gbQAMode", 9, 4, "LEAF", false, true, 12, true, 280, true, 253, true, 17, true, 6, -1, "", "", true, "MS Sans Serif", -16, "", true, 0, "clBlack", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fQAMode.pgcQAMode.tsQAMode.gbQAMode.cbbQAD22Double", "cbbQAD22Double", "IDC_QAMODE_CBBQAD22DOUBLE", "TComboBox", "fQAMode.pgcQAMode.tsQAMode.gbQAMode", "fQAMode.pgcQAMode.tsQAMode.gbQAMode", 10, 4, "LEAF", false, true, 259, true, 274, true, 115, true, 28, true, 5, -1, "", "", true, "MS Sans Serif", -16, "", true, 0, "clBlack", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fQAMode.pgcQAMode.tsQASampling", "tsQASampling", "IDD_QAMODE_PGCQAMODE_TSQASAMPLING", "TTabSheet", "fQAMode.pgcQAMode", "fQAMode", 1, 2, "SUBDLG", false, false, 0, false, 0, false, 0, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fQAMode.pgcQAMode.tsQASampling.pnlQASample", "pnlQASample", "IDD_QAMODE_PGCQAMODE_TSQASAMPLING_PNLQASAMPLE", "TPanel", "fQAMode.pgcQAMode.tsQASampling", "fQAMode.pgcQAMode.tsQASampling", 0, 3, "SUBDLG", false, true, 0, true, 0, true, 478, true, 374, true, 0, -1, "alClient", "", false, "", 0, "", false, 0, "", true, 12761254, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fQAMode.pgcQAMode.tsQASampling.pnlQASample.lblQASampleBin", "lblQASampleBin", "IDC_QAMODE_LBLQASAMPLEBIN", "TLabel", "fQAMode.pgcQAMode.tsQASampling.pnlQASample", "fQAMode.pgcQAMode.tsQASampling.pnlQASample", 0, 4, "LEAF", true, true, 20, true, 48, true, 93, true, 20, false, 0, -1, "", "", true, "MS Sans Serif", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fQAMode.pgcQAMode.tsQASampling.pnlQASample.lblQASampleTray", "lblQASampleTray", "IDC_QAMODE_LBLQASAMPLETRAY", "TLabel", "fQAMode.pgcQAMode.tsQASampling.pnlQASample", "fQAMode.pgcQAMode.tsQASampling.pnlQASample", 1, 4, "LEAF", true, true, 20, true, 84, true, 100, true, 20, false, 0, -1, "", "", true, "MS Sans Serif", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fQAMode.pgcQAMode.tsQASampling.pnlQASample.Label2", "Label2", "IDC_QAMODE_LABEL2", "TLabel", "fQAMode.pgcQAMode.tsQASampling.pnlQASample", "fQAMode.pgcQAMode.tsQASampling.pnlQASample", 2, 4, "LEAF", true, true, 20, true, 120, true, 113, true, 20, false, 0, -1, "", "", true, "MS Sans Serif", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fQAMode.pgcQAMode.tsQASampling.pnlQASample.cbTempOffset", "cbTempOffset", "IDC_QAMODE_CBTEMPOFFSET", "TCheckBox", "fQAMode.pgcQAMode.tsQASampling.pnlQASample", "fQAMode.pgcQAMode.tsQASampling.pnlQASample", 3, 4, "LEAF", false, true, 8, true, 12, true, 425, true, 25, true, 0, -1, "", "", true, "Arial Black", -19, "fsBold", true, 255, "clRed", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fQAMode.pgcQAMode.tsQASampling.pnlQASample.cbbQASampleBin", "cbbQASampleBin", "IDC_QAMODE_CBBQASAMPLEBIN", "TComboBox", "fQAMode.pgcQAMode.tsQASampling.pnlQASample", "fQAMode.pgcQAMode.tsQASampling.pnlQASample", 4, 4, "LEAF", false, true, 144, true, 44, true, 145, true, 28, true, 1, -1, "", "", true, "MS Sans Serif", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fQAMode.pgcQAMode.tsQASampling.pnlQASample.cbbQASampleTray", "cbbQASampleTray", "IDC_QAMODE_CBBQASAMPLETRAY", "TComboBox", "fQAMode.pgcQAMode.tsQASampling.pnlQASample", "fQAMode.pgcQAMode.tsQASampling.pnlQASample", 5, 4, "LEAF", false, true, 144, true, 80, true, 145, true, 28, true, 2, -1, "", "", true, "MS Sans Serif", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fQAMode.pgcQAMode.tsQASampling.pnlQASample.edtQASampleCnt", "edtQASampleCnt", "IDC_QAMODE_EDTQASAMPLECNT", "TEdit", "fQAMode.pgcQAMode.tsQASampling.pnlQASample", "fQAMode.pgcQAMode.tsQASampling.pnlQASample", 6, 4, "LEAF", false, true, 144, true, 116, true, 145, true, 28, true, 3, -1, "", "", true, "MS Sans Serif", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
};

const int kQAModeLayoutCount = 27;

} // namespace ht9045_layout
