// ===========================================================================
//  ShuttleMove_layout.gen.cpp
//  DO NOT EDIT -- GENERATED FILE. See the matching _layout.gen.h banner.
// ===========================================================================
#include "ShuttleMove_layout.gen.h"

namespace ht9045_layout {

const DfmCustomProp kShuttleMoveCustomProps[] = {
    { "XItem", "8" },
    { "XItem", "8" },
    { "XItem", "8" },
    { "YItem", "4" },
    { "XItem", "8" },
};

const DfmControlLayout kShuttleMoveLayout[] = {
    { "fShuttleMove", "fShuttleMove", "", "TfShuttleMove", "", "", 0, 0, "ROOT", false, true, 118, true, 202, false, 0, false, 0, false, 0, -1, "", "", true, "MS Sans Serif", -11, "", true, -2147483640, "clWindowText", true, -2147483633, "clBtnFace", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fShuttleMove.Panel1", "Panel1", "IDD_SHUTTLEMOVE_PANEL1", "TPanel", "fShuttleMove", "fShuttleMove", 0, 1, "SUBDLG", false, true, 0, true, 0, true, 1062, true, 989, true, 0, -1, "alClient", "", false, "", 0, "", false, 0, "", true, 12761254, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fShuttleMove.Panel1.Panel2", "Panel2", "IDD_SHUTTLEMOVE_PANEL1_PANEL2", "TPanel", "fShuttleMove.Panel1", "fShuttleMove.Panel1", 0, 2, "SUBDLG", false, true, 0, true, 0, true, 1062, true, 125, true, 0, -1, "alTop", "", false, "", 0, "", false, 0, "", true, 12761254, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fShuttleMove.Panel1.Panel2.sbShuttleSensor", "sbShuttleSensor", "IDC_SHUTTLEMOVE_SBSHUTTLESENSOR", "TSpeedButton", "fShuttleMove.Panel1.Panel2", "fShuttleMove.Panel1.Panel2", 0, 3, "LEAF", true, true, 844, true, 33, true, 65, true, 68, false, 0, 0, "", "", true, "Arial", -11, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fShuttleMove.Panel1.Panel2.sbSensorLatch", "sbSensorLatch", "IDC_SHUTTLEMOVE_SBSENSORLATCH", "TSpeedButton", "fShuttleMove.Panel1.Panel2", "fShuttleMove.Panel1.Panel2", 1, 3, "LEAF", true, true, 916, true, 34, true, 66, true, 65, false, 0, 0, "", "", true, "Arial", -11, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fShuttleMove.Panel1.Panel2.sbBarCode", "sbBarCode", "IDC_SHUTTLEMOVE_SBBARCODE", "TSpeedButton", "fShuttleMove.Panel1.Panel2", "fShuttleMove.Panel1.Panel2", 2, 3, "LEAF", true, true, 988, true, 34, true, 66, true, 65, false, 0, -1, "", "", true, "Arial", -11, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fShuttleMove.Panel1.Panel2.gbShuttleMove", "gbShuttleMove", "IDD_SHUTTLEMOVE_PANEL1_PANEL2_GBSHUTTLEMOVE", "TGroupBox", "fShuttleMove.Panel1.Panel2", "fShuttleMove.Panel1.Panel2", 3, 3, "SUBDLG", false, true, 0, true, 0, true, 605, true, 125, true, 0, -1, "alLeft", "", true, "MS Sans Serif", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fShuttleMove.Panel1.Panel2.gbShuttleMove.btShu2Right", "btShu2Right", "IDC_SHUTTLEMOVE_BTSHU2RIGHT", "TButton", "fShuttleMove.Panel1.Panel2.gbShuttleMove", "fShuttleMove.Panel1.Panel2.gbShuttleMove", 0, 4, "LEAF", false, true, 391, true, 24, true, 200, true, 40, true, 2, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fShuttleMove.Panel1.Panel2.gbShuttleMove.btShu1Right", "btShu1Right", "IDC_SHUTTLEMOVE_BTSHU1RIGHT", "TButton", "fShuttleMove.Panel1.Panel2.gbShuttleMove", "fShuttleMove.Panel1.Panel2.gbShuttleMove", 1, 4, "LEAF", false, true, 391, true, 76, true, 200, true, 40, true, 5, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fShuttleMove.Panel1.Panel2.gbShuttleMove.btShu2Left", "btShu2Left", "IDC_SHUTTLEMOVE_BTSHU2LEFT", "TButton", "fShuttleMove.Panel1.Panel2.gbShuttleMove", "fShuttleMove.Panel1.Panel2.gbShuttleMove", 2, 4, "LEAF", false, true, 178, true, 24, true, 200, true, 40, true, 1, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fShuttleMove.Panel1.Panel2.gbShuttleMove.btShu1Left", "btShu1Left", "IDC_SHUTTLEMOVE_BTSHU1LEFT", "TButton", "fShuttleMove.Panel1.Panel2.gbShuttleMove", "fShuttleMove.Panel1.Panel2.gbShuttleMove", 3, 4, "LEAF", false, true, 178, true, 76, true, 200, true, 40, true, 4, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fShuttleMove.Panel1.Panel2.gbShuttleMove.palSh2Encoder", "palSh2Encoder", "IDC_SHUTTLEMOVE_PALSH2ENCODER", "TPanel", "fShuttleMove.Panel1.Panel2.gbShuttleMove", "fShuttleMove.Panel1.Panel2.gbShuttleMove", 4, 4, "LEAF", false, true, 12, true, 24, true, 157, true, 40, true, 0, -1, "", "", true, "MS Sans Serif", -23, "", true, 16777215, "clWhite", true, 9534289, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fShuttleMove.Panel1.Panel2.gbShuttleMove.palSh1Encoder", "palSh1Encoder", "IDC_SHUTTLEMOVE_PALSH1ENCODER", "TPanel", "fShuttleMove.Panel1.Panel2.gbShuttleMove", "fShuttleMove.Panel1.Panel2.gbShuttleMove", 5, 4, "LEAF", false, true, 12, true, 76, true, 157, true, 40, true, 3, -1, "", "", true, "MS Sans Serif", -23, "", true, 16777215, "clWhite", true, 9534289, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fShuttleMove.Panel1.Panel2.gbScanOutShuttle", "gbScanOutShuttle", "IDD_SHUTTLEMOVE_PANEL1_PANEL2_GBSCANOUTSHUTTLE", "TGroupBox", "fShuttleMove.Panel1.Panel2", "fShuttleMove.Panel1.Panel2", 4, 3, "SUBDLG", false, true, 605, true, 0, true, 222, true, 125, true, 1, -1, "alLeft", "", true, "MS Sans Serif", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fShuttleMove.Panel1.Panel2.gbScanOutShuttle.btScanOutShu2", "btScanOutShu2", "IDC_SHUTTLEMOVE_BTSCANOUTSHU2", "TButton", "fShuttleMove.Panel1.Panel2.gbScanOutShuttle", "fShuttleMove.Panel1.Panel2.gbScanOutShuttle", 0, 4, "LEAF", false, true, 12, true, 24, true, 200, true, 40, true, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fShuttleMove.Panel1.Panel2.gbScanOutShuttle.btScanOutShu1", "btScanOutShu1", "IDC_SHUTTLEMOVE_BTSCANOUTSHU1", "TButton", "fShuttleMove.Panel1.Panel2.gbScanOutShuttle", "fShuttleMove.Panel1.Panel2.gbScanOutShuttle", 1, 4, "LEAF", false, true, 12, true, 76, true, 200, true, 40, true, 1, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fShuttleMove.Panel1.Panel3", "Panel3", "IDD_SHUTTLEMOVE_PANEL1_PANEL3", "TPanel", "fShuttleMove.Panel1", "fShuttleMove.Panel1", 1, 2, "SUBDLG", false, true, 0, true, 125, true, 1062, true, 588, true, 1, -1, "alTop", "", false, "", 0, "", false, 0, "", true, 12761254, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fShuttleMove.Panel1.Panel3.gbInFiberCheck", "gbInFiberCheck", "IDD_SHUTTLEMOVE_PANEL1_PANEL3_GBINFIBERCHECK", "TGroupBox", "fShuttleMove.Panel1.Panel3", "fShuttleMove.Panel1.Panel3", 0, 3, "SUBDLG", false, true, 0, true, 0, true, 1062, true, 116, true, 0, -1, "alTop", "", true, "MS Sans Serif", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fShuttleMove.Panel1.Panel3.gbInFiberCheck.btnInSH1Sen7DetectPos", "btnInSH1Sen7DetectPos", "IDC_SHUTTLEMOVE_BTNINSH1SEN7DETECTPOS", "TSpeedButton", "fShuttleMove.Panel1.Panel3.gbInFiberCheck", "fShuttleMove.Panel1.Panel3.gbInFiberCheck", 0, 4, "LEAF", true, true, 10, true, 73, true, 239, true, 30, false, 0, -1, "", "", true, "MS Sans Serif", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fShuttleMove.Panel1.Panel3.gbInFiberCheck.btnInSH2Sen7DetectPos", "btnInSH2Sen7DetectPos", "IDC_SHUTTLEMOVE_BTNINSH2SEN7DETECTPOS", "TSpeedButton", "fShuttleMove.Panel1.Panel3.gbInFiberCheck", "fShuttleMove.Panel1.Panel3.gbInFiberCheck", 1, 4, "LEAF", true, true, 10, true, 29, true, 239, true, 30, false, 0, -1, "", "", true, "MS Sans Serif", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fShuttleMove.Panel1.Panel3.gbInFiberCheck.edInSH2Sen7DetectPos", "edInSH2Sen7DetectPos", "IDC_SHUTTLEMOVE_EDINSH2SEN7DETECTPOS", "TEdit", "fShuttleMove.Panel1.Panel3.gbInFiberCheck", "fShuttleMove.Panel1.Panel3.gbInFiberCheck", 2, 4, "LEAF", false, true, 265, true, 27, true, 100, true, 28, true, 0, -1, "", "", true, "MS Sans Serif", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fShuttleMove.Panel1.Panel3.gbInFiberCheck.edInSH1Sen7DetectPos", "edInSH1Sen7DetectPos", "IDC_SHUTTLEMOVE_EDINSH1SEN7DETECTPOS", "TEdit", "fShuttleMove.Panel1.Panel3.gbInFiberCheck", "fShuttleMove.Panel1.Panel3.gbInFiberCheck", 3, 4, "LEAF", false, true, 265, true, 75, true, 100, true, 28, true, 2, -1, "", "", true, "MS Sans Serif", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fShuttleMove.Panel1.Panel3.gbInFiberCheck.mtedInSHSen7DetectPos", "mtedInSHSen7DetectPos", "IDC_SHUTTLEMOVE_MTEDINSHSEN7DETECTPOS", "TTMyTray", "fShuttleMove.Panel1.Panel3.gbInFiberCheck", "fShuttleMove.Panel1.Panel3.gbInFiberCheck", 4, 4, "LEAF", false, true, 380, true, 24, true, 661, true, 80, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 1, &kShuttleMoveCustomProps[0] },
    { "fShuttleMove.Panel1.Panel3.gbBarCode", "gbBarCode", "IDD_SHUTTLEMOVE_PANEL1_PANEL3_GBBARCODE", "TGroupBox", "fShuttleMove.Panel1.Panel3", "fShuttleMove.Panel1.Panel3", 1, 3, "SUBDLG", false, true, 0, true, 116, true, 1062, true, 108, true, 1, -1, "alTop", "", true, "MS Sans Serif", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fShuttleMove.Panel1.Panel3.gbBarCode.btInSH1BarCodePos", "btInSH1BarCodePos", "IDC_SHUTTLEMOVE_BTINSH1BARCODEPOS", "TSpeedButton", "fShuttleMove.Panel1.Panel3.gbBarCode", "fShuttleMove.Panel1.Panel3.gbBarCode", 0, 4, "LEAF", true, true, 10, true, 66, true, 239, true, 30, false, 0, -1, "", "", true, "MS Sans Serif", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fShuttleMove.Panel1.Panel3.gbBarCode.btInSH2BarCodePos", "btInSH2BarCodePos", "IDC_SHUTTLEMOVE_BTINSH2BARCODEPOS", "TSpeedButton", "fShuttleMove.Panel1.Panel3.gbBarCode", "fShuttleMove.Panel1.Panel3.gbBarCode", 1, 4, "LEAF", true, true, 10, true, 26, true, 239, true, 30, false, 0, -1, "", "", true, "MS Sans Serif", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fShuttleMove.Panel1.Panel3.gbBarCode.edInSH1BarCodePos", "edInSH1BarCodePos", "IDC_SHUTTLEMOVE_EDINSH1BARCODEPOS", "TEdit", "fShuttleMove.Panel1.Panel3.gbBarCode", "fShuttleMove.Panel1.Panel3.gbBarCode", 2, 4, "LEAF", false, true, 265, true, 66, true, 100, true, 28, true, 2, -1, "", "", true, "MS Sans Serif", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fShuttleMove.Panel1.Panel3.gbBarCode.edInSH2BarCodePos", "edInSH2BarCodePos", "IDC_SHUTTLEMOVE_EDINSH2BARCODEPOS", "TEdit", "fShuttleMove.Panel1.Panel3.gbBarCode", "fShuttleMove.Panel1.Panel3.gbBarCode", 3, 4, "LEAF", false, true, 265, true, 26, true, 100, true, 28, true, 0, -1, "", "", true, "MS Sans Serif", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fShuttleMove.Panel1.Panel3.gbBarCode.mtInSHBarCodePos", "mtInSHBarCodePos", "IDC_SHUTTLEMOVE_MTINSHBARCODEPOS", "TTMyTray", "fShuttleMove.Panel1.Panel3.gbBarCode", "fShuttleMove.Panel1.Panel3.gbBarCode", 4, 4, "LEAF", false, true, 380, true, 24, true, 661, true, 80, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 1, &kShuttleMoveCustomProps[1] },
    { "fShuttleMove.Panel1.Panel3.gbBarCode.btnTStep", "btnTStep", "IDC_SHUTTLEMOVE_BTNTSTEP", "TButton", "fShuttleMove.Panel1.Panel3.gbBarCode", "fShuttleMove.Panel1.Panel3.gbBarCode", 5, 4, "LEAF", false, true, 986, true, 79, true, 75, true, 25, true, 3, 0, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fShuttleMove.Panel1.Panel3.gbOutFiberCheck", "gbOutFiberCheck", "IDD_SHUTTLEMOVE_PANEL1_PANEL3_GBOUTFIBERCHECK", "TGroupBox", "fShuttleMove.Panel1.Panel3", "fShuttleMove.Panel1.Panel3", 2, 3, "SUBDLG", false, true, 0, true, 373, true, 1062, true, 213, true, 2, -1, "alTop", "", true, "MS Sans Serif", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fShuttleMove.Panel1.Panel3.gbOutFiberCheck.btOutSH1ZDetectPos", "btOutSH1ZDetectPos", "IDC_SHUTTLEMOVE_BTOUTSH1ZDETECTPOS", "TSpeedButton", "fShuttleMove.Panel1.Panel3.gbOutFiberCheck", "fShuttleMove.Panel1.Panel3.gbOutFiberCheck", 0, 4, "LEAF", true, true, 10, true, 62, true, 239, true, 30, false, 0, -1, "", "", true, "MS Sans Serif", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fShuttleMove.Panel1.Panel3.gbOutFiberCheck.btOutSH2ZDetectPos", "btOutSH2ZDetectPos", "IDC_SHUTTLEMOVE_BTOUTSH2ZDETECTPOS", "TSpeedButton", "fShuttleMove.Panel1.Panel3.gbOutFiberCheck", "fShuttleMove.Panel1.Panel3.gbOutFiberCheck", 1, 4, "LEAF", true, true, 10, true, 23, true, 239, true, 30, false, 0, -1, "", "", true, "MS Sans Serif", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fShuttleMove.Panel1.Panel3.gbOutFiberCheck.btOutSH1OneRowDetectPos", "btOutSH1OneRowDetectPos", "IDC_SHUTTLEMOVE_BTOUTSH1ONEROWDETECTPOS", "TSpeedButton", "fShuttleMove.Panel1.Panel3.gbOutFiberCheck", "fShuttleMove.Panel1.Panel3.gbOutFiberCheck", 2, 4, "LEAF", true, true, 10, true, 141, true, 239, true, 30, false, 0, -1, "", "", true, "MS Sans Serif", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fShuttleMove.Panel1.Panel3.gbOutFiberCheck.btOutSH2OneRowDetectPos", "btOutSH2OneRowDetectPos", "IDC_SHUTTLEMOVE_BTOUTSH2ONEROWDETECTPOS", "TSpeedButton", "fShuttleMove.Panel1.Panel3.gbOutFiberCheck", "fShuttleMove.Panel1.Panel3.gbOutFiberCheck", 3, 4, "LEAF", true, true, 10, true, 102, true, 239, true, 30, false, 0, -1, "", "", true, "MS Sans Serif", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fShuttleMove.Panel1.Panel3.gbOutFiberCheck.btRetry", "btRetry", "IDC_SHUTTLEMOVE_BTRETRY", "TButton", "fShuttleMove.Panel1.Panel3.gbOutFiberCheck", "fShuttleMove.Panel1.Panel3.gbOutFiberCheck", 4, 4, "LEAF", false, true, 12, true, 181, true, 75, true, 25, true, 5, 0, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fShuttleMove.Panel1.Panel3.gbOutFiberCheck.edOutSH1OneRowDetectPos", "edOutSH1OneRowDetectPos", "IDC_SHUTTLEMOVE_EDOUTSH1ONEROWDETECTPOS", "TEdit", "fShuttleMove.Panel1.Panel3.gbOutFiberCheck", "fShuttleMove.Panel1.Panel3.gbOutFiberCheck", 5, 4, "LEAF", false, true, 265, true, 142, true, 100, true, 28, true, 3, -1, "", "", true, "MS Sans Serif", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fShuttleMove.Panel1.Panel3.gbOutFiberCheck.edOutSH2OneRowDetectPos", "edOutSH2OneRowDetectPos", "IDC_SHUTTLEMOVE_EDOUTSH2ONEROWDETECTPOS", "TEdit", "fShuttleMove.Panel1.Panel3.gbOutFiberCheck", "fShuttleMove.Panel1.Panel3.gbOutFiberCheck", 6, 4, "LEAF", false, true, 265, true, 103, true, 100, true, 28, true, 2, -1, "", "", true, "MS Sans Serif", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fShuttleMove.Panel1.Panel3.gbOutFiberCheck.edOutSH1ZDetectPos", "edOutSH1ZDetectPos", "IDC_SHUTTLEMOVE_EDOUTSH1ZDETECTPOS", "TEdit", "fShuttleMove.Panel1.Panel3.gbOutFiberCheck", "fShuttleMove.Panel1.Panel3.gbOutFiberCheck", 7, 4, "LEAF", false, true, 265, true, 62, true, 100, true, 28, true, 1, -1, "", "", true, "MS Sans Serif", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fShuttleMove.Panel1.Panel3.gbOutFiberCheck.edOutSH2ZDetectPos", "edOutSH2ZDetectPos", "IDC_SHUTTLEMOVE_EDOUTSH2ZDETECTPOS", "TEdit", "fShuttleMove.Panel1.Panel3.gbOutFiberCheck", "fShuttleMove.Panel1.Panel3.gbOutFiberCheck", 8, 4, "LEAF", false, true, 265, true, 23, true, 100, true, 28, true, 0, -1, "", "", true, "MS Sans Serif", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fShuttleMove.Panel1.Panel3.gbOutFiberCheck.mtOutSHDetectPos", "mtOutSHDetectPos", "IDC_SHUTTLEMOVE_MTOUTSHDETECTPOS", "TTMyTray", "fShuttleMove.Panel1.Panel3.gbOutFiberCheck", "fShuttleMove.Panel1.Panel3.gbOutFiberCheck", 9, 4, "LEAF", false, true, 380, true, 24, true, 661, true, 153, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 2, &kShuttleMoveCustomProps[2] },
    { "fShuttleMove.Panel1.Panel3.gbInFiberCheckShtSnLct", "gbInFiberCheckShtSnLct", "IDD_SHUTTLEMOVE_PANEL1_PANEL3_GBINFIBERCHECKSHTSNLCT", "TGroupBox", "fShuttleMove.Panel1.Panel3", "fShuttleMove.Panel1.Panel3", 3, 3, "SUBDLG", false, true, 0, true, 224, true, 1062, true, 149, true, 3, -1, "alTop", "", true, "MS Sans Serif", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fShuttleMove.Panel1.Panel3.gbInFiberCheckShtSnLct.btnInSH1SenICDetectPos", "btnInSH1SenICDetectPos", "IDC_SHUTTLEMOVE_BTNINSH1SENICDETECTPOS", "TSpeedButton", "fShuttleMove.Panel1.Panel3.gbInFiberCheckShtSnLct", "fShuttleMove.Panel1.Panel3.gbInFiberCheckShtSnLct", 0, 4, "LEAF", true, true, 10, true, 69, true, 239, true, 30, false, 0, -1, "", "", true, "MS Sans Serif", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fShuttleMove.Panel1.Panel3.gbInFiberCheckShtSnLct.btnInSH2SenICDetectPos", "btnInSH2SenICDetectPos", "IDC_SHUTTLEMOVE_BTNINSH2SENICDETECTPOS", "TSpeedButton", "fShuttleMove.Panel1.Panel3.gbInFiberCheckShtSnLct", "fShuttleMove.Panel1.Panel3.gbInFiberCheckShtSnLct", 1, 4, "LEAF", true, true, 10, true, 29, true, 239, true, 30, false, 0, -1, "", "", true, "MS Sans Serif", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fShuttleMove.Panel1.Panel3.gbInFiberCheckShtSnLct.btnInSH1SenICDetectAction", "btnInSH1SenICDetectAction", "IDC_SHUTTLEMOVE_BTNINSH1SENICDETECTACTION", "TSpeedButton", "fShuttleMove.Panel1.Panel3.gbInFiberCheckShtSnLct", "fShuttleMove.Panel1.Panel3.gbInFiberCheckShtSnLct", 2, 4, "LEAF", true, true, 40, true, 109, true, 239, true, 30, false, 0, -1, "", "", true, "MS Sans Serif", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fShuttleMove.Panel1.Panel3.gbInFiberCheckShtSnLct.btnInSH2SenICDetectAction", "btnInSH2SenICDetectAction", "IDC_SHUTTLEMOVE_BTNINSH2SENICDETECTACTION", "TSpeedButton", "fShuttleMove.Panel1.Panel3.gbInFiberCheckShtSnLct", "fShuttleMove.Panel1.Panel3.gbInFiberCheckShtSnLct", 3, 4, "LEAF", true, true, 414, true, 109, true, 239, true, 30, false, 0, -1, "", "", true, "MS Sans Serif", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fShuttleMove.Panel1.Panel3.gbInFiberCheckShtSnLct.edInSH2SenICDetectPos", "edInSH2SenICDetectPos", "IDC_SHUTTLEMOVE_EDINSH2SENICDETECTPOS", "TEdit", "fShuttleMove.Panel1.Panel3.gbInFiberCheckShtSnLct", "fShuttleMove.Panel1.Panel3.gbInFiberCheckShtSnLct", 4, 4, "LEAF", false, true, 265, true, 27, true, 100, true, 28, true, 0, -1, "", "", true, "MS Sans Serif", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fShuttleMove.Panel1.Panel3.gbInFiberCheckShtSnLct.edInSH1SenICDetectPos", "edInSH1SenICDetectPos", "IDC_SHUTTLEMOVE_EDINSH1SENICDETECTPOS", "TEdit", "fShuttleMove.Panel1.Panel3.gbInFiberCheckShtSnLct", "fShuttleMove.Panel1.Panel3.gbInFiberCheckShtSnLct", 5, 4, "LEAF", false, true, 265, true, 71, true, 100, true, 28, true, 2, -1, "", "", true, "MS Sans Serif", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fShuttleMove.Panel1.Panel3.gbInFiberCheckShtSnLct.mtedInSHSenICDetectPos", "mtedInSHSenICDetectPos", "IDC_SHUTTLEMOVE_MTEDINSHSENICDETECTPOS", "TTMyTray", "fShuttleMove.Panel1.Panel3.gbInFiberCheckShtSnLct", "fShuttleMove.Panel1.Panel3.gbInFiberCheckShtSnLct", 6, 4, "LEAF", false, true, 380, true, 24, true, 661, true, 80, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 1, &kShuttleMoveCustomProps[4] },
    { "fShuttleMove.Panel1.Panel3.gbInFiberCheckShtSnLct.edInSH1SenICDetectZPos", "edInSH1SenICDetectZPos", "IDC_SHUTTLEMOVE_EDINSH1SENICDETECTZPOS", "TEdit", "fShuttleMove.Panel1.Panel3.gbInFiberCheckShtSnLct", "fShuttleMove.Panel1.Panel3.gbInFiberCheckShtSnLct", 7, 4, "LEAF", false, true, 285, true, 109, true, 100, true, 28, true, 3, -1, "", "", true, "MS Sans Serif", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fShuttleMove.Panel1.Panel3.gbInFiberCheckShtSnLct.edInSH2SenICDetectZPos", "edInSH2SenICDetectZPos", "IDC_SHUTTLEMOVE_EDINSH2SENICDETECTZPOS", "TEdit", "fShuttleMove.Panel1.Panel3.gbInFiberCheckShtSnLct", "fShuttleMove.Panel1.Panel3.gbInFiberCheckShtSnLct", 8, 4, "LEAF", false, true, 660, true, 109, true, 100, true, 28, true, 4, -1, "", "", true, "MS Sans Serif", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fShuttleMove.Panel1.Panel3.gbInFiberCheckShtSnLct.btStart", "btStart", "IDC_SHUTTLEMOVE_BTSTART", "TButton", "fShuttleMove.Panel1.Panel3.gbInFiberCheckShtSnLct", "fShuttleMove.Panel1.Panel3.gbInFiberCheckShtSnLct", 9, 4, "LEAF", false, true, 984, true, 123, true, 75, true, 25, true, 5, 0, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fShuttleMove.Panel1.meShuttleMaintain", "meShuttleMaintain", "IDC_SHUTTLEMOVE_MESHUTTLEMAINTAIN", "TMemo", "fShuttleMove.Panel1", "fShuttleMove.Panel1", 2, 2, "LEAF", false, true, 0, true, 713, true, 1062, true, 221, true, 2, -1, "alClient", "", false, "", 0, "", false, 0, "", true, 14670284, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fShuttleMove.Panel1.Panel4", "Panel4", "IDD_SHUTTLEMOVE_PANEL1_PANEL4", "TPanel", "fShuttleMove.Panel1", "fShuttleMove.Panel1", 3, 2, "SUBDLG", false, true, 0, true, 934, true, 1062, true, 55, true, 3, -1, "alBottom", "", false, "", 0, "", false, 0, "", true, 12761254, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fShuttleMove.Panel1.Panel4.sbUpdate", "sbUpdate", "IDC_SHUTTLEMOVE_SBUPDATE", "TSpeedButton", "fShuttleMove.Panel1.Panel4", "fShuttleMove.Panel1.Panel4", 0, 3, "LEAF", true, true, 61, true, 8, true, 323, true, 43, false, 0, -1, "", "", true, "MS Sans Serif", -24, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fShuttleMove.Panel1.Panel4.sbtExit", "sbtExit", "IDC_SHUTTLEMOVE_SBTEXIT", "TSpeedButton", "fShuttleMove.Panel1.Panel4", "fShuttleMove.Panel1.Panel4", 1, 3, "LEAF", true, true, 551, true, 7, true, 323, true, 44, false, 0, -1, "", "", true, "MS Sans Serif", -24, "", true, 0, "clBlack", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fShuttleMove.Panel1.Panel4.rbTemp", "rbTemp", "IDC_SHUTTLEMOVE_RBTEMP", "TRadioButton", "fShuttleMove.Panel1.Panel4", "fShuttleMove.Panel1.Panel4", 2, 3, "LEAF", false, true, -77, true, 18, true, 102, true, 17, true, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
};

const int kShuttleMoveLayoutCount = 57;

} // namespace ht9045_layout
