// ===========================================================================
//  SmartDiagnostic_layout.gen.cpp
//  DO NOT EDIT -- GENERATED FILE. See the matching _layout.gen.h banner.
// ===========================================================================
#include "SmartDiagnostic_layout.gen.h"

namespace ht9045_layout {

// (no custom-control properties in this form)

const DfmControlLayout kSmartDiagnosticLayout[] = {
    { "fSmartDiagnostic", "fSmartDiagnostic", "", "TfSmartDiagnostic", "", "", 0, 0, "ROOT", false, true, 378, true, 202, false, 0, false, 0, false, 0, -1, "", "", true, "MS Sans Serif", -11, "", true, -2147483640, "clWindowText", true, -2147483633, "clBtnFace", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSmartDiagnostic.pc_SmartDiagnostic", "pc_SmartDiagnostic", "IDC_SMARTDIAGNOSTIC_PC_SMARTDIAGNOSTIC", "TPageControl", "fSmartDiagnostic", "fSmartDiagnostic", 0, 1, "TABHOST", false, true, 0, true, 39, true, 800, true, 616, true, 1, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSmartDiagnostic.pc_SmartDiagnostic.ts_SmartDiagnostic_Summary", "ts_SmartDiagnostic_Summary", "IDD_SMARTDIAGNOSTIC_PC_SMARTDIAGNOSTIC_TS_SMARTDIAGNOSTIC_SUMMARY", "TTabSheet", "fSmartDiagnostic.pc_SmartDiagnostic", "fSmartDiagnostic", 0, 2, "SUBDLG", false, false, 0, false, 0, false, 0, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSmartDiagnostic.pc_SmartDiagnostic.ts_SmartDiagnostic_Summary.pn_SmartDiagnostic_Summary", "pn_SmartDiagnostic_Summary", "IDD_SMARTDIAGNOSTIC_PC_SMARTDIAGNOSTIC_TS_SMARTDIAGNOSTIC_SUMMARY_PN_SMARTDIAGNOSTIC_SUMMARY", "TPanel", "fSmartDiagnostic.pc_SmartDiagnostic.ts_SmartDiagnostic_Summary", "fSmartDiagnostic.pc_SmartDiagnostic.ts_SmartDiagnostic_Summary", 0, 3, "SUBDLG", false, true, 0, true, 0, true, 792, true, 585, true, 0, -1, "alClient", "", false, "", 0, "", false, 0, "", true, 12761254, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSmartDiagnostic.pc_SmartDiagnostic.ts_SmartDiagnostic_Summary.pn_SmartDiagnostic_Summary.sb_SmarDiagnostic_CreateCyliderName", "sb_SmarDiagnostic_CreateCyliderName", "IDC_SMARTDIAGNOSTIC_SB_SMARDIAGNOSTIC_CREATECYLIDERNAME", "TSpeedButton", "fSmartDiagnostic.pc_SmartDiagnostic.ts_SmartDiagnostic_Summary.pn_SmartDiagnostic_Summary", "fSmartDiagnostic.pc_SmartDiagnostic.ts_SmartDiagnostic_Summary.pn_SmartDiagnostic_Summary", 0, 4, "LEAF", true, true, 536, true, 5, true, 244, true, 40, false, 0, -1, "", "", true, "MS Sans Serif", -16, "", true, 8388608, "clNavy", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSmartDiagnostic.pc_SmartDiagnostic.ts_SmartDiagnostic_Summary.pn_SmartDiagnostic_Summary.lb_SmartDiagnostic_SystemTime", "lb_SmartDiagnostic_SystemTime", "IDC_SMARTDIAGNOSTIC_LB_SMARTDIAGNOSTIC_SYSTEMTIME", "TLabel", "fSmartDiagnostic.pc_SmartDiagnostic.ts_SmartDiagnostic_Summary.pn_SmartDiagnostic_Summary", "fSmartDiagnostic.pc_SmartDiagnostic.ts_SmartDiagnostic_Summary.pn_SmartDiagnostic_Summary", 1, 4, "LEAF", true, true, 10, true, 15, true, 90, true, 25, false, 0, -1, "", "", true, "MS Sans Serif", -21, "", true, 0, "clBlack", true, 12761254, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSmartDiagnostic.pc_SmartDiagnostic.ts_SmartDiagnostic_Summary.pn_SmartDiagnostic_Summary.sg_SmartDiagnostic_Summary", "sg_SmartDiagnostic_Summary", "IDC_SMARTDIAGNOSTIC_SG_SMARTDIAGNOSTIC_SUMMARY", "TStringGrid", "fSmartDiagnostic.pc_SmartDiagnostic.ts_SmartDiagnostic_Summary.pn_SmartDiagnostic_Summary", "fSmartDiagnostic.pc_SmartDiagnostic.ts_SmartDiagnostic_Summary.pn_SmartDiagnostic_Summary", 2, 4, "LEAF", false, true, 2, true, 52, true, 788, true, 531, true, 0, -1, "alBottom", "", true, "MS Sans Serif", -13, "", true, 8388608, "clNavy", true, 14670284, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSmartDiagnostic.pc_SmartDiagnostic.ts_SmartDiagnostic_Summary.pn_SmartDiagnostic_Summary.pn_SmartDiagnostic_Time", "pn_SmartDiagnostic_Time", "IDC_SMARTDIAGNOSTIC_PN_SMARTDIAGNOSTIC_TIME", "TPanel", "fSmartDiagnostic.pc_SmartDiagnostic.ts_SmartDiagnostic_Summary.pn_SmartDiagnostic_Summary", "fSmartDiagnostic.pc_SmartDiagnostic.ts_SmartDiagnostic_Summary.pn_SmartDiagnostic_Summary", 3, 4, "LEAF", false, true, 110, true, 15, true, 180, true, 25, true, 1, -1, "", "", true, "MS Sans Serif", -16, "", true, 16777215, "clWhite", true, 8421376, "clTeal", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSmartDiagnostic.pc_SmartDiagnostic.ts_SmartDiagnostic_Setup", "ts_SmartDiagnostic_Setup", "IDD_SMARTDIAGNOSTIC_PC_SMARTDIAGNOSTIC_TS_SMARTDIAGNOSTIC_SETUP", "TTabSheet", "fSmartDiagnostic.pc_SmartDiagnostic", "fSmartDiagnostic", 1, 2, "SUBDLG", false, false, 0, false, 0, false, 0, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSmartDiagnostic.pc_SmartDiagnostic.ts_SmartDiagnostic_Setup.pn_SmartDiagnostic_Setup", "pn_SmartDiagnostic_Setup", "IDD_SMARTDIAGNOSTIC_PC_SMARTDIAGNOSTIC_TS_SMARTDIAGNOSTIC_SETUP_PN_SMARTDIAGNOSTIC_SETUP", "TPanel", "fSmartDiagnostic.pc_SmartDiagnostic.ts_SmartDiagnostic_Setup", "fSmartDiagnostic.pc_SmartDiagnostic.ts_SmartDiagnostic_Setup", 0, 3, "SUBDLG", false, true, 0, true, 0, true, 792, true, 585, true, 0, -1, "alClient", "", false, "", 0, "", false, 0, "", true, 12761254, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSmartDiagnostic.pc_SmartDiagnostic.ts_SmartDiagnostic_Setup.pn_SmartDiagnostic_Setup.pn_SmartDiagnostic_CyliderManagement", "pn_SmartDiagnostic_CyliderManagement", "IDD_SMARTDIAGNOSTIC_PC_SMARTDIAGNOSTIC_TS_SMARTDIAGNOSTIC_SETUP_PN_SMARTDIAGNOSTIC_SETUP_PN_SMARTDIAGNOSTIC_CYLIDERMANAGEMENT", "TPanel", "fSmartDiagnostic.pc_SmartDiagnostic.ts_SmartDiagnostic_Setup.pn_SmartDiagnostic_Setup", "fSmartDiagnostic.pc_SmartDiagnostic.ts_SmartDiagnostic_Setup.pn_SmartDiagnostic_Setup", 0, 4, "SUBDLG", false, true, 10, true, 10, true, 250, true, 543, true, 0, -1, "", "", false, "", 0, "", false, 0, "", true, 12761254, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSmartDiagnostic.pc_SmartDiagnostic.ts_SmartDiagnostic_Setup.pn_SmartDiagnostic_Setup.pn_SmartDiagnostic_CyliderManagement.sb_SmartDiagnostic_ResetRecordCount", "sb_SmartDiagnostic_ResetRecordCount", "IDC_SMARTDIAGNOSTIC_SB_SMARTDIAGNOSTIC_RESETRECORDCOUNT", "TSpeedButton", "fSmartDiagnostic.pc_SmartDiagnostic.ts_SmartDiagnostic_Setup.pn_SmartDiagnostic_Setup.pn_SmartDiagnostic_CyliderManagement", "fSmartDiagnostic.pc_SmartDiagnostic.ts_SmartDiagnostic_Setup.pn_SmartDiagnostic_Setup.pn_SmartDiagnostic_CyliderManagement", 0, 5, "LEAF", true, true, 16, true, 61, true, 210, true, 40, false, 0, -1, "", "", true, "MS Sans Serif", -16, "", true, 8388608, "clNavy", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSmartDiagnostic.pc_SmartDiagnostic.ts_SmartDiagnostic_Setup.pn_SmartDiagnostic_Setup.pn_SmartDiagnostic_CyliderManagement.pn_SmartDiagnostic_CyliderManagementTop", "pn_SmartDiagnostic_CyliderManagementTop", "IDC_SMARTDIAGNOSTIC_PN_SMARTDIAGNOSTIC_CYLIDERMANAGEMENTTOP", "TPanel", "fSmartDiagnostic.pc_SmartDiagnostic.ts_SmartDiagnostic_Setup.pn_SmartDiagnostic_Setup.pn_SmartDiagnostic_CyliderManagement", "fSmartDiagnostic.pc_SmartDiagnostic.ts_SmartDiagnostic_Setup.pn_SmartDiagnostic_Setup.pn_SmartDiagnostic_CyliderManagement", 1, 5, "LEAF", false, true, 2, true, 2, true, 246, true, 20, true, 0, -1, "alTop", "", true, "MS Sans Serif", -19, "fsBold", true, 16777215, "clWhite", true, 9534289, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSmartDiagnostic.pc_SmartDiagnostic.ts_SmartDiagnostic_Setup.pn_SmartDiagnostic_Setup.pn_SmartDiagnostic_CyliderManagement.cob_SmartDiagnostic_CyliderName", "cob_SmartDiagnostic_CyliderName", "IDC_SMARTDIAGNOSTIC_COB_SMARTDIAGNOSTIC_CYLIDERNAME", "TComboBox", "fSmartDiagnostic.pc_SmartDiagnostic.ts_SmartDiagnostic_Setup.pn_SmartDiagnostic_Setup.pn_SmartDiagnostic_CyliderManagement", "fSmartDiagnostic.pc_SmartDiagnostic.ts_SmartDiagnostic_Setup.pn_SmartDiagnostic_Setup.pn_SmartDiagnostic_CyliderManagement", 2, 5, "LEAF", false, true, 20, true, 30, true, 200, true, 28, true, 1, -1, "", "", true, "MS Sans Serif", -16, "", true, 8388608, "clNavy", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSmartDiagnostic.pc_SmartDiagnostic.ts_SmartDiagnostic_Setup.pn_SmartDiagnostic_Setup.pn_SmartDiagnostic_CyliderManagement.sg_SmartDiagnostic_CyliderManagement", "sg_SmartDiagnostic_CyliderManagement", "IDC_SMARTDIAGNOSTIC_SG_SMARTDIAGNOSTIC_CYLIDERMANAGEMENT", "TStringGrid", "fSmartDiagnostic.pc_SmartDiagnostic.ts_SmartDiagnostic_Setup.pn_SmartDiagnostic_Setup.pn_SmartDiagnostic_CyliderManagement", "fSmartDiagnostic.pc_SmartDiagnostic.ts_SmartDiagnostic_Setup.pn_SmartDiagnostic_Setup.pn_SmartDiagnostic_CyliderManagement", 3, 5, "LEAF", false, true, 2, true, 108, true, 246, true, 433, true, 2, -1, "alBottom", "", true, "MS Sans Serif", -13, "", true, 8388608, "clNavy", true, 14670284, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSmartDiagnostic.pc_SmartDiagnostic.ts_SmartDiagnostic_Setup.pn_SmartDiagnostic_Setup.pn_SmartDiagnostic_Parameter", "pn_SmartDiagnostic_Parameter", "IDD_SMARTDIAGNOSTIC_PC_SMARTDIAGNOSTIC_TS_SMARTDIAGNOSTIC_SETUP_PN_SMARTDIAGNOSTIC_SETUP_PN_SMARTDIAGNOSTIC_PARAMETER", "TPanel", "fSmartDiagnostic.pc_SmartDiagnostic.ts_SmartDiagnostic_Setup.pn_SmartDiagnostic_Setup", "fSmartDiagnostic.pc_SmartDiagnostic.ts_SmartDiagnostic_Setup.pn_SmartDiagnostic_Setup", 1, 4, "SUBDLG", false, true, 265, true, 10, true, 515, true, 120, true, 1, -1, "", "", false, "", 0, "", false, 0, "", true, 12761254, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSmartDiagnostic.pc_SmartDiagnostic.ts_SmartDiagnostic_Setup.pn_SmartDiagnostic_Setup.pn_SmartDiagnostic_Parameter.lb_SmartDiagnostic_LimitCountValue", "lb_SmartDiagnostic_LimitCountValue", "IDC_SMARTDIAGNOSTIC_LB_SMARTDIAGNOSTIC_LIMITCOUNTVALUE", "TLabel", "fSmartDiagnostic.pc_SmartDiagnostic.ts_SmartDiagnostic_Setup.pn_SmartDiagnostic_Setup.pn_SmartDiagnostic_Parameter", "fSmartDiagnostic.pc_SmartDiagnostic.ts_SmartDiagnostic_Setup.pn_SmartDiagnostic_Setup.pn_SmartDiagnostic_Parameter", 0, 5, "LEAF", true, true, 10, true, 30, true, 200, true, 25, false, 0, -1, "", "", true, "MS Sans Serif", -16, "", true, 0, "clBlack", true, 12761254, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSmartDiagnostic.pc_SmartDiagnostic.ts_SmartDiagnostic_Setup.pn_SmartDiagnostic_Setup.pn_SmartDiagnostic_Parameter.lb_SmartDiagnostic_LimitCheckTime", "lb_SmartDiagnostic_LimitCheckTime", "IDC_SMARTDIAGNOSTIC_LB_SMARTDIAGNOSTIC_LIMITCHECKTIME", "TLabel", "fSmartDiagnostic.pc_SmartDiagnostic.ts_SmartDiagnostic_Setup.pn_SmartDiagnostic_Setup.pn_SmartDiagnostic_Parameter", "fSmartDiagnostic.pc_SmartDiagnostic.ts_SmartDiagnostic_Setup.pn_SmartDiagnostic_Setup.pn_SmartDiagnostic_Parameter", 1, 5, "LEAF", true, true, 10, true, 70, true, 200, true, 25, false, 0, -1, "", "", true, "MS Sans Serif", -16, "", true, 0, "clBlack", true, 12761254, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSmartDiagnostic.pc_SmartDiagnostic.ts_SmartDiagnostic_Setup.pn_SmartDiagnostic_Setup.pn_SmartDiagnostic_Parameter.pn_SmartDiagnostic_ParameterTop", "pn_SmartDiagnostic_ParameterTop", "IDC_SMARTDIAGNOSTIC_PN_SMARTDIAGNOSTIC_PARAMETERTOP", "TPanel", "fSmartDiagnostic.pc_SmartDiagnostic.ts_SmartDiagnostic_Setup.pn_SmartDiagnostic_Setup.pn_SmartDiagnostic_Parameter", "fSmartDiagnostic.pc_SmartDiagnostic.ts_SmartDiagnostic_Setup.pn_SmartDiagnostic_Setup.pn_SmartDiagnostic_Parameter", 2, 5, "LEAF", false, true, 2, true, 2, true, 511, true, 20, true, 0, -1, "alTop", "", true, "MS Sans Serif", -19, "fsBold", true, 16777215, "clWhite", true, 9534289, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSmartDiagnostic.pc_SmartDiagnostic.ts_SmartDiagnostic_Setup.pn_SmartDiagnostic_Setup.pn_SmartDiagnostic_Parameter.ed_SmartDiagnostic_LimitCountValue", "ed_SmartDiagnostic_LimitCountValue", "IDC_SMARTDIAGNOSTIC_ED_SMARTDIAGNOSTIC_LIMITCOUNTVALUE", "TEdit", "fSmartDiagnostic.pc_SmartDiagnostic.ts_SmartDiagnostic_Setup.pn_SmartDiagnostic_Setup.pn_SmartDiagnostic_Parameter", "fSmartDiagnostic.pc_SmartDiagnostic.ts_SmartDiagnostic_Setup.pn_SmartDiagnostic_Setup.pn_SmartDiagnostic_Parameter", 3, 5, "LEAF", false, true, 220, true, 30, true, 120, true, 24, true, 1, -1, "", "", true, "MS Sans Serif", -13, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSmartDiagnostic.pc_SmartDiagnostic.ts_SmartDiagnostic_Setup.pn_SmartDiagnostic_Setup.pn_SmartDiagnostic_Parameter.ed_SmartDiagnostic_LimitCheckTime", "ed_SmartDiagnostic_LimitCheckTime", "IDC_SMARTDIAGNOSTIC_ED_SMARTDIAGNOSTIC_LIMITCHECKTIME", "TEdit", "fSmartDiagnostic.pc_SmartDiagnostic.ts_SmartDiagnostic_Setup.pn_SmartDiagnostic_Setup.pn_SmartDiagnostic_Parameter", "fSmartDiagnostic.pc_SmartDiagnostic.ts_SmartDiagnostic_Setup.pn_SmartDiagnostic_Setup.pn_SmartDiagnostic_Parameter", 4, 5, "LEAF", false, true, 220, true, 70, true, 120, true, 24, true, 2, -1, "", "", true, "MS Sans Serif", -13, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSmartDiagnostic.pc_SmartDiagnostic.ts_SmartDiagnostic_Setup.pn_SmartDiagnostic_Setup.sgCylinder", "sgCylinder", "IDC_SMARTDIAGNOSTIC_SGCYLINDER", "TStringGrid", "fSmartDiagnostic.pc_SmartDiagnostic.ts_SmartDiagnostic_Setup.pn_SmartDiagnostic_Setup", "fSmartDiagnostic.pc_SmartDiagnostic.ts_SmartDiagnostic_Setup.pn_SmartDiagnostic_Setup", 2, 4, "LEAF", false, true, 264, true, 136, true, 985, true, 417, true, 2, -1, "", "", true, "MS Sans Serif", -13, "", true, 8388608, "clNavy", true, 14670284, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSmartDiagnostic.pc_SmartDiagnostic.ts_SmartDiagnostic_Setup.pn_SmartDiagnostic_Setup.edTemp", "edTemp", "IDC_SMARTDIAGNOSTIC_EDTEMP", "TEdit", "fSmartDiagnostic.pc_SmartDiagnostic.ts_SmartDiagnostic_Setup.pn_SmartDiagnostic_Setup", "fSmartDiagnostic.pc_SmartDiagnostic.ts_SmartDiagnostic_Setup.pn_SmartDiagnostic_Setup", 3, 4, "LEAF", false, true, 267, true, 556, true, 113, true, 21, true, 3, 0, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSmartDiagnostic.pn_SmartDiagnosticTitle", "pn_SmartDiagnosticTitle", "IDD_SMARTDIAGNOSTIC_PN_SMARTDIAGNOSTICTITLE", "TPanel", "fSmartDiagnostic", "fSmartDiagnostic", 1, 1, "SUBDLG", false, true, 0, true, 0, true, 804, true, 50, true, 0, -1, "alTop", "", false, "", 0, "", false, 0, "", true, 12761254, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSmartDiagnostic.pn_SmartDiagnosticTitle.sb_SmartDiagnostic_Setup", "sb_SmartDiagnostic_Setup", "IDC_SMARTDIAGNOSTIC_SB_SMARTDIAGNOSTIC_SETUP", "TSpeedButton", "fSmartDiagnostic.pn_SmartDiagnosticTitle", "fSmartDiagnostic.pn_SmartDiagnosticTitle", 0, 2, "LEAF", true, true, 130, true, 5, true, 120, true, 40, false, 0, -1, "", "", true, "MS Sans Serif", -16, "", true, 8388608, "clNavy", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSmartDiagnostic.pn_SmartDiagnosticTitle.sb_SmartDiagnostic_Summary", "sb_SmartDiagnostic_Summary", "IDC_SMARTDIAGNOSTIC_SB_SMARTDIAGNOSTIC_SUMMARY", "TSpeedButton", "fSmartDiagnostic.pn_SmartDiagnosticTitle", "fSmartDiagnostic.pn_SmartDiagnosticTitle", 1, 2, "LEAF", true, true, 5, true, 5, true, 120, true, 40, false, 0, -1, "", "", true, "MS Sans Serif", -16, "", true, 8388608, "clNavy", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSmartDiagnostic.pn_SmartDiagnosticTitle.sb_SmartDiagnostic_Exit", "sb_SmartDiagnostic_Exit", "IDC_SMARTDIAGNOSTIC_SB_SMARTDIAGNOSTIC_EXIT", "TSpeedButton", "fSmartDiagnostic.pn_SmartDiagnosticTitle", "fSmartDiagnostic.pn_SmartDiagnosticTitle", 2, 2, "LEAF", true, true, 675, true, 5, true, 120, true, 40, false, 0, -1, "", "", true, "MS Sans Serif", -16, "", true, 8388608, "clNavy", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSmartDiagnostic.pn_SmartDiagnosticTitle.sb_SmartDiagnostic_Save", "sb_SmartDiagnostic_Save", "IDC_SMARTDIAGNOSTIC_SB_SMARTDIAGNOSTIC_SAVE", "TSpeedButton", "fSmartDiagnostic.pn_SmartDiagnosticTitle", "fSmartDiagnostic.pn_SmartDiagnosticTitle", 3, 2, "LEAF", true, true, 550, true, 4, true, 120, true, 40, false, 0, -1, "", "", true, "MS Sans Serif", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fSmartDiagnostic.SmartDiagnosticTimer", "SmartDiagnosticTimer", "", "TTimer", "fSmartDiagnostic", "fSmartDiagnostic", 2, 1, "NONVISUAL", false, true, 508, true, 20, false, 0, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
};

const int kSmartDiagnosticLayoutCount = 29;

} // namespace ht9045_layout
