// ===========================================================================
//  uPadInterface_layout.gen.cpp
//  DO NOT EDIT -- GENERATED FILE. See the matching _layout.gen.h banner.
// ===========================================================================
#include "uPadInterface_layout.gen.h"

namespace ht9045_layout {

const DfmCustomProp kuPadInterfaceCustomProps[] = {
    { "Alias", "SnFKPowerOff" },
    { "LEDStyle", "LEDSqLarge" },
    { "Alias", "SnFKPowerOn" },
    { "LEDStyle", "LEDSqLarge" },
    { "Alias", "SnFKReset" },
    { "LEDStyle", "LEDSqLarge" },
    { "Alias", "SnFKPause" },
    { "LEDStyle", "LEDSqLarge" },
    { "Alias", "SnFKHome" },
    { "LEDStyle", "LEDSqLarge" },
    { "Alias", "SnFKStart" },
    { "LEDStyle", "LEDSqLarge" },
    { "Alias", "SnFKOneCycle" },
    { "LEDStyle", "LEDSqLarge" },
    { "Alias", "SnFKRetry" },
    { "LEDStyle", "LEDSqLarge" },
    { "Alias", "SnFKSkip" },
    { "LEDStyle", "LEDSqLarge" },
    { "Alias", "SnFKCleanOut" },
    { "LEDStyle", "LEDSqLarge" },
    { "Alias", "SnFKTrayFeed" },
    { "LEDStyle", "LEDSqLarge" },
    { "Alias", "SnFKTrayEnd" },
    { "LEDStyle", "LEDSqLarge" },
    { "Alias", "SnFKAlarmReset" },
    { "LEDStyle", "LEDSqLarge" },
    { "Alias", "SnFrontPadActive" },
    { "LEDStyle", "LEDSqLarge" },
    { "Alias", "SwFKPowerOff" },
    { "TrueColor", "16744448" },
    { "FalseColor", "8404992" },
    { "FalseFontColor", "clWhite" },
    { "Alias", "SwFKPowerOn" },
    { "TrueColor", "16744448" },
    { "FalseColor", "8404992" },
    { "FalseFontColor", "clWhite" },
    { "Alias", "SwFrontActiveLed" },
    { "TrueColor", "16744448" },
    { "FalseColor", "8404992" },
    { "FalseFontColor", "clWhite" },
    { "Alias", "SwFKStart" },
    { "TrueColor", "16744448" },
    { "FalseColor", "8404992" },
    { "FalseFontColor", "clWhite" },
    { "Alias", "SwFKHome" },
    { "TrueColor", "16744448" },
    { "FalseColor", "8404992" },
    { "FalseFontColor", "clWhite" },
    { "Alias", "SwFKPause" },
    { "TrueColor", "16744448" },
    { "FalseColor", "8404992" },
    { "FalseFontColor", "clWhite" },
    { "Alias", "SwFKReset" },
    { "TrueColor", "16744448" },
    { "FalseColor", "8404992" },
    { "FalseFontColor", "clWhite" },
    { "Alias", "SwFKOneCycle" },
    { "TrueColor", "16744448" },
    { "FalseColor", "8404992" },
    { "FalseFontColor", "clWhite" },
    { "Alias", "SwFKRetry" },
    { "TrueColor", "16744448" },
    { "FalseColor", "8404992" },
    { "FalseFontColor", "clWhite" },
    { "Alias", "SwFKSkip" },
    { "TrueColor", "16744448" },
    { "FalseColor", "8404992" },
    { "FalseFontColor", "clWhite" },
    { "Alias", "SwFKCleanOut" },
    { "TrueColor", "16744448" },
    { "FalseColor", "8404992" },
    { "FalseFontColor", "clWhite" },
    { "Alias", "SwFKAlarmReset" },
    { "TrueColor", "16744448" },
    { "FalseColor", "8404992" },
    { "FalseFontColor", "clWhite" },
    { "Alias", "SwFKTrayEnd" },
    { "TrueColor", "16744448" },
    { "FalseColor", "8404992" },
    { "FalseFontColor", "clWhite" },
    { "Alias", "SwFKTrayFeed" },
    { "TrueColor", "16744448" },
    { "FalseColor", "8404992" },
    { "FalseFontColor", "clWhite" },
    { "Alias", "SnRKPowerOff" },
    { "LEDStyle", "LEDSqLarge" },
    { "Alias", "SnRKPowerOn" },
    { "LEDStyle", "LEDSqLarge" },
    { "Alias", "SnRKReset" },
    { "LEDStyle", "LEDSqLarge" },
    { "Alias", "SnRKPause" },
    { "LEDStyle", "LEDSqLarge" },
    { "Alias", "SnRKHome" },
    { "LEDStyle", "LEDSqLarge" },
    { "Alias", "SnRKStart" },
    { "LEDStyle", "LEDSqLarge" },
    { "Alias", "SnRKOneCycle" },
    { "LEDStyle", "LEDSqLarge" },
    { "Alias", "SnRKRetry" },
    { "LEDStyle", "LEDSqLarge" },
    { "Alias", "SnRKSkip" },
    { "LEDStyle", "LEDSqLarge" },
    { "Alias", "SnRKCleanOut" },
    { "LEDStyle", "LEDSqLarge" },
    { "Alias", "SnRKTrayFeed" },
    { "LEDStyle", "LEDSqLarge" },
    { "Alias", "SnRKTrayEnd" },
    { "LEDStyle", "LEDSqLarge" },
    { "Alias", "SnRKAlarmReset" },
    { "LEDStyle", "LEDSqLarge" },
    { "Alias", "SnRKManualStep" },
    { "LEDStyle", "LEDSqLarge" },
    { "Alias", "SnRKManualTStart" },
    { "LEDStyle", "LEDSqLarge" },
    { "Alias", "SnRearPadActive" },
    { "LEDStyle", "LEDSqLarge" },
    { "Alias", "SnRKSafeLock" },
    { "LEDStyle", "LEDSqLarge" },
    { "Alias", "SwRKPowerOff" },
    { "TrueColor", "16744448" },
    { "FalseColor", "8404992" },
    { "FalseFontColor", "clWhite" },
    { "Alias", "SwRKPowerOn" },
    { "TrueColor", "16744448" },
    { "FalseColor", "8404992" },
    { "FalseFontColor", "clWhite" },
    { "Alias", "SwRKPause" },
    { "TrueColor", "16744448" },
    { "FalseColor", "8404992" },
    { "FalseFontColor", "clWhite" },
    { "Alias", "SwRKReset" },
    { "TrueColor", "16744448" },
    { "FalseColor", "8404992" },
    { "FalseFontColor", "clWhite" },
    { "Alias", "SwRKOneCycle" },
    { "TrueColor", "16744448" },
    { "FalseColor", "8404992" },
    { "FalseFontColor", "clWhite" },
    { "Alias", "SwRKRetry" },
    { "TrueColor", "16744448" },
    { "FalseColor", "8404992" },
    { "FalseFontColor", "clWhite" },
    { "Alias", "SwRKSkip" },
    { "TrueColor", "16744448" },
    { "FalseColor", "8404992" },
    { "FalseFontColor", "clWhite" },
    { "Alias", "SwRKHome" },
    { "TrueColor", "16744448" },
    { "FalseColor", "8404992" },
    { "FalseFontColor", "clWhite" },
    { "Alias", "SwRKStart" },
    { "TrueColor", "16744448" },
    { "FalseColor", "8404992" },
    { "FalseFontColor", "clWhite" },
    { "Alias", "SwRKCleanOut" },
    { "TrueColor", "16744448" },
    { "FalseColor", "8404992" },
    { "FalseFontColor", "clWhite" },
    { "Alias", "SwRKAlarmReset" },
    { "TrueColor", "16744448" },
    { "FalseColor", "8404992" },
    { "FalseFontColor", "clWhite" },
    { "Alias", "SwRKTrayEnd" },
    { "TrueColor", "16744448" },
    { "FalseColor", "8404992" },
    { "FalseFontColor", "clWhite" },
    { "Alias", "SwRKTrayFeed" },
    { "TrueColor", "16744448" },
    { "FalseColor", "8404992" },
    { "FalseFontColor", "clWhite" },
    { "Alias", "SwRKManualStep" },
    { "TrueColor", "16744448" },
    { "FalseColor", "8404992" },
    { "FalseFontColor", "clWhite" },
    { "Alias", "SwRKManualTStart" },
    { "TrueColor", "16744448" },
    { "FalseColor", "8404992" },
    { "FalseFontColor", "clWhite" },
    { "Alias", "SwRKManualStep" },
    { "TrueColor", "16744448" },
    { "FalseColor", "8404992" },
    { "FalseFontColor", "clWhite" },
    { "Alias", "SwRearActiveLed" },
    { "TrueColor", "16744448" },
    { "FalseColor", "8404992" },
    { "FalseFontColor", "clWhite" },
};

const DfmControlLayout kuPadInterfaceLayout[] = {
    { "fPadInterface", "fPadInterface", "", "TfPadInterface", "", "", 0, 0, "ROOT", false, true, 759, true, 183, false, 0, false, 0, false, 0, -1, "", "", true, "MS Sans Serif", -11, "", true, -2147483640, "clWindowText", true, 12761254, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fPadInterface.pc_PadInterface", "pc_PadInterface", "IDC_UPADINTERFACE_PC_PADINTERFACE", "TPageControl", "fPadInterface", "fPadInterface", 0, 1, "TABHOST", false, true, 0, true, 0, true, 935, true, 473, true, 1, -1, "alClient", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fPadInterface.pn_PadInterfaceTitle", "pn_PadInterfaceTitle", "IDD_UPADINTERFACE_PN_PADINTERFACETITLE", "TPanel", "fPadInterface", "fPadInterface", 1, 1, "SUBDLG", false, true, 0, true, 679, true, 935, true, 73, true, 3, -1, "alBottom", "", false, "", 0, "", false, 0, "", true, 12761254, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fPadInterface.pn_PadInterfaceTitle.sb_PadInterface_Exit", "sb_PadInterface_Exit", "IDC_UPADINTERFACE_SB_PADINTERFACE_EXIT", "TSpeedButton", "fPadInterface.pn_PadInterfaceTitle", "fPadInterface.pn_PadInterfaceTitle", 0, 2, "LEAF", true, true, 569, true, 13, true, 200, true, 40, false, 0, -1, "", "", true, "Arial", -16, "", true, 8388608, "clNavy", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fPadInterface.sb_PadInterface_MainPage", "sb_PadInterface_MainPage", "IDD_UPADINTERFACE_SB_PADINTERFACE_MAINPAGE", "TPanel", "fPadInterface", "fPadInterface", 2, 1, "SUBDLG", false, true, 0, true, 0, true, 935, true, 473, true, 0, -1, "alClient", "", false, "", 0, "", false, 0, "", true, 12761254, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front", "pn_PadInterface_Front", "IDD_UPADINTERFACE_SB_PADINTERFACE_MAINPAGE_PN_PADINTERFACE_FRONT", "TPanel", "fPadInterface.sb_PadInterface_MainPage", "fPadInterface.sb_PadInterface_MainPage", 0, 2, "SUBDLG", false, true, 0, true, 0, true, 460, true, 353, true, 0, -1, "", "", false, "", 0, "", false, 0, "", true, 14670284, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front.ml_PadInterface_FrontPowerOff", "ml_PadInterface_FrontPowerOff", "IDC_UPADINTERFACE_ML_PADINTERFACE_FRONTPOWEROFF", "TMyLed", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front", 0, 3, "LEAF", true, true, 49, true, 41, true, 22, true, 22, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 2, &kuPadInterfaceCustomProps[0] },
    { "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front.ml_PadInterface_FrontPowerOn", "ml_PadInterface_FrontPowerOn", "IDC_UPADINTERFACE_ML_PADINTERFACE_FRONTPOWERON", "TMyLed", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front", 1, 3, "LEAF", true, true, 162, true, 41, true, 22, true, 22, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 2, &kuPadInterfaceCustomProps[2] },
    { "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front.ml_PadInterface_FrontReset", "ml_PadInterface_FrontReset", "IDC_UPADINTERFACE_ML_PADINTERFACE_FRONTRESET", "TMyLed", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front", 2, 3, "LEAF", true, true, 49, true, 116, true, 22, true, 22, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 2, &kuPadInterfaceCustomProps[4] },
    { "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front.ml_PadInterface_FrontPause", "ml_PadInterface_FrontPause", "IDC_UPADINTERFACE_ML_PADINTERFACE_FRONTPAUSE", "TMyLed", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front", 3, 3, "LEAF", true, true, 162, true, 116, true, 22, true, 22, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 2, &kuPadInterfaceCustomProps[6] },
    { "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front.ml_PadInterface_FrontHome", "ml_PadInterface_FrontHome", "IDC_UPADINTERFACE_ML_PADINTERFACE_FRONTHOME", "TMyLed", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front", 4, 3, "LEAF", true, true, 275, true, 116, true, 22, true, 22, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 2, &kuPadInterfaceCustomProps[8] },
    { "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front.ml_PadInterface_FrontStart", "ml_PadInterface_FrontStart", "IDC_UPADINTERFACE_ML_PADINTERFACE_FRONTSTART", "TMyLed", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front", 5, 3, "LEAF", true, true, 388, true, 116, true, 22, true, 22, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 2, &kuPadInterfaceCustomProps[10] },
    { "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front.ml_PadInterface_FrontOneCycle", "ml_PadInterface_FrontOneCycle", "IDC_UPADINTERFACE_ML_PADINTERFACE_FRONTONECYCLE", "TMyLed", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front", 6, 3, "LEAF", true, true, 49, true, 192, true, 22, true, 22, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 2, &kuPadInterfaceCustomProps[12] },
    { "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front.ml_PadInterface_FrontRetry", "ml_PadInterface_FrontRetry", "IDC_UPADINTERFACE_ML_PADINTERFACE_FRONTRETRY", "TMyLed", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front", 7, 3, "LEAF", true, true, 162, true, 192, true, 22, true, 22, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 2, &kuPadInterfaceCustomProps[14] },
    { "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front.ml_PadInterface_FrontSkip", "ml_PadInterface_FrontSkip", "IDC_UPADINTERFACE_ML_PADINTERFACE_FRONTSKIP", "TMyLed", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front", 8, 3, "LEAF", true, true, 275, true, 192, true, 22, true, 22, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 2, &kuPadInterfaceCustomProps[16] },
    { "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front.ml_PadInterface_FrontCleanOut", "ml_PadInterface_FrontCleanOut", "IDC_UPADINTERFACE_ML_PADINTERFACE_FRONTCLEANOUT", "TMyLed", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front", 9, 3, "LEAF", true, true, 388, true, 192, true, 22, true, 22, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 2, &kuPadInterfaceCustomProps[18] },
    { "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front.ml_PadInterface_FrontTrayFeed", "ml_PadInterface_FrontTrayFeed", "IDC_UPADINTERFACE_ML_PADINTERFACE_FRONTTRAYFEED", "TMyLed", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front", 10, 3, "LEAF", true, true, 49, true, 268, true, 22, true, 22, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 2, &kuPadInterfaceCustomProps[20] },
    { "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front.ml_PadInterface_FrontTrayEnd", "ml_PadInterface_FrontTrayEnd", "IDC_UPADINTERFACE_ML_PADINTERFACE_FRONTTRAYEND", "TMyLed", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front", 11, 3, "LEAF", true, true, 162, true, 268, true, 22, true, 22, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 2, &kuPadInterfaceCustomProps[22] },
    { "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front.ml_PadInterface_FrontAlarmReset", "ml_PadInterface_FrontAlarmReset", "IDC_UPADINTERFACE_ML_PADINTERFACE_FRONTALARMRESET", "TMyLed", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front", 12, 3, "LEAF", true, true, 275, true, 268, true, 22, true, 22, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 2, &kuPadInterfaceCustomProps[24] },
    { "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front.ml_PadInterface_Front", "ml_PadInterface_Front", "IDC_UPADINTERFACE_ML_PADINTERFACE_FRONT", "TMyLed", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front", 13, 3, "LEAF", true, true, 388, true, 73, true, 22, true, 22, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 2, &kuPadInterfaceCustomProps[26] },
    { "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front.pn_PadInterface_FrontTop", "pn_PadInterface_FrontTop", "IDC_UPADINTERFACE_PN_PADINTERFACE_FRONTTOP", "TPanel", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front", 14, 3, "LEAF", false, true, 2, true, 2, true, 456, true, 32, true, 0, -1, "alTop", "", true, "Arial", -19, "fsBold", true, 16777215, "clWhite", true, 9534289, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front.sb_PadInterface_FrontPowerOff", "sb_PadInterface_FrontPowerOff", "IDC_UPADINTERFACE_SB_PADINTERFACE_FRONTPOWEROFF", "TBtnPanelLane", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front", 15, 3, "LEAF", false, true, 12, true, 62, true, 96, true, 48, true, 1, -1, "", "", true, "Arial", -15, "fsBold", true, 16777215, "clWhite", true, 8404992, "", true, 16744448, "", true, 8404992, "", false, 0, "", true, 16777215, "clWhite", 4, &kuPadInterfaceCustomProps[28] },
    { "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front.sb_PadInterface_FrontPowerOn", "sb_PadInterface_FrontPowerOn", "IDC_UPADINTERFACE_SB_PADINTERFACE_FRONTPOWERON", "TBtnPanelLane", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front", 16, 3, "LEAF", false, true, 125, true, 62, true, 96, true, 48, true, 2, -1, "", "", true, "Arial", -15, "fsBold", true, 16777215, "clWhite", true, 8404992, "", true, 16744448, "", true, 8404992, "", false, 0, "", true, 16777215, "clWhite", 4, &kuPadInterfaceCustomProps[32] },
    { "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front.sb_PadInterface_Front", "sb_PadInterface_Front", "IDC_UPADINTERFACE_SB_PADINTERFACE_FRONT", "TBtnPanelLane", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front", 17, 3, "LEAF", false, true, 351, true, 62, true, 96, true, 48, true, 3, -1, "", "", true, "Arial", -15, "fsBold", true, 16777215, "clWhite", true, 8404992, "", true, 16744448, "", true, 8404992, "", false, 0, "", true, 16777215, "clWhite", 4, &kuPadInterfaceCustomProps[36] },
    { "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front.sb_PadInterface_FrontStart", "sb_PadInterface_FrontStart", "IDC_UPADINTERFACE_SB_PADINTERFACE_FRONTSTART", "TBtnPanelLane", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front", 18, 3, "LEAF", false, true, 351, true, 138, true, 96, true, 48, true, 7, -1, "", "", true, "Arial", -15, "fsBold", true, 16777215, "clWhite", true, 8404992, "", true, 16744448, "", true, 8404992, "", false, 0, "", true, 16777215, "clWhite", 4, &kuPadInterfaceCustomProps[40] },
    { "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front.sb_PadInterface_FrontHome", "sb_PadInterface_FrontHome", "IDC_UPADINTERFACE_SB_PADINTERFACE_FRONTHOME", "TBtnPanelLane", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front", 19, 3, "LEAF", false, true, 238, true, 138, true, 96, true, 48, true, 6, -1, "", "", true, "Arial", -15, "fsBold", true, 16777215, "clWhite", true, 8404992, "", true, 16744448, "", true, 8404992, "", false, 0, "", true, 16777215, "clWhite", 4, &kuPadInterfaceCustomProps[44] },
    { "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front.sb_PadInterface_FrontPause", "sb_PadInterface_FrontPause", "IDC_UPADINTERFACE_SB_PADINTERFACE_FRONTPAUSE", "TBtnPanelLane", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front", 20, 3, "LEAF", false, true, 125, true, 138, true, 96, true, 48, true, 5, -1, "", "", true, "Arial", -15, "fsBold", true, 16777215, "clWhite", true, 8404992, "", true, 16744448, "", true, 8404992, "", false, 0, "", true, 16777215, "clWhite", 4, &kuPadInterfaceCustomProps[48] },
    { "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front.sb_PadInterface_FrontReset", "sb_PadInterface_FrontReset", "IDC_UPADINTERFACE_SB_PADINTERFACE_FRONTRESET", "TBtnPanelLane", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front", 21, 3, "LEAF", false, true, 12, true, 138, true, 96, true, 48, true, 4, -1, "", "", true, "Arial", -15, "fsBold", true, 16777215, "clWhite", true, 8404992, "", true, 16744448, "", true, 8404992, "", false, 0, "", true, 16777215, "clWhite", 4, &kuPadInterfaceCustomProps[52] },
    { "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front.sb_PadInterface_FrontOneCycle", "sb_PadInterface_FrontOneCycle", "IDC_UPADINTERFACE_SB_PADINTERFACE_FRONTONECYCLE", "TBtnPanelLane", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front", 22, 3, "LEAF", false, true, 12, true, 214, true, 96, true, 48, true, 8, -1, "", "", true, "Arial", -15, "fsBold", true, 16777215, "clWhite", true, 8404992, "", true, 16744448, "", true, 8404992, "", false, 0, "", true, 16777215, "clWhite", 4, &kuPadInterfaceCustomProps[56] },
    { "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front.sb_PadInterface_FrontRetry", "sb_PadInterface_FrontRetry", "IDC_UPADINTERFACE_SB_PADINTERFACE_FRONTRETRY", "TBtnPanelLane", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front", 23, 3, "LEAF", false, true, 125, true, 214, true, 96, true, 48, true, 9, -1, "", "", true, "Arial", -15, "fsBold", true, 16777215, "clWhite", true, 8404992, "", true, 16744448, "", true, 8404992, "", false, 0, "", true, 16777215, "clWhite", 4, &kuPadInterfaceCustomProps[60] },
    { "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front.sb_PadInterface_FrontSkip", "sb_PadInterface_FrontSkip", "IDC_UPADINTERFACE_SB_PADINTERFACE_FRONTSKIP", "TBtnPanelLane", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front", 24, 3, "LEAF", false, true, 238, true, 214, true, 96, true, 48, true, 10, -1, "", "", true, "Arial", -15, "fsBold", true, 16777215, "clWhite", true, 8404992, "", true, 16744448, "", true, 8404992, "", false, 0, "", true, 16777215, "clWhite", 4, &kuPadInterfaceCustomProps[64] },
    { "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front.sb_PadInterface_FrontCleanOut", "sb_PadInterface_FrontCleanOut", "IDC_UPADINTERFACE_SB_PADINTERFACE_FRONTCLEANOUT", "TBtnPanelLane", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front", 25, 3, "LEAF", false, true, 351, true, 214, true, 96, true, 48, true, 11, -1, "", "", true, "Arial", -15, "fsBold", true, 16777215, "clWhite", true, 8404992, "", true, 16744448, "", true, 8404992, "", false, 0, "", true, 16777215, "clWhite", 4, &kuPadInterfaceCustomProps[68] },
    { "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front.sb_PadInterface_FrontAlarmReset", "sb_PadInterface_FrontAlarmReset", "IDC_UPADINTERFACE_SB_PADINTERFACE_FRONTALARMRESET", "TBtnPanelLane", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front", 26, 3, "LEAF", false, true, 238, true, 290, true, 96, true, 48, true, 14, -1, "", "", true, "Arial", -15, "fsBold", true, 16777215, "clWhite", true, 8404992, "", true, 16744448, "", true, 8404992, "", false, 0, "", true, 16777215, "clWhite", 4, &kuPadInterfaceCustomProps[72] },
    { "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front.sb_PadInterface_FrontTrayEnd", "sb_PadInterface_FrontTrayEnd", "IDC_UPADINTERFACE_SB_PADINTERFACE_FRONTTRAYEND", "TBtnPanelLane", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front", 27, 3, "LEAF", false, true, 125, true, 290, true, 96, true, 48, true, 13, -1, "", "", true, "Arial", -15, "fsBold", true, 16777215, "clWhite", true, 8404992, "", true, 16744448, "", true, 8404992, "", false, 0, "", true, 16777215, "clWhite", 4, &kuPadInterfaceCustomProps[76] },
    { "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front.sb_PadInterface_FrontTrayFeed", "sb_PadInterface_FrontTrayFeed", "IDC_UPADINTERFACE_SB_PADINTERFACE_FRONTTRAYFEED", "TBtnPanelLane", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Front", 28, 3, "LEAF", false, true, 12, true, 290, true, 96, true, 48, true, 12, -1, "", "", true, "Arial", -15, "fsBold", true, 16777215, "clWhite", true, 8404992, "", true, 16744448, "", true, 8404992, "", false, 0, "", true, 16777215, "clWhite", 4, &kuPadInterfaceCustomProps[80] },
    { "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear", "pn_PadInterface_Rear", "IDD_UPADINTERFACE_SB_PADINTERFACE_MAINPAGE_PN_PADINTERFACE_REAR", "TPanel", "fPadInterface.sb_PadInterface_MainPage", "fPadInterface.sb_PadInterface_MainPage", 1, 2, "SUBDLG", false, true, 467, true, 0, true, 462, true, 433, true, 1, -1, "", "", true, "Arial", -15, "", true, -2147483640, "clWindowText", true, 14670284, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear.ml_PadInterface_RearPowerOff", "ml_PadInterface_RearPowerOff", "IDC_UPADINTERFACE_ML_PADINTERFACE_REARPOWEROFF", "TMyLed", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear", 0, 3, "LEAF", true, true, 49, true, 41, true, 22, true, 22, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 2, &kuPadInterfaceCustomProps[84] },
    { "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear.ml_PadInterface_RearPowerOn", "ml_PadInterface_RearPowerOn", "IDC_UPADINTERFACE_ML_PADINTERFACE_REARPOWERON", "TMyLed", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear", 1, 3, "LEAF", true, true, 162, true, 41, true, 22, true, 22, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 2, &kuPadInterfaceCustomProps[86] },
    { "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear.ml_PadInterface_RearReset", "ml_PadInterface_RearReset", "IDC_UPADINTERFACE_ML_PADINTERFACE_REARRESET", "TMyLed", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear", 2, 3, "LEAF", true, true, 49, true, 116, true, 22, true, 22, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 2, &kuPadInterfaceCustomProps[88] },
    { "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear.ml_PadInterface_RearPause", "ml_PadInterface_RearPause", "IDC_UPADINTERFACE_ML_PADINTERFACE_REARPAUSE", "TMyLed", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear", 3, 3, "LEAF", true, true, 162, true, 116, true, 22, true, 22, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 2, &kuPadInterfaceCustomProps[90] },
    { "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear.ml_PadInterface_RearHome", "ml_PadInterface_RearHome", "IDC_UPADINTERFACE_ML_PADINTERFACE_REARHOME", "TMyLed", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear", 4, 3, "LEAF", true, true, 275, true, 116, true, 22, true, 22, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 2, &kuPadInterfaceCustomProps[92] },
    { "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear.ml_PadInterface_RearStart", "ml_PadInterface_RearStart", "IDC_UPADINTERFACE_ML_PADINTERFACE_REARSTART", "TMyLed", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear", 5, 3, "LEAF", true, true, 388, true, 116, true, 22, true, 22, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 2, &kuPadInterfaceCustomProps[94] },
    { "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear.ml_PadInterface_RearOneCycle", "ml_PadInterface_RearOneCycle", "IDC_UPADINTERFACE_ML_PADINTERFACE_REARONECYCLE", "TMyLed", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear", 6, 3, "LEAF", true, true, 49, true, 192, true, 22, true, 22, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 2, &kuPadInterfaceCustomProps[96] },
    { "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear.ml_PadInterface_RearRetry", "ml_PadInterface_RearRetry", "IDC_UPADINTERFACE_ML_PADINTERFACE_REARRETRY", "TMyLed", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear", 7, 3, "LEAF", true, true, 162, true, 192, true, 22, true, 22, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 2, &kuPadInterfaceCustomProps[98] },
    { "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear.ml_PadInterface_RearSkip", "ml_PadInterface_RearSkip", "IDC_UPADINTERFACE_ML_PADINTERFACE_REARSKIP", "TMyLed", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear", 8, 3, "LEAF", true, true, 275, true, 192, true, 22, true, 22, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 2, &kuPadInterfaceCustomProps[100] },
    { "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear.ml_PadInterface_RearCleanOut", "ml_PadInterface_RearCleanOut", "IDC_UPADINTERFACE_ML_PADINTERFACE_REARCLEANOUT", "TMyLed", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear", 9, 3, "LEAF", true, true, 388, true, 192, true, 22, true, 22, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 2, &kuPadInterfaceCustomProps[102] },
    { "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear.ml_PadInterface_RearTrayFeed", "ml_PadInterface_RearTrayFeed", "IDC_UPADINTERFACE_ML_PADINTERFACE_REARTRAYFEED", "TMyLed", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear", 10, 3, "LEAF", true, true, 49, true, 268, true, 22, true, 22, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 2, &kuPadInterfaceCustomProps[104] },
    { "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear.ml_PadInterface_RearTrayEnd", "ml_PadInterface_RearTrayEnd", "IDC_UPADINTERFACE_ML_PADINTERFACE_REARTRAYEND", "TMyLed", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear", 11, 3, "LEAF", true, true, 162, true, 268, true, 22, true, 22, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 2, &kuPadInterfaceCustomProps[106] },
    { "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear.ml_PadInterface_RearAlarmReset", "ml_PadInterface_RearAlarmReset", "IDC_UPADINTERFACE_ML_PADINTERFACE_REARALARMRESET", "TMyLed", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear", 12, 3, "LEAF", true, true, 275, true, 268, true, 22, true, 22, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 2, &kuPadInterfaceCustomProps[108] },
    { "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear.ml_PadInterface_RearStep", "ml_PadInterface_RearStep", "IDC_UPADINTERFACE_ML_PADINTERFACE_REARSTEP", "TMyLed", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear", 13, 3, "LEAF", true, true, 275, true, 344, true, 22, true, 22, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 2, &kuPadInterfaceCustomProps[110] },
    { "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear.ml_PadInterface_RearTStart", "ml_PadInterface_RearTStart", "IDC_UPADINTERFACE_ML_PADINTERFACE_REARTSTART", "TMyLed", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear", 14, 3, "LEAF", true, true, 388, true, 344, true, 22, true, 22, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 2, &kuPadInterfaceCustomProps[112] },
    { "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear.ml_PadInterface_Rear", "ml_PadInterface_Rear", "IDC_UPADINTERFACE_ML_PADINTERFACE_REAR", "TMyLed", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear", 15, 3, "LEAF", true, true, 388, true, 41, true, 22, true, 22, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 2, &kuPadInterfaceCustomProps[114] },
    { "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear.ml_PadInterface_RearSafeLock", "ml_PadInterface_RearSafeLock", "IDC_UPADINTERFACE_ML_PADINTERFACE_REARSAFELOCK", "TMyLed", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear", 16, 3, "LEAF", true, true, 49, true, 344, true, 22, true, 22, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 2, &kuPadInterfaceCustomProps[116] },
    { "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear.pn_PadInterface_RearTop", "pn_PadInterface_RearTop", "IDC_UPADINTERFACE_PN_PADINTERFACE_REARTOP", "TPanel", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear", 17, 3, "LEAF", false, true, 2, true, 2, true, 458, true, 32, true, 0, -1, "alTop", "", true, "Arial", -19, "fsBold", true, 16777215, "clWhite", true, 9534289, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear.sb_PadInterface_RearPowerOff", "sb_PadInterface_RearPowerOff", "IDC_UPADINTERFACE_SB_PADINTERFACE_REARPOWEROFF", "TBtnPanelLane", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear", 18, 3, "LEAF", false, true, 12, true, 62, true, 96, true, 48, true, 1, -1, "", "", true, "Arial", -15, "fsBold", true, 16777215, "clWhite", true, 8404992, "", true, 16744448, "", true, 8404992, "", false, 0, "", true, 16777215, "clWhite", 4, &kuPadInterfaceCustomProps[118] },
    { "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear.sb_PadInterface_RearPowerOn", "sb_PadInterface_RearPowerOn", "IDC_UPADINTERFACE_SB_PADINTERFACE_REARPOWERON", "TBtnPanelLane", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear", 19, 3, "LEAF", false, true, 125, true, 62, true, 96, true, 48, true, 2, -1, "", "", true, "Arial", -15, "fsBold", true, 16777215, "clWhite", true, 8404992, "", true, 16744448, "", true, 8404992, "", false, 0, "", true, 16777215, "clWhite", 4, &kuPadInterfaceCustomProps[122] },
    { "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear.sb_PadInterface_RearPause", "sb_PadInterface_RearPause", "IDC_UPADINTERFACE_SB_PADINTERFACE_REARPAUSE", "TBtnPanelLane", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear", 20, 3, "LEAF", false, true, 125, true, 138, true, 96, true, 48, true, 5, -1, "", "", true, "Arial", -15, "fsBold", true, 16777215, "clWhite", true, 8404992, "", true, 16744448, "", true, 8404992, "", false, 0, "", true, 16777215, "clWhite", 4, &kuPadInterfaceCustomProps[126] },
    { "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear.sb_PadInterface_RearReset", "sb_PadInterface_RearReset", "IDC_UPADINTERFACE_SB_PADINTERFACE_REARRESET", "TBtnPanelLane", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear", 21, 3, "LEAF", false, true, 12, true, 138, true, 96, true, 48, true, 4, -1, "", "", true, "Arial", -15, "fsBold", true, 16777215, "clWhite", true, 8404992, "", true, 16744448, "", true, 8404992, "", false, 0, "", true, 16777215, "clWhite", 4, &kuPadInterfaceCustomProps[130] },
    { "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear.sb_PadInterface_RearOneCycle", "sb_PadInterface_RearOneCycle", "IDC_UPADINTERFACE_SB_PADINTERFACE_REARONECYCLE", "TBtnPanelLane", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear", 22, 3, "LEAF", false, true, 12, true, 214, true, 96, true, 48, true, 8, -1, "", "", true, "Arial", -15, "fsBold", true, 16777215, "clWhite", true, 8404992, "", true, 16744448, "", true, 8404992, "", false, 0, "", true, 16777215, "clWhite", 4, &kuPadInterfaceCustomProps[134] },
    { "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear.sb_PadInterface_RearRetry", "sb_PadInterface_RearRetry", "IDC_UPADINTERFACE_SB_PADINTERFACE_REARRETRY", "TBtnPanelLane", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear", 23, 3, "LEAF", false, true, 125, true, 214, true, 96, true, 48, true, 9, -1, "", "", true, "Arial", -15, "fsBold", true, 16777215, "clWhite", true, 8404992, "", true, 16744448, "", true, 8404992, "", false, 0, "", true, 16777215, "clWhite", 4, &kuPadInterfaceCustomProps[138] },
    { "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear.sb_PadInterface_RearSkip", "sb_PadInterface_RearSkip", "IDC_UPADINTERFACE_SB_PADINTERFACE_REARSKIP", "TBtnPanelLane", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear", 24, 3, "LEAF", false, true, 238, true, 214, true, 96, true, 48, true, 10, -1, "", "", true, "Arial", -15, "fsBold", true, 16777215, "clWhite", true, 8404992, "", true, 16744448, "", true, 8404992, "", false, 0, "", true, 16777215, "clWhite", 4, &kuPadInterfaceCustomProps[142] },
    { "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear.sb_PadInterface_RearHome", "sb_PadInterface_RearHome", "IDC_UPADINTERFACE_SB_PADINTERFACE_REARHOME", "TBtnPanelLane", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear", 25, 3, "LEAF", false, true, 238, true, 138, true, 96, true, 48, true, 6, -1, "", "", true, "Arial", -15, "fsBold", true, 16777215, "clWhite", true, 8404992, "", true, 16744448, "", true, 8404992, "", false, 0, "", true, 16777215, "clWhite", 4, &kuPadInterfaceCustomProps[146] },
    { "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear.sb_PadInterface_RearStart", "sb_PadInterface_RearStart", "IDC_UPADINTERFACE_SB_PADINTERFACE_REARSTART", "TBtnPanelLane", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear", 26, 3, "LEAF", false, true, 351, true, 138, true, 96, true, 48, true, 7, -1, "", "", true, "Arial", -15, "fsBold", true, 16777215, "clWhite", true, 8404992, "", true, 16744448, "", true, 8404992, "", false, 0, "", true, 16777215, "clWhite", 4, &kuPadInterfaceCustomProps[150] },
    { "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear.sb_PadInterface_RearCleanOut", "sb_PadInterface_RearCleanOut", "IDC_UPADINTERFACE_SB_PADINTERFACE_REARCLEANOUT", "TBtnPanelLane", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear", 27, 3, "LEAF", false, true, 351, true, 214, true, 96, true, 48, true, 11, -1, "", "", true, "Arial", -15, "fsBold", true, 16777215, "clWhite", true, 8404992, "", true, 16744448, "", true, 8404992, "", false, 0, "", true, 16777215, "clWhite", 4, &kuPadInterfaceCustomProps[154] },
    { "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear.sb_PadInterface_RearAlarmReset", "sb_PadInterface_RearAlarmReset", "IDC_UPADINTERFACE_SB_PADINTERFACE_REARALARMRESET", "TBtnPanelLane", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear", 28, 3, "LEAF", false, true, 238, true, 290, true, 96, true, 48, true, 14, -1, "", "", true, "Arial", -15, "fsBold", true, 16777215, "clWhite", true, 8404992, "", true, 16744448, "", true, 8404992, "", false, 0, "", true, 16777215, "clWhite", 4, &kuPadInterfaceCustomProps[158] },
    { "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear.sb_PadInterface_RearTrayEnd", "sb_PadInterface_RearTrayEnd", "IDC_UPADINTERFACE_SB_PADINTERFACE_REARTRAYEND", "TBtnPanelLane", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear", 29, 3, "LEAF", false, true, 125, true, 290, true, 96, true, 48, true, 13, -1, "", "", true, "Arial", -15, "fsBold", true, 16777215, "clWhite", true, 8404992, "", true, 16744448, "", true, 8404992, "", false, 0, "", true, 16777215, "clWhite", 4, &kuPadInterfaceCustomProps[162] },
    { "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear.sb_PadInterface_RearTrayFeed", "sb_PadInterface_RearTrayFeed", "IDC_UPADINTERFACE_SB_PADINTERFACE_REARTRAYFEED", "TBtnPanelLane", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear", 30, 3, "LEAF", false, true, 12, true, 290, true, 96, true, 48, true, 12, -1, "", "", true, "Arial", -15, "fsBold", true, 16777215, "clWhite", true, 8404992, "", true, 16744448, "", true, 8404992, "", false, 0, "", true, 16777215, "clWhite", 4, &kuPadInterfaceCustomProps[166] },
    { "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear.sb_PadInterface_RearStep", "sb_PadInterface_RearStep", "IDC_UPADINTERFACE_SB_PADINTERFACE_REARSTEP", "TBtnPanelLane", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear", 31, 3, "LEAF", false, true, 238, true, 366, true, 96, true, 48, true, 16, -1, "", "", true, "Arial", -15, "fsBold", true, 16777215, "clWhite", true, 8404992, "", true, 16744448, "", true, 8404992, "", false, 0, "", true, 16777215, "clWhite", 4, &kuPadInterfaceCustomProps[170] },
    { "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear.sb_PadInterface_RearTStart", "sb_PadInterface_RearTStart", "IDC_UPADINTERFACE_SB_PADINTERFACE_REARTSTART", "TBtnPanelLane", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear", 32, 3, "LEAF", false, true, 351, true, 366, true, 96, true, 48, true, 17, -1, "", "", true, "Arial", -15, "fsBold", true, 16777215, "clWhite", true, 8404992, "", true, 16744448, "", true, 8404992, "", false, 0, "", true, 16777215, "clWhite", 4, &kuPadInterfaceCustomProps[174] },
    { "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear.sb_PadInterface_RearSafeLock", "sb_PadInterface_RearSafeLock", "IDC_UPADINTERFACE_SB_PADINTERFACE_REARSAFELOCK", "TBtnPanelLane", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear", 33, 3, "LEAF", false, true, 12, true, 366, true, 96, true, 48, true, 15, -1, "", "", true, "Arial", -15, "fsBold", true, 16777215, "clWhite", true, 8404992, "", true, 16744448, "", true, 8404992, "", false, 0, "", true, 16777215, "clWhite", 4, &kuPadInterfaceCustomProps[178] },
    { "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear.sb_PadInterface_Rear", "sb_PadInterface_Rear", "IDC_UPADINTERFACE_SB_PADINTERFACE_REAR", "TBtnPanelLane", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear", "fPadInterface.sb_PadInterface_MainPage.pn_PadInterface_Rear", 34, 3, "LEAF", false, true, 351, true, 62, true, 96, true, 48, true, 3, -1, "", "", true, "Arial", -15, "fsBold", true, 16777215, "clWhite", true, 8404992, "", true, 16744448, "", true, 8404992, "", false, 0, "", true, 16777215, "clWhite", 4, &kuPadInterfaceCustomProps[182] },
    { "fPadInterface.sb_PadInterface_MainPage.sb_PadInterface_ManualSend", "sb_PadInterface_ManualSend", "IDC_UPADINTERFACE_SB_PADINTERFACE_MANUALSEND", "TButton", "fPadInterface.sb_PadInterface_MainPage", "fPadInterface.sb_PadInterface_MainPage", 2, 2, "LEAF", false, true, 228, true, 370, true, 90, true, 32, true, 2, -1, "", "", true, "Arial", -15, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fPadInterface.sb_PadInterface_MainPage.ed_PadInterface_ManualSend", "ed_PadInterface_ManualSend", "IDC_UPADINTERFACE_ED_PADINTERFACE_MANUALSEND", "TEdit", "fPadInterface.sb_PadInterface_MainPage", "fPadInterface.sb_PadInterface_MainPage", 3, 2, "LEAF", false, true, 24, true, 372, true, 189, true, 22, true, 3, -1, "", "", true, "Arial", -11, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fPadInterface.sb_PadInterface_MainPage.btnResetCom", "btnResetCom", "IDC_UPADINTERFACE_BTNRESETCOM", "TButton", "fPadInterface.sb_PadInterface_MainPage", "fPadInterface.sb_PadInterface_MainPage", 4, 2, "LEAF", false, true, 228, true, 408, true, 90, true, 32, true, 4, -1, "", "", true, "Arial", -15, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fPadInterface.sb_PadInterface_MainPage.cb_PadInterface_PadLedBling", "cb_PadInterface_PadLedBling", "IDC_UPADINTERFACE_CB_PADINTERFACE_PADLEDBLING", "TCheckBox", "fPadInterface.sb_PadInterface_MainPage", "fPadInterface.sb_PadInterface_MainPage", 5, 2, "LEAF", false, true, 24, true, 412, true, 185, true, 17, true, 5, -1, "", "", true, "Arial", -16, "", true, 16711680, "clBlue", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fPadInterface.Memo_PadInterface", "Memo_PadInterface", "IDC_UPADINTERFACE_MEMO_PADINTERFACE", "TMemo", "fPadInterface", "fPadInterface", 3, 1, "LEAF", false, true, 0, true, 473, true, 935, true, 206, true, 2, -1, "alBottom", "", true, "新細明體", -15, "", true, -2147483640, "clWindowText", true, 14670284, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
};

const int kuPadInterfaceLayoutCount = 76;

} // namespace ht9045_layout
