// ============================================================================
// DO NOT EDIT -- machine-generated by emit_rc.py W7-B1b v1.0 on LoadCCD/LoadCCDMap.dfm
// AI(W906-W7-B1b) 20260728: generated .rc/_ids.h from the .dfm IR (see
// docs/W7_UI_ARCHITECTURE_PLAN.md S6 W7-B1b). Hand edits will be
// overwritten and are rejected by the idempotence gate (G7).
// Source golden: LoadCCD/LoadCCDMap.dfm
// ============================================================================

#ifndef HT9045_UI_GEN_LOADCCDMAP_IDS_H
#define HT9045_UI_GEN_LOADCCDMAP_IDS_H

// Dialog template IDs
#define IDD_LOADCCDMAP 8192
#define IDD_LOADCCDMAP_PANEL1 8193

// Control IDs (D11 join key: mechanically derived from the
// .dfm leaf control name -- IDC_<FORMSTEM>_<CONTROLNAME>)
#define IDC_LOADCCDMAP_LABEL1 1024
#define IDC_LOADCCDMAP_LEDACONNECT 1025
#define IDC_LOADCCDMAP_EDTPORT 1026
#define IDC_LOADCCDMAP_BTNCONNECT 1027
#define IDC_LOADCCDMAP_MEMO1 1028
#define IDC_LOADCCDMAP_CCD1 1029
#define IDC_LOADCCDMAP_CCD2 1030
#define IDC_LOADCCDMAP_BTNCCDTEST 1031

#endif // HT9045_UI_GEN_LOADCCDMAP_IDS_H
