//---------------------------------------------------------------------------

#ifndef cShowBinSelectH
#define cShowBinSelectH
//---------------------------------------------------------------------------
#include <Classes.hpp>
#include <ComCtrls.hpp>
#include <Controls.hpp>
#include <ExtCtrls.hpp>
#include <Grids.hpp>
#include <StdCtrls.hpp>
#include <Buttons.hpp>
#include <Forms.hpp>
#include "HTray.h"
//---------------------------------------------------------------------------
class TfShowBinSelect : public TForm
{
__published:    // IDE-managed Components
    TPageControl *PageControl1;
    TTabSheet *tsTestBin;
    TTabSheet *tsCategoryInfo;
    TStringGrid *StrGrdCategory;
    TTabSheet *Tab_UPH;
    TStringGrid *UPH_StringGrid;
    TTabSheet *tsUnloadMap;
    TStatusBar *sbRunStatus;
    TTabSheet *tsIndex;
    TLabel *labIndexIn;
    TLabel *labIndexOut;
    TLabel *labOutArm;
    TLabel *IndexInput;
    TLabel *IndexOut;
    TLabel *OutArm_input;
    TLabel *labAutoClean;
    TLabel *AutocleanCount;
    TGroupBox *gbAutoCleanCount;
    TSpeedButton *btnAutoClean;
    TEdit *ed_AutoCleanCount;
    TTimer *TimerAutoCleanCount;
        TScrollBox *ScrollBox1;
    TPanel *palUnloader;
    TLabel *labAuto1;
    TLabel *labAuto2;
    TLabel *labAuto3;
    TLabel *labFix1;
    TLabel *labFix2;
    TLabel *labFix3;
    TLabel *labFix4;
    TLabel *labFix5;
    TLabel *labFix6;
    TButton *btReturn;
    TSpeedButton *btnCleanReset;
    TTabSheet *tsASE;
    TLabel *labScheduleNAME_1;
    TLabel *labInQty_1;
    TLabel *labScheduleNAME;
    TLabel *labInQty;
    TLabel *labInArm;
    TLabel *labInArm_input;
    TButton *btnClearCount;
    TTabSheet *PageControl1_ART;
    TStringGrid *StrGrdCategoryART;
    TLabel *labLowYield_1;
    TLabel *labLowYield;
    TLabel *labArmDiff_1;
    TLabel *labArmDiff;
    TLabel *labSiteDiff_1;
    TLabel *labSiteDiff;
    TLabel *labTotalYield_1;
    TLabel *labTotalYield;
    TTabSheet *Tab_ARTSkipICCount;
    TStringGrid *StrARTSkipICCount;
    TLabel *AutocleanlifeTime;
    TPanel *BulkBox;
    TLabel *LabBulkBox;
    TLabel *LabErrorBinNowCount;
    TLabel *Label3;
    TRadioGroup *rg_FixBinBox;
    TEdit *ed_FixBinBoxAlarmCount;
    TLabel *labBinBox;
    TLabel *Label7;
    TLabel *Label8;
    TLabel *Label9;
    TLabel *Label10;
    TLabel *Label11;
    TLabel *labTotalYieldTotal_1;
    TLabel *labTotalYieldTotal;
    TLabel *labJamrate;
    TLabel *Jamrate;
    TPanel *Panel1;
    TLabel *Label1;
    TLabel *IntervalByTotalCount;
    TLabel *Label4;
    TLabel *IntervalByTotal;
    TPanel *pnlSpeciallYield;
    TLabel *lblSpeciallYieldTotal_1;
    TLabel *lblSpeciallYield_1;
    TLabel *lblSpeciallYield;
    TLabel *lblSpeciallYieldTotal;
    TPanel *PLoadInput;
    TRadioGroup *LoadKeyIn;
    TEdit *EdLoadCount;
    TButton *btnSetInpputCnt;
    TTabSheet *tsFxiAI;
    TTabSheet *tsARTNormalBin;
    TTabSheet *tsARTRTBin;
    TLabel *labMag1;
    TLabel *labMag2;
    TLabel *labMag3;
    TLabel *labMag4;
    TLabel *labMag5;
    TLabel *labMag6;
    TLabel *labMag7;
    TLabel *labMag8;
    TLabel *labMag9;
    TLabel *labMag10;
    TLabel *labMag11;
    TLabel *labMag12;
    TLabel *labMag13;
    TLabel *labMag14;
    TLabel *labAuto4;
    TLabel *labAuto5;
    TLabel *labAuto6;
    TLabel *labFix7;
    TLabel *labFix8;
    TLabel *labFix9;
    TLabel *labFix10;
    TLabel *labFix11;
    TLabel *labFix12;
    TScrollBox *ScrollBox2;
    TScrollBox *ScrollBox3;
    TPanel *palARTNor;
    TLabel *labArtFtAuto1;
    TLabel *labArtFtAuto2;
    TLabel *labArtFtAuto3;
    TLabel *labArtFtFix1;
    TLabel *labArtFtFix2;
    TLabel *labArtFtFix3;
    TLabel *labArtFtFix4;
    TLabel *labArtFtFix5;
    TLabel *labArtFtFix6;
    TLabel *labArtFtBinBox;
    TLabel *labArtFtMag1;
    TLabel *labArtFtMag2;
    TLabel *labArtFtMag3;
    TLabel *labArtFtMag4;
    TLabel *labArtFtMag5;
    TLabel *labArtFtMag6;
    TLabel *labArtFtMag7;
    TLabel *labArtFtMag8;
    TLabel *labArtFtMag9;
    TLabel *labArtFtMag10;
    TLabel *labArtFtMag11;
    TLabel *labArtFtMag12;
    TLabel *labArtFtMag13;
    TLabel *labArtFtMag14;
    TLabel *labArtFtAuto4;
    TLabel *labArtFtAuto5;
    TLabel *labArtFtAuto6;
    TLabel *labArtFtFix7;
    TLabel *labArtFtFix8;
    TLabel *labArtFtFix9;
    TLabel *labArtFtFix10;
    TLabel *labArtFtFix11;
    TLabel *labArtFtFix12;
    TPanel *palARTRT;
    TLabel *labArtRtAuto1;
    TLabel *labArtRtAuto2;
    TLabel *labArtRtAuto3;
    TLabel *labArtRtFix1;
    TLabel *labArtRtFix2;
    TLabel *labArtRtFix3;
    TLabel *labArtRtFix4;
    TLabel *labArtRtFix5;
    TLabel *labArtRtFix6;
    TLabel *labArtRtBinBox;
    TLabel *labArtRtMag1;
    TLabel *labArtRtMag2;
    TLabel *labArtRtMag3;
    TLabel *labArtRtMag4;
    TLabel *labArtRtMag5;
    TLabel *labArtRtMag6;
    TLabel *labArtRtMag7;
    TLabel *labArtRtMag8;
    TLabel *labArtRtMag9;
    TLabel *labArtRtMag10;
    TLabel *labArtRtMag11;
    TLabel *labArtRtMag12;
    TLabel *labArtRtMag13;
    TLabel *labArtRtMag14;
    TLabel *labArtRtAuto4;
    TLabel *labArtRtAuto5;
    TLabel *labArtRtAuto6;
    TLabel *labArtRtFix7;
    TLabel *labArtRtFix8;
    TLabel *labArtRtFix9;
    TLabel *labArtRtFix10;
    TLabel *labArtRtFix11;
    TLabel *labArtRtFix12;
    TLabeledEdit *edAiAuto1;
    TLabeledEdit *edAiAuto2;
    TLabeledEdit *edAiAuto3;
    TLabeledEdit *edAiAuto4;
    TLabeledEdit *edAiAuto5;
    TLabeledEdit *edAiAuto6;
    TLabeledEdit *edlAiFix1;
    TLabeledEdit *edlAiFix2;
    TLabeledEdit *edlAiFix3;
    TLabeledEdit *edlAiFix4;
    TLabeledEdit *edlAiFix5;
    TLabeledEdit *edlAiFix6;
    TLabeledEdit *edlAiFix7;
    TLabeledEdit *edlAiFix8;
    TLabeledEdit *edlAiFix9;
    TLabeledEdit *edlAiFix10;
    TLabeledEdit *edlAiFix11;
    TLabeledEdit *edlAiFix12;
    TLabeledEdit *edlAiMag1;
    TLabeledEdit *edlAiMag2;
    TLabeledEdit *edlAiMag3;
    TLabeledEdit *edlAiMag4;
    TLabeledEdit *edlAiMag5;
    TLabeledEdit *edlAiMag6;
    TLabeledEdit *edlAiMag7;
    TLabeledEdit *edlAiMag8;
    TLabeledEdit *edlAiMag9;
    TLabeledEdit *edlAiMag10;
    TLabeledEdit *edlAiMag11;
    TLabeledEdit *edlAiMag12;
    TLabeledEdit *edlAiMag13;
    TLabeledEdit *edlAiMag14;
    TLabeledEdit *edlAiBinBox;
    TPanel *pnlShowBin;
    TLabel *laAuto1;
    TLabel *laAuto2;
    TLabel *laAuto3;
    TLabel *laBinBox;
    TLabel *laMag1;
    TLabel *laMag2;
    TLabel *laMag3;
    TLabel *laMag4;
    TLabel *laMag5;
    TLabel *laMag6;
    TLabel *laMag7;
    TLabel *laMag8;
    TLabel *laMag9;
    TLabel *laMag10;
    TLabel *laMag11;
    TLabel *laMag12;
    TLabel *laMag13;
    TLabel *laMag14;
    TLabel *laAuto5;
    TLabel *laAuto6;
    TLabel *laFix4;
    TLabel *laFix5;
    TLabel *laFix6;
    TLabel *laAuto4;
    TLabel *laFix1;
    TLabel *laFix2;
    TLabel *laFix3;
    TLabel *laFix7;
    TLabel *laFix8;
    TLabel *laFix9;
    TLabel *laFix10;
    TLabel *laFix11;
    TLabel *laFix12;
    TPanel *pnlShowBin_ARTFT;
    TLabel *laArtFtAuto1;
    TLabel *laArtFtAuto2;
    TLabel *laArtFtAuto3;
    TLabel *laArtFtBinBox;
    TLabel *laArtFtMag1;
    TLabel *laArtFtMag2;
    TLabel *laArtFtMag3;
    TLabel *laArtFtMag4;
    TLabel *laArtFtMag5;
    TLabel *laArtFtMag6;
    TLabel *laArtFtMag7;
    TLabel *laArtFtMag8;
    TLabel *laArtFtMag9;
    TLabel *laArtFtMag10;
    TLabel *laArtFtMag11;
    TLabel *laArtFtMag12;
    TLabel *laArtFtMag13;
    TLabel *laArtFtMag14;
    TLabel *laArtFtAuto5;
    TLabel *laArtFtAuto6;
    TLabel *laArtFtFix4;
    TLabel *laArtFtFix5;
    TLabel *laArtFtFix6;
    TLabel *laArtFtAuto4;
    TLabel *laArtFtFix1;
    TLabel *laArtFtFix2;
    TLabel *laArtFtFix3;
    TLabel *laArtFtFix7;
    TLabel *laArtFtFix8;
    TLabel *laArtFtFix9;
    TLabel *laArtFtFix10;
    TLabel *laArtFtFix11;
    TLabel *laArtFtFix12;
    TPanel *pnlShowBin_ARTRT;
    TLabel *laArtRtAuto1;
    TLabel *laArtRtAuto2;
    TLabel *laArtRtAuto3;
    TLabel *laArtRtBinBox;
    TLabel *laArtRtMag1;
    TLabel *laArtRtMag2;
    TLabel *laArtRtMag3;
    TLabel *laArtRtMag4;
    TLabel *laArtRtMag5;
    TLabel *laArtRtMag6;
    TLabel *laArtRtMag7;
    TLabel *laArtRtMag8;
    TLabel *laArtRtMag9;
    TLabel *laArtRtMag10;
    TLabel *laArtRtMag11;
    TLabel *laArtRtMag12;
    TLabel *laArtRtMag13;
    TLabel *laArtRtMag14;
    TLabel *laArtRtAuto5;
    TLabel *laArtRtAuto6;
    TLabel *laArtRtFix4;
    TLabel *laArtRtFix5;
    TLabel *laArtRtFix6;
    TLabel *laArtRtAuto4;
    TLabel *laArtRtFix1;
    TLabel *laArtRtFix2;
    TLabel *laArtRtFix3;
    TLabel *laArtRtFix7;
    TLabel *laArtRtFix8;
    TLabel *laArtRtFix9;
    TLabel *laArtRtFix10;
    TLabel *laArtRtFix11;
    TLabel *laArtRtFix12;
    TPanel *pnlFix123;
    TGroupBox *gbFix1;
    TLabel *lblFix1;
    TPanel *pnlFix1;
    TGroupBox *gbFix2;
    TLabel *lblFix2;
    TPanel *pnlFix2;
    TGroupBox *gbFix3;
    TLabel *lblFix3;
    TPanel *pnlFix3;
    TGroupBox *gbBinBox;
    TLabel *lblBinBox;
    TPanel *pnlBinBox;
    TPanel *pnlAuto123;
    TGroupBox *gbAuto1;
    TLabel *lblAuto1;
    TPanel *pnlAuto1;
    TGroupBox *gbAuto2;
    TLabel *lblAuto2;
    TPanel *pnlAuto2;
    TGroupBox *gbAuto3;
    TLabel *lblAuto3;
    TPanel *pnlAuto3;
    TPanel *pnlLoad;
    TGroupBox *gbLoader;
    TPanel *pnlLoader;
    TGroupBox *gbEmpty;
    TPanel *pnlEmpty;
    TGroupBox *gbColor;
    TPanel *pnlColor;
    TPanel *pnlMag123;
    TGroupBox *gbMag1;
    TLabel *lblMag1;
    TPanel *pnlMag1;
    TGroupBox *gbMag2;
    TLabel *lblMag2;
    TPanel *pnlMag2;
    TGroupBox *gbMag3;
    TLabel *lblMag3;
    TPanel *pnlMag3;
    TGroupBox *gbMag4;
    TLabel *lblMag4;
    TPanel *pnlMag4;
    TGroupBox *gbMag5;
    TLabel *lblMag5;
    TPanel *pnlMag5;
    TGroupBox *gbMag6;
    TLabel *lblMag6;
    TPanel *pnlMag6;
    TGroupBox *gbMag7;
    TLabel *lblMag7;
    TPanel *pnlMag7;
    TGroupBox *gbMag8;
    TLabel *lblMag8;
    TPanel *pnlMag8;
    TGroupBox *gbMag9;
    TLabel *lblMag9;
    TPanel *pnlMag9;
    TGroupBox *gbMag10;
    TLabel *lblMag10;
    TPanel *pnlMag10;
    TGroupBox *gbMag11;
    TLabel *lblMag11;
    TPanel *pnlMag11;
    TGroupBox *gbMag12;
    TLabel *lblMag12;
    TPanel *pnlMag12;
    TGroupBox *gbMag13;
    TLabel *lblMag13;
    TPanel *pnlMag13;
    TGroupBox *gbMag14;
    TLabel *lblMag14;
    TPanel *pnlMag14;
    TPanel *pnlFix789;
    TGroupBox *gbFix10;
    TLabel *lblFix10;
    TPanel *pnlFix10;
    TGroupBox *gbFix11;
    TLabel *lblFix11;
    TPanel *pnlFix11;
    TGroupBox *gbFix12;
    TLabel *lblFix12;
    TPanel *pnlFix12;
    TGroupBox *gbFix9;
    TLabel *lblFix9;
    TPanel *pnlFix9;
    TGroupBox *gbFix8;
    TLabel *lblFix8;
    TPanel *pnlFix8;
    TGroupBox *gbFix7;
    TLabel *lblFix7;
    TPanel *pnlFix7;
    TPanel *pnlAuto456;
    TGroupBox *gbAuto6;
    TLabel *lblAuto6;
    TPanel *pnlAuto6;
    TGroupBox *gbAuto5;
    TLabel *lblAuto5;
    TPanel *pnlAuto5;
    TGroupBox *gbAuto4;
    TLabel *lblAuto4;
    TPanel *pnlAuto4;
    TGroupBox *gbFix4;
    TLabel *lblFix4;
    TPanel *pnlFix4;
    TGroupBox *gbFix5;
    TLabel *lblFix5;
    TPanel *pnlFix5;
    TGroupBox *gbFix6;
    TLabel *lblFix6;
    TPanel *pnlFix6;
    TTabSheet *tsCategoryInfoContCT;
    TStringGrid *StrGrdCategoryContCT;
    TGroupBox *gbTriggerAlm;
    TLabel *labTriggerAlm;
    TEdit *edtTriggerAlm;
    TSpeedButton *btnICMisPlacementAuto1;
    TSpeedButton *btnICMisPlacementAuto2;
    TSpeedButton *btnICMisPlacementAuto3;
    TLabel *Label2;
    TPanel *palAutoDeviceEjection;
    TSpeedButton *btnAutoDeviceEjectionRemove;
    TLabel *Label5;
    TSpeedButton *btnAutoDeviceEjection;
    TGroupBox *gbCopyRecipe;
    TSpeedButton *sbCopyRecipe;
    void __fastcall FormShow(TObject *Sender);
    void __fastcall FormClose(TObject *Sender, TCloseAction &Action);
    void __fastcall PageControl1Change(TObject *Sender);
    void __fastcall UPH_StringGridDblClick(TObject *Sender);
    void __fastcall btnAutoCleanClick(TObject *Sender);
    void __fastcall TimerAutoCleanCountTimer(TObject *Sender);
    void __fastcall ed_AutoCleanCountClick(TObject *Sender);
        void __fastcall labAuto1Click(TObject *Sender);
        void __fastcall btReturnClick(TObject *Sender);
    void __fastcall btnCleanResetClick(TObject *Sender);
    void __fastcall btnClearCountClick(TObject *Sender);
    void __fastcall FormDestroy(TObject *Sender);
    void __fastcall edSLT01Change(TObject *Sender);
    void __fastcall btnSetInpputCntClick(TObject *Sender);
    void __fastcall EdLoadCountClick(TObject *Sender);
    void __fastcall btnICMisPlacementClick(TObject *Sender);
    void __fastcall sbCopyRecipeClick(TObject *Sender);
private:    // User declarations
    void __fastcall ShowBinDigital();
public:     // User declarations
    __fastcall TfShowBinSelect(TComponent* Owner);
    void __fastcall ShowBinSel();
    void __fastcall ShowBinSel_ARTNor();                                        //JerryYang 20220331 : �n���n�Dshow ART BIN
    void __fastcall ShowBinSel_ARTRT();                                         //JerryYang 20220331 : �n���n�Dshow ART BIN
    void __fastcall DoShowBinDigital();
    void __fastcall InitShowBinDigital();
    bool bShow;
    bool bUpdateBinDigital;
    int iShowBinDigitalTask;
    int iShowAutoBin[12];
    int iNumPanelType;                                                          //Steven 20090919 : Number of num panel
    TLabel *MyBinSel[e3TrayCount];                                              //kevin 20160819 add Bult box //kevin 20140305
    TLabel *MyBinSelLab[e3TrayCount];                                           //kevin 20160819 add Bult box //kevin 20140305
    TLabel *MyBinSelARTFT[e3TrayCount];                                         //JerryYang 20220331 : �n���n�Dshow ART BIN
    TLabel *MyBinSelARTRT[e3TrayCount];                                         //JerryYang 20220331 : �n���n�Dshow ART BIN
    TLabel *MyBinSelARTFTLab[e3TrayCount];                                      //JerryYang 20220331 : �n���n�Dshow ART BIN
    TLabel *MyBinSelARTRTLab[e3TrayCount];                                      //JerryYang 20220331 : �n���n�Dshow ART BIN
    TGroupBox *grpBinDisp[e3TrayCount];
    void SetLabelVisible(int iTag, bool bVisible);
    void SetAutoVisible();

    int ColorRed;
    int ColorGreen;
    int ColorOrange;

    TStringList *tsUPH;

    void __fastcall ShowCategoryBin();
    void __fastcall ChangeBinDispStatus();                                      //Steven 20110411 : ��ܥثe��ܾ������A
    void __fastcall ShowInitialString();
    void CaculateUPH();                                                         //Steven 20160727 : Show immediate UPH
    int iLowYieldBinSelectContactCount;                                         //KaiChen 20181115 : BinSelect�̭� Yield����ϥ� Contact Count
    void RefreshAiCnt();                                                        //Sam 20210609 : Fix AOI �n��ɯ�
    TLabeledEdit *EditAi[e3TrayCount];                                          //Sam 20210609 : Fix AOI �n��ɯ�
};
//---------------------------------------------------------------------------
extern PACKAGE TfShowBinSelect *fShowBinSelect;
//---------------------------------------------------------------------------
#endif
