// ===========================================================================
//  BinDisplay/BinDisp_layout.gen.cpp
//  DO NOT EDIT -- GENERATED FILE. See the matching _layout.gen.h banner.
// ===========================================================================
#include "BinDisp_layout.gen.h"

namespace ht9045_layout {

// (no custom-control properties in this form)

const DfmControlLayout kBinDispLayout[] = {
    { "Form1", "Form1", "", "TForm1", "", "", 0, 0, "ROOT", false, true, 413, true, 265, true, 476, true, 487, false, 0, -1, "", "", true, "MS Sans Serif", -11, "", true, -2147483640, "clWindowText", true, -2147483633, "clBtnFace", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "Form1.Panel3", "Panel3", "IDD_BINDISP_PANEL3", "TPanel", "Form1", "Form1", 0, 1, "SUBDLG", false, true, 3, true, 3, true, 450, true, 422, true, 0, -1, "", "", false, "", 0, "", false, 0, "", true, 12761254, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "Form1.Panel3.Label7", "Label7", "IDC_BINDISP_LABEL7", "TLabel", "Form1.Panel3", "Form1.Panel3", 0, 2, "LEAF", true, true, 19, true, 4, true, 394, true, 40, false, 0, -1, "", "", true, "微軟正黑體", -32, "fsBold", true, 32768, "clGreen", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "Form1.Panel3.GroupBox1", "GroupBox1", "IDD_BINDISP_PANEL3_GROUPBOX1", "TGroupBox", "Form1.Panel3", "Form1.Panel3", 1, 2, "SUBDLG", false, true, 36, true, 76, true, 185, true, 329, true, 0, -1, "", "", true, "MS Sans Serif", -13, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "Form1.Panel3.GroupBox1.CheckBox1", "CheckBox1", "IDC_BINDISP_CHECKBOX1", "TCheckBox", "Form1.Panel3.GroupBox1", "Form1.Panel3.GroupBox1", 0, 3, "LEAF", false, true, 12, true, 20, true, 97, true, 17, true, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "Form1.Panel3.GroupBox1.CheckBox2", "CheckBox2", "IDC_BINDISP_CHECKBOX2", "TCheckBox", "Form1.Panel3.GroupBox1", "Form1.Panel3.GroupBox1", 1, 3, "LEAF", false, true, 12, true, 46, true, 97, true, 17, true, 1, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "Form1.Panel3.GroupBox1.CheckBox3", "CheckBox3", "IDC_BINDISP_CHECKBOX3", "TCheckBox", "Form1.Panel3.GroupBox1", "Form1.Panel3.GroupBox1", 2, 3, "LEAF", false, true, 12, true, 72, true, 97, true, 17, true, 2, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "Form1.Panel3.GroupBox1.CheckBox4", "CheckBox4", "IDC_BINDISP_CHECKBOX4", "TCheckBox", "Form1.Panel3.GroupBox1", "Form1.Panel3.GroupBox1", 3, 3, "LEAF", false, true, 12, true, 97, true, 97, true, 17, true, 3, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "Form1.Panel3.GroupBox1.CheckBox5", "CheckBox5", "IDC_BINDISP_CHECKBOX5", "TCheckBox", "Form1.Panel3.GroupBox1", "Form1.Panel3.GroupBox1", 4, 3, "LEAF", false, true, 12, true, 123, true, 97, true, 17, true, 4, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "Form1.Panel3.GroupBox1.CheckBox6", "CheckBox6", "IDC_BINDISP_CHECKBOX6", "TCheckBox", "Form1.Panel3.GroupBox1", "Form1.Panel3.GroupBox1", 5, 3, "LEAF", false, true, 12, true, 149, true, 97, true, 17, true, 5, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "Form1.Panel3.GroupBox1.CheckBox7", "CheckBox7", "IDC_BINDISP_CHECKBOX7", "TCheckBox", "Form1.Panel3.GroupBox1", "Form1.Panel3.GroupBox1", 6, 3, "LEAF", false, true, 12, true, 175, true, 97, true, 17, true, 6, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "Form1.Panel3.GroupBox1.CheckBox8", "CheckBox8", "IDC_BINDISP_CHECKBOX8", "TCheckBox", "Form1.Panel3.GroupBox1", "Form1.Panel3.GroupBox1", 7, 3, "LEAF", false, true, 12, true, 201, true, 97, true, 17, true, 7, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "Form1.Panel3.GroupBox1.CheckBox9", "CheckBox9", "IDC_BINDISP_CHECKBOX9", "TCheckBox", "Form1.Panel3.GroupBox1", "Form1.Panel3.GroupBox1", 8, 3, "LEAF", false, true, 12, true, 227, true, 97, true, 17, true, 8, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "Form1.Panel3.GroupBox1.CheckBox10", "CheckBox10", "IDC_BINDISP_CHECKBOX10", "TCheckBox", "Form1.Panel3.GroupBox1", "Form1.Panel3.GroupBox1", 9, 3, "LEAF", false, true, 12, true, 252, true, 97, true, 17, true, 9, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "Form1.Panel3.GroupBox1.CheckBox11", "CheckBox11", "IDC_BINDISP_CHECKBOX11", "TCheckBox", "Form1.Panel3.GroupBox1", "Form1.Panel3.GroupBox1", 10, 3, "LEAF", false, true, 12, true, 278, true, 97, true, 17, true, 10, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "Form1.Panel3.GroupBox1.CheckBox12", "CheckBox12", "IDC_BINDISP_CHECKBOX12", "TCheckBox", "Form1.Panel3.GroupBox1", "Form1.Panel3.GroupBox1", 11, 3, "LEAF", false, true, 12, true, 304, true, 97, true, 17, true, 11, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "Form1.Panel3.GroupBox2", "GroupBox2", "IDD_BINDISP_PANEL3_GROUPBOX2", "TGroupBox", "Form1.Panel3", "Form1.Panel3", 2, 2, "SUBDLG", false, true, 232, true, 84, true, 181, true, 121, true, 1, -1, "", "", true, "MS Sans Serif", -13, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "Form1.Panel3.GroupBox2.ComboBox1", "ComboBox1", "IDC_BINDISP_COMBOBOX1", "TComboBox", "Form1.Panel3.GroupBox2", "Form1.Panel3.GroupBox2", 0, 3, "LEAF", false, true, 16, true, 24, true, 145, true, 24, true, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "Form1.Panel3.GroupBox2.ComboBox2", "ComboBox2", "IDC_BINDISP_COMBOBOX2", "TComboBox", "Form1.Panel3.GroupBox2", "Form1.Panel3.GroupBox2", 1, 3, "LEAF", false, true, 16, true, 72, true, 145, true, 24, true, 1, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "Form1.Panel3.Button1", "Button1", "IDC_BINDISP_BUTTON1", "TButton", "Form1.Panel3", "Form1.Panel3", 3, 2, "LEAF", false, true, 232, true, 340, true, 181, true, 61, true, 2, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "Form1.StatusBar1", "StatusBar1", "IDC_BINDISP_STATUSBAR1", "TStatusBar", "Form1", "Form1", 1, 1, "LEAF", false, true, 0, true, 430, true, 460, true, 19, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
};

const int kBinDispLayoutCount = 21;

} // namespace ht9045_layout
