// ============================================================================
// DO NOT EDIT -- machine-generated by emit_rc.py W7-B1b v1.0 on RotateKit/aRotateDegreeClass.dfm
// AI(W906-W7-B1b) 20260728: generated .rc/_ids.h from the .dfm IR (see
// docs/W7_UI_ARCHITECTURE_PLAN.md S6 W7-B1b). Hand edits will be
// overwritten and are rejected by the idempotence gate (G7).
// Source golden: RotateKit/aRotateDegreeClass.dfm
// ============================================================================

#ifndef HT9045_UI_GEN_AROTATEDEGREECLASS_IDS_H
#define HT9045_UI_GEN_AROTATEDEGREECLASS_IDS_H

// Dialog template IDs
#define IDD_AROTATEDEGREECLASS 8192
#define IDD_AROTATEDEGREECLASS_PNLROTDEGREE 8193
#define IDD_AROTATEDEGREECLASS_PNLROTDEGREE_RGROTATEDEGREE 8194
#define IDD_AROTATEDEGREECLASS_PNLROTDEGREE_GRPROTDEGREE 8195

// Control IDs (D11 join key: mechanically derived from the
// .dfm leaf control name -- IDC_<FORMSTEM>_<CONTROLNAME>)
#define IDC_AROTATEDEGREECLASS_RGROTATEDEGREE_FRAME 1024  // synthesized: SYNTH_CONTAINER_FRAME
#define IDC_AROTATEDEGREECLASS_RGROTATEDEGREE_ITEM0 1025  // synthesized: SYNTH_RADIOGROUP_ITEM
#define IDC_AROTATEDEGREECLASS_RGROTATEDEGREE_ITEM1 1026  // synthesized: SYNTH_RADIOGROUP_ITEM
#define IDC_AROTATEDEGREECLASS_RGROTATEDEGREE_ITEM2 1027  // synthesized: SYNTH_RADIOGROUP_ITEM
#define IDC_AROTATEDEGREECLASS_RGROTATEDEGREE_ITEM3 1028  // synthesized: SYNTH_RADIOGROUP_ITEM
#define IDC_AROTATEDEGREECLASS_GRPROTDEGREE_FRAME 1029  // synthesized: SYNTH_CONTAINER_FRAME
#define IDC_AROTATEDEGREECLASS_IMGROTDEGREE 1030
#define IDC_AROTATEDEGREECLASS_LBLSITEMAP 1031

#endif // HT9045_UI_GEN_AROTATEDEGREECLASS_IDS_H
