//---------------------------------------------------------------------------

#ifndef cTrayAssignmentH
#define cTrayAssignmentH
//---------------------------------------------------------------------------
#include <Buttons.hpp>
#include <Classes.hpp>
#include <ComCtrls.hpp>
#include <Controls.hpp>
#include <ExtCtrls.hpp>
#include <StdCtrls.hpp>
//---------------------------------------------------------------------------
class TfTrayAssignment : public TForm
{
__published:    // IDE-managed Components
    TPanel *palTrayAssign;
    TGroupBox *gbAuto3;
    TImage *imgAuto3;
    TGroupBox *gbAuto2;
    TImage *imgAuto2;
    TGroupBox *gbAuto1;
    TImage *imgAuto1;
    TGroupBox *gbColorTray;
    TGroupBox *gbEmptyTray;
    TGroupBox *GroupBox1;
    TImage *imgLoader;
    TComboBox *cbLoader;
    TComboBox *cbEmpty;
    TComboBox *cbColor;
    TEdit *edAuto1Type;
    TEdit *edAuto2Type;
    TEdit *edAuto3Type;
    TPageControl *pgRunMode;
    TTabSheet *tsNormalTestGroup;
    TTabSheet *tsReTestGroup;
    TPanel *pnlFTTrayFrom;
    TShape *Shape11;
    TLabel *Label63;
    TRadioGroup *RGAuto1;
    TRadioGroup *RGAuto2;
    TRadioGroup *RGAuto3;
    TPanel *pnlRTTrayFrom;
    TShape *Shape1;
    TLabel *Label1;
    TRadioGroup *rgAuto1_RT;
    TRadioGroup *rgAuto2_RT;
    TRadioGroup *rgAuto3_RT;
    TTabSheet *tsNormalTestGraph;
    TTabSheet *tsReTestGraph;
    TImage *ImgNormalTest;
    TScrollBar *sbNormalTest;
    TImage *ImgReTest;
    TScrollBar *sbNormalTest_RT;
    TPanel *Panel2;
    TSpeedButton *sbtExit;
    TSpeedButton *spbSave;
    TCheckBox *chkTrayEndRecvAuto1;
    TCheckBox *chkTrayEndRecvAuto2;
    TCheckBox *chkTrayEndRecvAuto3;
    TPanel *Panel3;
    TPanel *Panel5;
    TGroupBox *grpCheckLoaderDirection;
    TCheckBox *chkCheckLoadDirection;
    TGroupBox *gbColorTrayMode;
    TCheckBox *chkColorTray;
    TGroupBox *gbUnloadMode;
    TCheckBox *chkAutoTrayFeed;
    TCheckBox *cbManuTakeAutoFailTray_FT;
    TCheckBox *cbManuTakeAutoFailTray_RT;
    TRadioGroup *rgLoaderTrayMode;
    TGroupBox *grpICSortFunc;
    TGroupBox *grpICSort3;
    TGroupBox *grpICSort2;
    TGroupBox *grpICSort1;
    TCheckBox *chkICSort1;
    TCheckBox *chkICSort2;
    TCheckBox *chkICSort3;
    TLabel *Label3;
    TLabel *Label6;
    TLabel *Label7;
    TEdit *edtICSort1_1;
    TLabel *Label8;
    TLabel *Label9;
    TEdit *edtICSort1_2;
    TLabel *Label10;
    TEdit *edtICSort1_3;
    TLabel *Label11;
    TEdit *edtICSort1_4;
    TLabel *Label12;
    TEdit *edtICSort1_5;
    TEdit *edtICSort1_6;
    TLabel *Label13;
    TEdit *edtICSort2_1;
    TLabel *Label14;
    TLabel *Label15;
    TEdit *edtICSort2_2;
    TLabel *Label16;
    TEdit *edtICSort2_3;
    TLabel *Label17;
    TEdit *edtICSort2_4;
    TLabel *Label18;
    TEdit *edtICSort2_5;
    TEdit *edtICSort2_6;
    TLabel *Label19;
    TEdit *edtICSort3_1;
    TLabel *Label20;
    TLabel *Label21;
    TEdit *edtICSort3_2;
    TLabel *Label22;
    TEdit *edtICSort3_3;
    TLabel *Label23;
    TEdit *edtICSort3_4;
    TLabel *Label24;
    TEdit *edtICSort3_5;
    TEdit *edtICSort3_6;
    TLabel *Label25;
    TGroupBox *grpICSort4;
    TLabel *Label26;
    TLabel *Label27;
    TLabel *Label28;
    TLabel *Label29;
    TLabel *Label30;
    TLabel *Label31;
    TLabel *Label32;
    TCheckBox *chkICSort4;
    TEdit *edtICSort4_1;
    TEdit *edtICSort4_2;
    TEdit *edtICSort4_3;
    TEdit *edtICSort4_4;
    TEdit *edtICSort4_5;
    TEdit *edtICSort4_6;
    TGroupBox *grpICSort6;
    TLabel *Label33;
    TLabel *Label34;
    TLabel *Label35;
    TLabel *Label36;
    TLabel *Label37;
    TLabel *Label38;
    TLabel *Label39;
    TCheckBox *chkICSort6;
    TEdit *edtICSort6_1;
    TEdit *edtICSort6_2;
    TEdit *edtICSort6_3;
    TEdit *edtICSort6_4;
    TEdit *edtICSort6_5;
    TEdit *edtICSort6_6;
    TGroupBox *grpICSort5;
    TLabel *Label40;
    TLabel *Label41;
    TLabel *Label42;
    TLabel *Label43;
    TLabel *Label44;
    TLabel *Label45;
    TLabel *Label46;
    TCheckBox *chkICSort5;
    TEdit *edtICSort5_1;
    TEdit *edtICSort5_2;
    TEdit *edtICSort5_3;
    TEdit *edtICSort5_4;
    TEdit *edtICSort5_5;
    TEdit *edtICSort5_6;
    TPanel *pnlTop;
    TRadioGroup *rgLoaderType;
    TGroupBox *grpFix1;
    TImage *imgFix1;
    TLabel *labFix1;
    TComboBox *cbFix1;
    TCheckBox *ckUseFix1;
    TGroupBox *grpFix2;
    TImage *imgFix2;
    TLabel *labFix2;
    TComboBox *cbFix2;
    TCheckBox *ckUseFix2;
    TGroupBox *grpFix3;
    TImage *imgFix3;
    TLabel *labFix3;
    TComboBox *cbFix3;
    TCheckBox *ckUseFix3;
    TRadioGroup *rgFixTrayMode;
    TGroupBox *gbRotateKit;
    TLabel *Label4;
    TLabel *Label5;
    TComboBox *cbInputRotateKIT;
    TComboBox *cbOutputRotateKIT;
    TPanel *pnlLoad_FT;
    TLabel *Label64;
    TLabel *lblHint;
    TRadioGroup *RGLoader;
    TGroupBox *grpFix4;
    TImage *imgFix4;
    TLabel *labFix4;
    TComboBox *cbFix4;
    TCheckBox *ckUseFix4;
    TGroupBox *grpFix5;
    TImage *imgFix5;
    TLabel *labFix5;
    TComboBox *cbFix5;
    TCheckBox *ckUseFix5;
    TGroupBox *grpFix6;
    TImage *imgFix6;
    TLabel *labFix6;
    TComboBox *cbFix6;
    TCheckBox *ckUseFix6;
    TRadioGroup *RGAuto4;
    TRadioGroup *RGAuto5;
    TRadioGroup *RGAuto6;
    TGroupBox *gbAuto6;
    TImage *imgAuto6;
    TEdit *edAuto6Type;
    TCheckBox *chkTrayEndRecvAuto6;
    TGroupBox *gbAuto5;
    TImage *imgAuto5;
    TEdit *edAuto5Type;
    TCheckBox *chkTrayEndRecvAuto5;
    TGroupBox *gbAuto4;
    TImage *imgAuto4;
    TEdit *edAuto4Type;
    TCheckBox *chkTrayEndRecvAuto4;
    TPanel *pnlLoad_RT;
    TRadioGroup *rgLoad_RT;
    TLabel *Label2;
    TRadioGroup *rgAuto4_RT;
    TRadioGroup *rgAuto5_RT;
    TRadioGroup *rgAuto6_RT;
    TRadioButton *rbTemp;
    TLabel *lblHint2;
    TGroupBox *gbTrayArmMode;
    TCheckBox *cbMoveAfterTrayGoOut;
    TPanel *palAMR;
    TCheckBox *cbSpecTrayCnt;
    TLabel *Label47;
    TEdit *edAMRInputTrayCount;
    TLabel *Label49;
    TEdit *edAMRFullTrayCount;
    TGroupBox *grpVTestNoTBin;
    TLabel *Label48;
    TLabel *Label50;
    TLabel *Label51;
    TEdit *edNoRTBinFix1;
    TEdit *edNoRTBinFix2;
    TEdit *edNoRTBinFix3;
    TCheckBox *cbVTestNoRTBin;
    void __fastcall FormShow(TObject *Sender);
    void __fastcall imgLoaderClick(TObject *Sender);
    void __fastcall rgLoaderTypeClick(TObject *Sender);
    void __fastcall rgFixTrayModeClick(TObject *Sender);
    void __fastcall cbEmptyChange(TObject *Sender);
    void __fastcall RGLoaderClick(TObject *Sender);
    void __fastcall rgLoad_RTClick(TObject *Sender);
    void __fastcall cbLoaderChange(TObject *Sender);
    void __fastcall FormClose(TObject *Sender, TCloseAction &Action);
    void __fastcall spbSaveClick(TObject *Sender);
    void __fastcall sbtExitClick(TObject *Sender);
    void __fastcall sbNormalTestChange(TObject *Sender);
    void __fastcall sbNormalTest_RTChange(TObject *Sender);
        void __fastcall RGAuto2Click(TObject *Sender);
    void __fastcall cbLoaderDropDown(TObject *Sender);
    void __fastcall edtICSort1_1MouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
    void __fastcall FormShortCut(TWMKey &Msg, bool &Handled);
private:    // User declarations
    int iTrayDirect[eTrayCount];
    int iLoadDirect;
    void __fastcall LoadImage();
    void __fastcall GraphicToRadio();
    void __fastcall RadioToGraphic();
    void __fastcall GraphicToRadio_RT();
    void __fastcall RadioToGraphic_RT();

public:     // User declarations
    __fastcall TfTrayAssignment(TComponent* Owner);
    void __fastcall ReadFile();
    void __fastcall ShowCompnet();
    void __fastcall ShowTrayDirectIMG();
    void __fastcall DoIniDataToForm();
    int BinTrayDetect(int iBinTray,int bAuto12);
    void __fastcall SaveSetupFile(AnsiString szDir,AnsiString S);//kevin 20150105
    int iLoaderType;
    bool fShow;
    TCheckBox *chkICSort[MAX_AUTO_TRAY];
    TEdit *edtICSort[MAX_AUTO_TRAY][6];
    void FixCanUse();
};
//---------------------------------------------------------------------------
extern PACKAGE TfTrayAssignment *fTrayAssignment;
//---------------------------------------------------------------------------
#endif
