//******************************************************************************
//
//  注意!! uTemp_Set為Handler 溫度設定相關, 修改時要小心!!
//
//******************************************************************************
#ifndef uTemp_SetH
#define uTemp_SetH
//---------------------------------------------------------------------------
#include <Buttons.hpp>
#include <Classes.hpp>
#include <Controls.hpp>
#include <ExtCtrls.hpp>
#include <StdCtrls.hpp>
#include <ComCtrls.hpp>
#include <jpeg.hpp>
#include <Classes.hpp>
#include <Forms.hpp>
#include "PComm.h"
#include "MyTempPanel.h"
#include "MachineType.h"
#include <Grids.hpp>

#define MAX_DEFROST_AREA 7
//---------------------------------------------------------------------------

extern const int LowBase;
extern const int MidBase;
extern const int HigBase;
extern const int UserOffSet;
extern const int SingleLimit;
extern const int TargetTemp;                                                    //Steven 20140924 : 各個加熱區獨立有自己的設定值
extern const int AmbientHotLow;                                                 //kevin 20140918 恆溫控制 低  offset
extern const int AmbientHotMid;                                                 //kevin 20140918 恆溫控制 中 offset
extern const int InitTempOffset;                                                //Steven 20141117 : 起測時溫度要補Offset
extern const int TestOverTimeTempOffset;                                        //20160312 : 距離上次測試時間超過所設定時間要補Offset
extern const int KitLowBase;                                                    //JerryYang 20221003 Analog要求新增Kit三點offset
extern const int KitMidBase;
extern const int KitHigBase;
extern const int KitAmbientHotLow;
extern const int KitAmbientHotMid;
extern const int SHigBase;                                                      //Ztex 2024.07.27 Add 6 Point Temperature Offset
//extern const int RemoteOffset;
//extern const int TempEditTotal;

class TfTemp_Set : public TForm
{
__published:    // IDE-managed Components
    TPanel *Panel7;
    TSpeedButton *spbSave;
    TSpeedButton *sbtExit;
    TPanel *Panel8;
    TPanel *Panel1;
    TGroupBox *gbTempOffset;
    TPageControl *pgcTempOffset;
    TTabSheet *thNormal;
    TTabSheet *tsArm1;
    TTabSheet *tsArm2;
    TTabSheet *tsATC;
    TTabSheet *tsHeatGun;
    TPanel *Panel6;
    TPanel *Panel11;
    TPanel *Panel2;
    TPanel *Panel13;
    TPanel *pnlHeatMode;
    TGroupBox *gbBasePoint;
    TRadioButton *rb1Point;
    TRadioButton *rb2Point;
    TRadioButton *rb3Point;
    TCheckBox *cbHeaterGun;
    TTabSheet *tsDUT;
    TPanel *Panel15;
    TPanel *Panel16;
    TImage *Image2;
    TCheckBox *cbUseFixTemp;
    TEdit *edFixedTemp;
    TCheckBox *cbShowFixTemp;
    TPanel *Panel21;
    TPanel *Panel27;
    TPanel *Panel28;
    TRadioButton *rb5Point;
    TPanel *Panel4;
    TPanel *Panel31;
    TPanel *Panel32;
    TPanel *palATC;
    TTabSheet *tsATC_PID;
    TPanel *pnlATC_PIDOffset;
    TLabel *Label371;
    TLabel *Label372;
    TLabel *Label373;
    TLabel *Label374;
    TLabel *Label375;
    TLabel *Label376;
    TPanel *pnlATC_PIDOffsetTop;
    TEdit *edtATCPIDOffset_MinP;
    TEdit *edtATCPIDOffset_MinI;
    TEdit *edtATCPIDOffset_MinD;
    TEdit *edtATCPIDOffset_MaxP;
    TEdit *edtATCPIDOffset_MaxI;
    TEdit *edtATCPIDOffset_MaxD;
    TCheckBox *cdATCUsePIDCtrl;
    TTabSheet *tsATC70;
    TGroupBox *gbATCInitialOffset;
    TLabel *labATCInitialOffset1;
    TLabel *labATCInitialOffset2;
    TLabel *labATCInitialOffset4;
    TLabel *labATCInitialOffset3;
    TEdit *edATCInitialOffset1;
    TEdit *edATCInitialOffset2;
    TEdit *edATCInitialOffset3;
    TEdit *edATCInitialOffset4;
    TGroupBox *gbATC70;
    TCheckBox *rbATC70ActiveOn;
    TGroupBox *gbATCConsFail;
    TLabel *labATCContFailOffset1;
    TLabel *labATCContFailOffset2;
    TLabel *labATCContFailOffset4;
    TLabel *labATCContFailOffset3;
    TLabel *Label26;
    TEdit *edATCContFailOffset1;
    TEdit *edATCContFailOffset2;
    TEdit *edATCContFailOffset3;
    TEdit *edATCContFailOffset4;
    TCheckBox *cbEnableATCConsFailOffset;
    TEdit *edATCContFailOffsetCnt;
    TGroupBox *gbATCQAModeOffset;
    TLabel *labATCQAModeOffset1;
    TLabel *labATCQAModeOffset2;
    TLabel *labATCQAModeOffset4;
    TLabel *labATCQAModeOffset3;
    TEdit *edATCQAModeOffset1;
    TEdit *edATCQAModeOffset2;
    TEdit *edATCQAModeOffset3;
    TEdit *edATCQAModeOffset4;
    TCheckBox *cbEnableATCQAModeOffset;
    TEdit *edWorkTemp;
    TButton *btClearAll;
    TPanel *pnlOffsetBase;
    TGroupBox *gbATCTestTimeOffset;
    TLabel *labATCTestTimeOffset1;
    TLabel *labATCTestTimeOffset2;
    TLabel *labATCTestTimeOffset4;
    TLabel *labATCTestTimeOffset3;
    TEdit *edATCTestTimeOffset1;
    TEdit *edATCTestTimeOffset2;
    TEdit *edATCTestTimeOffset3;
    TEdit *edATCTestTimeOffset4;
    TCheckBox *cbATCTestTimeOffset;
    TLabel *labATCTestTimeOffset;
    TEdit *edATCTestTimeOffset;
    TPanel *Panel36;
    TPanel *Panel41;
    TPanel *Panel42;
    TGroupBox *gbTSD;
    TCheckBox *rbATC7TSDFunction;
    TLabel *Label17;
    TEdit *edTSDTimeOut;
    TPageControl *pgcTempSetting;
    TTabSheet *tsHot;
    TGroupBox *gbHotModeSetting;
    TLabel *Label1;
    TLabel *Label2;
    TLabel *Label3;
    TLabel *Label30;
    TLabel *Label10;
    TLabel *Label79;
    TLabel *Label21;
    TLabel *Label22;
    TLabel *lblShtSoakTime;
    TLabel *lbllblShtSoakTimeSec;
    TLabel *Label44;
    TLabel *Label45;
    TEdit *edSoakTime;
    TEdit *edJamSoakTime;
    TEdit *edInitialWaitTime;
    TEdit *edInitialStart1Time;
    TEdit *edInitialStart2Time;
    TEdit *edChamberCoolTemp;
    TRadioGroup *rgShuttleSoakTime;
    TRadioGroup *rgZ1Down;
    TPanel *PnlIndexSoakTime;
    TLabel *Label54;
    TLabel *Label53;
    TLabel *Label55;
    TLabel *Label56;
    TEdit *edIndexSoakTime;
    TEdit *edOSTime;
    TCheckBox *chkTesterDock;
    TEdit *edtTestDock;
    TCheckBox *cbEnableIndividualMode;
    TGroupBox *gbNoFullsiteOffset;
    TLabel *Label109;
    TLabel *Label110;
    TLabel *Label111;
    TLabel *Label112;
    TLabel *Label113;
    TLabel *Label114;
    TLabel *Label83;
    TLabel *Label115;
    TLabel *Label9;
    TLabel *Label11;
    TLabel *Label12;
    TLabel *Label13;
    TEdit *edArm1NoFullsiteOffset_1;
    TEdit *edArm1NoFullsiteOffset_2;
    TEdit *edArm1NoFullsiteOffset_3;
    TEdit *edArm2NoFullsiteOffset_1;
    TEdit *edArm2NoFullsiteOffset_2;
    TEdit *edArm2NoFullsiteOffset_3;
    TEdit *edArm1NoFullsiteOffset_4;
    TEdit *edArm2NoFullsiteOffset_4;
    TEdit *edArm1NoFullsiteOffset_5;
    TEdit *edArm2NoFullsiteOffset_5;
    TCheckBox *chkSoakTimeReduce;
    TTabSheet *tsAmbient;
    TGroupBox *gbAmbientModeSetting;
    TLabel *Label4;
    TLabel *Label5;
    TLabel *Label6;
    TLabel *Label7;
    TLabel *Label31;
    TLabel *Label80;
    TCheckBox *cbUseAbitCHK;
    TRadioGroup *rgAmbCheck;
    TEdit *edAmbTemp;
    TEdit *edAbitInitWaitTime;
    TEdit *edAbitColdTime;
    TCheckBox *chkAmbUsingAFan;
    TGroupBox *gbSocketAirCooling;
    TLabel *Label19;
    TLabel *Label20;
    TLabel *Label27;
    TLabel *Label28;
    TEdit *edSocketAirCoolingOn;
    TEdit *edSocketAirCoolingOff;
    TGroupBox *rgAmbientBrand;
    TLabel *Label14;
    TLabel *Label15;
    TCheckBox *cbUseAmbGuard;
    TEdit *edAmbGuardband;
    TTabSheet *tsAmbCtr;
    TTabSheet *tsOther;
    TPageControl *pgcOtherFunc;
    TTabSheet *tsInitOffset;
    TGroupBox *bgTempOffset;
    TLabel *labContctCount;
    TLabel *labTempDownContactDelay;
    TCheckBox *cbTempOffset;
    TEdit *edTempOffsetCount;
    TEdit *edTempDownContactDelay;
    TPanel *pnlUseOtherArmToTestAfterInitialDelay;
    TCheckBox *cbUseOtherArmToTestAfterInitialDelay;
    TGroupBox *GroupBox1;
    TPanel *pnl1stDevice;
    TCheckBox *cbEveryFirstDeviceUseInitialDelay;
    TEdit *edtInitialDelay_1;
    TPanel *pnlTitle;
    TLabel *lblDelayTime;
    TLabel *lblTriggerTime;
    TPanel *pnlPause;
    TCheckBox *cbWhenPressStopOverUseInitialDelay;
    TEdit *edtInitialDelay_6;
    TEdit *edOverSec;
    TPanel *pnlLowTestTime;
    TCheckBox *cbWhenHappenTestedTimeBelowUseInitialDelay;
    TEdit *edtInitialDelay_4;
    TEdit *edBelowSec;
    TPanel *pnlHeatDoor;
    TCheckBox *cbAfterOpenHeatDoorUseInitialDelay;
    TEdit *edtInitialDelay_5;
    TPanel *pnlAutoClean;
    TEdit *edtInitialDelay_3;
    TCheckBox *cbAfterAutoCleanFunctionUseInitialDelay;
    TPanel *pnlAlarmMsg;
    TCheckBox *cbAfterShowAlarmMessageUseInitialDelay;
    TEdit *edtInitialDelay_2;
    TPanel *pnlOTD;
    TCheckBox *cbOTDUnlockDelay;
    TEdit *edtInitialDelay_9;
    TPanel *pnlEOTTime;
    TCheckBox *cbTestFinishToNextTestOver;
    TEdit *iTestFinishToNextTestOver;
    TEdit *edtInitialDelay_8;
    TPanel *pnlNoFullsite;
    TCheckBox *cbWhenNoFullSiteUseInitialDelay;
    TEdit *edtInitialDelay_7;
    TTabSheet *tsBoostFunc;
    TGroupBox *grpMidPrecondition;
    TPanel *pnlIdleTime_Mid;
    TLabel *lblIdleTime_Mid;
    TEdit *edtIdleTime_Mid;
    TPanel *pnlBoostOffset_Mid;
    TLabel *lblBoostOffset_Mid;
    TEdit *edtBoostOffset_Mid;
    TPanel *pnlBoostDuration_Mid;
    TLabel *lblBoostDuration_Mid;
    TEdit *edtBoostDuration_Mid;
    TPanel *pnlPostBoost_Mid;
    TLabel *lblPostBoost_Mid;
    TEdit *edtPostBoost_Mid;
    TPanel *Panel14;
    TCheckBox *chkBoostFunction;
    TGroupBox *grpShortPrecondition;
    TPanel *pnlIdleTime_Short;
    TLabel *lblIdleTime_Short1;
    TLabel *lblIdleTime_Short;
    TEdit *edtIdleTime_Short;
    TPanel *pnlBoostOffset_Short;
    TLabel *lblBoostOffset_Short1;
    TLabel *lblBoostOffset_Short;
    TEdit *edtBoostOffset_Short;
    TPanel *pnlBoostDuration_Short;
    TLabel *lblBoostDuration_Short1;
    TLabel *lblBoostDuration_Short;
    TEdit *edtBoostDuration_Short;
    TPanel *pnlPostBoost_Short;
    TLabel *lblPostBoost_Short1;
    TLabel *lblPostBoost_Short;
    TEdit *edtPostBoost_Short;
    TGroupBox *grpLongPrecondition;
    TPanel *pnlIdleTime_Long;
    TLabel *lblIdleTime_Long1;
    TLabel *lblIdleTime_Long;
    TEdit *edtIdleTime_Long;
    TPanel *pnlBoostOffset_Long;
    TLabel *lblBoostOffset_Long1;
    TLabel *lblBoostOffset_Long;
    TEdit *edtBoostOffset_Long;
    TPanel *pnlBoostDuration_Long;
    TLabel *lblBoostDuration_Long1;
    TLabel *lblBoostDuration_Long;
    TEdit *edtBoostDuration_Long;
    TPanel *pnlPostBoost_Long;
    TLabel *lblPostBoost_Long1;
    TLabel *lblPostBoost_Long;
    TEdit *edtPostBoost_Long;
    TGroupBox *grpTempCtrl;
    TLabel *lblAmbGuardBand;
    TLabel *lblAmbGuardBandDeg;
    TEdit *edAmbHotGuartbent;
    TCheckBox *chkShuttleNoHeatUp;
    TGroupBox *rgTemperatureMode1;
    TRadioGroup *rgTemperatureMode;
    TGroupBox *rgIndexHeatMode1;
    TPanel *Panel5;
    TPanel *Panel10;
    TPanel *Panel25;
    TPanel *Panel29;
    TPanel *Panel34;
    TPanel *Panel17;
    TLabel *lblNotice;
    TMemo *palIndiTemp;
    TMemo *Memo1;
    TMemo *Memo2;
    TMemo *memoInitialTempOffset;
    TMemo *Memo3;
    TPanel *pnlArm2Offset;
    TLabel *lblArm2Offset;
    TEdit *edArm2Offset;
    TPanel *pnlArm1Offset;
    TLabel *lblArm1Offset;
    TEdit *edArm1Offset;
    TGroupBox *grpBoostMode;
    TRadioGroup *rgBoostMode;
    TPanel *Panel18;
    TGroupBox *grbATCTempAlarm;
    TLabel *Label46;
    TEdit *edtATCSP2;
    TGroupBox *grpTemperatureCheck;
    TCheckBox *rbTestStartOn;
    TCheckBox *rbHandlerStartOn;
    TGroupBox *gb_TjFunction;
    TCheckBox *chk_UseTj;
    TRadioGroup *rg_TjMode;
    TEdit *edt_TjAvgTimes;
    TPanel *Panel19;
    TGroupBox *gbChillerTemp;
    TEdit *edChillerTemp;
    TGroupBox *gbATCAmbientTemp;
    TLabel *Label16;
    TEdit *edATCAmbTemp;
    TGroupBox *grpTempAlwaysSameTime;
    TLabel *lb1;
    TEdit *edTempAlwaysSameAlarm;
    TPanel *Panel20;
    TGroupBox *grpATCTempOffset;
    TLabel *lb2;
    TLabel *lb3;
    TLabel *lb4;
    TLabel *lb5;
    TLabel *lb6;
    TLabel *lb7;
    TEdit *edtATCOffset_01;
    TEdit *edtATCOffset_02;
    TEdit *edtATCOffset_03;
    TEdit *edtATCOffset_04;
    TEdit *edtATCOffset_05;
    TEdit *edtATCOffset_06;
    TEdit *edtATCOffset_07;
    TEdit *edtATCOffset_08;
    TEdit *edtATCOffset_09;
    TEdit *edtATCOffset_10;
    TEdit *edtATCOffset_11;
    TEdit *edtATCOffset_12;
    TEdit *edtATCOffset_13;
    TEdit *edtATCOffset_14;
    TEdit *edtATCOffset_15;
    TEdit *edtATCOffset_16;
    TEdit *edtATCOffset_17;
    TEdit *edtATCOffset_25;
    TEdit *edtATCOffset_26;
    TEdit *edtATCOffset_18;
    TEdit *edtATCOffset_19;
    TEdit *edtATCOffset_27;
    TEdit *edtATCOffset_28;
    TEdit *edtATCOffset_20;
    TEdit *edtATCOffset_21;
    TEdit *edtATCOffset_29;
    TEdit *edtATCOffset_30;
    TEdit *edtATCOffset_22;
    TEdit *edtATCOffset_23;
    TEdit *edtATCOffset_31;
    TEdit *edtATCOffset_32;
    TEdit *edtATCOffset_24;
    TGroupBox *grpInPC;
    TLabel *lblATCInPC1;
    TLabel *lblATCInPC2;
    TLabel *lblATCInPC4;
    TLabel *lblATCInPC3;
    TEdit *edtATCInPC1;
    TEdit *edtATCInPC2;
    TEdit *edtATCInPC3;
    TEdit *edtATCInPC4;
    TImage *Image1;
    TLabel *lblCurr;
    TLabel *Label18;
    TEdit *edtCurrTemp;
    TCheckBox *chkUseCDAOnly;
    TTabSheet *tsLBCtr;
    TPanel *Panel22;
    TCheckBox *chkLBTempFunction;
    TGroupBox *grpLBPre;
    TPanel *Panel24;
    TLabel *lblLBTempMin_1;
    TLabel *lblLBTempMin;
    TEdit *edtLBTempMin;
    TPanel *Panel26;
    TLabel *lblLBTempOffset_1;
    TLabel *lblLBTempOffset;
    TEdit *edtLBTempOffset;
    TGroupBox *grpLBInitialOffset;
    TPanel *pnlLBInitialOffset1;
    TLabel *lblIdleTime_LB_1;
    TLabel *lblIdleTime_LB;
    TEdit *edtIdleTime_LB;
    TPanel *pnlLBInitialOffset2;
    TLabel *lblBoostOffset_LB_1;
    TLabel *lblBoostOffset_LB;
    TEdit *edtBoostOffset_LB;
    TPanel *pnlLBInitialOffset3;
    TLabel *lblBoostDuration_LB_1;
    TLabel *lblBoostDuration_LB;
    TEdit *edtBoostDuration_LB;
    TPanel *pnlLBInitialOffset4;
    TLabel *lblPostBoost_LB_1;
    TLabel *lblPostBoost_LB;
    TEdit *edtPostBoost_LB;
    TTabSheet *tsUnUse;
    TGroupBox *grpBoostOffset;
    TPanel *pnlBoostOffset1;
    TLabel *lblBoostOffset2;
    TLabel *lblBoostOffset;
    TEdit *edtBoostTempMin;
    TPanel *pnlBoostOffset2;
    TLabel *lblBoostOffset3;
    TLabel *lblBoostOffset1;
    TEdit *edtBoostOffset;
    TPanel *pnlBoostOffset;
    TCheckBox *chkBoostOffset;
    TPanel *pnlLBInitialOffset;
    TCheckBox *chkLBInitOffset;
    TSpeedButton *btnSort;
    TPanel *Panel30;
    TCheckBox *rbATCActiveOn;
    TGroupBox *grpRS232;
    TCheckBox *rbTemperatureSetOn;
    TCheckBox *cbATCReferTempSensor;
    TSpeedButton *sbSafeTestATC;
    TGroupBox *gbFileName;
    TEdit *edAtcFileName;
    TComboBox *cbbATC_RecipeFile;
    TRadioButton *RaWriteATCFile;
    TRadioButton *RachoiceATCFile;
    TPanel *Panel33;
    TLabel *Label8;
    TLabel *Label23;
    TEdit *edtLBTimeOut;
    TPanel *Panel38;
    TCheckBox *cbTestStartToNextTestStart;
    TEdit *iTeststartToNextTestStart;
    TEdit *edtInitialDelay_10;
    TLabel *lblFT;
    TLabel *lblRT;
    TEdit *edtInitialDelay_1_RT;
    TEdit *edtInitialDelay_2_RT;
    TEdit *edtInitialDelay_3_RT;
    TEdit *edtInitialDelay_5_RT;
    TEdit *edtInitialDelay_4_RT;
    TEdit *edtInitialDelay_6_RT;
    TEdit *edtInitialDelay_7_RT;
    TEdit *edtInitialDelay_9_RT;
    TEdit *edtInitialDelay_8_RT;
    TEdit *edtInitialDelay_10_RT;
    TPanel *Panel3;
    TPanel *Panel12;
    TPanel *Panel23;
    TPanel *Panel9;
    TPanel *Panel37;
    TGroupBox *gbATCPackageOffset;
    TLabel *Label24;
    TLabel *Label25;
    TLabel *Label32;
    TEdit *edtATC_PackageOffset_01;
    TEdit *edtATC_PackageOffset_02;
    TEdit *edtATC_PackageOffset_03;
    TEdit *edtATC_PackageTemp_03;
    TEdit *edtATC_PackageTemp_02;
    TEdit *edtATC_PackageTemp_01;
    TGroupBox *grpTJTempRange;
    TEdit *edTJTempRange_High;
    TLabel *lbTJTempRange_High;
    TEdit *edTJTempRange_Low;
    TLabel *lbTJTempRange_Low;
    TGroupBox *gb_HotGunFlow;
    TLabel *Label29;
    TLabel *Label33;
    TEdit *edtHotGunFLowLimit_H;
    TEdit *edtHotGunFLowLimit_L;
    TPanel *pnlthreshold;
    TLabel *lblthreshold_1;
    TLabel *lblthreshold;
    TEdit *edtThreshold;
    TPanel *PnlDewPointAlarm;
    TLabel *Label34;
    TLabel *Label35;
    TLabel *Label36;
    TLabel *Label37;
    TCheckBox *cbWaitDewPoint;
    TEdit *edDewPointAlarmInterval;
    TEdit *edDewPointRange;
    TTabSheet *tsATC_FFC;
    TPanel *Panel131;
    TLabel *lbIndiVidualTemperArm2Enable;
    TLabel *lbIndiVidualTemperArm2TimeOn;
    TLabel *lbIndiVidualTemperArm2TimeOff;
    TLabel *lbIndiVidualTemperArm2Offset;
    TLabel *Label729;
    TLabel *Label730;
    TLabel *Label731;
    TLabel *Label732;
    TLabel *Label733;
    TLabel *Label734;
    TLabel *Label735;
    TLabel *Label736;
    TLabel *Label737;
    TLabel *Label738;
    TLabel *Label739;
    TLabel *Label740;
    TLabel *Label741;
    TLabel *Label742;
    TLabel *Label743;
    TLabel *Label744;
    TLabel *Label745;
    TLabel *Label746;
    TLabel *Label747;
    TLabel *Label748;
    TLabel *Label749;
    TLabel *Label750;
    TLabel *Label751;
    TLabel *Label752;
    TLabel *Label753;
    TLabel *Label754;
    TLabel *Label755;
    TLabel *Label756;
    TLabel *Label757;
    TLabel *Label758;
    TPanel *Panel132;
    TCheckBox *edFFC_Arm2Enable_01;
    TCheckBox *edFFC_Arm2Enable_02;
    TCheckBox *edFFC_Arm2Enable_03;
    TCheckBox *edFFC_Arm2Enable_04;
    TCheckBox *edFFC_Arm2Enable_05;
    TCheckBox *edFFC_Arm2Enable_06;
    TCheckBox *edFFC_Arm2Enable_07;
    TCheckBox *edFFC_Arm2Enable_08;
    TCheckBox *edFFC_Arm2Enable_09;
    TCheckBox *edFFC_Arm2Enable_10;
    TEdit *edFFC_Arm2TimeOn_01;
    TEdit *edFFC_Arm2TimeOn_02;
    TEdit *edFFC_Arm2TimeOff_01;
    TEdit *edFFC_Arm2TimeOff_02;
    TEdit *edFFC_Arm2Offset_01;
    TEdit *edFFC_Arm2Offset_02;
    TEdit *edFFC_Arm2TimeOn_03;
    TEdit *edFFC_Arm2TimeOff_03;
    TEdit *edFFC_Arm2Offset_03;
    TEdit *edFFC_Arm2Offset_04;
    TEdit *edFFC_Arm2TimeOff_04;
    TEdit *edFFC_Arm2TimeOn_04;
    TEdit *edFFC_Arm2TimeOn_05;
    TEdit *edFFC_Arm2TimeOff_05;
    TEdit *edFFC_Arm2Offset_05;
    TEdit *edFFC_Arm2Offset_06;
    TEdit *edFFC_Arm2TimeOff_06;
    TEdit *edFFC_Arm2TimeOn_06;
    TEdit *edFFC_Arm2TimeOn_07;
    TEdit *edFFC_Arm2TimeOn_08;
    TEdit *edFFC_Arm2TimeOn_09;
    TEdit *edFFC_Arm2TimeOn_10;
    TEdit *edFFC_Arm2TimeOff_10;
    TEdit *edFFC_Arm2TimeOff_09;
    TEdit *edFFC_Arm2TimeOff_08;
    TEdit *edFFC_Arm2TimeOff_07;
    TEdit *edFFC_Arm2Offset_10;
    TEdit *edFFC_Arm2Offset_09;
    TEdit *edFFC_Arm2Offset_08;
    TEdit *edFFC_Arm2Offset_07;
    TButton *btnSameAsArm1;
    TPanel *Panel129;
    TLabel *lbIndiVidualTemperArm1Enable;
    TLabel *lbIndiVidualTemperArm1TimeOn;
    TLabel *lbIndiVidualTemperArm1TimeOff;
    TLabel *lbIndiVidualTemperArm1Offset;
    TLabel *Label699;
    TLabel *Label700;
    TLabel *Label701;
    TLabel *Label702;
    TLabel *Label703;
    TLabel *Label704;
    TLabel *Label705;
    TLabel *Label706;
    TLabel *Label707;
    TLabel *Label708;
    TLabel *Label709;
    TLabel *Label710;
    TLabel *Label711;
    TLabel *Label712;
    TLabel *Label713;
    TLabel *Label714;
    TLabel *Label715;
    TLabel *Label716;
    TLabel *Label717;
    TLabel *Label718;
    TLabel *Label719;
    TLabel *Label720;
    TLabel *Label721;
    TLabel *Label722;
    TLabel *Label723;
    TLabel *Label724;
    TLabel *Label725;
    TLabel *Label726;
    TLabel *Label727;
    TLabel *Label728;
    TPanel *Panel130;
    TCheckBox *edFFC_Arm1Enable_01;
    TCheckBox *edFFC_Arm1Enable_02;
    TCheckBox *edFFC_Arm1Enable_03;
    TCheckBox *edFFC_Arm1Enable_04;
    TCheckBox *edFFC_Arm1Enable_06;
    TCheckBox *edFFC_Arm1Enable_05;
    TCheckBox *edFFC_Arm1Enable_07;
    TCheckBox *edFFC_Arm1Enable_09;
    TCheckBox *edFFC_Arm1Enable_08;
    TCheckBox *edFFC_Arm1Enable_10;
    TEdit *edFFC_Arm1TimeOn_07;
    TEdit *edFFC_Arm1TimeOff_01;
    TEdit *edFFC_Arm1Offset_01;
    TEdit *edFFC_Arm1TimeOn_06;
    TEdit *edFFC_Arm1TimeOff_02;
    TEdit *edFFC_Arm1Offset_02;
    TEdit *edFFC_Arm1TimeOn_08;
    TEdit *edFFC_Arm1TimeOff_03;
    TEdit *edFFC_Arm1Offset_03;
    TEdit *edFFC_Arm1TimeOn_10;
    TEdit *edFFC_Arm1TimeOff_04;
    TEdit *edFFC_Arm1Offset_04;
    TEdit *edFFC_Arm1TimeOn_09;
    TEdit *edFFC_Arm1TimeOff_05;
    TEdit *edFFC_Arm1Offset_05;
    TEdit *edFFC_Arm1TimeOn_02;
    TEdit *edFFC_Arm1TimeOff_06;
    TEdit *edFFC_Arm1Offset_06;
    TEdit *edFFC_Arm1TimeOn_01;
    TEdit *edFFC_Arm1TimeOff_07;
    TEdit *edFFC_Arm1Offset_07;
    TEdit *edFFC_Arm1TimeOn_03;
    TEdit *edFFC_Arm1TimeOff_08;
    TEdit *edFFC_Arm1Offset_08;
    TEdit *edFFC_Arm1TimeOn_05;
    TEdit *edFFC_Arm1TimeOff_09;
    TEdit *edFFC_Arm1Offset_09;
    TEdit *edFFC_Arm1TimeOn_04;
    TEdit *edFFC_Arm1TimeOff_10;
    TEdit *edFFC_Arm1Offset_10;
    TCheckBox *cbFFCOffsetEnable;
    TGroupBox *grpChamberBoost;
    TLabel *lblChamberBoostTime;
    TLabel *lblChamberBoostOffset;
    TCheckBox *chkChamberBoost;
    TEdit *edtChamberBoostTime;
    TEdit *edtChamberBoostOffset;
    TTabSheet *tsSigmaForTemp;
    TGroupBox *gbcb3SigmaTempMonitior;
    TLabel *Label803;
    TLabel *Label804;
    TCheckBox *cb3SigmaTempMonitior_Enable;
    TEdit *edt3SigmaTempMonitior_SetCount;
    TEdit *edt3SigmaTempMonitior_Set3xSigmaValue;
    TCheckBox *cbATCHeaterGun;
    TPanel *pnlCover;
    TGroupBox *gbHeatGunTempATC;
    TLabel *Label38;
    TEdit *edtHeatGunTempATC;
    TCheckBox *chkTempCalByRecipe;
    TPanel *palLBAir;
    TLabel *labLB1;
    TLabel *labLB3;
    TLabel *labLB2;
    TLabel *labLB4;
    TCheckBox *cbBlowLB;
    TEdit *edLBTempAlarmTime;
    TEdit *edtLBAirOnTemp;
    TGroupBox *grpATC_HotAir;
    TLabel *Label39;
    TLabel *Label40;
    TEdit *edtATC_HotGunTemp;
    TEdit *edtATC_HotGunTime;
    TCheckBox *chkSLKNoHeatUp;
    TCheckBox *cbByPassChamber;
    TRadioGroup *rgBasePoint;
    TRadioButton *rbTemp;
    TGroupBox *grpTJFunction;
    TLabel *Label822;
    TLabel *Label824;
    TCheckBox *cbEnableTJFunction;
    TEdit *edtSetTJ_Offset;
    TEdit *edtSetTJ_Slope;
    TCheckBox *cbTjWatchdog;
    TLabel *Label41;
    TEdit *edtDelayAfterSOT;
    TLabel *Label42;
    TEdit *edtInputVLow;
    TEdit *edtInputVHigh;
    TStringGrid *sgTjMap;
    TRadioGroup *rgTjMapType;
    TRadioGroup *rgATC60AirOn;
    TLabel *labReadyTempRange;
    TEdit *edTempReadyRange;
    TGroupBox *gbMultiZone;
    TCheckBox *cbMultiZoneFunction;
    TCheckBox *cbZoneEnable1;
    TEdit *edZoneSetting1;
    TCheckBox *cbZoneEnable2;
    TEdit *edZoneSetting2;
    TCheckBox *cbZoneEnable3;
    TEdit *edZoneSetting3;
    TCheckBox *cbZoneEnable4;
    TEdit *edZoneSetting4;
    TTabSheet *tsOthers;
    TEdit *edLBTempHighSettingValue;
    TEdit *edLBTempLowSettingValue;
    TEdit *edATCOfsTime;
    TTabSheet *tsTriTempSet;
    TGroupBox *gbDefrostFunction;
    TGroupBox *GroupBox3;
    TStringGrid *sgDefrostStatus;
    TGroupBox *GroupBox4;
    TButton *btnDefrostStart;
    TButton *btnDefrostEnd;
    TComboBox *cbSelectDevice;
    TGroupBox *GroupBox5;
    TButton *btn_DefrostAllUseStart;
    TButton *btn_DefrostAllUseEnd;
    TGroupBox *GroupBox6;
    TLabel *Label43;
    TCheckBox *cbEnableTesterDryAirControl;
    TEdit *edt_Defrost_Time_Too_Lower;
    TLabel *lblTempBase;
    TEdit *edAbLow;
    TEdit *edAbMid;
    TEdit *edLowBase;
    TEdit *edMidBase;
    TEdit *edHighBase;
    TEdit *edSHighBase;
    TTimer *tmr_ATC_Deforst;
    TGroupBox *grpIndexAirStream;
    TLabel *Label63;
    TLabel *Label64;
    TLabel *Label47;
    TLabel *Label66;
    TEdit *edt_SetIndexAirstreamTemp;
    TEdit *edt_SetAirstreamTemperatureRang_Index;
    TCheckBox *chk_EnableArm_1_Air;
    TCheckBox *chk_EnableArm_2_Air;
    TEdit *edt_AirVolumeLmt_Index;
    TGroupBox *grpSocketAirStream;
    TLabel *Label577;
    TLabel *Label578;
    TLabel *Label48;
    TLabel *Label67;
    TEdit *edtSetTempature2AirMachine;
    TEdit *edt_SetAirstreamTemperatureRang_Socket;
    TCheckBox *cb_EnableAirMachineSocket;
    TCheckBox *chk_EnableSocket_Air;
    TEdit *edt_AirVolumeLmt_Socket;
    TRadioButton *rb6Point;
    TPageControl *PageControl1;
    TTabSheet *tsStandard;
    TRadioGroup *rgIndexHeatMode;
    TTabSheet *tsTriTemp;
    TCheckBox *chkTriTempEnableOutSht;
    TCheckBox *chkTriTempEnableIndex;
    TCheckBox *chkTriTempEnableBase;
    TCheckBox *chk_IndexHeaterDoor;
    TGroupBox *gbPowerFollowFuncAct;
    TLabel *Label883;
    TLabel *Label884;
    TLabel *Label885;
    TLabel *Label49;
    TCheckBox *cbPowerFollow_Enable;
    TEdit *edtPowerFollower_PFSlope;
    TEdit *edtPowerFollow_FullPower;
    TEdit *edtPowerFollower_WGain;
    TEdit *edtPowerFollower_Many2one;
    TGroupBox *grpTemperatureRise;
    TLabel *Label50;
    TLabel *Label51;
    TCheckBox *cbATCTempRise;
    TEdit *edt_TempRiseTemp;
    TEdit *edt_TempRise_Delay;
    TCheckBox *cbUseTC2Offset;
    TCheckBox *chkTempErrorAction;
    TGroupBox *gbATC_Type;
    TEdit *edtATC_Type;
    TEdit *edContinuousSec;
    TCheckBox *cbLBTempHighAlarmEnable;
    TCheckBox *cbLBTempLowAlarmEnable;
    TTabSheet *tsATCMultiSensor;
    TCheckBox *cbMultiSensorOffsetEnable;
    TCheckBox *cbMultiSensorEnable1;
    TCheckBox *cbMultiSensorEnable2;
    TCheckBox *cbMultiSensorEnable3;
    TCheckBox *cbMultiSensorEnable4;
    TPanel *Panel35;
    TPanel *Panel39;
    TEdit *edATC_Arm1_S1_TC2;
    TEdit *edATC_Arm1_S1_TC3;
    TEdit *edATC_Arm1_S1_TC4;
    TEdit *edATC_Arm1_S1_TC1;
    TLabel *Label52;
    TLabel *Label57;
    TLabel *Label58;
    TLabel *Label59;
    TLabel *Label60;
    TEdit *edATC_Arm1_S2_TC1;
    TEdit *edATC_Arm1_S2_TC2;
    TEdit *edATC_Arm1_S2_TC3;
    TEdit *edATC_Arm1_S2_TC4;
    TLabel *Label61;
    TEdit *edATC_Arm1_S3_TC1;
    TEdit *edATC_Arm1_S3_TC2;
    TEdit *edATC_Arm1_S3_TC3;
    TEdit *edATC_Arm1_S3_TC4;
    TLabel *Label62;
    TEdit *edATC_Arm1_S4_TC1;
    TEdit *edATC_Arm1_S4_TC2;
    TEdit *edATC_Arm1_S4_TC3;
    TEdit *edATC_Arm1_S4_TC4;
    TLabel *Label65;
    TPanel *Panel40;
    TLabel *Label68;
    TLabel *Label69;
    TLabel *Label70;
    TLabel *Label71;
    TLabel *Label72;
    TLabel *Label73;
    TLabel *Label74;
    TLabel *Label75;
    TPanel *Panel43;
    TEdit *edATC_Arm2_S1_TC2;
    TEdit *edATC_Arm2_S1_TC3;
    TEdit *edATC_Arm2_S1_TC4;
    TEdit *edATC_Arm2_S1_TC1;
    TEdit *edATC_Arm2_S2_TC1;
    TEdit *edATC_Arm2_S2_TC2;
    TEdit *edATC_Arm2_S2_TC3;
    TEdit *edATC_Arm2_S2_TC4;
    TEdit *edATC_Arm2_S3_TC1;
    TEdit *edATC_Arm2_S3_TC2;
    TEdit *edATC_Arm2_S3_TC3;
    TEdit *edATC_Arm2_S3_TC4;
    TEdit *edATC_Arm2_S4_TC1;
    TEdit *edATC_Arm2_S4_TC2;
    TEdit *edATC_Arm2_S4_TC3;
    TEdit *edATC_Arm2_S4_TC4;
    void __fastcall rb1PointClick(TObject *Sender);
    void __fastcall FormShow(TObject *Sender);
    void __fastcall edSoakTimeKeyPress(TObject *Sender, char &Key);
    void __fastcall edSoakTimeClick(TObject *Sender);
    void __fastcall edLHP1MouseDown(TObject *Sender, TMouseButton Button,
          TShiftState Shift, int X, int Y);
    void __fastcall FormClose(TObject *Sender, TCloseAction &Action);
    void __fastcall edLHP1KeyUp(TObject *Sender, WORD &Key,
          TShiftState Shift);
    void __fastcall edLowBaseMouseDown(TObject *Sender, TMouseButton Button,
          TShiftState Shift, int X, int Y);
    void __fastcall rgIndexHeatModeClick(TObject *Sender);
    void __fastcall spbSaveClick(TObject *Sender);
    void __fastcall sbtExitClick(TObject *Sender);
    void __fastcall btClearAllClick(TObject *Sender);
    void __fastcall pgcTempOffsetChange(TObject *Sender);
    void __fastcall edLHeatGun1MouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
    void __fastcall rgTemperatureModeClick(TObject *Sender);
    void __fastcall edTargetHP1MouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
    void __fastcall cbEnableIndividualModeClick(TObject *Sender);
    void __fastcall edtATCInPC1MouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
    void __fastcall rbATC70ActiveOnClick(TObject *Sender);
    void __fastcall rbATCActiveOnClick(TObject *Sender);
    void __fastcall edAtcFileNameMouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
    void __fastcall edATCAmbTempMouseDown(TObject *Sender, TMouseButton Button,
          TShiftState Shift, int X, int Y);
    void __fastcall edArm1OffsetMouseDown(TObject *Sender, TMouseButton Button,
          TShiftState Shift, int X, int Y);
    void __fastcall edATCTestTimeOffsetMouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
    void __fastcall edATCInitialOffset1MouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
    void __fastcall edATCTempAlwaysSameAlarmMouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
    void __fastcall edArm1NoFullsiteOffset_1MouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
    void __fastcall edTSDTimeOutMouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
    void __fastcall sbSafeTestATCClick(TObject *Sender);
    void __fastcall edATCChillerTempMouseDown(TObject *Sender,
        TMouseButton Button, TShiftState Shift, int X, int Y);
    void __fastcall edAmbTempClick(TObject *Sender);
    void __fastcall FormCreate(TObject *Sender);
    void __fastcall edtIdleTime_LongClick(TObject *Sender);
    void __fastcall edtBoostOffset_LongClick(TObject *Sender);
    void __fastcall edAmbHotGuartbentClick(TObject *Sender);
    void __fastcall edtBoostOffsetClick(TObject *Sender);
    void __fastcall edtInitialDelay_1Click(TObject *Sender);
    void __fastcall btnSortClick(TObject *Sender);
    void __fastcall edLimitHP1MouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
    void __fastcall edtLBTimeOutClick(TObject *Sender);
    void __fastcall FormDestroy(TObject *Sender);
    void __fastcall edTJTempRange_HighClick(TObject *Sender);
    void __fastcall edTJTempRange_LowClick(TObject *Sender);
    void __fastcall edtThresholdClick(TObject *Sender);
    void __fastcall edDewPointRangeMouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
    void __fastcall edDewPointAlarmIntervalMouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
    void __fastcall btnSameAsArm1Click(TObject *Sender);
    void __fastcall edtChamberBoostTimeClick(TObject *Sender);
    void __fastcall edtChamberBoostOffsetClick(TObject *Sender);
    void __fastcall edTempOffsetCountClick(TObject *Sender);
    void __fastcall edTempDownContactDelayClick(TObject *Sender);
    void __fastcall edtHeatGunTempATCMouseDown(TObject *Sender, TMouseButton Button,
          TShiftState Shift, int X, int Y);
    void __fastcall chkTempCalByRecipeClick(TObject *Sender);
    void __fastcall FormShortCut(TWMKey &Msg, bool &Handled);
    void __fastcall edLBTempAlarmTimeMouseDown(TObject *Sender, TMouseButton Button,
          TShiftState Shift, int X, int Y);
    void __fastcall edtLBAirOnTempMouseDown(TObject *Sender, TMouseButton Button,
          TShiftState Shift, int X, int Y);
    void __fastcall edtATCPIDOffset_MinPClick(TObject *Sender);
    void __fastcall edJamSoakTimeClick(TObject *Sender);
    void __fastcall edFFC_Arm1TimeOn_01Click(TObject *Sender);
    void __fastcall edtATC_HotGunTimeClick(TObject *Sender);
    void __fastcall edtLBTempMinClick(TObject *Sender);
    void __fastcall edAmbGuardbandClick(TObject *Sender);
    void __fastcall rgBasePointClick(TObject *Sender);
    void __fastcall edtSetTJ_OffsetClick(TObject *Sender);
    void __fastcall edtSetTJ_SlopeChange(TObject *Sender);
    void __fastcall sgTjMapMouseDown(TObject *Sender, TMouseButton Button,
          TShiftState Shift, int X, int Y);
    void __fastcall rgTjMapTypeClick(TObject *Sender);
    void __fastcall edTempReadyRangeMouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
    void __fastcall edATCOfsTimeMouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
    void __fastcall btnDefrostStartClick(TObject *Sender);
    void __fastcall btnDefrostEndClick(TObject *Sender);
    void __fastcall btn_DefrostAllUseStartClick(TObject *Sender);
    void __fastcall btn_DefrostAllUseEndClick(TObject *Sender);
    void __fastcall edt_Defrost_Time_Too_LowerClick(TObject *Sender);
    void __fastcall edtSetTempature2AirMachineClick(TObject *Sender);
    void __fastcall edt_SetAirstreamTemperatureRang_SocketClick(
          TObject *Sender);
    void __fastcall tmr_ATC_DeforstTimer(TObject *Sender);
    void __fastcall cbSelectDeviceChange(TObject *Sender);
    void __fastcall edt_AirVolumeLmt_IndexClick(TObject *Sender);
    void __fastcall cbATCReferTempSensorClick(TObject *Sender);
private:    // User declarations
    void DisableOffset();
    void DisplayTargetTempEdit(bool Visible);
    bool CheckTempSettingChange();                                              //JerryYang 20170213 (Steven) 修改Run check觸發條件
    void ShowLineOnTop();
public:     // User declarations
    __fastcall TfTemp_Set(TComponent* Owner);
    bool fShow;
    int iTempMoldSet;
    TMyTempPanel *myTempPal[tcTotalCount];
    void __fastcall SetBasePointIMG(int iPoint);
    void __fastcall UpDateEdit();
    void __fastcall ReadTempFile(bool bUpdateAll);
    void __fastcall DoIniDataToForm(bool bUpdateAll);
    void __fastcall SaveSetupFile(AnsiString szDir, AnsiString S);              //kevin 20150105
    void __fastcall SendATCSelfTest(int Source);                                //Ifor 20160823 add 送出ATC Self Test 1:Auto  2:Manually
    int  __fastcall SaveRemoteTempOffset(int iArm, int iSite, double dOffset);
    void __fastcall SaveRemoteTempOffsetFromGPIB(AnsiString Msg);               //Steven 20241113 : for MSG_CMD_SetTJ / DEVICETEMP / SETTESTOFFSET_
    void __fastcall ReadRemoteTempOffset();

    TLabel *lblIndexLabel[2][16];
    double MaxTempSetting();                                                    //Steven 20170427 : 回傳機台可以用的最大溫度值
    double MinTempSetting();                                                    //Steven 20230707 : 回傳機台可以用的最低溫度值
    void ControlATC60AirFlow(int iStatus=-1);

    int iAddrToATC[tcTotalCount];                                               //Steven 20241105 : 溫控器的地址轉為ATC的頻道
    int iATCToAddr[ATC_HEAD_COUNT];                                             //Steven 20241105 : ATC的頻道轉為溫控器的地址
    int iSiteToATC[2][MAX_Index_Row][MAX_Index_Col];                            //Steven 20241105 : ATC的頻道轉為Site的Row & Col
    int iSiteToOfs[2][MAX_Index_Row][MAX_Index_Col];                            //Steven 20241105 : ATC的頻道轉為Site的Offset index
    int iATCToSiteArm[ATC_HEAD_COUNT];                                          //Steven 20241105 : Site的Row & Col轉為ATC的頻道
    int iATCToSiteRow[ATC_HEAD_COUNT];                                          //Steven 20241105 : Site的Row & Col轉為ATC的頻道
    int iATCToSiteCol[ATC_HEAD_COUNT];                                          //Steven 20241105 : Site的Row & Col轉為ATC的頻道
    int InitialAddrToATC();                                                     //Steven 20241105 : 更新轉換矩陣
    bool bNeedChange;

    TTimer  *tmrDefrost;                                                        //Ztex 2023.04.19 Add HT-1032 TriTemp Function
    struct stcDefrostFunction
    {
        bool bDefrostReq[MAX_DEFROST_AREA];
        bool bDefrostSetTemp[MAX_DEFROST_AREA];
        bool bDefrostHeart_OK[MAX_DEFROST_AREA];
        bool bDefrostStart[MAX_DEFROST_AREA];
        bool bDefrostEnd[MAX_DEFROST_AREA];
        AnsiString strDefrostDevice[MAX_DEFROST_AREA];
        int iDefrostCountingDownTime[MAX_DEFROST_AREA];
    }DefrostFunction;
    bool bTestDefrost;
    void SwitchOnOffRefrigeratorNo(int iRefrigeratorNo, int iOnOff);
    void UseCloseSiteTemperatureCtrl(int iChannel, bool bUse);
    void SetSingleWorkTemperature(int iChannel, double fTemp, bool bDefrost=false);
    void SetCloseSiteTemperature(double fTemp);
    void SetTempPanelCaption();
    int  CheckVerSupportFunction();
    void ATC_Power();
    void ATC_Online_Or_offline();
    void __fastcall CheckAirMachineStatus();
    void Tri_Temp_Low_Temperature_Use_Heater();
    void Handler_Send_To_ATC_DewPoint(double dDewPoint_Index,double dDewPoint_InSht,double dDewPointOutSht);
    void Tri_Temp_High_Temperature_UseNo_Heater();                              //Ztex 2023.04.19 Add HT-1032 TriTemp Function

};
//---------------------------------------------------------------------------
extern PACKAGE TfTemp_Set *fTemp_Set;
//******************************************************************************
//
//  注意!! uTemp_Set為Handler 溫度設定相關, 修改時要小心!!
//
//******************************************************************************
#endif
