// ===========================================================================
//  ProductionInfo/uESDControl_layout.gen.cpp
//  DO NOT EDIT -- GENERATED FILE. See the matching _layout.gen.h banner.
// ===========================================================================
#include "uESDControl_layout.gen.h"

namespace ht9045_layout {

// (no custom-control properties in this form)

const DfmControlLayout kuESDControlLayout[] = {
    { "ESDForm", "ESDForm", "", "TESDForm", "", "", 0, 0, "ROOT", false, true, 394, true, 118, false, 0, false, 0, false, 0, -1, "", "", true, "MS Sans Serif", -11, "", true, -2147483640, "clWindowText", true, 12761254, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "ESDForm.sbExit", "sbExit", "IDC_UESDCONTROL_SBEXIT", "TSpeedButton", "ESDForm", "ESDForm", 0, 1, "LEAF", true, true, 0, true, 526, true, 795, true, 45, false, 0, -1, "", "", true, "MS Sans Serif", -13, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "ESDForm.pcESDMain", "pcESDMain", "IDC_UESDCONTROL_PCESDMAIN", "TPageControl", "ESDForm", "ESDForm", 1, 1, "TABHOST", false, true, 0, true, 0, true, 831, true, 520, true, 0, -1, "alTop", "", true, "MS Sans Serif", -13, "", true, 8388608, "clNavy", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "ESDForm.pcESDMain.tsESDMain", "tsESDMain", "IDD_UESDCONTROL_PCESDMAIN_TSESDMAIN", "TTabSheet", "ESDForm.pcESDMain", "ESDForm", 0, 2, "SUBDLG", false, false, 0, false, 0, false, 0, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "ESDForm.pcESDMain.tsESDMain.sbESDDataImport", "sbESDDataImport", "IDC_UESDCONTROL_SBESDDATAIMPORT", "TSpeedButton", "ESDForm.pcESDMain.tsESDMain", "ESDForm.pcESDMain.tsESDMain", 0, 3, "LEAF", true, true, 2, true, 440, true, 110, true, 45, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "ESDForm.pcESDMain.tsESDMain.pn_ESDDataItem", "pn_ESDDataItem", "IDC_UESDCONTROL_PN_ESDDATAITEM", "TPanel", "ESDForm.pcESDMain.tsESDMain", "ESDForm.pcESDMain.tsESDMain", 1, 3, "LEAF", false, true, 0, true, 0, true, 823, true, 30, true, 0, -1, "alTop", "", false, "", 0, "", false, 0, "", true, 12761254, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "ESDForm.pcESDMain.tsESDMain.ESDDBGrid", "ESDDBGrid", "IDC_UESDCONTROL_ESDDBGRID", "TDBGrid", "ESDForm.pcESDMain.tsESDMain", "ESDForm.pcESDMain.tsESDMain", 2, 3, "LEAF", false, true, 0, true, 30, true, 823, true, 404, true, 1, -1, "alTop", "", false, "", 0, "", false, 0, "", true, 14670284, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "ESDForm.pcESDMain.tsESDSetup", "tsESDSetup", "IDD_UESDCONTROL_PCESDMAIN_TSESDSETUP", "TTabSheet", "ESDForm.pcESDMain", "ESDForm", 1, 2, "SUBDLG", false, false, 0, false, 0, false, 0, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "ESDForm.pcESDMain.tsESDSetup.SpeedButton1", "SpeedButton1", "IDC_UESDCONTROL_SPEEDBUTTON1", "TSpeedButton", "ESDForm.pcESDMain.tsESDSetup", "ESDForm.pcESDMain.tsESDSetup", 0, 3, "LEAF", true, true, 152, true, 328, true, 65, true, 25, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "ESDForm.pcESDMain.tsESDSetup.FileListBox1", "FileListBox1", "IDC_UESDCONTROL_FILELISTBOX1", "TFileListBox", "ESDForm.pcESDMain.tsESDSetup", "ESDForm.pcESDMain.tsESDSetup", 1, 3, "LEAF", false, true, 2, true, 39, true, 23, true, 34, true, 2, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "ESDForm.pcESDMain.tsESDSetup.DirectoryListBox1", "DirectoryListBox1", "IDC_UESDCONTROL_DIRECTORYLISTBOX1", "TDirectoryListBox", "ESDForm.pcESDMain.tsESDSetup", "ESDForm.pcESDMain.tsESDSetup", 2, 3, "LEAF", false, true, 2, true, 3, true, 39, true, 30, true, 1, -1, "", "", true, "MS Sans Serif", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "ESDForm.pcESDMain.tsESDSetup.Panel1", "Panel1", "IDD_UESDCONTROL_PCESDMAIN_TSESDSETUP_PANEL1", "TPanel", "ESDForm.pcESDMain.tsESDSetup", "ESDForm.pcESDMain.tsESDSetup", 3, 3, "SUBDLG", false, true, 0, true, 0, true, 823, true, 257, true, 0, -1, "alTop", "", false, "", 0, "", false, 0, "", true, 12761254, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "ESDForm.pcESDMain.tsESDSetup.Panel1.Label1", "Label1", "IDC_UESDCONTROL_LABEL1", "TLabel", "ESDForm.pcESDMain.tsESDSetup.Panel1", "ESDForm.pcESDMain.tsESDSetup.Panel1", 0, 4, "LEAF", true, true, 16, true, 24, true, 178, true, 16, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "ESDForm.pcESDMain.tsESDSetup.Panel1.sbAddESDTimeSet", "sbAddESDTimeSet", "IDC_UESDCONTROL_SBADDESDTIMESET", "TSpeedButton", "ESDForm.pcESDMain.tsESDSetup.Panel1", "ESDForm.pcESDMain.tsESDSetup.Panel1", 1, 4, "LEAF", true, true, 10, true, 200, true, 110, true, 45, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "ESDForm.pcESDMain.tsESDSetup.Panel1.sbDeleteESDTime", "sbDeleteESDTime", "IDC_UESDCONTROL_SBDELETEESDTIME", "TSpeedButton", "ESDForm.pcESDMain.tsESDSetup.Panel1", "ESDForm.pcESDMain.tsESDSetup.Panel1", 2, 4, "LEAF", true, true, 125, true, 200, true, 110, true, 45, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "ESDForm.pcESDMain.tsESDSetup.Panel1.sbUpdate", "sbUpdate", "IDC_UESDCONTROL_SBUPDATE", "TSpeedButton", "ESDForm.pcESDMain.tsESDSetup.Panel1", "ESDForm.pcESDMain.tsESDSetup.Panel1", 3, 4, "LEAF", true, true, 506, true, 200, true, 110, true, 45, false, 0, -1, "", "", true, "MS Sans Serif", -13, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "ESDForm.pcESDMain.tsESDSetup.Panel1.sbSetTime", "sbSetTime", "IDC_UESDCONTROL_SBSETTIME", "TSpeedButton", "ESDForm.pcESDMain.tsESDSetup.Panel1", "ESDForm.pcESDMain.tsESDSetup.Panel1", 4, 4, "LEAF", true, true, 626, true, 84, true, 140, true, 31, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "ESDForm.pcESDMain.tsESDSetup.Panel1.sgESDSetTime", "sgESDSetTime", "IDC_UESDCONTROL_SGESDSETTIME", "TStringGrid", "ESDForm.pcESDMain.tsESDSetup.Panel1", "ESDForm.pcESDMain.tsESDSetup.Panel1", 5, 4, "LEAF", false, true, 10, true, 50, true, 605, true, 137, true, 1, -1, "", "", false, "", 0, "", false, 0, "", true, 14670284, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "ESDForm.pcESDMain.tsESDSetup.Panel1.edESDCheckForwardTime", "edESDCheckForwardTime", "IDC_UESDCONTROL_EDESDCHECKFORWARDTIME", "TEdit", "ESDForm.pcESDMain.tsESDSetup.Panel1", "ESDForm.pcESDMain.tsESDSetup.Panel1", 6, 4, "LEAF", false, true, 104, true, 20, true, 57, true, 24, true, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "ESDForm.pcESDMain.tsESDSetup.Panel1.DateTimePickerESD", "DateTimePickerESD", "IDC_UESDCONTROL_DATETIMEPICKERESD", "TDateTimePicker", "ESDForm.pcESDMain.tsESDSetup.Panel1", "ESDForm.pcESDMain.tsESDSetup.Panel1", 7, 4, "LEAF", false, true, 624, true, 50, true, 140, true, 24, true, 2, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "ESDForm.pcESDMain.tsESDSetup.edtWESD", "edtWESD", "IDC_UESDCONTROL_EDTWESD", "TEdit", "ESDForm.pcESDMain.tsESDSetup", "ESDForm.pcESDMain.tsESDSetup", 4, 3, "LEAF", false, true, 256, true, 328, true, 121, true, 24, true, 3, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "ESDForm.pcESDMain.tsESDSetup.edtLESD", "edtLESD", "IDC_UESDCONTROL_EDTLESD", "TEdit", "ESDForm.pcESDMain.tsESDSetup", "ESDForm.pcESDMain.tsESDSetup", 5, 3, "LEAF", false, true, 384, true, 328, true, 121, true, 24, true, 4, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "ESDForm.pcESDMain.tsESDSetup.edtRESD", "edtRESD", "IDC_UESDCONTROL_EDTRESD", "TEdit", "ESDForm.pcESDMain.tsESDSetup", "ESDForm.pcESDMain.tsESDSetup", 6, 3, "LEAF", false, true, 512, true, 328, true, 121, true, 24, true, 5, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "ESDForm.pcESDMain.TabSheet1", "TabSheet1", "IDD_UESDCONTROL_PCESDMAIN_TABSHEET1", "TTabSheet", "ESDForm.pcESDMain", "ESDForm", 2, 2, "SUBDLG", false, false, 0, false, 0, false, 0, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "ESDForm.pcESDMain.TabSheet1.sg_List_AUTOMOTIVE", "sg_List_AUTOMOTIVE", "IDC_UESDCONTROL_SG_LIST_AUTOMOTIVE", "TStringGrid", "ESDForm.pcESDMain.TabSheet1", "ESDForm.pcESDMain.TabSheet1", 0, 3, "LEAF", false, true, 0, true, 0, true, 823, true, 486, true, 0, -1, "alClient", "", true, "MS Sans Serif", -11, "", true, -2147483640, "clWindowText", true, 14670284, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "ESDForm.DataSourceESD", "DataSourceESD", "", "TDataSource", "ESDForm", "ESDForm", 2, 1, "NONVISUAL", false, true, 800, true, 8, false, 0, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "ESDForm.TableESD", "TableESD", "", "TTable", "ESDForm", "ESDForm", 3, 1, "NONVISUAL", false, true, 800, true, 40, false, 0, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "ESDForm.ESDQuery", "ESDQuery", "", "TQuery", "ESDForm", "ESDForm", 4, 1, "NONVISUAL", false, true, 800, true, 72, false, 0, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
};

const int kuESDControlLayoutCount = 28;

} // namespace ht9045_layout
