// ============================================================================
// DO NOT EDIT -- machine-generated by emit_rc.py W7-B1b v1.0 on BarcodeReader.dfm
// AI(W906-W7-B1b) 20260728: generated .rc/_ids.h from the .dfm IR (see
// docs/W7_UI_ARCHITECTURE_PLAN.md S6 W7-B1b). Hand edits will be
// overwritten and are rejected by the idempotence gate (G7).
// Source golden: BarcodeReader.dfm
// ============================================================================

#ifndef HT9045_UI_GEN_BARCODEREADER_IDS_H
#define HT9045_UI_GEN_BARCODEREADER_IDS_H

// Dialog template IDs
#define IDD_BARCODEREADER 8192
#define IDD_BARCODEREADER_PNLBARCODEREADER 8193

// Control IDs (D11 join key: mechanically derived from the
// .dfm leaf control name -- IDC_<FORMSTEM>_<CONTROLNAME>)
#define IDC_BARCODEREADER_LBLINPUTTYPE 1024
#define IDC_BARCODEREADER_EDTBARCODENUMBER 1025
#define IDC_BARCODEREADER_BTNENTER 1026

#endif // HT9045_UI_GEN_BARCODEREADER_IDS_H
