// ============================================================================
// DO NOT EDIT -- machine-generated by emit_rc.py W7-B1b v1.0 on cBinAoiSel.dfm
// AI(W906-W7-B1b) 20260728: generated .rc/_ids.h from the .dfm IR (see
// docs/W7_UI_ARCHITECTURE_PLAN.md S6 W7-B1b). Hand edits will be
// overwritten and are rejected by the idempotence gate (G7).
// Source golden: cBinAoiSel.dfm
// ============================================================================

#ifndef HT9045_UI_GEN_CBINAOISEL_IDS_H
#define HT9045_UI_GEN_CBINAOISEL_IDS_H

// Dialog template IDs
#define IDD_CBINAOISEL 8192
#define IDD_CBINAOISEL_PANEL2 8193
#define IDD_CBINAOISEL_SCROLLBOX1 8194

// Control IDs (D11 join key: mechanically derived from the
// .dfm leaf control name -- IDC_<FORMSTEM>_<CONTROLNAME>)
#define IDC_CBINAOISEL_LABEL1 1024
#define IDC_CBINAOISEL_SPBEXIT 1025

#endif // HT9045_UI_GEN_CBINAOISEL_IDS_H
