// ============================================================================
// DO NOT EDIT -- machine-generated by emit_rc.py W7-B1b v1.0 on cBuilder.dfm
// AI(W906-W7-B1b) 20260728: generated .rc/_ids.h from the .dfm IR (see
// docs/W7_UI_ARCHITECTURE_PLAN.md S6 W7-B1b). Hand edits will be
// overwritten and are rejected by the idempotence gate (G7).
// Source golden: cBuilder.dfm
// ============================================================================

#ifndef HT9045_UI_GEN_CBUILDER_IDS_H
#define HT9045_UI_GEN_CBUILDER_IDS_H

// Dialog template IDs
#define IDD_CBUILDER 8192
#define IDD_CBUILDER_GROUPBOX5 8193
#define IDD_CBUILDER_GROUPBOX6 8194
#define IDD_CBUILDER_GROUPBOX7 8195

// Control IDs (D11 join key: mechanically derived from the
// .dfm leaf control name -- IDC_<FORMSTEM>_<CONTROLNAME>)
#define IDC_CBUILDER_SPBEXIT 1024
#define IDC_CBUILDER_GROUPBOX5_FRAME 1025  // synthesized: SYNTH_CONTAINER_FRAME
#define IDC_CBUILDER_LABEL78 1026
#define IDC_CBUILDER_LABEL79 1027
#define IDC_CBUILDER_CBSOURCEFILE 1028
#define IDC_CBUILDER_EDNEWFILENAME 1029
#define IDC_CBUILDER_BTCREATESETUPFILE 1030
#define IDC_CBUILDER_GROUPBOX6_FRAME 1031  // synthesized: SYNTH_CONTAINER_FRAME
#define IDC_CBUILDER_LABEL81 1032
#define IDC_CBUILDER_BTDELETESETUPFILE 1033
#define IDC_CBUILDER_CBDELETEFILE 1034
#define IDC_CBUILDER_GROUPBOX7_FRAME 1035  // synthesized: SYNTH_CONTAINER_FRAME
#define IDC_CBUILDER_LABDIR 1036
#define IDC_CBUILDER_SPBIMPORT 1037
#define IDC_CBUILDER_SPBEXPORT 1038
#define IDC_CBUILDER_CHECKLISTBOX1 1039
#define IDC_CBUILDER_DIRECTORYLISTBOX1 1040
#define IDC_CBUILDER_DRIVECOMBOBOX1 1041

#endif // HT9045_UI_GEN_CBUILDER_IDS_H
