// ============================================================================
// DO NOT EDIT -- machine-generated by emit_rc.py W7-B1b v1.0 on CCDInterface.dfm
// AI(W906-W7-B1b) 20260728: generated .rc/_ids.h from the .dfm IR (see
// docs/W7_UI_ARCHITECTURE_PLAN.md S6 W7-B1b). Hand edits will be
// overwritten and are rejected by the idempotence gate (G7).
// Source golden: CCDInterface.dfm
// ============================================================================

#ifndef HT9045_UI_GEN_CCDINTERFACE_IDS_H
#define HT9045_UI_GEN_CCDINTERFACE_IDS_H

// Dialog template IDs
#define IDD_CCDINTERFACE 8192
#define IDD_CCDINTERFACE_GROUPBOX1 8193

// Control IDs (D11 join key: mechanically derived from the
// .dfm leaf control name -- IDC_<FORMSTEM>_<CONTROLNAME>)
#define IDC_CCDINTERFACE_MEMO 1024
#define IDC_CCDINTERFACE_BUTTON1 1025
#define IDC_CCDINTERFACE_BUTTON2 1026
#define IDC_CCDINTERFACE_BUTTON3 1027
#define IDC_CCDINTERFACE_BUTTON4 1028
#define IDC_CCDINTERFACE_EDIT1 1029
#define IDC_CCDINTERFACE_BUTTON5 1030
#define IDC_CCDINTERFACE_GROUPBOX1_FRAME 1031  // synthesized: SYNTH_CONTAINER_FRAME
#define IDC_CCDINTERFACE_LABEL1 1032
#define IDC_CCDINTERFACE_LABEL2 1033
#define IDC_CCDINTERFACE_COUNTCBOX 1034
#define IDC_CCDINTERFACE_BUTTON6 1035
#define IDC_CCDINTERFACE_EDSAVEPATH 1036
#define IDC_CCDINTERFACE_VIDEOCBOX 1037

#endif // HT9045_UI_GEN_CCDINTERFACE_IDS_H
