// ============================================================================
// DO NOT EDIT -- machine-generated by emit_rc.py W7-B1b v1.0 on cContactCT.dfm
// AI(W906-W7-B1b) 20260728: generated .rc/_ids.h from the .dfm IR (see
// docs/W7_UI_ARCHITECTURE_PLAN.md S6 W7-B1b). Hand edits will be
// overwritten and are rejected by the idempotence gate (G7).
// Source golden: cContactCT.dfm
// ============================================================================

#ifndef HT9045_UI_GEN_CCONTACTCT_IDS_H
#define HT9045_UI_GEN_CCONTACTCT_IDS_H

// Dialog template IDs
#define IDD_CCONTACTCT 8192
#define IDD_CCONTACTCT_RGYIELDTYPE 8193
#define IDD_CCONTACTCT_PALCLEARCNT 8194

// Control IDs (D11 join key: mechanically derived from the
// .dfm leaf control name -- IDC_<FORMSTEM>_<CONTROLNAME>)
#define IDC_CCONTACTCT_SGYIELD 1024
#define IDC_CCONTACTCT_RGYIELDTYPE_FRAME 1025  // synthesized: SYNTH_CONTAINER_FRAME
#define IDC_CCONTACTCT_RGYIELDTYPE_ITEM0 1026  // synthesized: SYNTH_RADIOGROUP_ITEM
#define IDC_CCONTACTCT_RGYIELDTYPE_ITEM1 1027  // synthesized: SYNTH_RADIOGROUP_ITEM
#define IDC_CCONTACTCT_RGYIELDTYPE_ITEM2 1028  // synthesized: SYNTH_RADIOGROUP_ITEM
#define IDC_CCONTACTCT_RGYIELDTYPE_ITEM3 1029  // synthesized: SYNTH_RADIOGROUP_ITEM
#define IDC_CCONTACTCT_RGYIELDTYPE_ITEM4 1030  // synthesized: SYNTH_RADIOGROUP_ITEM
#define IDC_CCONTACTCT_RGYIELDTYPE_ITEM5 1031  // synthesized: SYNTH_RADIOGROUP_ITEM
#define IDC_CCONTACTCT_RGYIELDTYPE_ITEM6 1032  // synthesized: SYNTH_RADIOGROUP_ITEM
#define IDC_CCONTACTCT_RGYIELDTYPE_ITEM7 1033  // synthesized: SYNTH_RADIOGROUP_ITEM
#define IDC_CCONTACTCT_RGYIELDTYPE_ITEM8 1034  // synthesized: SYNTH_RADIOGROUP_ITEM
#define IDC_CCONTACTCT_RGYIELDTYPE_ITEM9 1035  // synthesized: SYNTH_RADIOGROUP_ITEM
#define IDC_CCONTACTCT_RGYIELDTYPE_ITEM10 1036  // synthesized: SYNTH_RADIOGROUP_ITEM
#define IDC_CCONTACTCT_BTCLEARCOUNT 1037
#define IDC_CCONTACTCT_BTYIELDCHART 1038

#endif // HT9045_UI_GEN_CCONTACTCT_IDS_H
