// ============================================================================
// DO NOT EDIT -- machine-generated by emit_rc.py W7-B1b v1.0 on cCounterClear.dfm
// AI(W906-W7-B1b) 20260728: generated .rc/_ids.h from the .dfm IR (see
// docs/W7_UI_ARCHITECTURE_PLAN.md S6 W7-B1b). Hand edits will be
// overwritten and are rejected by the idempotence gate (G7).
// Source golden: cCounterClear.dfm
// ============================================================================

#ifndef HT9045_UI_GEN_CCOUNTERCLEAR_IDS_H
#define HT9045_UI_GEN_CCOUNTERCLEAR_IDS_H

// Dialog template IDs
#define IDD_CCOUNTERCLEAR 8192
#define IDD_CCOUNTERCLEAR_GBITEMS 8193

// Control IDs (D11 join key: mechanically derived from the
// .dfm leaf control name -- IDC_<FORMSTEM>_<CONTROLNAME>)
#define IDC_CCOUNTERCLEAR_SPBEXIT 1024
#define IDC_CCOUNTERCLEAR_GBITEMS_FRAME 1025  // synthesized: SYNTH_CONTAINER_FRAME
#define IDC_CCOUNTERCLEAR_SPBEXE 1026
#define IDC_CCOUNTERCLEAR_CBALARMDATA 1027
#define IDC_CCOUNTERCLEAR_CBTESTCATEGORY 1028
#define IDC_CCOUNTERCLEAR_CBSCANNER 1029
#define IDC_CCOUNTERCLEAR_CBLOADINGCOUNT 1030
#define IDC_CCOUNTERCLEAR_CBCONTACTCOUNTCURR 1031
#define IDC_CCOUNTERCLEAR_CBCONTACTCOUNTHIS 1032
#define IDC_CCOUNTERCLEAR_CBSORTINGCOUNT 1033
#define IDC_CCOUNTERCLEAR_CBTIMEDATA 1034
#define IDC_CCOUNTERCLEAR_CBSELECTALL 1035

#endif // HT9045_UI_GEN_CCOUNTERCLEAR_IDS_H
