// ============================================================================
// DO NOT EDIT -- machine-generated by emit_rc.py W7-B1b v1.0 on cDataHandling.dfm
// AI(W906-W7-B1b) 20260728: generated .rc/_ids.h from the .dfm IR (see
// docs/W7_UI_ARCHITECTURE_PLAN.md S6 W7-B1b). Hand edits will be
// overwritten and are rejected by the idempotence gate (G7).
// Source golden: cDataHandling.dfm
// ============================================================================

#ifndef HT9045_UI_GEN_CDATAHANDLING_IDS_H
#define HT9045_UI_GEN_CDATAHANDLING_IDS_H

// Dialog template IDs
#define IDD_CDATAHANDLING 8192
#define IDD_CDATAHANDLING_GROUPBOX1 8193
#define IDD_CDATAHANDLING_GROUPBOX2 8194
#define IDD_CDATAHANDLING_GROUPBOX3 8195

// Control IDs (D11 join key: mechanically derived from the
// .dfm leaf control name -- IDC_<FORMSTEM>_<CONTROLNAME>)
#define IDC_CDATAHANDLING_SBTEXIT 1024
#define IDC_CDATAHANDLING_SPBEXE 1025
#define IDC_CDATAHANDLING_GROUPBOX1_FRAME 1026  // synthesized: SYNTH_CONTAINER_FRAME
#define IDC_CDATAHANDLING_COMBOBOX1 1027
#define IDC_CDATAHANDLING_GROUPBOX2_FRAME 1028  // synthesized: SYNTH_CONTAINER_FRAME
#define IDC_CDATAHANDLING_CHECKBOX1 1029
#define IDC_CDATAHANDLING_CHECKBOX2 1030
#define IDC_CDATAHANDLING_CHECKBOX3 1031
#define IDC_CDATAHANDLING_GROUPBOX3_FRAME 1032  // synthesized: SYNTH_CONTAINER_FRAME
#define IDC_CDATAHANDLING_CHECKLISTBOX1 1033

#endif // HT9045_UI_GEN_CDATAHANDLING_IDS_H
