// ============================================================================
// DO NOT EDIT -- machine-generated by emit_rc.py W7-B1b v1.0 on cDefrostNote.dfm
// AI(W906-W7-B1b) 20260728: generated .rc/_ids.h from the .dfm IR (see
// docs/W7_UI_ARCHITECTURE_PLAN.md S6 W7-B1b). Hand edits will be
// overwritten and are rejected by the idempotence gate (G7).
// Source golden: cDefrostNote.dfm
// ============================================================================

#ifndef HT9045_UI_GEN_CDEFROSTNOTE_IDS_H
#define HT9045_UI_GEN_CDEFROSTNOTE_IDS_H

// Dialog template IDs
#define IDD_CDEFROSTNOTE 8192
#define IDD_CDEFROSTNOTE_PANEL11 8193

// Control IDs (D11 join key: mechanically derived from the
// .dfm leaf control name -- IDC_<FORMSTEM>_<CONTROLNAME>)
#define IDC_CDEFROSTNOTE_PNL_SHOWMESSAGE 1024
#define IDC_CDEFROSTNOTE_BTN_START 1025
#define IDC_CDEFROSTNOTE_BTN_INTERRUPT 1026

#endif // HT9045_UI_GEN_CDEFROSTNOTE_IDS_H
