// ============================================================================
// DO NOT EDIT -- machine-generated by emit_rc.py W7-B1b v1.0 on cheksocket.dfm
// AI(W906-W7-B1b) 20260728: generated .rc/_ids.h from the .dfm IR (see
// docs/W7_UI_ARCHITECTURE_PLAN.md S6 W7-B1b). Hand edits will be
// overwritten and are rejected by the idempotence gate (G7).
// Source golden: cheksocket.dfm
// ============================================================================

#ifndef HT9045_UI_GEN_CHEKSOCKET_IDS_H
#define HT9045_UI_GEN_CHEKSOCKET_IDS_H

// Dialog template IDs
#define IDD_CHEKSOCKET 8192
#define IDD_CHEKSOCKET_PAGECONTROL1_TABSHEET1 8193
#define IDD_CHEKSOCKET_PAGECONTROL1_TABSHEET2 8194
#define IDD_CHEKSOCKET_PAGECONTROL1_TABSHEET3 8195
#define IDD_CHEKSOCKET_PAGECONTROL1_TABSHEET4 8196

// Control IDs (D11 join key: mechanically derived from the
// .dfm leaf control name -- IDC_<FORMSTEM>_<CONTROLNAME>)
#define IDC_CHEKSOCKET_SPEEDBUTTON1 1024
#define IDC_CHEKSOCKET_SPEEDBUTTON2 1025
#define IDC_CHEKSOCKET_SPEEDBUTTON3 1026
#define IDC_CHEKSOCKET_SPEEDBUTTON8 1027
#define IDC_CHEKSOCKET_LABEL3 1028
#define IDC_CHEKSOCKET_LABEL1 1029
#define IDC_CHEKSOCKET_PAGECONTROL1 1030
#define IDC_CHEKSOCKET_ROI1 1031
#define IDC_CHEKSOCKET_EASYMAIN 1032
#define IDC_CHEKSOCKET_BUTTON1 1033
#define IDC_CHEKSOCKET_BUTTON2 1034
#define IDC_CHEKSOCKET_ROI2 1035
#define IDC_CHEKSOCKET_MEMO1 1036
#define IDC_CHEKSOCKET_CCD 1037
#define IDC_CHEKSOCKET_SCROLLBAR1 1038
#define IDC_CHEKSOCKET_EDIT3 1039
#define IDC_CHEKSOCKET_LIVEIMAGE 1040
#define IDC_CHEKSOCKET_SOURCEIMAGE 1041
#define IDC_CHEKSOCKET_EBW8IMAGE1 1042
#define IDC_CHEKSOCKET_EBW8IMAGE2 1043

#endif // HT9045_UI_GEN_CHEKSOCKET_IDS_H
