// ============================================================================
// DO NOT EDIT -- machine-generated by emit_rc.py W7-B1b v1.0 on cHotPlate.dfm
// AI(W906-W7-B1b) 20260728: generated .rc/_ids.h from the .dfm IR (see
// docs/W7_UI_ARCHITECTURE_PLAN.md S6 W7-B1b). Hand edits will be
// overwritten and are rejected by the idempotence gate (G7).
// Source golden: cHotPlate.dfm
// ============================================================================

#ifndef HT9045_UI_GEN_CHOTPLATE_IDS_H
#define HT9045_UI_GEN_CHOTPLATE_IDS_H

// Dialog template IDs
#define IDD_CHOTPLATE 8192
#define IDD_CHOTPLATE_PANEL1 8193
#define IDD_CHOTPLATE_GROUPBOX1 8194
#define IDD_CHOTPLATE_GROUPBOX2 8195
#define IDD_CHOTPLATE_PANEL2 8196

// Control IDs (D11 join key: mechanically derived from the
// .dfm leaf control name -- IDC_<FORMSTEM>_<CONTROLNAME>)
#define IDC_CHOTPLATE_LABEL1 1024
#define IDC_CHOTPLATE_HOTPLATENAME 1025
#define IDC_CHOTPLATE_GROUPBOX1_FRAME 1026  // synthesized: SYNTH_CONTAINER_FRAME
#define IDC_CHOTPLATE_IMAGE1 1027
#define IDC_CHOTPLATE_IMAGE2 1028
#define IDC_CHOTPLATE_CBENABLEHP2 1029
#define IDC_CHOTPLATE_CBENABLEHP1 1030
#define IDC_CHOTPLATE_GROUPBOX2_FRAME 1031  // synthesized: SYNTH_CONTAINER_FRAME
#define IDC_CHOTPLATE_IMAGE3 1032
#define IDC_CHOTPLATE_LABEL2 1033
#define IDC_CHOTPLATE_LABEL3 1034
#define IDC_CHOTPLATE_LABEL4 1035
#define IDC_CHOTPLATE_LABEL5 1036
#define IDC_CHOTPLATE_LABEL6 1037
#define IDC_CHOTPLATE_LABEL7 1038
#define IDC_CHOTPLATE_LABEL8 1039
#define IDC_CHOTPLATE_XST1 1040
#define IDC_CHOTPLATE_XPITCH1 1041
#define IDC_CHOTPLATE_XCT1 1042
#define IDC_CHOTPLATE_YST1 1043
#define IDC_CHOTPLATE_YPITCH1 1044
#define IDC_CHOTPLATE_YCT1 1045
#define IDC_CHOTPLATE_CBSELECTHPFROMDB 1046
#define IDC_CHOTPLATE_CHKUSEWIDEHOTPLATE 1047
#define IDC_CHOTPLATE_CHKTRAYHOTPLATECHECK 1048
#define IDC_CHOTPLATE_SPBSAVE 1049
#define IDC_CHOTPLATE_SBTEXIT 1050

#endif // HT9045_UI_GEN_CHOTPLATE_IDS_H
