// ============================================================================
// DO NOT EDIT -- machine-generated by emit_rc.py W7-B1b v1.0 on cTestCategory.dfm
// AI(W906-W7-B1b) 20260728: generated .rc/_ids.h from the .dfm IR (see
// docs/W7_UI_ARCHITECTURE_PLAN.md S6 W7-B1b). Hand edits will be
// overwritten and are rejected by the idempotence gate (G7).
// Source golden: cTestCategory.dfm
// ============================================================================

#ifndef HT9045_UI_GEN_CTESTCATEGORY_IDS_H
#define HT9045_UI_GEN_CTESTCATEGORY_IDS_H

// Dialog template IDs
#define IDD_CTESTCATEGORY 8192

// Control IDs (D11 join key: mechanically derived from the
// .dfm leaf control name -- IDC_<FORMSTEM>_<CONTROLNAME>)
#define IDC_CTESTCATEGORY_SGARM2 1024
#define IDC_CTESTCATEGORY_SGARM1 1025

#endif // HT9045_UI_GEN_CTESTCATEGORY_IDS_H
