// ============================================================================
// DO NOT EDIT -- machine-generated by emit_rc.py W7-B1b v1.0 on HS_Function.dfm
// AI(W906-W7-B1b) 20260728: generated .rc/_ids.h from the .dfm IR (see
// docs/W7_UI_ARCHITECTURE_PLAN.md S6 W7-B1b). Hand edits will be
// overwritten and are rejected by the idempotence gate (G7).
// Source golden: HS_Function.dfm
// ============================================================================

#ifndef HT9045_UI_GEN_HS_FUNCTION_IDS_H
#define HT9045_UI_GEN_HS_FUNCTION_IDS_H

// Dialog template IDs
#define IDD_HS_FUNCTION 8192
#define IDD_HS_FUNCTION_PNLSLFETESTRUN 8193
#define IDD_HS_FUNCTION_PNLSLFETESTRUN_PL_ATCSELFTESTSATUS_01 8194
#define IDD_HS_FUNCTION_PNLSLFETESTRUN_PL_ATCSELFTESTSATUS_02 8195
#define IDD_HS_FUNCTION_PNLSLFETESTRUN_PL_ATCSELFTESTSATUS_03 8196
#define IDD_HS_FUNCTION_PNLSLFETESTRUN_PL_ATCSELFTESTSATUS_99 8197

// Control IDs (D11 join key: mechanically derived from the
// .dfm leaf control name -- IDC_<FORMSTEM>_<CONTROLNAME>)
#define IDC_HS_FUNCTION_LABEL1 1024
#define IDC_HS_FUNCTION_LABEL2 1025
#define IDC_HS_FUNCTION_LABEL3 1026
#define IDC_HS_FUNCTION_LABEL4 1027
#define IDC_HS_FUNCTION_LABEL5 1028

#endif // HT9045_UI_GEN_HS_FUNCTION_IDS_H
