// ============================================================================
// DO NOT EDIT -- machine-generated by emit_rc.py W7-B1b v1.0 on INPUT.dfm
// AI(W906-W7-B1b) 20260728: generated .rc/_ids.h from the .dfm IR (see
// docs/W7_UI_ARCHITECTURE_PLAN.md S6 W7-B1b). Hand edits will be
// overwritten and are rejected by the idempotence gate (G7).
// Source golden: INPUT.dfm
// ============================================================================

#ifndef HT9045_UI_GEN_INPUT_IDS_H
#define HT9045_UI_GEN_INPUT_IDS_H

// Dialog template IDs
#define IDD_INPUT 8192

// Control IDs (D11 join key: mechanically derived from the
// .dfm leaf control name -- IDC_<FORMSTEM>_<CONTROLNAME>)
#define IDC_INPUT_SPEEDBUTTON1 1024
#define IDC_INPUT_SPEEDBUTTON2 1025
#define IDC_INPUT_SPEEDBUTTON3 1026
#define IDC_INPUT_SPEEDBUTTON4 1027
#define IDC_INPUT_SPEEDBUTTON5 1028
#define IDC_INPUT_SPEEDBUTTON6 1029
#define IDC_INPUT_SPEEDBUTTON7 1030
#define IDC_INPUT_LABEL1 1031
#define IDC_INPUT_BUTTON1 1032
#define IDC_INPUT_EDIT1 1033
#define IDC_INPUT_BUTTON2 1034
#define IDC_INPUT_BUTTON3 1035
#define IDC_INPUT_BUTTON5 1036
#define IDC_INPUT_BUTTON6 1037
#define IDC_INPUT_BUTTON8 1038
#define IDC_INPUT_BUTTON9 1039
#define IDC_INPUT_BUTTON11 1040
#define IDC_INPUT_BUTTON12 1041
#define IDC_INPUT_BUTTON15 1042
#define IDC_INPUT_BUTTON17 1043
#define IDC_INPUT_BUTTON18 1044
#define IDC_INPUT_BUTTON13 1045
#define IDC_INPUT_BUTTON4 1046

#endif // HT9045_UI_GEN_INPUT_IDS_H
