// ============================================================================
// DO NOT EDIT -- machine-generated by emit_rc.py W7-B1b v1.0 on InputForm.dfm
// AI(W906-W7-B1b) 20260728: generated .rc/_ids.h from the .dfm IR (see
// docs/W7_UI_ARCHITECTURE_PLAN.md S6 W7-B1b). Hand edits will be
// overwritten and are rejected by the idempotence gate (G7).
// Source golden: InputForm.dfm
// ============================================================================

#ifndef HT9045_UI_GEN_INPUTFORM_IDS_H
#define HT9045_UI_GEN_INPUTFORM_IDS_H

// Dialog template IDs
#define IDD_INPUTFORM 8192

// Control IDs (D11 join key: mechanically derived from the
// .dfm leaf control name -- IDC_<FORMSTEM>_<CONTROLNAME>)
#define IDC_INPUTFORM_LABEL1 1024
#define IDC_INPUTFORM_IMAGE1 1025
#define IDC_INPUTFORM_EDIT1 1026
#define IDC_INPUTFORM_BUTTON1 1027
#define IDC_INPUTFORM_EDIT2 1028
#define IDC_INPUTFORM_EDIT3 1029

#endif // HT9045_UI_GEN_INPUTFORM_IDS_H
