// ============================================================================
// DO NOT EDIT -- machine-generated by emit_rc.py W7-B1b v1.0 on login.dfm
// AI(W906-W7-B1b) 20260728: generated .rc/_ids.h from the .dfm IR (see
// docs/W7_UI_ARCHITECTURE_PLAN.md S6 W7-B1b). Hand edits will be
// overwritten and are rejected by the idempotence gate (G7).
// Source golden: login.dfm
// ============================================================================

#ifndef HT9045_UI_GEN_LOGIN_IDS_H
#define HT9045_UI_GEN_LOGIN_IDS_H

// Dialog template IDs
#define IDD_LOGIN 8192
#define IDD_LOGIN_RGLOGINOPTION 8193

// Control IDs (D11 join key: mechanically derived from the
// .dfm leaf control name -- IDC_<FORMSTEM>_<CONTROLNAME>)
#define IDC_LOGIN_LABUSERNAME 1024
#define IDC_LOGIN_LABOLDPASSWORD 1025
#define IDC_LOGIN_SBOK 1026
#define IDC_LOGIN_LABNEWPASSWORD 1027
#define IDC_LOGIN_EDUSERNAME 1028
#define IDC_LOGIN_EDLOGINOLDPASSWORD 1029
#define IDC_LOGIN_EDLOGINNEWPASSWORD 1030
#define IDC_LOGIN_CBLOGINUSERNAME 1031
#define IDC_LOGIN_RGLOGINOPTION_FRAME 1032  // synthesized: SYNTH_CONTAINER_FRAME
#define IDC_LOGIN_RGLOGINOPTION_ITEM0 1033  // synthesized: SYNTH_RADIOGROUP_ITEM
#define IDC_LOGIN_RGLOGINOPTION_ITEM1 1034  // synthesized: SYNTH_RADIOGROUP_ITEM
#define IDC_LOGIN_RGLOGINOPTION_ITEM2 1035  // synthesized: SYNTH_RADIOGROUP_ITEM

#endif // HT9045_UI_GEN_LOGIN_IDS_H
