// ============================================================================
// DO NOT EDIT -- machine-generated by emit_rc.py W7-B1b v1.0 on mymessbox.dfm
// AI(W906-W7-B1b) 20260728: generated .rc/_ids.h from the .dfm IR (see
// docs/W7_UI_ARCHITECTURE_PLAN.md S6 W7-B1b). Hand edits will be
// overwritten and are rejected by the idempotence gate (G7).
// Source golden: mymessbox.dfm
// ============================================================================

#ifndef HT9045_UI_GEN_MYMESSBOX_IDS_H
#define HT9045_UI_GEN_MYMESSBOX_IDS_H

// Dialog template IDs
#define IDD_MYMESSBOX 8192
#define IDD_MYMESSBOX_PNLMAIN 8193

// Control IDs (D11 join key: mechanically derived from the
// .dfm leaf control name -- IDC_<FORMSTEM>_<CONTROLNAME>)
#define IDC_MYMESSBOX_LABSTOPTIME 1024
#define IDC_MYMESSBOX_LBLSECSMSG 1025
#define IDC_MYMESSBOX_PNLPAUSE 1026
#define IDC_MYMESSBOX_PNLNO 1027
#define IDC_MYMESSBOX_PNLYES 1028
#define IDC_MYMESSBOX_PNLALARMRESET 1029
#define IDC_MYMESSBOX_PALWAITEAP 1030
#define IDC_MYMESSBOX_LBLSUBMSG 1031
#define IDC_MYMESSBOX_LBLMAINMSG 1032
#define IDC_MYMESSBOX_LBLCHINESEMSG 1033
#define IDC_MYMESSBOX_MOSECSGEM 1034

#endif // HT9045_UI_GEN_MYMESSBOX_IDS_H
