// ============================================================================
// DO NOT EDIT -- machine-generated by emit_rc.py W7-B1b v1.0 on RPDefault.dfm
// AI(W906-W7-B1b) 20260728: generated .rc/_ids.h from the .dfm IR (see
// docs/W7_UI_ARCHITECTURE_PLAN.md S6 W7-B1b). Hand edits will be
// overwritten and are rejected by the idempotence gate (G7).
// Source golden: RPDefault.dfm
// ============================================================================

#ifndef HT9045_UI_GEN_RPDEFAULT_IDS_H
#define HT9045_UI_GEN_RPDEFAULT_IDS_H

// Dialog template IDs
#define IDD_RPDEFAULT 8192
#define IDD_RPDEFAULT_GBTESTINGSTOPTIME 8193
#define IDD_RPDEFAULT_GBTESTINGSTOPTIME_PNL1 8194

// Control IDs (D11 join key: mechanically derived from the
// .dfm leaf control name -- IDC_<FORMSTEM>_<CONTROLNAME>)
#define IDC_RPDEFAULT_GBTESTINGSTOPTIME_FRAME 1024  // synthesized: SYNTH_CONTAINER_FRAME
#define IDC_RPDEFAULT_SPBDEFAULTEVIEWSHOW 1025
#define IDC_RPDEFAULT_SPBSAVE 1026
#define IDC_RPDEFAULT_SPBEXIT 1027
#define IDC_RPDEFAULT_STRNGRDRECIEPEPARAMETERDEFAULT 1028
#define IDC_RPDEFAULT_LABEL1 1029
#define IDC_RPDEFAULT_LABEL2 1030
#define IDC_RPDEFAULT_SPBREPLYRPDEFAULT 1031
#define IDC_RPDEFAULT_SPBSETRPDEFAULT 1032
#define IDC_RPDEFAULT_PNL2 1033
#define IDC_RPDEFAULT_PNLRPDEFAULTFALSECOLOR 1034
#define IDC_RPDEFAULT_PNLRPDEFAULTTRUECOLOR 1035

#endif // HT9045_UI_GEN_RPDEFAULT_IDS_H
