// ============================================================================
// DO NOT EDIT -- machine-generated by emit_rc.py W7-B1b v1.0 on uhome.dfm
// AI(W906-W7-B1b) 20260728: generated .rc/_ids.h from the .dfm IR (see
// docs/W7_UI_ARCHITECTURE_PLAN.md S6 W7-B1b). Hand edits will be
// overwritten and are rejected by the idempotence gate (G7).
// Source golden: uhome.dfm
// ============================================================================

#ifndef HT9045_UI_GEN_UHOME_IDS_H
#define HT9045_UI_GEN_UHOME_IDS_H

// Dialog template IDs
#define IDD_UHOME 8192
#define IDD_UHOME_PANEL2 8193
#define IDD_UHOME_PANEL1 8194
#define IDD_UHOME_PANEL3 8195

// Control IDs (D11 join key: mechanically derived from the
// .dfm leaf control name -- IDC_<FORMSTEM>_<CONTROLNAME>)
#define IDC_UHOME_PALUNUSE 1024
#define IDC_UHOME_PANEL104 1025
#define IDC_UHOME_BEVEL1 1026
#define IDC_UHOME_LABEL26 1027
#define IDC_UHOME_SPEEDBUTTON1 1028
#define IDC_UHOME_NAME 1029
#define IDC_UHOME_LEDHOME 1030
#define IDC_UHOME_EDPOS 1031
#define IDC_UHOME_PNLLINE1 1032
#define IDC_UHOME_PNLLINE2 1033
#define IDC_UHOME_PNLLINE3 1034
#define IDC_UHOME_SBABORTHOME 1035
#define IDC_UHOME_LISTBOX1 1036

#endif // HT9045_UI_GEN_UHOME_IDS_H
