// ============================================================================
// DO NOT EDIT -- machine-generated by emit_rc.py W7-B1b v1.0 on uShowMessage.dfm
// AI(W906-W7-B1b) 20260728: generated .rc/_ids.h from the .dfm IR (see
// docs/W7_UI_ARCHITECTURE_PLAN.md S6 W7-B1b). Hand edits will be
// overwritten and are rejected by the idempotence gate (G7).
// Source golden: uShowMessage.dfm
// ============================================================================

#ifndef HT9045_UI_GEN_USHOWMESSAGE_IDS_H
#define HT9045_UI_GEN_USHOWMESSAGE_IDS_H

// Dialog template IDs
#define IDD_USHOWMESSAGE 8192

// Control IDs (D11 join key: mechanically derived from the
// .dfm leaf control name -- IDC_<FORMSTEM>_<CONTROLNAME>)
#define IDC_USHOWMESSAGE_LBLINDEXCYCLETIME 1024
#define IDC_USHOWMESSAGE_LBLTESTTIME 1025
#define IDC_USHOWMESSAGE_LBLINITIALMESSAGE 1026
#define IDC_USHOWMESSAGE_IMGTRAY 1027
#define IDC_USHOWMESSAGE_IMGDEVICE 1028
#define IDC_USHOWMESSAGE_IMGTRAYHERE 1029
#define IDC_USHOWMESSAGE_IMGDEVICEHERE 1030
#define IDC_USHOWMESSAGE_SGDSPEEDVIEW 1031
#define IDC_USHOWMESSAGE_PROGRESSBAR1 1032
#define IDC_USHOWMESSAGE_BTNBACKTOMAIN 1033

#endif // HT9045_UI_GEN_USHOWMESSAGE_IDS_H
