// ============================================================================
// DO NOT EDIT -- machine-generated by emit_rc.py W7-B1b v1.0 on uTrayEditForm.dfm
// AI(W906-W7-B1b) 20260728: generated .rc/_ids.h from the .dfm IR (see
// docs/W7_UI_ARCHITECTURE_PLAN.md S6 W7-B1b). Hand edits will be
// overwritten and are rejected by the idempotence gate (G7).
// Source golden: uTrayEditForm.dfm
// ============================================================================

#ifndef HT9045_UI_GEN_UTRAYEDITFORM_IDS_H
#define HT9045_UI_GEN_UTRAYEDITFORM_IDS_H

// Dialog template IDs
#define IDD_UTRAYEDITFORM 8192

// Control IDs (D11 join key: mechanically derived from the
// .dfm leaf control name -- IDC_<FORMSTEM>_<CONTROLNAME>)
#define IDC_UTRAYEDITFORM_SPBUPDATE 1024
#define IDC_UTRAYEDITFORM_SPEEDBUTTON2 1025
#define IDC_UTRAYEDITFORM_LABEL1 1026
#define IDC_UTRAYEDITFORM_LABEL2 1027
#define IDC_UTRAYEDITFORM_MTLOADERBUFFER 1028
#define IDC_UTRAYEDITFORM_EDTYPOS 1029
#define IDC_UTRAYEDITFORM_EDTXPOS 1030
#define IDC_UTRAYEDITFORM_BUTTON1 1031
#define IDC_UTRAYEDITFORM_BITBTN1 1032
#define IDC_UTRAYEDITFORM_BUTTON2 1033
#define IDC_UTRAYEDITFORM_CHECKBOX1 1034
#define IDC_UTRAYEDITFORM_CBBINCOUNT 1035

#endif // HT9045_UI_GEN_UTRAYEDITFORM_IDS_H
