// ===========================================================================
//  ATC/WinWaySetting_layout.gen.cpp
//  DO NOT EDIT -- GENERATED FILE. See the matching _layout.gen.h banner.
// ===========================================================================
#include "WinWaySetting_layout.gen.h"

namespace ht9045_layout {

// (no custom-control properties in this form)

const DfmControlLayout kWinWaySettingLayout[] = {
    { "fWinway", "fWinway", "", "TfWinway", "", "", 0, 0, "ROOT", false, true, 280, true, 264, true, 330, true, 518, false, 0, -1, "", "", true, "MS Sans Serif", -11, "", true, -2147483640, "clWindowText", true, 12761254, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fWinway.lblWinwayNumber", "lblWinwayNumber", "IDC_WINWAYSETTING_LBLWINWAYNUMBER", "TLabel", "fWinway", "fWinway", 0, 1, "LEAF", true, true, 16, true, 8, true, 24, true, 20, false, 0, -1, "", "", true, "MS Sans Serif", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fWinway.btnUpdate", "btnUpdate", "IDC_WINWAYSETTING_BTNUPDATE", "TSpeedButton", "fWinway", "fWinway", 1, 1, "LEAF", true, true, 16, true, 308, true, 287, true, 41, false, 0, -1, "", "", true, "Arial", -16, "fsBold", true, 25600, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fWinway.grpcps", "grpcps", "IDD_WINWAYSETTING_GRPCPS", "TGroupBox", "fWinway", "fWinway", 2, 1, "SUBDLG", false, true, 11, true, 40, true, 289, true, 273, true, 0, -1, "", "", true, "MS Sans Serif", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fWinway.grpcps.lbl1", "lbl1", "IDC_WINWAYSETTING_LBL1", "TLabel", "fWinway.grpcps", "fWinway.grpcps", 0, 2, "LEAF", true, true, 2, true, 84, true, 104, true, 20, false, 0, -1, "", "", true, "MS Sans Serif", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fWinway.grpcps.lbl2", "lbl2", "IDC_WINWAYSETTING_LBL2", "TLabel", "fWinway.grpcps", "fWinway.grpcps", 1, 2, "LEAF", true, true, 2, true, 131, true, 104, true, 20, false, 0, -1, "", "", true, "MS Sans Serif", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fWinway.grpcps.lbl3", "lbl3", "IDC_WINWAYSETTING_LBL3", "TLabel", "fWinway.grpcps", "fWinway.grpcps", 2, 2, "LEAF", true, true, 2, true, 178, true, 104, true, 20, false, 0, -1, "", "", true, "MS Sans Serif", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fWinway.grpcps.lbl4", "lbl4", "IDC_WINWAYSETTING_LBL4", "TLabel", "fWinway.grpcps", "fWinway.grpcps", 3, 2, "LEAF", true, true, 2, true, 225, true, 104, true, 20, false, 0, -1, "", "", true, "MS Sans Serif", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fWinway.grpcps.lbl5", "lbl5", "IDC_WINWAYSETTING_LBL5", "TLabel", "fWinway.grpcps", "fWinway.grpcps", 4, 2, "LEAF", true, true, 2, true, 37, true, 104, true, 20, false, 0, -1, "", "", true, "MS Sans Serif", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fWinway.grpcps.cbbBaudRate", "cbbBaudRate", "IDC_WINWAYSETTING_CBBBAUDRATE", "TComboBox", "fWinway.grpcps", "fWinway.grpcps", 5, 2, "LEAF", false, true, 104, true, 81, true, 170, true, 28, true, 0, -1, "", "", true, "MS Sans Serif", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fWinway.grpcps.cbbByteSize", "cbbByteSize", "IDC_WINWAYSETTING_CBBBYTESIZE", "TComboBox", "fWinway.grpcps", "fWinway.grpcps", 6, 2, "LEAF", false, true, 104, true, 128, true, 170, true, 28, true, 1, -1, "", "", true, "MS Sans Serif", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fWinway.grpcps.cbbStopBit", "cbbStopBit", "IDC_WINWAYSETTING_CBBSTOPBIT", "TComboBox", "fWinway.grpcps", "fWinway.grpcps", 7, 2, "LEAF", false, true, 104, true, 174, true, 170, true, 28, true, 2, -1, "", "", true, "MS Sans Serif", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fWinway.grpcps.cbbParity", "cbbParity", "IDC_WINWAYSETTING_CBBPARITY", "TComboBox", "fWinway.grpcps", "fWinway.grpcps", 8, 2, "LEAF", false, true, 104, true, 221, true, 170, true, 28, true, 3, -1, "", "", true, "MS Sans Serif", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fWinway.grpcps.cbbDevice", "cbbDevice", "IDC_WINWAYSETTING_CBBDEVICE", "TComboBox", "fWinway.grpcps", "fWinway.grpcps", 9, 2, "LEAF", false, true, 104, true, 34, true, 170, true, 28, true, 4, -1, "", "", true, "MS Sans Serif", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fWinway.cbbWinwayATCIndex", "cbbWinwayATCIndex", "IDC_WINWAYSETTING_CBBWINWAYATCINDEX", "TComboBox", "fWinway", "fWinway", 3, 1, "LEAF", false, true, 48, true, 8, true, 145, true, 21, true, 1, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fWinway.grpcommu", "grpcommu", "IDD_WINWAYSETTING_GRPCOMMU", "TGroupBox", "fWinway", "fWinway", 4, 1, "SUBDLG", false, true, 8, true, 368, true, 289, true, 97, true, 2, -1, "", "", true, "MS Sans Serif", -16, "", true, -2147483640, "clWindowText", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fWinway.grpcommu.lbl6", "lbl6", "IDC_WINWAYSETTING_LBL6", "TLabel", "fWinway.grpcommu", "fWinway.grpcommu", 0, 2, "LEAF", true, true, 16, true, 24, true, 115, true, 20, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fWinway.grpcommu.lbl7", "lbl7", "IDC_WINWAYSETTING_LBL7", "TLabel", "fWinway.grpcommu", "fWinway.grpcommu", 1, 2, "LEAF", true, true, 16, true, 64, true, 140, true, 20, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fWinway.grpcommu.lblShowPT", "lblShowPT", "IDC_WINWAYSETTING_LBLSHOWPT", "TLabel", "fWinway.grpcommu", "fWinway.grpcommu", 2, 2, "LEAF", true, true, 184, true, 64, true, 9, true, 20, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fWinway.grpcommu.edtSetTemp", "edtSetTemp", "IDC_WINWAYSETTING_EDTSETTEMP", "TEdit", "fWinway.grpcommu", "fWinway.grpcommu", 3, 2, "LEAF", false, true, 136, true, 24, true, 97, true, 28, true, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fWinway.grpcommu.btnSendTemp", "btnSendTemp", "IDC_WINWAYSETTING_BTNSENDTEMP", "TButton", "fWinway.grpcommu", "fWinway.grpcommu", 4, 2, "LEAF", false, true, 248, true, 24, true, 33, true, 33, true, 1, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fWinway.grpcommu.btnGetPV", "btnGetPV", "IDC_WINWAYSETTING_BTNGETPV", "TButton", "fWinway.grpcommu", "fWinway.grpcommu", 5, 2, "LEAF", false, true, 248, true, 64, true, 33, true, 33, true, 2, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fWinway.WinWayATCComm1", "WinWayATCComm1", "", "TComm", "fWinway", "fWinway", 5, 1, "NONVISUAL", false, true, 184, true, 8, false, 0, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fWinway.WinWayATCComm2", "WinWayATCComm2", "", "TComm", "fWinway", "fWinway", 6, 1, "NONVISUAL", false, true, 216, true, 8, false, 0, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fWinway.WinWayATCComm3", "WinWayATCComm3", "", "TComm", "fWinway", "fWinway", 7, 1, "NONVISUAL", false, true, 248, true, 8, false, 0, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
    { "fWinway.WinWayATCComm4", "WinWayATCComm4", "", "TComm", "fWinway", "fWinway", 8, 1, "NONVISUAL", false, true, 280, true, 8, false, 0, false, 0, false, 0, -1, "", "", false, "", 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", false, 0, "", 0, nullptr },
};

const int kWinWaySettingLayoutCount = 26;

} // namespace ht9045_layout
