// ============================================================================
// DO NOT EDIT -- machine-generated by emit_rc.py W7-B1b v1.0 on ASE_K Socket/aseTest.dfm
// AI(W906-W7-B1b) 20260728: generated .rc/_ids.h from the .dfm IR (see
// docs/W7_UI_ARCHITECTURE_PLAN.md S6 W7-B1b). Hand edits will be
// overwritten and are rejected by the idempotence gate (G7).
// Source golden: ASE_K Socket/aseTest.dfm
// ============================================================================

#ifndef HT9045_UI_GEN_ASETEST_IDS_H
#define HT9045_UI_GEN_ASETEST_IDS_H

// Dialog template IDs
#define IDD_ASETEST 8192
#define IDD_ASETEST_PAGECONTROL1_COMMUCATION 8193
#define IDD_ASETEST_PAGECONTROL1_SETUP 8194

// Control IDs (D11 join key: mechanically derived from the
// .dfm leaf control name -- IDC_<FORMSTEM>_<CONTROLNAME>)
#define IDC_ASETEST_PAGECONTROL1 1024
#define IDC_ASETEST_MEMO1 1025
#define IDC_ASETEST_BTNTEST 1026
#define IDC_ASETEST_EDTTESTMSG 1027
#define IDC_ASETEST_EDTRECVMSG 1028
#define IDC_ASETEST_BTNTESTRECV 1029
#define IDC_ASETEST_LABEL1 1030
#define IDC_ASETEST_LABEL24 1031
#define IDC_ASETEST_LABEL2 1032
#define IDC_ASETEST_LABEL3 1033
#define IDC_ASETEST_IPADDRESS1 1034
#define IDC_ASETEST_IPPORT1 1035
#define IDC_ASETEST_CONNECT 1036
#define IDC_ASETEST_SAVEDATA 1037
#define IDC_ASETEST_BUTTON2 1038
#define IDC_ASETEST_IPPORT2 1039

#endif // HT9045_UI_GEN_ASETEST_IDS_H
