// ============================================================================
// DO NOT EDIT -- machine-generated by emit_rc.py W7-B1b v1.0 on ASE_K Socket/DataCompileForm.dfm
// AI(W906-W7-B1b) 20260728: generated .rc/_ids.h from the .dfm IR (see
// docs/W7_UI_ARCHITECTURE_PLAN.md S6 W7-B1b). Hand edits will be
// overwritten and are rejected by the idempotence gate (G7).
// Source golden: ASE_K Socket/DataCompileForm.dfm
// ============================================================================

#ifndef HT9045_UI_GEN_DATACOMPILEFORM_IDS_H
#define HT9045_UI_GEN_DATACOMPILEFORM_IDS_H

// Dialog template IDs
#define IDD_DATACOMPILEFORM 8192
#define IDD_DATACOMPILEFORM_PANEL1 8193

// Control IDs (D11 join key: mechanically derived from the
// .dfm leaf control name -- IDC_<FORMSTEM>_<CONTROLNAME>)
#define IDC_DATACOMPILEFORM_LABEL1 1024
#define IDC_DATACOMPILEFORM_LABEL2 1025
#define IDC_DATACOMPILEFORM_LABEL3 1026
#define IDC_DATACOMPILEFORM_LABEL4 1027
#define IDC_DATACOMPILEFORM_LABEL5 1028
#define IDC_DATACOMPILEFORM_LABEL6 1029
#define IDC_DATACOMPILEFORM_LABEL7 1030
#define IDC_DATACOMPILEFORM_LABEL8 1031
#define IDC_DATACOMPILEFORM_LABEL9 1032
#define IDC_DATACOMPILEFORM_EDTWORKTEMP 1033
#define IDC_DATACOMPILEFORM_EDTSOAKTIME 1034
#define IDC_DATACOMPILEFORM_EDTFORCEPERPIN 1035
#define IDC_DATACOMPILEFORM_EDTPINCOUNT 1036
#define IDC_DATACOMPILEFORM_EDTSITEMAP 1037
#define IDC_DATACOMPILEFORM_EDTBINMAP 1038
#define IDC_DATACOMPILEFORM_BTNCOMPARE 1039

#endif // HT9045_UI_GEN_DATACOMPILEFORM_IDS_H
