// ============================================================================
// DO NOT EDIT -- machine-generated by emit_rc.py W7-B1b v1.0 on ASE_K Socket/Socket_ASE_KR.dfm
// AI(W906-W7-B1b) 20260728: generated .rc/_ids.h from the .dfm IR (see
// docs/W7_UI_ARCHITECTURE_PLAN.md S6 W7-B1b). Hand edits will be
// overwritten and are rejected by the idempotence gate (G7).
// Source golden: ASE_K Socket/Socket_ASE_KR.dfm
// ============================================================================

#ifndef HT9045_UI_GEN_SOCKET_ASE_KR_IDS_H
#define HT9045_UI_GEN_SOCKET_ASE_KR_IDS_H

// Dialog template IDs
#define IDD_SOCKET_ASE_KR 8192
#define IDD_SOCKET_ASE_KR_GROUPBOX1 8193
#define IDD_SOCKET_ASE_KR_GROUPBOX3 8194
#define IDD_SOCKET_ASE_KR_GROUPBOX1_GBSETTING 8195

// Control IDs (D11 join key: mechanically derived from the
// .dfm leaf control name -- IDC_<FORMSTEM>_<CONTROLNAME>)
#define IDC_SOCKET_ASE_KR_SPLITTER1 1024
#define IDC_SOCKET_ASE_KR_MEMO 1025
#define IDC_SOCKET_ASE_KR_GROUPBOX1_FRAME 1026  // synthesized: SYNTH_CONTAINER_FRAME
#define IDC_SOCKET_ASE_KR_ONLINE 1027
#define IDC_SOCKET_ASE_KR_CBENABLESOCKET 1028
#define IDC_SOCKET_ASE_KR_BTNOK 1029
#define IDC_SOCKET_ASE_KR_BTNCANCEL 1030
#define IDC_SOCKET_ASE_KR_GROUPBOX3_FRAME 1031  // synthesized: SYNTH_CONTAINER_FRAME
#define IDC_SOCKET_ASE_KR_BTNC1N1 1032
#define IDC_SOCKET_ASE_KR_BTNC1N3 1033
#define IDC_SOCKET_ASE_KR_BTNC6N1 1034
#define IDC_SOCKET_ASE_KR_BTNC9N1 1035
#define IDC_SOCKET_ASE_KR_BTNC9N3 1036
#define IDC_SOCKET_ASE_KR_BTNC9N5 1037
#define IDC_SOCKET_ASE_KR_BUTTON1 1038
#define IDC_SOCKET_ASE_KR_BUTTON2 1039
#define IDC_SOCKET_ASE_KR_GBSETTING_FRAME 1040  // synthesized: SYNTH_CONTAINER_FRAME
#define IDC_SOCKET_ASE_KR_LABEL1 1041
#define IDC_SOCKET_ASE_KR_LABEL2 1042
#define IDC_SOCKET_ASE_KR_LABEL3 1043
#define IDC_SOCKET_ASE_KR_EDTSERVERIP_1 1044
#define IDC_SOCKET_ASE_KR_EDTSERVERPORT 1045
#define IDC_SOCKET_ASE_KR_EDTSOCKETTIMEOUT 1046
#define IDC_SOCKET_ASE_KR_EDTSERVERIP_2 1047
#define IDC_SOCKET_ASE_KR_EDTSERVERIP_3 1048
#define IDC_SOCKET_ASE_KR_EDTSERVERIP_4 1049

#endif // HT9045_UI_GEN_SOCKET_ASE_KR_IDS_H
